B: B::EventHandler Class Reference
B::EventHandler Class Reference
Carbon Events
Holds a set of Carbon Event handlers for a given Carbon Event target.
#include <BEventHandler.h>
Public Member Functions
Constructors / Destructor
EventHandler (EventTargetRef inTarget)
Constructs the event handler with the EventTargetRef.
EventHandler (HIObjectRef inTarget)
EventHandler (HIViewRef inTarget)
EventHandler (MenuRef inTarget)
EventHandler (WindowRef inTarget)
virtual ~EventHandler ()
Destructor.
Initialisation
void Init ()
Prepare the event handler to receive events.
Inquiries
EventTargetRef GetTarget () const
Returns the EventTargetRef that this event handler is attached to.
Functors
template<UInt32 CLASS, UInt32 KIND>
void Add (boost::function1< bool, Event< CLASS, KIND > & > inFunctor)
Adds a handler that will invoke inFunctor in response to a Carbon Event of the given CLASS and KIND.
template<UInt32 CLASS, UInt32 KIND, class T >
void Add (T *inObject, bool(T::*inFunction)(Event< CLASS, KIND > &))
Adds a handler that will invoke inObject->*inFunction in response to a Carbon Event of the given CLASS and KIND.
template<UInt32 CLASS, UInt32 KIND>
void Remove ()
Removes the handler for the Carbon Event of the given CLASS and KIND.
Static Public Member Functions
Sending HICommands
static void IssueCommand (UInt32 inCommandID)
Sends the HICommand given in inCommandID to the user input target.
Detailed Description
Holds a set of Carbon Event handlers for a given Carbon Event target.
EventHandler holds a set of mappings between Carbon Event class/kind pairs on the one hand, and functions implementing the Carbon Events on the other.
Often, clients will want to handle a Carbon Event via a member function. This it can be done by one of the overloads of Add() which takes an object and a pointer-to-member-function for that object. For example:
class MyObject {
    bool MyHandleEvent(Event<kMyEventClass, kMyEventKind>& event);
};
MyObject obj;
myEventHandler.Add(&obj, &MyObject::MyHandleEvent);
See also
Handling Carbon Events
Constructor & Destructor Documentation
B::EventHandler::EventHandler (HIObjectRef inTarget)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
B::EventHandler::EventHandler (HIViewRef inTarget)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
B::EventHandler::EventHandler (MenuRef inTarget)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
B::EventHandler::EventHandler (WindowRef inTarget)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Member Function Documentation
void B::EventHandler::IssueCommand (UInt32 inCommandID) static
Sends the HICommand given in inCommandID to the user input target.
B_THROW_IF_STATUS(err);
template<UInt32 CLASS, UInt32 KIND> void B::EventHandler::Add (boost::function1< bool, Event< CLASS, KIND > & > inFunctor)
Adds a handler that will invoke inFunctor in response to a Carbon Event of the given CLASS and KIND.
Parameters
CLASS Template parameter. Should be an integral four-char constant representing a Carbon Event class.
KIND Template parameter. Should be an integral four-char constant representing a Carbon Event kind in CLASS's namespace.
FUNCTOR Template parameter. Should be callable via bool operator () (EventHandlerCallRef inHandlerCallRef, EventRef inEvent).
Parameters
inFunctor The functor that implements the Carbon Event.
Referenced by B::CustomView::CustomView(), B::Drawer::Drawer(), B::MultipleDocumentPolicy< DOC_FACTORY >::Init(), B::Window::operator delete(), B::PredefinedView::PredefinedView(), B::TabbedView::TabbedView(), B::Toolbar::Toolbar(), B::ToolbarItem::ToolbarItem(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::~Application(), B::DataBrowser::~DataBrowser(), B::DocumentWindow< DOCUMENT >::~DocumentWindow(), B::TextFieldPart::~TextFieldPart(), and B::UndoPolicyEvents< UNDO_POLICY >::~UndoPolicyEvents().
template<UInt32 CLASS, UInt32 KIND, class T > void B::EventHandler::Add (T * inObject, bool(T::*)(Event< CLASS, KIND > &) inFunction)
Adds a handler that will invoke inObject->*inFunction in response to a Carbon Event of the given CLASS and KIND.
Parameters
CLASS Template parameter. Should be an integral four-char constant representing a Carbon Event class.
KIND Template parameter. Should be an integral four-char constant representing a Carbon Event kind in CLASS's namespace.
T Template parameter. Should of class type.
Parameters
inObject The object that implements the Carbon Event.
inFunction The member function of T that implements the Carbon Event.
template<UInt32 CLASS, UInt32 KIND> void B::EventHandler::Remove ()
Removes the handler for the Carbon Event of the given CLASS and KIND.
Parameters
CLASS Template parameter. Should be an integral four-char constant representing a Carbon Event class.
KIND Template parameter. Should be an integral four-char constant representing a Carbon Event kind in CLASS's namespace.
The documentation for this class was generated from the following files:
BEventHandler.h
BEventHandler.cpp