B: B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY > Class Template Reference
B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY > Class Template Reference
The application object.
#include <BApplication.h>
Public Types
Types
Template parameter. Should be a class that implements the PRINT_POLICY policy.
typedef DOC_POLICY DocPolicyType
An easy-to-access synonym for DOC_POLICY.
typedef UNDO_POLICY UndoPolicyType
An easy-to-access synonym for UNDO_POLICY.
typedef PRINT_POLICY PrintPolicyType
An easy-to-access synonym for PRINT_POLICY.
Public Member Functions
Constructor / Destructor
Application ()
Constructor.
virtual ~Application ()
Destructor.
Inquiries
bool IsQuitting () const
Returns true if the application is in the process of quitting the main event loop.
const Bundle & GetBundle () const
Returns the application bundle.
Nib & GetNib () const
Returns the application's main nib.
DocPolicyType & GetDocumentPolicy ()
Returns the application's document policy.
UndoPolicyType & GetUndoPolicy ()
Returns the application's undo policy.
PrintPolicyType & GetPrintPolicy ()
Returns the application's print policy.
String GetName () const
Returns the application's process' name.
Event Loop
virtual void Run ()
Initialises the application, then enters the event loop.
Public Member Functions inherited from B::AEObject
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual SInt32 GetUniqueID () const
Returns the object's unique id.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
Returns the AEObject matching a given property, if any.
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
Reads the value of the property identified by inPropertyID from ioReader.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
Implements the AppleScript "close" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
Implements the AppleScript "print" event.
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
Implements the AppleScript "save" event.
virtual void RevertObject ()
Implements the AppleScript "revert" event.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
Static Public Member Functions
Singleton Access
static Application & Get ()
Returns the application object.
Static Public Member Functions inherited from B::AEObject
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Protected Member Functions
Initialisation
virtual void Initialize ()
Main initialisation routine.
virtual void RegisterDocuments ()
Register the application's document classes, if any.
virtual void RegisterViews (ViewFactory &ioFactory)
Register the application's view classes, if any.
virtual void RegisterAppleEvents (AEObjectSupport &ioObjectSupport)
Register the application's Apple Events, if necessary.
virtual void RegisterHelp ()
Register the application's help book, if any.
virtual void LoadMenuBar (const char *inMenuBarName)
Loads the named menu bar.
virtual void PostprocessMenuBar ()
Performs post-processing on the menu bar, once all of its items have been added.
User Interface
virtual void ShowAboutBox ()
Displays the application's About box.
virtual void ShowPreferences ()
Displays the application's Preferences dialog.
Carbon Event Handlers
virtual void HandleActivated (WindowRef inClickedWindow)
Handles the kEventAppActivated event.
virtual void HandleDeactivated ()
Handles the kEventAppDeactivated event.
virtual void HandleQuit ()
Handles the kEventAppQuit event.
virtual bool HandleCommand (const HICommandExtended &inHICommand)
Handles the kEventCommandProcess event.
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
Handles the kEventCommandUpdateStatus event.
virtual bool HandleEnableItems (MenuRef inMenu)
Handles the kEventMenuEnableItems event.
Apple Event Handlers
virtual void OpenApplication ()
Handles the Open Application ('oapp') event.
virtual void ReopenApplication ()
Handles the Reopen Application ('rapp') event.
virtual void QuitApplication (OSType inSaveOption=kAEAsk)
Handles the Quit Application ('quit') event.
Overrides from AEObject
virtual size_t CountElements (DescType inElementType) const
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
virtual void ActivateObject ()
virtual void MakeSpecifier (AEWriter &ioWriter) const
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
Protected Member Functions inherited from B::AEObject
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Static Protected Member Functions
static void AddSubmenusToVector (MenuRef inMenu, std::vector< MenuRef > &ioVector)
Static Protected Member Functions inherited from B::AEObject
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Additional Inherited Members
Related Functions inherited from B::AEObject
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Detailed Description
template<class DOC_POLICY, class UNDO_POLICY, class PRINT_POLICY>
class B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >
The application object.
This is the topmost object in the application. An application is typically started by creating an instance of Application from within main():
int main()
{
    B::Application<B::NullDocumentPolicy, B::NullPrintPolicy>   theApp;
    theApp.Run();
    return 0;
}
The class' main responsibilities are:
Application initialisation. This can be subdivided into the following areas:
Document class registration.
View registration.
Apple Event registration.
AEOM class registration.
Document policy initialisation.
UI initialisation.
Support for required AppleEvents.
Implements the AEOM top-level container.
Allows access to the Application singleton.
Runs the application's event loop.
Application has three template parameters, which modify its behaviour:
DOC_POLICY, which determines how the application supports documents. This parameter is of class type and should follow the DOC_POLICY policy. There are three supplied implementations of this policy:
NullDocumentPolicy, for applications that don't use documents.
SingleDocumentPolicy, for applications that only open one document at a time.
MultipleDocumentPolicy, for applications that can open more than one document at a time.
UNDO_POLICY, which determines how the application supports Undo. This parameter is of class type and should implement the UNDO_POLICY policy. There are three supplied implementations of this policy:
NullUndoPolicy, for applications that don't need to support Undo.
MultipleUndoPolicy, for applications that need separate Undo and Redo stacks of arbitrary size.
SingleUndoPolicy, for applications that need only a simple 1-level-deep Undo.
PRINT_POLICY, which determines how the application supports printing.
Todo:
Complete documentation.
Constructor & Destructor Documentation
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Application ()
Constructor.
The constructor puts the Application object in the following state:
Its bundle is the main bundle.
Its nib is that specified in the bundle's Info.plist file.
It installs Carbon Event handlers.
Its document policy is an instance of DOC_POLICY.
Its print policy is an instance of PRINT_POLICY.
Its undo manager is taken from inUndoManager, or an instance of UndoManager if inUndoManager is NULL.
Its "frontmost" status is determined from the OS.
Note
If inUndoManager is not NULL, then ownership of it is transferred to the Application object.
References B::PRINT_POLICY::EnablePrintCommand(), B::ErrorHandler::Get(), B::AEObject::GetAEObjectPtr(), and B::AEObject::SetDefaultObject().
Member Function Documentation
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Run () virtual
Initialises the application, then enters the event loop.
The function does not return until the application has quit the event loop.
References B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize () protected virtual
Main initialisation routine.
This function is called immediately prior to entering the event loop. It calls each of the more specialised initialisation functions (eg, RegisterDocuments()) in turn.
Derived classes will normally override the more specialised functions. However, if they have initialisation needs that aren't covered by the base class, they may override this function instead.
References B::ViewFactory::Default(), B::DOC_POLICY::Init(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::LoadMenuBar(), B::Bundle::PackageCreator(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::PostprocessMenuBar(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterDocuments(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterHelp(), B::AEObjectSupport::RegisterScriptingDefinitions(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterViews(), and B::ViewFactory::SetDefaultSignature().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Run().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterDocuments () protected virtual
Register the application's document classes, if any.
Applications that support documents may override this to register their document classes with the document policy's document factory object. Currently only MultipleDocumentFactory supports document registration.
Assuming the application's document policy contains an instance of MultipleDocumentFactory, a document class can be registered like this:
GetDocumentPolicy().GetFactory().RegisterDocumentClass<MyDocument, cMyDocumentClass>();
where MyDocument is the C++ class of the document, and cMyDocumentClass is the AEOM identifier for the class.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterViews (ViewFactory & ioFactory) protected virtual
Register the application's view classes, if any.
Applications that contain classes derived from PredefinedView may register their derived classes by overriding this member function. Once a class is registered, then any time a Window object is instantiated from a nib, any HIView within it that matches the ControlKind & HIViewID specified at registration time will automatically have a corresponding view object created for it.
Views are typically registered like this:
ioFactory.Register<MyViewClass>(kMyViewObjectID);
where MyViewClass is the C++ class of the view, and kMyViewObjectID is the integer identifier for a particular instance of the view in a nib.
Parameters
ioFactory The view factory with which to register views.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents (AEObjectSupport & ioObjectSupport) protected virtual
Register the application's Apple Events, if necessary.
The standard Apple Events are already routed properly to the correct object. However, in some cases some additional work is required. First, for events that don't have a direct parameter; a callback needs to be installed for each of them. Second, for events that have non-standard direct parameters, i.e. that aren't object specifiers. That is the case of the Open Document event.
Derived classes which override this function should call the base class before performing their own registrations.
References B::AEObjectSupport::IsEventDefined(), B::DOC_POLICY::RegisterAppleEvents(), B::UNDO_POLICY::RegisterAppleEvents(), and B::AEObjectSupport::SetClassEventHandler().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterHelp () protected virtual
Register the application's help book, if any.
The default implementation calls AHRegisterHelpBook() if the application bundle's Info.plist contains a CFBundleHelpBookFolder key, which is required to support Apple Help.
Derived classes may override this function to provide extra Help menu items.
References B::HelpUtilities::HasHelpBook(), and B::HelpUtilities::RegisterHelpBook().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::LoadMenuBar (const char * inMenuBarName) protected virtual
Loads the named menu bar.
Loads the named menu bar, and makes it the current menu bar.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ShowAboutBox () protected virtual
Displays the application's About box.
Derived classes may override this function in order to implement a custom About Box.
The default implementation brings up the B framework's built-in About Box, which follows the Aqua Human Interface Guidelines.
In order to display a description of the application in the About Box, you need to add a key called "B::AboutBoxDescription" to your InfoPlist.strings file (or to your Info.plist, if you aren't localising your application).
References B::AboutBox::Display(), B::AEObject::GetAEObjectPtr(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::GetBundle().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleCommand().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ShowPreferences () protected virtual
Displays the application's Preferences dialog.
Derived classes may override this function in order to implement the application's Preferences window.
The default implementation does nothing.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleCommand(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleActivated (WindowRef inClickedWindow) protected virtual
Handles the kEventAppActivated event.
Derived classes may override this function in order to do some processing whenever the application becomes active. The override should call the base class before doing its own processing.
Parameters
inClickedWindow If non NULL, then the activation occurred as a result of the user clicking in this window.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleDeactivated () protected virtual
Handles the kEventAppDeactivated event.
Derived classes may override this function in order to do some processing whenever the application is no longer frontmost. The override should call the base class after doing its own processing.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleQuit () protected virtual
Handles the kEventAppQuit event.
Derived classes may override this function in order to do some processing when the main event loop is exited. The override should call the base class before doing its own processing.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > bool B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleCommand (const HICommandExtended & inHICommand) protected virtual
Handles the kEventCommandProcess event.
Derived classes should override this function to handle application-wide commands (i.e. commands that aren't handled by other entities such as windows or documents).
References B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ShowAboutBox(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ShowPreferences().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > bool B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleUpdateStatus (const HICommandExtended & inHICommand, CommandData & ioCmdData) protected virtual
Handles the kEventCommandUpdateStatus event.
Derived classes should override this function to update the status of application-wide commands (i.e. commands that aren't handled by other entities such as windows or documents).
References B::CommandData::SetEnabled().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > bool B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleEnableItems (MenuRef inMenu) protected virtual
Handles the kEventMenuEnableItems event.
This function is a solution to the problem of menu items not being enabled/disabled properly if no handler in the chain leading up from the user input focus knows about them. For example, suppose there is a menu item "Foo" that is only handled by a custom HIView called FooView. When a FooView is in the focus chain, it enables the Foo menu item. However, when the focus moves elsewhere, there aren't any handlers in the chain that "know" Foo needs to be disabled.
So, what this function does is to disable all menu items in non-system menus. After it returns, the kEventCommandUpdateStatus events are sent, which give handlers the chance to re-renable menu items as appropriate.
References B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleActivated(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleCommand(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleDeactivated(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleQuit(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleUpdateStatus().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::OpenApplication () protected virtual
Handles the Open Application ('oapp') event.
Derived classes may override this function in order to change the application's behaviour upon receipt of an Open Application ('oapp') event.
By default, the application delegates to its document policy.
References B::DOC_POLICY::OpenApplication().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ReopenApplication () protected virtual
Handles the Reopen Application ('rapp') event.
Derived classes may override this function in order to change the application's behaviour upon receipt of an Reopen Application ('rapp') event.
By default, the application delegates to its document policy.
References B::DOC_POLICY::ReopenApplication().
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
template<class DOC_POLICY , class UNDO_POLICY , class PRINT_POLICY > void B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication (OSType inSaveOption = kAEAsk) protected virtual
Handles the Quit Application ('quit') event.
Derived classes may override this function in order to change the application's behaviour upon receipt of an Quit Application ('quit') event.
By default, the application delegates to its document policy.
References B::DOC_POLICY::CountDocuments(), B::AEObject::CountElements(), B::AEObject::DoesClassInheritFrom(), B::AEObject::GetAEObjectPtr(), B::AEObject::GetClassID(), B::DOC_POLICY::GetDocumentByIndex(), B::DOC_POLICY::GetDocumentByName(), B::DOC_POLICY::GetDocumentByUniqueID(), B::AEObject::GetElementByIndex(), B::AEObject::GetElementByName(), B::AEObject::GetElementByUniqueID(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::GetName(), B::AEEvent< kCoreEventClass, kAEQuitApplication >::mSaveOption, B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::OpenApplication(), B::DOC_POLICY::OpenNewDocument(), B::DOC_POLICY::QuitApplication(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ReopenApplication(), B::Bundle::ShortVersionString(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::ShowPreferences(), B::AEWriter::WriteDesc(), and B::AEObject::WriteProperty().
The documentation for this class was generated from the following files:
BApplication.h
BApplication.tpl.h