B: B::ErrorHandler Class Reference
B::ErrorHandler Class Reference
Error Handling
Centralised error handling.
#include <BErrorHandler.h>
Public Member Functions
Message Tables
void AddMessageTable (CFStringRef inTable)
Adds inTable to the collection of tables used to generate error messages.
void RemoveMessageTable (CFStringRef inTable)
Removes inTable from the collection of tables used to generate error messages.
Quiet Exceptions & Asserts
The "quiet flags" are a hint to AboutToThrow() & AssertionFailed() that they should not display a user interface.
bool GetQuietThrows () const
Returns the quiet flag for throws.
void SetQuietThrows (bool quiet)
Changes the quiet flag for throws.
bool GetQuietAsserts () const
Returns the quiet flag for asserts.
void SetQuietAsserts (bool quiet)
Changes the quiet flag for asserts.
Static Public Member Functions
Singleton Access
This is a per-thread singleton.
static boost::intrusive_ptr< ErrorHandler > Get ()
Returns the ErrorHandler instance for the current thread.
static void Set (ErrorHandler *inHandler)
Changes the ErrorHandler instance for the current thread.
Asserts
static void HandleAssert (const char *cond, const char *file, int line, const char *func)
Calls the assert hook, passing it cond, file, line and func.
Protected Member Functions
Constructor / Destructor
ErrorHandler ()
Constructor.
virtual ~ErrorHandler () throw ()
Destructor.
Hooks
virtual void AboutToThrow (const std::exception &ex, const char *file, int line, const char *func)
This is called before throwing exception ex in debug builds.
virtual void AboutToThrow (const std::exception &ex)
This is called before throwing exception ex in release builds.
virtual void AssertionFailed (const char *cond, const char *file, int line, const char *func)
This is called when an assertion fails in debug builds.
Friends
class ErrorHandlerGlobals
void intrusive_ptr_add_ref (ErrorHandler *eh)
void intrusive_ptr_release (ErrorHandler *eh)
Throwing Exceptions
Clients should normally use one of the exception-throwing macros instead of calling these functions directly.
template<class EXCEPTION >
static void ThrowException (const EXCEPTION &ex, const char *file, int line, const char *func)
Calls the throw hook (passing it file, line and func), then throws ex.
template<class EXCEPTION >
static void ThrowException (const EXCEPTION &ex)
Calls the throw hook, then throws ex.
static void ThrowBadAllocException (const char *file, int line, const char *func)
Calls the throw hook (passing it file, line and func), then throws std::bad_alloc.
static void ThrowBadAllocException ()
Calls the throw hook, then throws std::bad_alloc.
static void ThrowOSStatusException (OSStatus err, const char *file, int line, const char *func)
Calls the throw hook (passing it file, line and func), then throws RuntimeOSStatusException.
static void ThrowOSStatusException (OSStatus err)
Calls the throw hook, then throws RuntimeOSStatusException.
static void ThrowErrnoException (int errn, const char *file, int line, const char *func)
Calls the throw hook (passing it file, line and func), then throws ErrnoException.
static void ThrowErrnoException (const char *file, int line, const char *func)
static void ThrowErrnoException (int errn)
Calls the throw hook, then ErrnoException.
static void ThrowErrnoException ()
virtual void ThrowStatusException (OSStatus inStatus, const String &inMessage)
Throws an exception object matching inStatus and inMessage.
Querying Exception Objects
static OSStatus GetStatus (const std::exception &ex, OSStatus default_status) throw ()
Returns an OS error code describing ex.
CFStringRef CopyExceptionMessage (const std::exception &ex) const throw ()
Returns a string describing ex.
Detailed Description
Centralised error handling.
ErrorHandler is a per-thread singleton object to which all throws and asserts (at least those that go through the macros B_THROW(), B_ASSERT(), etc.) are funnelled. To retrieve the current thread's error handler, call Get(). To change it, call Set(). Note that Set() allows the developer to write a custom error-handling object. This is useful for doing things such as logging exceptions to a file or system log.
Get() actually returns a smart pointer. The singleton's lifetime is controlled by the number of clients of the smart pointer. If you have code that depends upon the availability of the error handler, event during thread termination or application shutdown, it should hold on to this smart pointer.
When an exception is thrown or an assertion fails, ErrorHandler will display an alert by default. This can be changed by calling SetQuietThrows() and SetQuietAsserts().
See also
Exceptions and Error Handling
Member Function Documentation
boost::intrusive_ptr< ErrorHandler > B::ErrorHandler::Get () static
Returns the ErrorHandler instance for the current thread.
If there isn't an error handler for the current thread, one will be created.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Application(), AssertionFailed(), HandleAssert(), B::AEObjectSupport::RegisterScriptingDefinitions(), B::AEObjectSupport::RethrowExceptionFromAppleEventReply(), B::EventBase::Retrieve(), and ThrowException().
void B::ErrorHandler::Set (ErrorHandler * inHandler) static
Changes the ErrorHandler instance for the current thread.
Note
Ownership of inHandler is transferred to the ErrorHandler class. If an exception is thrown, inHandler is deleted.
void B::ErrorHandler::ThrowErrnoException (const char * file, int line, const char * func) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ThrowException().
void B::ErrorHandler::ThrowErrnoException () static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References ThrowException().
void B::ErrorHandler::ThrowStatusException (OSStatus inStatus, const String & inMessage) virtual
Throws an exception object matching inStatus and inMessage.
Parameters
inStatus The OS error code to translate into an exception object.
inMessage The string to put into the exception; may be NULL.
References B::String::cf_ref(), and B::String::empty().
CFStringRef B::ErrorHandler::CopyExceptionMessage (const std::exception & ex) const throw ()
Returns a string describing ex.
The returned string is meant to be used in a quasi-debugging context, such as an Apple Event reply.
References B::OSPtr< T >::get(), B::OSPtr< T >::release(), and B::OSPtr< T >::reset().
Referenced by AboutToThrow().
void B::ErrorHandler::AboutToThrow (const std::exception & ex, const char * file, int line, const char * func) protected virtual
This is called before throwing exception ex in debug builds.
Derived classes may override this function to provide custom functionality when an exception is thrown. It is up to the derived class to obey the quiet flag (as returned by GetQuietThrows()) if it so chooses.
The default implementation displays an alert.
References B::String::assign(), BLocalizedStringFromTableInBundle, BLocalizedStringWithDefaultValue, B::String::cf_ref(), CopyExceptionMessage(), GetQuietThrows(), GetStatus(), B::Bundle::Main(), and SetQuietThrows().
Referenced by AboutToThrow(), and SetQuietAsserts().
void B::ErrorHandler::AboutToThrow (const std::exception & ex) protected virtual
This is called before throwing exception ex in release builds.
Derived classes may override this function to provide custom functionality when an exception is thrown. It is up to the derived class to obey the quiet flag (as returned by GetQuietThrows()) if it so chooses.
The default implementation displays an alert.
References AboutToThrow().
void B::ErrorHandler::AssertionFailed (const char * cond, const char * file, int line, const char * func) protected virtual
This is called when an assertion fails in debug builds.
Derived classes may override this function to provide custom functionality when an assertion fails. It is up to the derived class to obey the quiet flag (as returned by GetQuietAsserts()) if it so chooses.
The default implementation displays an alert.
References BLocalizedStringFromTableInBundle, BLocalizedStringWithDefaultValue, B::String::cf_ref(), Get(), GetQuietAsserts(), B::Bundle::Main(), and SetQuietAsserts().
Referenced by SetQuietAsserts().
The documentation for this class was generated from the following files:
BErrorHandler.h
BErrorHandler.cpp