B: B::AEObject Class Reference
B::AEObject Class Reference abstract
Apple Events
The root class for objects visible to AppleScript.
#include <BAEObject.h>
Classes
class IndexSpecifier
Convenience wrapper around AEEventFunctor::IndexSpecifier<...>.
class InsertionLocationSpecifier
Convenience wrapper around AEEventFunctor::InsertionLocation<...>.
class NameSpecifier
Convenience wrapper around AEEventFunctor::NameSpecifier<...>.
class ObjectListSpecifier
Writes out a list of object specifiers to an AEWriter.
class ObjectWriter
Helper class that writes out an AEObject to an AEWriter.
class PropertySpecifier
Convenience wrapper around AEEventBase::PropertySpecifier<...>.
class UniqueIDSpecifier
Convenience wrapper around AEEventFunctor::UniqueIDSpecifier<...>.
Public Member Functions
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
Constructors / Destructor.
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
Modifiers.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
Access Keys.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual String GetName () const
Returns the object's name.
virtual SInt32 GetUniqueID () const
Returns the object's unique id.
Elements.
virtual size_t CountElements (DescType inElementType) const
Returns the number of elements of the given class.
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
Returns the element of the given class with the given index.
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
Returns the element of the given class with the given unique ID.
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
Returns the element of the given class with the given name.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
Properties.
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
Returns the AEObject matching a given property, if any.
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
Reads the value of the property identified by inPropertyID from ioReader.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
Object Resolution.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
Standard Events.
Derived classes wishing to implement some of the Standard Suite AppleEvents supported directly by AEObject need only override the appropriate function below.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
Implements the AppleScript "close" event.
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
Implements the AppleScript "make" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
Implements the AppleScript "print" event.
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
Implements the AppleScript "save" event.
virtual void RevertObject ()
Implements the AppleScript "revert" event.
virtual void ActivateObject ()
Implements the AppleScript "activate" event.
Object values.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
Static Public Member Functions
Default Object.
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
Utilities.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
Tokens.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
Apple Event handler registration.
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
Protected Member Functions
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Static Protected Member Functions
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Related Functions
(Note that these are not member functions.)
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Inquiries.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
Sending AppleEvents.
These functions offer a simple way of sending one of the standard AppleEvents to the object.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
Making AppleEvents.
These functions offer a simple way of creating one of the standard AppleEvents (targeting the object). An event created in this way can be sent later on.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
Object Specifiers.
These functions allow conversions between AEObjects and object specifiers.
virtual void MakeSpecifier (AEWriter &ioWriter) const =0
Writes out an object-specifier representation of the object.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
Comparisons.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Detailed Description
The root class for objects visible to AppleScript.
B's support for the Apple Event Object Model (AEOM) entails deriving classes from AEObject and implementing properties, elements and events for those classes in a way that matches the application's AppleScript dictionary.
Some important classes, such as B::Application, B::Document and B::Window, already derive from AEObject and support the standard properties, elements, and events as described in the Apple Event Registry.
AEObject's main services are:
Property support. Overridable functions are provided to allow the getting & setting of properties.
Element support. Overridable functions are provided to allow the counting of elements, as well as retrieving individual elements. Element retrieval may be done with a name, an index, or a unique id, matching the "by name", "by index", and "by id" key forms in AppleScript.
Standard event support. Overridable functions are provided for the commonly used events in the Standard Suite, and some events in the Miscellaneous Standards Suite.
Functions for creating and sending any of the Standard suite events to a AEObject.
Functions for building up object specifier descriptors.
Constructor & Destructor Documentation
B::AEObject::AEObject (AEObjectPtr inContainer, DescType inClassID) explicit
Constructor.
The two arguments establish (1) what kind (i.e., class) of object this is, and (2) where the object is located in the AEOM hierarchy. Note that inContainer may in theory be NULL, but in practice it almost never is because that implies that the object is at the top of the object hierarchy, and that place is already taken by Application.
Parameters
inContainer The object's container (as seen in AppleScript).
inClassID The object's class ID; must match the application's AppleScript dictionary.
B::AEObject::~AEObject () virtual
Destructor.
Override to release resources.
Member Function Documentation
AEObjectPtr B::AEObject::GetDefaultObject () static
Returns the default object. This is usually the application.
The default object is used in a number of different ways. First of all, it is used when attempting to resolve an object specifier denoting the null container. It's also used when coercing tokens (again during object resolution) of class cApplication. Finally, it's used as the target of AppleEvents in the absence of a direct parameter.
Referenced by B::AEObjectSupport::Resolve(), and Resolve().
void B::AEObject::SetDefaultObject (AEObjectPtr inObject) static
Sets the default object.
Attention
There shouldn't ever be a need to call this function.
See also
GetDefaultObject
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Application().
bool B::AEObject::InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
Parameters
inBaseClassID The base class ID; must match the application's AppleScript dictionary.
References DoesClassInheritFrom(), and GetClassID().
Referenced by GetClassID(), and B::Window::SetIdealSize().
bool B::AEObject::DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID) static
Returns true if inClassID is or derives from inBaseClassID.
Parameters
inClassID The class ID; must match the application's AppleScript dictionary.
inBaseClassID The base class ID; must match the application's AppleScript dictionary.
References B::AEObjectSupport::Get(), and GetClassID().
Referenced by B::AEObjectSupport::CountAllElements(), B::MultipleDocumentPolicy< DOC_FACTORY >::CountDocuments(), GetClassID(), B::MultipleDocumentPolicy< DOC_FACTORY >::GetDocumentByIndex(), B::MultipleDocumentPolicy< DOC_FACTORY >::GetDocumentByName(), B::MultipleDocumentPolicy< DOC_FACTORY >::GetDocumentByUniqueID(), B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), InheritsFrom(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
void B::AEObject::SetContainer (AEObjectPtr inContainer)
Changes the object's container.
Since a AEObject doesn't hold pointers to its elements, changing an AEObject's container is as simple as changing the value of the mContainer member variable. However, if a derived class does hold pointers to its elements, it will need to add logic so those pointers are added and removed as appropriate.
Parameters
inContainer The object's new container.
Referenced by GetClassID().
unsigned B::AEObject::GetIndex () const virtual
Returns the object's (zero-based) index within its container.
The default implementation iterates over all of the elements of the object's container, until it find one that matches itself. It then returns that element's index.
Derived classes may override this function to provide a more efficient implementation.
Referenced by GetClassID(), B::DocumentWindow< DOCUMENT >::MakeSpecifier(), and B::AboutBox::~AboutBox().
String B::AEObject::GetName () const virtual
Returns the object's name.
If a derived class's instances can be identified by name, then it needs to override this function to provide the name.
The default implementation throws an exception.
Reimplemented in B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >, and B::AbstractDocument.
Referenced by GetClassID().
SInt32 B::AEObject::GetUniqueID () const virtual
Returns the object's unique id.
If a derived class's instances can be identified by unique id, then it needs to override this function to provide the id.
The default implementation throws an exception.
Reimplemented in B::AbstractDocument.
Referenced by GetClassID(), and B::Window::SetIdealSize().
size_t B::AEObject::CountElements (DescType inElementType) const virtual
Returns the number of elements of the given class.
A derived class containing elements needs to override this function to provide the number of elements of a given class.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the element count for a class A needs to include instances of classes derived from A. It follows that if inElementType is cObject, then the count should include all of the container's elements, regardless of class.
The default implementation handles counting cObject; for all other element types it throws an exception.
Parameters
inElementType The base class ID of the elements to count; must match the application's AppleScript dictionary.
Reimplemented in B::AETextObject.
References B::AEObjectSupport::CountAllElements(), B::AEObjectSupport::Get(), and GetAEObjectPtr().
Referenced by AccessElementsByAbsolutePos(), B::AETextObject::CountElements(), GetAllElements(), GetClassID(), B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), GetElementByName(), GetElementByUniqueID(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObjectPtr B::AEObject::GetElementByIndex (DescType inElementType, size_t inIndex) const virtual
Returns the element of the given class with the given index.
A derived class containing elements must override this function if either of the following conditions is true:
The class supports indexed access to its elements;
The class supports by-name or by-id access to its elements, and relies on the default implementations of GetElementByName() and GetElementByUniqueID() for that access.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "index-space" for an instance of class A includes instances of classes derived from A.
The default implementation throws an exception.
Parameters
inElementType The base class ID of the element; must match the application's AppleScript dictionary.
inIndex The element's zero-based index.
Reimplemented in B::AETextObject.
Referenced by AccessElementsByAbsolutePos(), GetAllElements(), GetClassID(), B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), B::AETextObject::GetElementByIndex(), GetElementByName(), GetElementByUniqueID(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObjectPtr B::AEObject::GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const virtual
Returns the element of the given class with the given unique ID.
A derived class containing elements accessible by unique id may override this function to provide a more efficient implementation.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "id-space" for an instance of class A includes instances of classes derived from A.
The default implementation iterates over the elements of the given class, looking for a match on the unique id (a.k.a. pID) property. So the elements need to implement that property.
Parameters
inElementType The base class ID of the element; must match the application's AppleScript dictionary.
inUniqueID The element's unique id.
References CountElements(), and GetElementByIndex().
Referenced by AccessElementsByUniqueID(), GetClassID(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObjectPtr B::AEObject::GetElementByName (DescType inElementType, const String & inName) const virtual
Returns the element of the given class with the given name.
A derived class containing elements accessible by name may override this function to provide a more efficient implementation.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "name-space" for an instance of class A includes instances of classes derived from A.
The default implementation iterates over the elements of the given class, looking for a match on the name (a.k.a. pName) property. So the elements need to implement that property.
Parameters
inElementType The base class ID of the element; must match the application's AppleScript dictionary.
inName The element's name.
References B::AEObjectSupport::CompareStrings(), CountElements(), and GetElementByIndex().
Referenced by AccessElementsByName(), GetClassID(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
void B::AEObject::GetAllElements (DescType inElementType, std::list< AEObjectPtr > & outElements) const virtual
Returns all of the elements of the given class.
Parameters
inElementType The base class ID of the element; must match the application's AppleScript dictionary.
Reimplemented in B::AETextObject.
References CountElements(), and GetElementByIndex().
Referenced by AccessElementsByAbsolutePos(), and GetClassID().
AEObjectPtr B::AEObject::GetPropertyObject (DescType inPropertyID) const virtual
Returns the AEObject matching a given property, if any.
A derived class containing properties implemented as full-fledged AEObjects may override this function.
Often, properties are simple values such as integers or strings. Sometimes however, they are more complex and may even be represented by AEObjects in their own right. This is where this function becomes useful.
Whenever AppleScript needs a property, this function is called, giving a container the opportunity to return an object as the property's "value". If the function returns NULL, it's assumed that the property is "simple" (i.e., representable in an Apple Event descriptor) and the ReadProperty() or WriteProperty() function is called subsequently.
The default implementation always returns NULL.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
Reimplemented in B::AETextObject.
Referenced by AccessPropertyByID(), GetClassID(), and B::DocumentWindow< DOCUMENT >::MakeSpecifier().
void B::AEObject::WriteProperty (DescType inPropertyID, AEWriter & ioWriter) const virtual
Writes the value of the property identified by inPropertyID into ioWriter.
A derived class containing properties implemented as simple values must override this function.
Exceptions
AENoSuchObjectException If the property ID is unknown to the container; this should not happen however, because MOSL only feeds the class property IDs that have been declared a priori.
The default implementation throws an exception. Note that MoreOSL handles the pProperties properties.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
ioWriter The Apple Event descriptor stream to fill with the property's value.
Reimplemented in B::AETextObject.
References GetClassID(), B::AEWriter::Write(), and WritePropertiesProperty().
Referenced by GetClassID(), B::AbstractDocument::MakeCurrent(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication(), and B::Window::SetIdealSize().
void B::AEObject::ReadProperty (DescType inPropertyID, AEReader & ioReader) virtual
Reads the value of the property identified by inPropertyID from ioReader.
A derived class containing modifiable properties implemented as simple values must override this function.
Exceptions
AENoSuchObjectException If the property ID is unknown to the container; this should not happen however, because MOSL filters unknown property IDs prior to calling this function.
AENotModifiableException If the property is non-modifiable; this should not happen however, because MOSL filters non-modifiable properties prior to calling this function.
The default implementation throws an exception.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
ioReader The Apple Event descriptor stream containing the property's new value.
Reimplemented in B::AETextObject.
References ReadPropertiesProperty().
Referenced by GetClassID(), ReadPropertiesProperty(), and B::Window::SetIdealSize().
template<typename ITERATOR > void B::AEObject::WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter & ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
Parameters
ioWriter The Apple Event descriptor stream to fill with the property's value.
References GetAEObjectPtr().
Referenced by GetClassID(), and WritePropertiesProperty().
AEObjectPtr B::AEObject::CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord & inProperties) virtual
Implements the AppleScript "duplicate" event.
A derived class implementing the AppleScript "duplicate" event must override this function. Consult the Apple Event Registry for more information.
Returns
A valid AEObject. In case of error an exception is thrown.
The default implementation throws an exception.
Parameters
inPosition The position of the duplicate.
inTarget The container or sibling of the new AEObject.
inProperties The new AEObject's properties (optional).
Referenced by GetClassID().
void B::AEObject::CloseObject (OSType inSaveOption = kAEAsk, const Url & inUrl = Url()) virtual
Implements the AppleScript "close" event.
A derived class implementing the AppleScript "close" event must override this function. Consult the Apple Event Registry for more information.
Returns
A valid AEObject. In case of error an exception is thrown.
The default implementation throws an exception.
Parameters
inSaveOption A hint as to the behaviour to adopt if the AEObject has unsaved changes (optional).
inUrl The URL if the file in which to save the AEObject (optional).
Referenced by GetClassID().
AEObjectPtr B::AEObject::CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord & inProperties, const AEDesc & inData) virtual
Implements the AppleScript "make" event.
A derived class implementing the AppleScript "make" event must override this function. Consult the Apple Event Registry for more information.
Returns
A valid AEObject. In case of error an exception is thrown.
Note
The object (i.e. "this") is always the container of the to-be-created AEObject. InTarget will be either the object or one of the object's elements, depending on the value of inPosition.
The default implementation throws an exception.
Parameters
inObjectClass The class ID of the new AEObject.
inPosition The position of the new AEObject.
inTarget The container or sibling of the new AEObject.
inProperties The new AEObject's properties (optional).
inData The new AEObject's intrinsic data (optional).
Referenced by GetClassID().
void B::AEObject::DeleteObject () virtual
Implements the AppleScript "delete" event.
A derived class implementing the AppleScript "delete" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Referenced by GetClassID().
AEObjectPtr B::AEObject::MoveObject (DescType inPosition, AEObjectPtr inTarget) virtual
Implements the AppleScript "move" event.
A derived class implementing the AppleScript "move" event must override this function. Consult the Apple Event Registry for more information.
Returns
A valid AEObject. In case of error an exception is thrown. The returned object may be "this".
The default implementation throws an exception.
Parameters
inPosition The new position of the object.
inTarget The object's new container or sibling (depending on the value of inPosition).
Referenced by GetClassID().
void B::AEObject::OpenObject () virtual
Implements the AppleScript "open" event.
A derived class implementing the AppleScript "open" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Referenced by GetClassID().
void B::AEObject::PrintObject (PrintSettings * inSettings, Printer * inPrinter, bool inShowDialog) virtual
Implements the AppleScript "print" event.
A derived class implementing the AppleScript "print" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Parameters
inSettings The print settings to use. May be NULL.
inPrinter The printer to print to. May be NULL.
inShowDialog Should we display the print dialog?
Reimplemented in B::AbstractDocument.
Referenced by GetClassID().
void B::AEObject::SaveObject (const Url & inUrl = Url(), const String & inObjectType = String()) virtual
Implements the AppleScript "save" event.
A derived class implementing the AppleScript "save" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Parameters
inUrl The URL if the file in which to save the AEObject (optional).
inObjectType The HFS file type of the file in which to save the AEObject (optional).
Referenced by GetClassID().
void B::AEObject::RevertObject () virtual
Implements the AppleScript "revert" event.
A derived class implementing the AppleScript "revert" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Referenced by GetClassID().
void B::AEObject::ActivateObject () virtual
Implements the AppleScript "activate" event.
A derived class implementing the AppleScript "activate" event must override this function. Consult the Apple Event Registry for more information.
The default implementation throws an exception.
Referenced by GetClassID().
AEObjectPtr B::AEObject::SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord * inProperties = NULL, AESendMode inMode = 0)
Sends a "duplicate" event to the object.
Consult the Apple Event Registry for more information.
Returns
The newly-created AEObject.
Parameters
inPosition The position of the duplicate.
inTarget The container or sibling of the new AEObject.
inProperties The new AEObject's properties (optional).
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendCloseAppleEvent (OSType inSaveOption = kAEAsk, const Url & inUrl = Url(), AESendMode inMode = 0)
Sends a "close" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inSaveOption A hint as to the behaviour to adopt if the AEObject has unsaved changes (optional).
inUrl The URL if the file in which to save the AEObject (optional).
inMode The mode for AESend().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog(), B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskSaveChangesDialog(), B::Document< UNDO_POLICY, PRINT_POLICY >::CreateSaveDialog(), GetClassID(), and B::Window::SetIdealSize().
SInt32 B::AEObject::SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode = 0) const
Sends a "close" event to the object.
Consult the Apple Event Registry for more information.
Referenced by GetClassID().
AEObjectPtr B::AEObject::SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord * inProperties = NULL, const AEDesc * inData = NULL, AESendMode inMode = 0) static
Sends a "make" event to the object.
Consult the Apple Event Registry for more information.
Note
The newly-created AEObject will be either an element or a sibling of the object, depending on the value of inPosition.
Parameters
inObjectClass The class ID of the new AEObject.
inPosition The position of the new AEObject.
inTarget The object to which inPosition is relative.
inProperties The new AEObject's properties (optional).
inData The new AEObject's intrinsic data (optional).
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendDeleteAppleEvent (AESendMode inMode = 0)
Sends a "delete" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendGetDataAppleEvent (AEDesc & outValue, DescType inRequestedType = typeWildCard, AESendMode inMode = 0) const
Sends a "get" event to retrieve the object's data.
Consult the Apple Event Registry for more information.
Parameters
outValue The output value.
inRequestedType The requested type of the data.
inMode The mode for AESend().
Referenced by GetClassID().
template<DescType TYPE> void B::AEObject::SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType & outValue, DescType inRequestedType = typeWildCard, AESendMode inMode = 0) const
Sends a "get" event to retrieve the object's data.
The C/C++ type of outValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
outValue The output value.
inRequestedType The requested type of the data.
inMode The mode for AESend().
void B::AEObject::SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc & outValue, DescType inRequestedType = typeWildCard, AESendMode inMode = 0) const
Sends a "get" event to retrieve one of the object's properties.
Consult the Apple Event Registry for more information.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
outValue The output value.
inRequestedType The requested type of the data.
inMode The mode for AESend().
References GetAEObjectPtr().
Referenced by GetClassID().
template<DescType TYPE> void B::AEObject::SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType & outValue, DescType inRequestedType = typeWildCard, AESendMode inMode = 0) const
Sends a "get" event to retrieve one of the object's properties.
The C/C++ type of outValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
outValue The output value.
inRequestedType The requested type of the data.
inMode The mode for AESend().
AEObjectPtr B::AEObject::SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode = 0)
Sends a "move" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inPosition The new position of the object.
inTarget The object's new container or sibling (depending on the value of inPosition).
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendOpenAppleEvent (AESendMode inMode = 0)
Sends a "open" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendPrintAppleEvent (bool inShowDialog = false, const AERecord * inProperties = NULL, AESendMode inMode = 0)
Sends a "print" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inShowDialog The "show dialog" flag (optional).
inProperties The print job properties (optional).
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendSaveAppleEvent (const Url & inUrl = Url(), const String & inObjectType = String(), AESendMode inMode = 0)
Sends a "save" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inUrl The URL if the file in which to save the AEObject (optional).
inObjectType The HFS file type of the file in which to save the AEObject (optional).
inMode The mode for AESend().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateSaveDialog(), GetClassID(), and B::AbstractDocument::MakeCurrent().
void B::AEObject::SendRevertAppleEvent (AESendMode inMode = 0)
Sends a "revert" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inMode The mode for AESend().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog(), and GetClassID().
void B::AEObject::SendSelectAppleEvent (AESendMode inMode = 0)
Sends a "select" event to the object.
Consult the Apple Event Registry for more information.
Parameters
inMode The mode for AESend().
Referenced by GetClassID().
void B::AEObject::SendSetDataAppleEvent (const AEDesc & inValue, AESendMode inMode = 0)
Sends "set" event to change the object's data.
The new value is encapsulated with an Apple Event descriptor.
Parameters
inValue The Apple Event descriptor containing the new value.
inMode The mode for AESend().
Referenced by GetClassID().
template<DescType TYPE> void B::AEObject::SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType & inValue, AESendMode inMode = 0)
Sends "set" event to change the object's data.
The C/C++ type of inValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
inValue The property's new value.
inMode The mode for AESend().
References B::AEEventBase::SendEvent().
void B::AEObject::SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc & inValue, AESendMode inMode = 0)
Sends "set" event to change one of the object's properties.
The new property value is encapsulated with an Apple Event descriptor.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
inValue The Apple Event descriptor containing the property's new value.
inMode The mode for AESend().
References GetAEObjectPtr().
Referenced by GetClassID(), and B::Window::SetIdealSize().
template<DescType TYPE> void B::AEObject::SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType & inValue, AESendMode inMode = 0)
Sends "set" event to change one of the object's properties.
The C/C++ type of inValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
inValue The property's new value.
inMode The mode for AESend().
References B::AEEventBase::SendEvent().
void B::AEObject::MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord * inProperties, AppleEvent & outEvent) const
Creates a "duplicate" event targeting the object.
Consult the Apple Event Registry for more information.
Note
The newly-created AEObject will be either an element or a sibling of the object (i.e. "this"), depending on the value of inPosition.
Parameters
inPosition The position of the duplicate.
inTarget The container or sibling of the new AEObject.
inProperties The new AEObject's properties (optional).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeCloseAppleEvent (OSType inSaveOption, const Url & inUrl, AppleEvent & outEvent) const
Creates a "close" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inSaveOption A hint as to the behaviour to adopt if the AEObject has unsaved changes (optional).
inUrl The URL if the file in which to save the AEObject (optional).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent & outEvent) const
Creates a "count" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inObjectClass The class ID of the elements to count.
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord * inProperties, const AEDesc * inData, AppleEvent & outEvent) static
Creates a "create" event targeting the object.
Consult the Apple Event Registry for more information.
Note
The newly-created AEObject will be either an element or a sibling of the object (i.e. "this"), depending on the value of inPosition.
Parameters
inObjectClass The class ID of the new AEObject.
inPosition The position of the new AEObject.
inTarget The object to which inPosition is relative.
inProperties The new AEObject's properties (optional).
inData The new AEObject's intrinsic data (optional).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeDeleteAppleEvent (AppleEvent & outEvent) const
Creates a "delete" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent & outEvent) const
Creates a "get" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inRequestedType The requested type of the data (default = typeWildCard).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent & outEvent) const
Creates a "get" event targeting one of the object's properties.
Consult the Apple Event Registry for more information.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
inRequestedType The requested type of the data (default = typeWildCard).
outEvent The output Apple Event.
References GetAEObjectPtr().
Referenced by GetClassID().
void B::AEObject::MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent & outEvent) const
Creates a "move" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inPosition The new position of the object.
inTarget The object's new container or sibling (depending on the value of inPosition).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeOpenAppleEvent (AppleEvent & outEvent) const
Creates a "open" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakePrintAppleEvent (bool inShowDialog, const AERecord * inProperties, AppleEvent & outEvent) const
Creates a "print" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inShowDialog The "show dialog" flag (optional).
inProperties The print job properties (optional).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeRevertAppleEvent (AppleEvent & outEvent) const
Creates a "revert" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeSaveAppleEvent (const Url & inUrl, const String & inObjectType, AppleEvent & outEvent) const
Creates a "save" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
inUrl The URL if the file in which to save the AEObject (optional).
inObjectType The HFS file type of the file in which to save the AEObject (optional).
outEvent The output Apple Event.
Referenced by GetClassID().
void B::AEObject::MakeSelectAppleEvent (AppleEvent & outEvent) const
Creates a "select" event targeting the object.
Consult the Apple Event Registry for more information.
Parameters
outEvent The output Apple Event.
Referenced by GetClassID().
template<DescType TYPE> void B::AEObject::MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType & inValue, AppleEvent & outEvent) const
Creates a "set" event targeting the object.
The C/C++ type of inValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
inValue The property's new value.
outEvent The output Apple Event.
void B::AEObject::MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc & inValue, AppleEvent & outEvent) const
Creates a "set" event targeting one of the object's properties.
The new property value is encapsulated with an Apple Event descriptor.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
inValue The Apple Event descriptor containing the property's new value.
outEvent The output Apple Event.
References GetAEObjectPtr().
Referenced by GetClassID().
template<DescType TYPE> void B::AEObject::MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType & inValue, AppleEvent & outEvent) const
Creates a "set" event targeting one of the object's properties.
The C/C++ type of inValue (i.e. the property's new value) is determined by the TYPE template parameter, via an instantiation of the DescParam class template.
Parameters
TYPE Template parameter. Should be a four-char constant in the DescType namespace.
Parameters
inPropertyID The property ID; must match the application's AppleScript dictionary.
inValue The property's new value.
outEvent The output Apple Event.
References GetAEObjectPtr().
void B::AEObject::MakeSpecifier (AEWriter & ioWriter) const pure virtual
Writes out an object-specifier representation of the object.
Attention
All derived classes must override this function.
The default implementation throws an exception.
Parameters
ioWriter The Apple Event stream into which the object specifier is to be written.
Implemented in B::DocumentWindow< DOCUMENT >.
Referenced by GetClassID(), B::DescParamHelper::GetCoercedData(), B::Window::SetIdealSize(), and WriteValue().
void B::AEObject::MakePropertySpecifier (DescType inPropertyID, AEWriter & ioWriter) const virtual
Writes out an object specifier representation of one of the object's properties.
This is a convenience routine.
Parameters
inPropertyID One of the object's properties.
ioWriter The Apple Event stream into which the object specifier is to be written.
References BuildPropertySpecifier(), and GetAEObjectPtr().
Referenced by GetClassID().
AEObjectPtr B::AEObject::Resolve (const AEDesc & inDesc) static
Resolves an object specifier into a AEObject.
This is a convenience routine that calls through to AEObjectSupport.
Returns
A valid AEObject. If an error occurs an exception is thrown.
Parameters
inDesc The object specifier.
References B::AEObjectSupport::Get().
Referenced by GetClassID().
AEObjectPtr B::AEObject::Resolve (const AEDesc & inDesc, const std::nothrow_t &) static
Resolves an object specifier into a AEObject (nothrow variant).
This is a convenience routine that calls through to AEObjectSupport.
Returns
A valid AEObject, or NULL if an error occurs.
Parameters
inDesc The object specifier.
References B::AEWriter::Close(), B::AEObjectSupport::Get(), GetDefaultObject(), B::AEObjectSupport::GetPropertyInfo(), B::AEDescriptor::GetType(), B::AEInfo::PropertyInfo::mAccess, B::AEEvent< kAECoreSuite, kAECreateElement >::mData, B::AEEvent< kAECoreSuite, kAEDoObjectsExist >::mExists, B::AEEvent< kAECoreSuite, kAEClone >::mInsertPosition, B::AEEvent< kAECoreSuite, kAECreateElement >::mInsertPosition, B::AEEvent< kAECoreSuite, kAEMove >::mInsertPosition, B::AEEvent< kAECoreSuite, kAECountElements >::mObjectClass, B::AEEvent< kAECoreSuite, kAECreateElement >::mObjectClass, B::AEEvent< kAECoreSuite, kAESave >::mObjectType, B::AEEvent< kAECoreSuite, kAEClose >::mObjectUrl, B::AEEvent< kAECoreSuite, kAESave >::mObjectUrl, B::AEEvent< kAECoreSuite, kAEClone >::mProperties, B::AEEvent< kAECoreSuite, kAECreateElement >::mProperties, B::AEEvent< kAECoreSuite, kAEGetData >::mRequestedType, B::AEEvent< kAECoreSuite, kAEClose >::mSaveOption, B::AEEvent< kAECoreSuite, kAEClone >::mTarget, B::AEEvent< kAECoreSuite, kAEMove >::mTarget, B::AEObjectSupport::Resolve(), B::AEObjectSupport::SetClassEventHandler(), and B::AEWriter::WriteDesc().
void B::AEObject::BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String & inName, AEWriter & ioWriter) static
Write out an object specifier for an element of a given class and name in the given container.
Note
Because the element is identified by its class ID and name and not by a AEObject directly, this function can be used to create object specifiers of objects that don't (yet) exist.
Parameters
inContainer The container.
inObjectClass The element's class ID.
inName The element's name.
ioWriter The Apple Event stream into which the object specifier is to be written.
Referenced by GetClassID(), and B::Window::SetIdealSize().
void B::AEObject::BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter & ioWriter) static
Write out an object specifier for an element of a given class and index in the given container.
Note
Because the element is identified by its class ID and index and not by a AEObject directly, this function can be used to create object specifiers of objects that don't (yet) exist.
Parameters
inContainer The container.
inObjectClass The element's class ID.
inIndex The element's index.
ioWriter The Apple Event stream into which the object specifier is to be written.
Referenced by GetClassID(), B::DocumentWindow< DOCUMENT >::MakeSpecifier(), and B::AboutBox::~AboutBox().
void B::AEObject::BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter & ioWriter) static
Write out an object specifier for an element of a given class and unique id in the given container.
Note
Because the element is identified by its class ID and unique id and not by a AEObject directly, this function can be used to create object specifiers of objects that don't (yet) exist.
Parameters
inContainer The container.
inObjectClass The element's class ID.
inUniqueID The element's unique id.
ioWriter The Apple Event stream into which the object specifier is to be written.
Referenced by GetClassID(), and B::AbstractDocument::PrintDocument().
void B::AEObject::BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter & ioWriter) static
Write out an object specifier for the given property in the given object.
Parameters
inObject The object.
inPropertyID The property ID.
ioWriter The Apple Event stream into which the object specifier is to be written.
Referenced by GetClassID(), and MakePropertySpecifier().
void B::AEObject::WriteValue (AEWriter & ioWriter) const virtual
Writes the value of the object into ioWriter.
Parameters
ioWriter The Apple Event descriptor stream to fill with the object's value.
References MakeSpecifier().
Referenced by GetClassID().
void B::AEObject::WritePropertiesProperty (AEWriter & ioWriter, bool inWriteableOnly) const protected
Writes the pProperties property into ioWriter.
Parameters
ioWriter The Apple Event descriptor stream to fill with the property's value.
inWriteableOnly If true, only writeable properties should be written out.
References GetPropertyIDs(), B::AEInfo::PropertyInfo::mAccess, B::AEInfo::PropertyInfo::mInProperties, and WriteProperties().
Referenced by WriteProperty().
void B::AEObject::ReadPropertiesProperty (AEReader & ioReader, bool inIgnoreReadOnly) protected
Reads the pProperties property from ioReader.
Parameters
inIgnoreReadOnly If true, only writeable properties should be read.
References B::AEObjectSupport::Get(), GetClassID(), and ReadProperty().
Referenced by ReadProperty().
Friends And Related Function Documentation
AEWriter & operator<< (AEWriter & writer, const AEObject & obj) related
Writes out the AEObject obj to the AEWriter writer.
References B::AEWriter::WriteObject().
AEWriter & operator<< (AEWriter & writer, const AEObject * obj) related
Writes out the AEObject pointed to by obj to the AEWriter writer.
Note
If obj is NULL, the results are undefined.
References B::AEWriter::WriteObject().
AEWriter & operator<< (AEWriter & writer, ConstAEObjectPtr ptr) related
Writes out the AEObject pointed to by ptr to the AEWriter writer.
Note
If ptr is NULL, the results are undefined.
References B::AEWriter::WriteObject().
The documentation for this class was generated from the following files:
BAEObject.h
BAEObject.cpp