B: B::HybridView Class Reference
B::HybridView Class Reference
Views
Base class for implementations of HIView that can also be used by clients of the view.
#include <BHybridView.h>
Public Member Functions
HIViewRef GetViewRef () const
Rect GetBounds () const
Rect GetFrame () const
int GetValue () const
int GetMinimum () const
int GetMaximum () const
String GetText () const
bool IsFocused () const
bool IsHighlighted () const
bool IsActive () const
bool IsEnabled () const
bool IsVisible () const
bool IsCommandSentToUserFocus () const
WindowRef GetOwner () const
void DebugPrint () const
HIObjectRef GetObjectRef () const
EventTargetRef GetEventTarget () const
HIViewPartCode GetFocusPart () const
HIViewPartCode GetHighlightPart () const
void SetFrame (const Rect &fr)
void MoveFrameBy (float dx, float dy)
void MoveFrameTo (float x, float y)
void ResizeFrameBy (float dw, float dh)
void ResizeFrameTo (float w, float h)
void SetValue (int inValue)
void SetMinimum (int inMininum)
void SetMaximum (int inMaximum)
void SetText (const String &inText)
void SetHighlight (HIViewPartCode inPart)
void Activate (bool inActivate)
void Enable (bool inEnable)
void Show (bool inShow)
void SendCommandToUserFocus (bool inSendIt)
Public Member Functions inherited from B::EventTarget
template<>
EventTargetRef GetEventTarget (WindowRef inObj)
template<>
EventTargetRef GetEventTarget (HIViewRef inObj)
template<>
EventTargetRef GetEventTarget (HIObjectRef inObj)
template<>
EventTargetRef GetEventTarget (EventTargetRef inObj)
void SetAccessible (bool inAccessible)
Make the object archivable.
void SetAccessibilityAttribute (CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetAccessibilityAttribute (UInt64 inIdentifier, CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetArchivable (bool inArchivable)
Make the object archivable.
bool IsAccessible () const
Is the object accessible?
bool IsArchivable () const
Is the object archivable?
operator HIObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
HIObjectRef GetObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
Public Member Functions inherited from B::View
void SetViewID (const HIViewID &inID)
Returns the view's full HIViewID.
void SetID (SInt32 inID)
Sets the view's HIViewID::id field while preserving its HIViewID::signature.
void SetCommandID (UInt32 inCommandID)
void SetFrame (const Rect &inNewFrame)
void MoveFrameBy (float deltaX, float deltaY)
void MoveFrameTo (float x, float y)
void ResizeFrameBy (float deltaWidth, float deltaHeight)
void ResizeFrameTo (float width, float height)
void SetValue (int inValue)
void SetMinimum (int inMininum)
void SetMaximum (int inMaximum)
void SetFocus (HIViewPartCode part)
void SetHighlight (HIViewPartCode part)
void Activate (bool inActivate)
void Enable (bool inEnable)
void Show (bool inShow)
void SendCommandToUserFocus (bool inSendIt)
void AddSubview (View *subview)
void RemoveFromSuperview ()
operator HIViewRef () const
Returns the object's underlying HIViewRef.
HIViewRef GetViewRef () const
Returns the object's underlying HIViewRef.
HIObjectRef GetObjectRef () const
Returns the object's underlying HIObjectRef.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
SInt32 GetSize () const
Returns the view's size variant.
void SetSize (SInt32 inSize)
Sets the view's size variant.
ControlFontStyleRec GetFontStyle () const
Returns the view's font/style attributes.
void SetFontStyle (const ControlFontStyleRec &inFontStyle)
Sets the view's font/style attributes.
ControlActionUPP GetActionProc () const
Returns the view's action proc.
void SetActionProc (ControlActionUPP inActionProc)
Sets the view's action proc.
HIViewKind GetKind () const
Returns the view's kind. This is an immutable property of the view.
HIViewID GetViewID () const
Returns the view's full HIViewID.
SInt32 GetID () const
Returns the view's HIViewID::id field.
UInt32 GetCommandID () const
Rect GetBounds () const
Rect GetFrame () const
std::pair< Rect, float > GetBestBounds () const
int GetValue () const
Returns the view's current value.
int GetMinimum () const
Returns the view's minimum value.
int GetMaximum () const
Returns the view's maximum value.
HIViewPartCode GetFocusPart () const
Returns the view's currently focused part.
bool IsFocused () const
Returns whether the view has the focus.
HIViewPartCode GetHighlightPart () const
Returns the view's currently highlighted part.
bool IsHighlighted () const
Returns whether the view has a highlighted part.
bool IsActive () const
Returns whether the view is active.
bool IsViewActive () const
Returns whether the view is active, independently of the active state of its parent views.
bool IsEnabled () const
Returns whether the view is enabled.
bool IsViewEnabled () const
Returns whether the view is enabled, independently of the enabled state of its parent views.
bool IsVisible () const
Returns whether the view is visible.
bool IsViewVisible () const
Returns whether the view is visible, independently of the visible state of its parent views.
bool IsCommandSentToUserFocus () const
WindowRef GetOwner () const
void DebugPrint () const
void SetLeftBinding (HIBindingKind inBinding)
Sets the binding of the view's left side.
void SetTopBinding (HIBindingKind inBinding)
Sets the binding of the view's top side.
void SetRightBinding (HIBindingKind inBinding)
Sets the binding of the view's right side.
void SetBottomBinding (HIBindingKind inBinding)
Sets the binding of the view's bottom side.
void SetBindings (HIBindingKind inLeftBinding, HIBindingKind inTopBinding, HIBindingKind inRightBinding, HIBindingKind inBottomBinding)
Sets the bindings of all of the view's sides at once.
void SetHorizontalScale (float inRatio, View *inView=NULL)
Sets the view's horizontal scaling.
void SetVerticalScale (float inRatio, View *inView=NULL)
Sets the view's vertical scaling.
void SetHorizontalPosition (HIPositionKind inPosition, View *inView=NULL, float inOffset=0.0f)
Sets the view's horizontal position.
void SetVerticalPosition (HIPositionKind inPosition, View *inView=NULL, float inOffset=0.0f)
Sets the view's vertical position.
void SetLayout (const HILayoutInfo &inLayout)
Sets the view's full layout info.
HILayoutInfo GetLayout () const
Gets the view's full layout info.
void ApplyLayout ()
Changes the view's size & location to match its layout information.
void SuspendLayout ()
Disables layout for this view and its children.
void ResumeLayout ()
Enables layout for this view and its children.
bool IsLayoutActive () const
Returns whether layout is enabled for this view.
bool IsViewLayoutActive () const
Returns whether layout is enabled for this view, independently of the layout state of its parent views.
const_iterator begin () const
Returns an iterator pointing to the beginning of the view's subviews.
const_iterator end () const
Returns an iterator pointing to the end of the view's subviews.
const_reverse_iterator rbegin () const
Returns an reverse iterator pointing to the beginning of the view's subviews.
const_reverse_iterator rend () const
Returns an reverse iterator pointing to the end of the view's subviews.
HIViewRef FindSubview (int inID) const
Returns the view's subview that matches the main bundle's signature and inID.
HIViewRef FindSubview (const HIViewID &inID) const
HIViewRef FindSubview (int inID, const std::nothrow_t &) const
Returns the view's subview that matches the main bundle's signature and inID, or NULL.
HIViewRef FindSubview (const HIViewID &inID, const std::nothrow_t &) const
template<class VIEW >
VIEW * FindTypedSubview (int inID) const
Returns the view's properly typed subview that matches the main bundle's signature and inID.
template<class VIEW >
VIEW * FindTypedSubview (const HIViewID &inID) const
Static Public Member Functions
Object Creation
template<class T >
static std::pair< OSPtr< HIViewRef >, T * > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, Collection inCollection)
Creates an instance of class T.
template<class T >
static std::pair< OSPtr< HIViewRef >, T * > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, EventRef inEvent)
Creates an instance of class T.
Static Public Member Functions inherited from B::CustomView
template<class T >
static OSPtr< HIViewRef > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, Collection inCollection)
Creates an instance of class T.
template<class T >
static OSPtr< HIViewRef > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, EventRef inEvent)
Creates an instance of class T.
static OSPtr< HIViewRef > Create (CFStringRef inClassID, const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, EventRef inEvent)
Creates an instance of class inClassID.
static CustomView * FromViewRef (HIViewRef inViewRef)
Returns the CustomView object belonging to inViewRef, or NULL.
static void AwakenView (HIViewRef inView, Nib *inFromNib)
Tell inView to awaken.
Static Public Member Functions inherited from B::EventTarget
template<class T >
static void Register ()
Registers class T (which must derive from EventTarget) with the HIToolbox.
template<class T >
static void Unregister ()
Unregisters class T (which must derive from EventTarget) from the HIToolbox.
template<class T >
static HIObjectClassRef GetObjectClass ()
Returns the object class associated with type T (which must derive from EventTarget), or NULL.
template<class T >
static OSPtr< HIObjectRef > Create (EventRef inEvent=NULL)
Creates an instance of class T.
static OSPtr< HIObjectRef > Create (CFStringRef inClassID, EventRef inEvent=NULL)
Creates an instance of class inClassID.
template<class T >
static T * InstanceData (HIObjectRef objRef)
Retrieves the C++ object of type T associated with the HIObjectRef objRef.
template<typename T >
static EventTargetRef GetEventTarget (T inObject)
Retrieves the EventTargetRef associated with inObject.
Static Public Member Functions inherited from B::View
static void InstantiateSubviews (HIViewRef inSuperView, const ViewFactory &inFactory)
Create instances of View for each subview of inSuperView.
static void AwakenViewAndChildren (HIViewRef inView, Nib *inFromNib)
Tell inView and its subviews to awaken.
static View * GetViewFromRef (HIViewRef inViewRef)
Returns the View object associated with inViewRef.
static View * GetViewFromRef (HIViewRef inViewRef, const std::nothrow_t &)
Returns the View object associated with inViewRef, without throwing an exception.
template<class VIEW >
static VIEW * GetTypedViewFromRef (HIViewRef inViewRef)
Returns the properly typed View object associated with inViewRef.
template<class VIEW >
static VIEW * GetTypedViewFromRef (HIViewRef inViewRef, const std::nothrow_t &)
Returns the properly typed View object associated with inViewRef, without throwing an exception.
template<class VIEW >
static VIEW * FindTypedSubview (HIViewRef inSuperview, int inID)
Returns the properly typed subview of inSuperview that matches the main bundle's signature and inID.
template<class VIEW >
static VIEW * FindTypedSubview (HIViewRef inSuperview, const HIViewID &inID)
Protected Member Functions
HybridView (HIObjectRef inObjectRef, EViewFlags inViewFlags)
virtual void Awaken (Nib *inNib)
virtual void InitializeView (Collection inCollection)
virtual void OwningWindowChanged (WindowRef inOriginalWindow, WindowRef inCurrentWindow)
Protected Member Functions inherited from B::CustomView
CustomView (HIObjectRef inObjectRef, EViewFlags inViewFlags)
Constructor.
HIViewRef GetViewRef () const
Returns the view's underlying HIViewRef.
HIViewID GetViewID () const
Returns the view's full HIViewID.
Rect GetBounds () const
Returns the view's bounds.
Rect GetFrame () const
Returns the view's bounds.
int GetValue () const
Returns the view's current value.
int GetMinimum () const
Returns the view's minimum value.
int GetMaximum () const
Returns the view's maximum value.
String GetTitle () const
Returns the view's title, if any.
bool IsFocused () const
Returns whether the view is focused.
bool IsHighlighted () const
Returns whether the view is highlighted.
bool IsActive () const
Returns whether the view is active.
bool IsEnabled () const
Returns whether the view is enabled.
bool IsVisible () const
Returns whether the view is visible.
bool IsCommandSentToUserFocus () const
Returns whether the view sends commands to the user focus.
bool IsContainer () const
Returns whether the view may contain other views.
bool IsCompositing () const
Returns whether the view is currently in a composited window.
WindowRef GetOwner () const
Returns the view's enclosing window, if any.
HIViewPartCode GetFocusPart () const
Returns the view's currently focused part, if any.
HIViewPartCode GetHighlightPart () const
Returns the view's currently highlighted part, if any.
void DebugPrint () const
Prints debugging information to stdout.
virtual void DisposeView ()
View cleanup.
virtual const ViewPartVector & GetViewParts () const
Returns the view parts defined by this view.
virtual ControlKind GetKind () const =0
Returns the view's ControlKind.
virtual UInt32 CalcControlFeatures () const
Computes the Control Manager control features for this view.
virtual void Draw (HIViewPartCode inPart, CGContextRef inContext, const Shape *inDrawShape)
Draws the view.
virtual Shape GetStructureShape () const
Returns the view's structure shape.
virtual Shape GetContentShape () const
Returns the view's content shape.
virtual Shape GetOpaqueShape () const
Returns the view's opaque shape.
virtual Shape GetClickableShape () const
Returns the view's clickable shape.
virtual Shape GetPartShape (HIViewPartCode inPart) const
Returns the shape of one of the view's parts.
virtual bool GetViewShape (HIViewPartCode inPart, Shape &outShape) const
High-level function that returns the shape of one of the view's parts.
virtual Rect GetStructureBounds () const
Returns the bounds of the view's structure shape.
virtual Rect GetContentBounds () const
Returns the bounds of the view's content shape.
virtual Rect GetOpaqueBounds () const
Returns the bounds of the view's opaque shape.
virtual Rect GetClickableBounds () const
Returns the bounds of the view's clickable shape.
virtual Rect GetPartBounds (HIViewPartCode inPart) const
Returns the bounds of the shape of one of the view's parts.
virtual bool GetViewBounds (HIViewPartCode inPart, Rect &outBounds) const
High-level function that returns the bounds of the shape of one of the view's parts.
virtual HIViewPartCode HitTest (const Point &inMouseLoc) const
Returns the view part containing inMouseLoc, if any.
virtual void Hit (HIViewPartCode inPart, UInt32 inKeyModifiers)
The view was hit in inPart.
virtual HIViewPartCode Track (const Point &inMouseLoc, UInt32 inClickCount, UInt32 &ioKeyModifiers)
Perform mouse tracking.
virtual ClickActivationResult GetClickActivation (const Point &inMouseLoc, UInt32 inKeyModifiers, EventMouseButton inMouseButton, UInt32 inClickCount, UInt32 inMouseChord)
Determines whether the view's containing window should be activated when clicked in the background.
virtual HIViewPartCode SetFocusPart (HIViewPartCode inPart, bool inFocusEverything)
High-level function that handles focus-change requests.
virtual bool SetData (HIViewPartCode inPart, ResType inDataTag, const void *inDataPtr, size_t inDataSize)
Changes a piece of view data.
virtual bool GetData (HIViewPartCode inPart, ResType inDataTag, void *inDataPtr, size_t &ioDataSize) const
Retrieves a piece of view data.
virtual Rect GetOptimalBounds () const
Retrieves the view's optimal bounds.
virtual std::pair< Size, Size > GetMinMaxSize () const
Retrieves the view's minimal and maximal sizes.
virtual float GetBaseline () const
Retrieves the view's text baseline.
virtual bool BoundsChanged (UInt32 inAttributes, const Rect &inPreviousBounds, const Rect &inCurrentBounds)
Notifies the view that its bounds have changed.
virtual void HighlightChanged (HIViewPartCode inOldHilitePart, HIViewPartCode inNewHilitePart)
Notifies the view that its highlight state has changed.
virtual void FocusChanging (HIViewPartCode inOldFocusPart, HIViewPartCode inNewFocusPart)
Notifies the view that its focus state has changed.
virtual void ActivateStateChanged (bool inActive)
Notifies the view that its active state has changed.
virtual void VisibilityChanged ()
Notifies the view that its visibility has changed.
virtual void ValueFieldChanged ()
Notifies the view that one of its value/minimum/maximum fields has changed.
virtual void TitleChanged ()
Notifies the view that its title has changed.
virtual void EnabledStateChanged ()
Notifies the view that its enabled state has changed.
virtual void AddedSubview (HIViewRef inSubview)
Notifies the view that a view has been added as one of its children.
virtual void RemovingSubview (HIViewRef inSubview)
Notifies the view that one of its subviews is about to be removed.
virtual bool DragEnter (DragRef inDragRef)
Notifies the view that the user has dragged something into it.
virtual void DragWithin (DragRef inDragRef)
Notifies the view that the user is moving within it during a drag.
virtual void DragLeave (DragRef inDragRef)
Notifies the view that the user is moving out of it during a drag.
virtual bool DragReceive (DragRef inDragRef)
Notifies the view that the user has dropped something onto it.
virtual bool TextInput (const UniChar *inText, size_t inLength, EventRef inKeyboardEvent)
Notifies the view that the user has entered some text.
virtual void GetScrollInfo (Size &outImageSize, Size &outViewSize, Size &outLineSize, Point &outOrigin) const
Retrieves the view's scroll information.
virtual void ScrollTo (const Point &inOrigin)
Tells the view to move its origin.
virtual bool HandleCommand (const HICommandExtended &inHICommand)
Handles an HICommand.
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
Returns the status of an HICommand.
virtual void TrackingAreaEntered (HIViewTrackingAreaRef inTrackingRef, const Point &inMouseLocation, UInt32 inKeyModifiers)
The mouse has just entered the tracking region identified by inTrackingRef.
virtual void TrackingAreaExited (HIViewTrackingAreaRef inTrackingRef, const Point &inMouseLocation, UInt32 inKeyModifiers)
The mouse has just left the tracking region identified by inTrackingRef.
bool HandleChooseKey (HIViewPartCode inPart, const UniChar *inText, size_t inLength, EventRef inKeyboardEvent)
Handles translating a "space" key press into a click.
HIViewPartCode FindNextPart (HIViewPartCode inStartPart, bool inFocusEverything) const
Returns the next focusable part after inStartPart, if any.
HIViewPartCode FindPreviousPart (HIViewPartCode inStartPart, bool inFocusEverything) const
Returns the focusable part before inStartPart, if any.
bool FindPart (HIViewPartCode inPart) const
Returns true if inPart is a known part.
void ScrollInfoChanged () const
Notifies the view's superview that its scroll information has changed.
void SetFrame (const Rect &inNewFrame)
void MoveFrameBy (float deltaX, float deltaY)
void MoveFrameTo (float x, float y)
void ResizeFrameBy (float deltaWidth, float deltaHeight)
void ResizeFrameTo (float width, float height)
void SetOrigin (const HIPoint &inOrigin)
Changes the view's origin (useful for scrollable views).
void SetValue (int inValue)
Changes the view's current value.
void SetMinimum (int inMininum)
Changes the view's minimum value.
void SetMaximum (int inMaximum)
Changes the view's maximum value.
void SetTitle (const String &inTitle)
Changes the view's title.
void SetHighlight (HIViewPartCode inPart)
Changes the view's highlighted part.
void Activate (bool inActivate)
Changes the view's active state.
void Enable (bool inEnable)
Changes the view's enabled state.
void Show (bool inShow)
Changes the view's visible state.
void SendCommandToUserFocus (bool inSendIt)
Changes the destination of HICommands generated by the view.
void Reshape ()
Notifies the HIView system that the view's contours have changed.
void Invalidate ()
Invalidates the entire view.
void Invalidate (const Rect &inRect)
Invalidates a portion of the view.
void Invalidate (const Shape &inShape)
Invalidates a portion of the view.
void Invalidate (const MutableShape &inShape)
Invalidates a portion of the view.
void InvalidatePart (HIViewPartCode inPart)
Invalidates one of the view's parts.
void AddSubview (HIViewRef subview)
Adds a subview to this view.
Protected Member Functions inherited from B::EventTarget
EventTarget (HIObjectRef inObjectRef)
Constructor.
virtual ~EventTarget ()
Destructor.
void operator delete (void *ptr)
Protected delete prevents external clients from deleting instances directly.
virtual void Initialize (EventRef inEvent)
Override to extract initialisation arguments from inEvent.
virtual bool IsEqualTo (HIObjectRef inObjectRef)
Returns true if this is "equal" to inObjectRef.
virtual void PrintDebugInfo ()
Override to print debugging information to stdout.
virtual void Unarchive (HIArchiveRef ioArchive)
Decode the object into the given archive. This is called instead of Initialize().
virtual void Archive (HIArchiveRef ioArchive) const
Encode the object into the given archive.
Protected Member Functions inherited from B::View
View (HIViewRef inViewRef)
Additional Inherited Members
Public Types inherited from B::CustomView
enum EViewFlags {
kViewNone = 0x00000000, kViewOpaque = 0x00000001, kViewFocus = 0x00000002, kViewFocusOnClick = 0x00000004,
kViewContainer = 0x00000008, kViewDragAndDrop = 0x00000010, kViewScrollable = 0x00000020, kViewCommands = 0x00000040,
kViewHit = 0x00000080, kViewTracking = 0x00000100, kViewTrackingArea = 0x00000200, kViewLiveFeedback = 0x00000400,
kViewClickActivation = 0x00000800, kViewNoDrawing = 0x00010000, kViewNoClicking = 0x00020000, kViewInvalOnActivate = 0x00100000,
kViewInvalOnHilite = 0x00200000, kViewInvalOnEnable = 0x00400000, kViewInvalOnValue = 0x00800000, kViewInvalOnTitle = 0x01000000,
kViewInvalOnFocus = 0x02000000
}
Flags controlling view behaviour.
enum EViewPartFocus { kFocusAlways = 1, kFocusNever, kFocusFull }
The focus behaviour of a view part.
typedef std::pair< HIViewPartCode, EViewPartFocus > ViewPart
Associates a view part (identified by its part code) and a focus behaviour.
typedef std::vector< ViewPart > ViewPartVector
Defines all of a view's parts and their focus behaviour.
Public Types inherited from B::View
typedef ViewUtils::SubviewIterator const_iterator
A constant iterator that moves forward through a view's subviews.
typedef ViewUtils::ReverseSubviewIterator const_reverse_iterator
A constant iterator that moves backward through a view's subviews.
Static Public Attributes inherited from B::CustomView
static const CFStringRef kHIObjectBaseClassID = kHIViewClassID
The default HIObject base class for views.
Static Public Attributes inherited from B::EventTarget
static const CFStringRef kHIObjectBaseClassID = NULL
The default base class ID, representing HIObject.
Protected Types inherited from B::EventTarget
typedef EventTarget *(* ConstructProcPtr) (HIObjectRef inObjectRef)
Object construction callback.
Static Protected Member Functions inherited from B::CustomView
static HIViewTrackingAreaID GetTrackingAreaID (HIViewTrackingAreaRef inTrackingRef)
Returns the given tracking area's ID.
static void SetTrackingAreaShape (HIViewTrackingAreaRef inTrackingRef, const Shape &inShape)
Changes the given tracking area's shape.
static void RemoveSubview (HIViewRef subview)
Removes a subview.
Static Protected Member Functions inherited from B::EventTarget
static void PrivateRegister (CFStringRef inClassID, CFStringRef inBaseClassID, ConstructProcPtr inConstructor)
Registers class inClassID.
static void PrivateUnregister (CFStringRef inClassID)
Unregisters class inClassID.
static HIObjectClassRef PrivateFindClassObject (CFStringRef inClassID)
Returns the object class associated with type inClassID, or NULL.
static HIObjectRef PrivateCreate (CFStringRef inClassID, EventRef inEvent)
Creates an instance of class inClassID.
Protected Attributes inherited from B::CustomView
const EViewFlags mViewFlags
The view's flags.
bool mAwakened
Protected Attributes inherited from B::EventTarget
const HIObjectRef mObjectRef
The underlying toolbox object.
Protected Attributes inherited from B::View
bool mAwakened
Detailed Description
Base class for implementations of HIView that can also be used by clients of the view.
Todo:
Document this class!
Member Function Documentation
template<class T > std::pair< OSPtr< HIViewRef >, T * > B::HybridView::Create (const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, Collection inCollection) static
Creates an instance of class T.
Parameters
T The C/C++ type of the view. Must be HybridView or derived from HybridView.
Parameters
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inCollection Initialisation data for the new view; may be NULL.
References B::OSPtr< T >::get().
template<class T > std::pair< OSPtr< HIViewRef >, T * > B::HybridView::Create (const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, EventRef inEvent) static
Creates an instance of class T.
Parameters
T The C/C++ type of the view. Must be HybridView or derived from HybridView.
Parameters
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inEvent Initialisation data for the new view; may be NULL.
References B::OSPtr< T >::get().
void B::HybridView::InitializeView (Collection inCollection) protected virtual
Perform any initialisation of the view. Derived classes may override this to set up the view's initial state. Such overrides should call the base class implementation prior to performing work of their own.
Reimplemented from B::CustomView.
References B::CustomView::InitializeView(), and B::CustomView::OwningWindowChanged().
The documentation for this class was generated from the following files:
BHybridView.h
BHybridView.cpp