B: B::AutoAEWriterRecord Class Reference
B::AutoAEWriterRecord Class Reference
Apple Events
A stack-based class for opening a descriptor record.
#include <BAEWriter.h>
Public Member Functions
AutoAEWriterRecord (AEWriter &writer)
Opens a descriptor record.
AutoAEWriterRecord (AEWriter &writer, DescType type)
Opens a descriptor record of type type.
AutoAEWriterRecord (AEWriter &writer, DescType type, AEKeyword key)
Opens a descriptor record of type type, identified by key.
~AutoAEWriterRecord ()
Destructor.
Detailed Description
A stack-based class for opening a descriptor record.
The constructor opens the descriptor record, the destructor closes it.
Constructor & Destructor Documentation
B::AutoAEWriterRecord::AutoAEWriterRecord (AEWriter & writer)
Opens a descriptor record.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
References B::AEWriter::OpenRecord().
B::AutoAEWriterRecord::AutoAEWriterRecord (AEWriter & writer, DescType type)
Opens a descriptor record of type type.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
References B::AEWriter::OpenRecord().
B::AutoAEWriterRecord::AutoAEWriterRecord (AEWriter & writer, DescType type, AEKeyword key)
Opens a descriptor record of type type, identified by key.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
References B::AEWriter::OpenRecordKey().
The documentation for this class was generated from the following files:
BAEWriter.h
BAEWriter.cpp