B: B::String Class Reference
B::String Class Reference
Adapter class for immutable strings.
#include <BString.h>
Classes
class const_iterator
Non-modifiable iterator on a string.
class iterator
Modifiable iterator on a string.
class reference
Modifiable reference to a character in a string.
Public Types
Types
typedef UniChar value_type
The type of the characters.
typedef size_t size_type
The unsigned integral type for size values and indices.
typedef ptrdiff_t difference_type
The signed integral type for difference values.
typedef value_type const_reference
The type of constant character references.
typedef value_type * pointer
The type of constant character pointers.
typedef const value_type * const_pointer
The type of constant character pointers.
typedef CFAllocatorRef allocator_type
The type of constant iterators.
typedef std::reverse_iterator< iterator > reverse_iterator
The type of reverse iterators.
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
The type of constant reverse iterators.
Public Member Functions
Constructors / Destructor
String ()
Default constructor.
String (const String &str)
Copy constructor.
String (CFAllocatorRef allocator)
Allocator constructor.
String (const String &str, size_type pos, size_type n=npos, CFAllocatorRef allocator=NULL)
String constructor.
String (const MutableString &str)
MutableString constructor.
String (const MutableString &str, size_type pos, size_type n=npos, CFAllocatorRef allocator=NULL)
MutableString constructor.
String (CFStringRef cfstr)
CFStringRef constructor.
String (CFStringRef cfstr, const from_copy_t &)
CFStringRef constructor.
String (CFStringRef cfstr, const std::nothrow_t &)
CFStringRef constructor.
String (CFStringRef cfstr, const from_copy_t &, const std::nothrow_t &)
CFStringRef constructor.
String (CFStringRef cfstr, size_type pos, size_type n=npos, CFAllocatorRef allocator=NULL)
CFStringRef constructor.
String (const UniChar *ustr, size_type n=npos, CFAllocatorRef allocator=NULL)
UniChar array constructor.
String (size_type n, UniChar c, CFAllocatorRef allocator=NULL)
UniChar constructor.
String (const std::wstring &wstr, size_type pos=0, size_type n=npos, CFAllocatorRef allocator=NULL)
std::wstring constructor.
String (const wchar_t *wcstr, size_type n=npos, CFAllocatorRef allocator=NULL)
wchar_t array constructor.
String (const std::string &sstr, CFStringEncoding encoding=kCFStringEncodingASCII, size_type pos=0, size_type n=npos, CFAllocatorRef allocator=NULL)
std::string constructor.
String (const char *cstr, CFStringEncoding encoding=kCFStringEncodingASCII, size_type n=npos, CFAllocatorRef allocator=NULL)
char* array constructor.
String (ConstStringPtr pstr, CFStringEncoding encoding=kCFStringEncodingASCII, CFAllocatorRef allocator=NULL)
Pascal string constructor.
String (const std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external, CFAllocatorRef allocator=NULL)
Blob constructor.
String (const OSPtr< CFStringRef > &cfstr)
OSPtr<CFStringRef> constructor.
String (const OSPtr< CFMutableStringRef > &cfstr)
OSPtr<CFMutableStringRef> constructor.
template<class InputIterator >
String (InputIterator first, InputIterator last, CFAllocatorRef allocator=NULL)
Range constructor.
~String ()
Destructor.
Operations for Size and Capacity
size_type size () const
Returns the number of characters in the string.
size_type length () const
Returns the number of characters in the string.
bool empty () const
Returns whether the string is empty.
size_type max_size () const
Returns the maximum number of characters a string could contain.
size_type capacity () const
Returns the number of characters the string could contain without reallocation.
Comparisons
int compare (const String &str) const
Compares the string to str.
int compare (size_type pos1, size_type n1, const String &str) const
Compares the string to str.
int compare (size_type pos1, size_type n1, const String &str, size_type pos2, size_type n2) const
Compares the string to str.
int compare (CFStringRef cfstr) const
Compares the string to cfstr.
int compare (size_type pos1, size_type n1, CFStringRef cfstr) const
Compares the string to cfstr.
int compare (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2) const
Compares the string to cfstr.
int compare (const UniChar *ustr) const
Compares the string to ustr.
int compare (size_type pos1, size_type n1, const UniChar *ustr) const
Compares the string to ustr.
int compare (size_type pos1, size_type n1, const UniChar *ustr, size_type n2) const
Compares the string to ustr.
int compare (const std::string &sstr, CFStringEncoding encoding) const
Compares the string to sstr.
int compare (size_type pos1, size_type n1, const std::string &sstr, CFStringEncoding encoding) const
Compares the string to sstr.
int compare (size_type pos1, size_type n1, const std::string &sstr, CFStringEncoding encoding, size_type pos2, size_type n2) const
Compares the string to sstr.
Character Access
const_reference operator[] (size_type pos) const
Returns the character at index pos.
const_reference at (size_type pos) const
Returns the character at index pos.
Generating CFStringRefs and Character Arrays.
Because of the fundamental differences in underlying storage between String and std::basic_string<>, it's impossible to provide direct counterparts to std::basic_string<>c_str() and std::basic_string<>data(). cf_ref() is analogous to c_str().
The various overloads of copy() allow conversions from String to a number of output types.
CFStringRef cf_ref () const
Returns the underlying CFStringRef.
OSPtr< CFStringRef > cf_ptr () const
Returns a "smart pointer" to the underlying CFStringRef.
size_type copy (UniChar *ustr, size_type n, size_type pos=0) const
Copies the string to a UniChar array.
size_type copy (wchar_t *wcstr, size_type n, size_type pos=0) const
Copies the string to a wchar_t array.
size_type copy (char *cstr, size_type n, size_type &pos, CFStringEncoding encoding) const
Copies at most n bytes, starting at index pos in *this, into the buffer pointed to by cstr.
void copy (CFMutableStringRef cfstr) const
Copies the string to a CFMutableStringRef.
void copy (std::wstring &wstr) const
Copies the string to a std::wstring.
void copy (std::string &sstr, CFStringEncoding encoding) const
Copies the string to a std::string.
void copy (StringPtr pstr, size_type n, CFStringEncoding encoding) const
Copies the string to a Pascal String.
void copy (std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external, char loss_byte=0) const
Copies the string to a blob.
Assignment
These various overloads of operator = and assign() replace the string's underlying CFStringRef.
String & operator= (const String &str)
String assignemnt.
String & operator= (const MutableString &str)
MutableString assignemnt.
String & operator= (CFStringRef cfstr)
CFStringRef assignemnt.
String & operator= (CFMutableStringRef cfstr)
CFMutableStringRef assignemnt.
String & operator= (const OSPtr< CFStringRef > &cfstr)
OSPtr<CFStringRef> assignemnt.
String & operator= (const OSPtr< CFMutableStringRef > &cfstr)
OSPtr<CFMutableStringRef> assignemnt.
String & operator= (const UniChar *ustr)
UniChar array assignemnt.
String & operator= (UniChar c)
UniChar assignemnt.
String & operator= (const std::wstring &wstr)
std::wstring assignemnt.
String & operator= (const wchar_t *ustr)
Null-terminated wchar_t array assignemnt.
String & operator= (const std::string &sstr)
std::string assignemnt.
String & operator= (const char *cstr)
Null-terminated char array assignemnt.
String & operator= (ConstStringPtr pstr)
Pascal string assignemnt.
String & assign (const String &str, size_type pos=0, size_type n=npos)
String assignemnt.
String & assign (const MutableString &str, size_type pos=0, size_type n=npos)
MutableString assignemnt.
String & assign (CFStringRef cfstr)
CFStringRef assignemnt.
String & assign (CFStringRef cfstr, const from_copy_t &)
CFStringRef assignemnt.
String & assign (CFStringRef cfstr, const std::nothrow_t &)
CFStringRef assignemnt.
String & assign (CFStringRef cfstr, const from_copy_t &, const std::nothrow_t &)
CFStringRef assignemnt.
String & assign (CFStringRef cfstr, size_type pos, size_type n=npos)
CFStringRef assignemnt.
String & assign (const UniChar *ustr, size_type n=npos)
UniChar array assignemnt.
String & assign (size_type n, UniChar c)
UniChar assignemnt.
String & assign (const std::wstring &wstr, size_type pos=0, size_type n=npos)
std::wstring assignemnt.
String & assign (const wchar_t *wcstr, size_type n=npos)
wchar_t array assignemnt.
String & assign (const std::string &sstr, CFStringEncoding encoding, size_type pos=0, size_type n=npos)
std::string assignemnt.
String & assign (const char *cstr, CFStringEncoding encoding, size_type n=npos)
char array assignemnt.
String & assign (ConstStringPtr pstr, CFStringEncoding encoding)
Pascal string assignemnt.
String & assign (const std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external)
Blob assignemnt.
template<class InputIterator >
String & assign (InputIterator first, InputIterator last)
Range assignment.
void swap (String &str)
Exchanges the contents of the string with str.
Erasing Characters
void clear ()
Removes all characters.
Finding a Character
size_type find (UniChar c, size_type pos=0) const
Finds the first occurrence of given character.
size_type rfind (UniChar c, size_type pos=0) const
Finds the last occurrence of given character.
Finding a Substring
size_type find (const String &str, size_type pos=0) const
Finds the first String.
size_type rfind (const String &str, size_type pos=0) const
Finds the last String.
size_type find (CFStringRef cfstr, size_type pos=0) const
Finds the first CFStringRef.
size_type rfind (CFStringRef cfstr, size_type pos=0) const
Finds the last CFStringRef.
size_type find (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the first UniChar array.
size_type rfind (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the last UniChar array.
size_type find (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first std::string.
size_type rfind (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last std::string.
Finding the First of a Set of Characters
size_type find_first_of (const String &str, size_type pos=0) const
Finds the first character in a set given as a String.
size_type find_first_not_of (const String &str, size_type pos=0) const
Finds the first character not in a set given as a String.
size_type find_first_of (CFStringRef cfstr, size_type pos=0) const
Finds the first character in a set given as a CFStringRef.
size_type find_first_not_of (CFStringRef cfstr, size_type pos=0) const
Finds the first character not in a set given as a CFStringRef.
size_type find_first_of (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the first character in a set given as a UniChar array.
size_type find_first_not_of (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the first character not in a set given as a UniChar array.
size_type find_first_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first character in a set given as a std::string.
size_type find_first_not_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first character not in a set given as a std::string.
Finding the Last of a Set of Characters
size_type find_last_of (const String &str, size_type pos=0) const
Finds the last character in a set given as a String.
size_type find_last_not_of (const String &str, size_type pos=0) const
Finds the last character not in a set given as a String.
size_type find_last_of (CFStringRef cfstr, size_type pos=0) const
Finds the last character in a set given as a CFStringRef.
size_type find_last_not_of (CFStringRef cfstr, size_type pos=0) const
Finds the last character not in a set given as a CFStringRef.
size_type find_last_of (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the last character in a set given as a UniChar array.
size_type find_last_not_of (const UniChar *ustr, size_type pos=0, size_type n=npos) const
Finds the last character not in a set given as a UniChar array.
size_type find_last_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last character in a set given as a std::string.
size_type find_last_not_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last character not in a set given as a std::string.
Substrings
String substr (size_type pos=0, size_type n=npos) const
Returns a substring.
Generating Iterators
const_iterator begin () const
Returns a constant random access iterator for the beginning of the string.
const_iterator end () const
Returns a constant random access iterator for the end of the string.
const_reverse_iterator rbegin () const
Returns a constant random access iterator for the beginning of a reverse iteration of the string.
const_reverse_iterator rend () const
Returns a constant random access iterator for the end of a reverse iteration of the string.
Allocator Support
allocator_type get_allocator () const
Returns the string's allocator.
I/O Support
std::ostream & Write (std::ostream &ostr, CFStringEncoding encoding) const
Write the characters of str to ostr.
std::istream & Read (std::istream &istr, CFStringEncoding encoding)
Reads the characters of the next word from istr into the string.
std::istream & GetLine (std::istream &istr, char delim, CFStringEncoding encoding)
Reads the characters of the next line from istr into the string.
Static Public Attributes
Constants
static const size_type npos = size_type(-1)
Sentinel value meaning "not found" or "all remaining characters".
Friends
class MutableString
Related Functions
(Note that these are not member functions.)
String Concatenation
String operator+ (const String &s1, const String &s2)
Input/Output Functions
String only supports I/O to char streams (i.e., std::basic_ostream<char,char_traits<char>>).
std::ostream & operator<< (std::ostream &os, const String &str)
std::istream & operator>> (std::istream &is, String &str)
std::istream & getline (std::istream &is, String &str, char delim)
std::istream & getline (std::istream &is, String &str)
String Comparisons
bool operator== (const String &s1, const String &s2)
bool operator!= (const String &s1, const String &s2)
bool operator< (const String &s1, const String &s2)
bool operator<= (const String &s1, const String &s2)
bool operator> (const String &s1, const String &s2)
bool operator>= (const String &s1, const String &s2)
Miscellaneous
void swap (String &s1, String &s2)
Detailed Description
Adapter class for immutable strings.
String provides a wrapper around a CoreFoundation CFStringRef object, giving it an interface similar (nearly identical in fact) to std::string. This makes it possible to use String with STL algorithms, with standard streams, etc.
String tries to share its underlying CFStringRef whenever possible.
Specifically, String implements the const member functions of std::string. This reflects the immutable nature of the underlying CFStringRef. The exception to this is the various overloads of operator = () and assign(), whose absence would have made the class much more difficult to use; they are implemented by replacing the underlying CFStringRef, rather than by changing its contents.
Other notable differences with std::basic_string<...>:
- There are no template parameters, because CFStrings only have one underlying
  character type, namely @c UniChar.  One can think of String as
  analogous to <tt>std::basic_string<UniChar,char_traits<UniChar>,CFAllocatorRef></tt>.
- There are many more conversions.  This reflects String's role as an adapter
  between CoreFoundation and the Standard C++ Library.  For example, one may
  construct instances of String with any of the following types:
    - String
    - MutableString
    - <tt>CFStringRef</tt>
    - <tt>const UniChar*</tt>
    - <tt>std::string</tt>
    - <tt>std::wstring</tt>
    - <tt>const char*</tt>
    - <tt>const wchar_t*</tt>
    - <tt>UniChar</tt>
    - <tt>ConstStringPtr</tt>
    - <tt>std::vector<UInt8></tt>
- Likewise, one may copy() a String into one of the following data structures:
    - <tt>CFMutableStringRef</tt>
    - <tt>std::string</tt>
    - <tt>std::wstring</tt>
    - <tt>char*</tt>
    - <tt>wchar_t*</tt>
    - <tt>UniChar*</tt>
    - <tt>StringPtr</tt>
    - <tt>std::vector<UInt8></tt>
- The allocator type is fixed as @c CFAllocatorRef.  The allocator type is not a
  template parameter, however allocators @e are passed as arguments to
  constructors and can be retrieved via get_allocator().
- The underlying @c CFStringRef's storage is not accessible, so it's not
  possible to take the address of an element of a String.  String
  is incompatible with the STL in this respect.
A number of related #defines provide support for localised strings, and are designed to integrate with Apple's localisation tools such as genstrings. They are:
- #BLocalizedString
- #BLocalizedStringFromTable
- #BLocalizedStringFromTableInBundle
- #BLocalizedStringWithDefaultValue
Member Typedef Documentation
typedef CFAllocatorRef B::String::allocator_type
The type of constant iterators.
The type of the allocator.
Constructor & Destructor Documentation
B::String::String ()
Default constructor.
Creates an empty string using the default allocator.
Referenced by B::operator+(), operator+(), and substr().
B::String::String (const String & str)
Copy constructor.
Creates a string as a copy of str, using str's allocator.
Parameters
str The source string.
B::String::String (CFAllocatorRef allocator) explicit
Allocator constructor.
Parameters
allocator The new object's allocator.
B::String::String (const String & str, size_type pos, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
String constructor.
Creates a string that is initialised by, at most, the first n characters of str starting with index pos.
Parameters
str The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (const MutableString & str) explicit
MutableString constructor.
Creates a string as a copy of str, using str's allocator.
Parameters
str The source string.
References B::MutableString::cf_ref(), and B::MutableString::get_allocator().
B::String::String (const MutableString & str, size_type pos, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
MutableString constructor.
Creates a string that is initialised by, at most, the first n characters of str starting with index pos.
Parameters
str The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (CFStringRef cfstr) explicit
CFStringRef constructor.
Creates a string as a copy of cfstr, using cfstr's allocator.
Parameters
cfstr The source string.
B::String::String (CFStringRef cfstr, const from_copy_t &) explicit
CFStringRef constructor.
Creates a string as a copy of cfstr, using cfstr's allocator. The input string's retain count is not incremented.
Parameters
cfstr The source string.
B::String::String (CFStringRef cfstr, const std::nothrow_t &) explicit
CFStringRef constructor.
Creates a string as a copy of cfstr, using cfstr's allocator. If cfstr is NULL, use an empty string instead.
Parameters
cfstr The source string.
B::String::String (CFStringRef cfstr, const from_copy_t & , const std::nothrow_t &) explicit
CFStringRef constructor.
Creates a string as a copy of cfstr, using cfstr's allocator. If cfstr is NULL, use an empty string instead. The input string's retain count is not incremented.
Parameters
cfstr The source string.
B::String::String (CFStringRef cfstr, size_type pos, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
CFStringRef constructor.
Creates a new string that is initialised by, at most, the first n characters of cfstr starting with index pos.
Parameters
cfstr The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (const UniChar * ustr, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
UniChar array constructor.
Creates a string that is initialised by, at most, the first n characters of ustr. If n is npos, then ustr is assumed to be null-terminated; else, NULL ('\0') characters have no special meaning.
Parameters
ustr The source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (size_type n, UniChar c, CFAllocatorRef allocator = NULL) explicit
UniChar constructor.
Creates a string that is initialised by n occurrences of character c.
Parameters
n The number of occurrences of c.
c The character to copy.
allocator The new object's allocator.
B::String::String (const std::wstring & wstr, size_type pos = 0, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
std::wstring constructor.
Creates a string that is initialised by, at most, the first n characters of wstr starting with index pos.
Parameters
wstr The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (const wchar_t * wcstr, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
wchar_t array constructor.
Creates a string that is initialised by, at most, the first n characters of wcstr. If n is npos, then wcstr is assumed to be null-terminated; else, NULL (L'\0') characters have no special meaning.
Parameters
wcstr The source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (const std::string & sstr, CFStringEncoding encoding = kCFStringEncodingASCII, size_type pos = 0, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
std::string constructor.
Creates a string that is initialised by, at most, the first n characters of sstr starting with index pos. The source string is assumed to be encoded using the character encoding given in encoding.
Note
The default value for encoding is kCFStringEncodingASCII. This allows the caller to pass in a string literal without having to worry about specifying an encoding. It also will be more likely to catch errors (erroneous encodings).
Parameters
sstr The source string.
encoding The character encoding of the source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (const char * cstr, CFStringEncoding encoding = kCFStringEncodingASCII, size_type n = npos, CFAllocatorRef allocator = NULL) explicit
char* array constructor.
Creates a string that is initialised by, at most, the first n characters of cstr. If n is npos, then cstr is assumed to be null-terminated; else, NULL ('\0') characters have no special meaning. The source string is assumed to be encoded using the character encoding given in encoding.
Note
The default value for encoding is kCFStringEncodingASCII. This allows the caller to pass in a string literal without having to worry about specifying an encoding. It also will be more likely to catch errors (erroneous encodings).
Parameters
cstr The source string.
encoding The character encoding of the source string.
n The number of characters to copy.
allocator The new object's allocator.
B::String::String (ConstStringPtr pstr, CFStringEncoding encoding = kCFStringEncodingASCII, CFAllocatorRef allocator = NULL) explicit
Pascal string constructor.
Creates a string that is initialised by pstr. The source string is assumed to be encoded using the character encoding given in encoding.
Note
The default value for encoding is kCFStringEncodingASCII. This allows the caller to pass in a string literal without having to worry about specifying an encoding. It also will be more likely to catch errors (erroneous encodings).
Parameters
pstr The source string.
encoding The character encoding of the source string.
allocator The new object's allocator.
B::String::String (const std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external, CFAllocatorRef allocator = NULL) explicit
Blob constructor.
Creates a string that is initialised by blob. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
blob The source blob.
encoding The character encoding of blob.
external If true, checks for BOM and performs byte-swapping as necessary.
allocator The new object's allocator.
B::String::String (const OSPtr< CFStringRef > & cfstr) explicit
OSPtr<CFStringRef> constructor.
Creates a string as a copy of cfstr, using cfstr's allocator.
Parameters
cfstr The source string.
References B::OSPtr< T >::get().
B::String::String (const OSPtr< CFMutableStringRef > & cfstr) explicit
OSPtr<CFMutableStringRef> constructor.
Creates a string as a copy of cfstr, using cfstr's allocator.
Parameters
cfstr The source string.
References B::OSPtr< T >::get().
template<class InputIterator > B::String::String (InputIterator first, InputIterator last, CFAllocatorRef allocator = NULL) explicit
Range constructor.
Creates a string that is initialised by all character of the range [first, last).
Parameters
first The start of the range of characters for the new string.
last The end of the range of characters for the new string.
allocator The new object's allocator.
Member Function Documentation
int B::String::compare (const String & str) const
Compares the string to str.
Compares the string *this with the string str.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Parameters
str The string to compare against.
References cf_ref().
Referenced by operator!=(), B::operator!=(), operator<(), B::operator<(), operator<=(), B::operator<=(), operator==(), B::operator==(), operator>(), B::operator>(), operator>=(), and B::operator>=().
int B::String::compare (size_type pos1, size_type n1, const String & str) const
Compares the string to str.
Compares, at most, n1 characters of string *this, starting with index pos1 with string str.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
str The string to compare against.
References cf_ref().
int B::String::compare (size_type pos1, size_type n1, const String & str, size_type pos2, size_type n2) const
Compares the string to str.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string str starting with index pos2.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Exceptions
std::out_of_range If pos1 > size() or pos2 > str.size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
str The string to compare against.
pos2 The index of the first character to compare in str.
n2 The number of characters to compare in str.
References cf_ref().
int B::String::compare (CFStringRef cfstr) const
Compares the string to cfstr.
Compares the string *this with the string cfstr.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Parameters
cfstr The string to compare against.
int B::String::compare (size_type pos1, size_type n1, CFStringRef cfstr) const
Compares the string to cfstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with string cfstr.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
cfstr The string to compare against.
int B::String::compare (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2) const
Compares the string to cfstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string cfstr starting with index pos2.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Exceptions
std::out_of_range If pos1 > size() or pos2 > CFStringGetLength(cfstr).
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
cfstr The string to compare against.
pos2 The index of the first character to compare in cfstr.
n2 The number of characters to compare in cfstr.
int B::String::compare (const UniChar * ustr) const
Compares the string to ustr.
Compares the string *this with the null-terminated UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Parameters
ustr The string to compare against.
int B::String::compare (size_type pos1, size_type n1, const UniChar * ustr) const
Compares the string to ustr.
Compares, at most, n1 characters of string *this, starting with index pos1 with the null-terminated UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
ustr The string to compare against.
int B::String::compare (size_type pos1, size_type n1, const UniChar * ustr, size_type n2) const
Compares the string to ustr.
Compares, at most, n1 characters of string *this, starting with index pos1 with n2 characters of UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
ustr The string to compare against.
n2 The number of characters to compare in ustr.
int B::String::compare (const std::string & sstr, CFStringEncoding encoding) const
Compares the string to sstr.
Compares the string *this with the string sstr, which is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Parameters
sstr The string to compare against.
encoding The character encoding of sstr.
int B::String::compare (size_type pos1, size_type n1, const std::string & sstr, CFStringEncoding encoding) const
Compares the string to sstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with the string sstr, which is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
sstr The string to compare against.
encoding The character encoding of sstr.
int B::String::compare (size_type pos1, size_type n1, const std::string & sstr, CFStringEncoding encoding, size_type pos2, size_type n2) const
Compares the string to sstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string sstr starting with index pos2. Sstr is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Exceptions
std::out_of_range If pos1 > size() or pos2 > sstr.size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
sstr The string to compare against.
encoding The character encoding of sstr.
pos2 The index of the first character to compare in str.
n2 The number of characters to compare in sstr.
String::const_reference B::String::operator[] (size_type pos) const
Returns the character at index pos.
If pos equals length(), the function returns '\0'. If pos is smaller than zero or greater than length(), the results are undefined.
Parameters
pos The index of the character to return.
References length().
String::const_reference B::String::at (size_type pos) const
Returns the character at index pos.
If pos is smaller than zero or greater than or equal to length(), the function throws an std::out_of_range exception.
Exceptions
std::out_of_range
References npos, and size().
String::size_type B::String::copy (UniChar * ustr, size_type n, size_type pos = 0) const
Copies the string to a UniChar array.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by ustr. No null character is appended.
Returns
The number of copied characters.
Parameters
ustr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion.
Referenced by B::CreateImageFromURL(), B::ExceptionStringHolder::GetString(), B::HelpButton::Instantiate(), B::InteractWithUserDialog::InteractWithUserDialog(), B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentWriteStream(), B::ExceptionStreamer::Rethrow(), B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Set(), B::InteractWithUserDialog::SetText(), and Write().
String::size_type B::String::copy (wchar_t * wcstr, size_type n, size_type pos = 0) const
Copies the string to a wchar_t array.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by wcstr. The string's characters are converted to wchar_t upon copying. No null character is appended.
Returns
The number of copied characters.
Parameters
wcstr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion.
String::size_type B::String::copy (char * cstr, size_type n, size_type & pos, CFStringEncoding encoding) const
Copies at most n bytes, starting at index pos in *this, into the buffer pointed to by cstr.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by wcstr. The string's characters are converted to encoding upon copying. No null character is appended.
Returns
The number of copied characters.
Parameters
cstr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion. On output, holds the index of the next character to convert, or npos if conversion is complete.
encoding The output buffer's encoding.
void B::String::copy (CFMutableStringRef cfstr) const
Copies the string to a CFMutableStringRef.
The current contents of cfstr are completely replaced. If cfstr doesn't have enough capacity to hold the contents, the results are undefined.
Parameters
cfstr The output string.
References cf_ref().
void B::String::copy (std::wstring & wstr) const
Copies the string to a std::wstring.
The string's characters are converted to wchar_t upon copying.
Parameters
wstr The output string.
void B::String::copy (std::string & sstr, CFStringEncoding encoding) const
Copies the string to a std::string.
The string's characters are converted to encoding upon copying.
Parameters
sstr The output string.
encoding The output string's encoding.
void B::String::copy (StringPtr pstr, size_type n, CFStringEncoding encoding) const
Copies the string to a Pascal String.
The string's characters are converted to encoding upon copying.
Parameters
pstr The output string.
n The maximum size of the output string, including length byte.
encoding The output string's encoding.
void B::String::copy (std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external, char loss_byte = 0) const
Copies the string to a blob.
If external is true, then the string is converted to an "external form", which usually means it is made suitable for writing to a file. In Unicode-speak, this implies prepending a BOM (Byte-Order Mark) character. The string's characters are converted to encoding upon copying. If loss_byte is non-zero, then any characters unconvertible to encoding will be replaced by loss_byte; else, conversion errors will cause an exception.
Parameters
blob The output buffer.
encoding The output string's encoding.
external If true, blob get a leading BOM.
loss_byte The character to substitute for unconvertible characters.
String & B::String::operator= (const String & str)
String assignemnt.
Parameters
str The input string.
References cf_ref().
String & B::String::operator= (const MutableString & str)
MutableString assignemnt.
Parameters
str The input string.
References swap().
String & B::String::operator= (CFStringRef cfstr)
CFStringRef assignemnt.
Parameters
cfstr The input string.
String & B::String::operator= (const OSPtr< CFStringRef > & cfstr)
OSPtr<CFStringRef> assignemnt.
Parameters
cfstr The input string.
References B::OSPtr< T >::get().
String & B::String::operator= (const OSPtr< CFMutableStringRef > & cfstr)
OSPtr<CFMutableStringRef> assignemnt.
Parameters
cfstr The input string.
References B::OSPtr< T >::get().
String & B::String::operator= (const UniChar * ustr)
UniChar array assignemnt.
Parameters
ustr The input string.
References get_allocator(), npos, and swap().
String & B::String::operator= (UniChar c)
UniChar assignemnt.
Parameters
c The input character.
References get_allocator(), and swap().
String & B::String::operator= (const std::wstring & wstr)
std::wstring assignemnt.
Parameters
wstr The input string.
References get_allocator(), and swap().
String & B::String::operator= (const wchar_t * wcstr)
Null-terminated wchar_t array assignemnt.
Parameters
wcstr The input string.
References get_allocator(), npos, and swap().
String & B::String::operator= (const std::string & sstr)
std::string assignemnt.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
sstr The input string.
References get_allocator(), and swap().
String & B::String::operator= (const char * cstr)
Null-terminated char array assignemnt.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
cstr The input string.
References get_allocator(), npos, and swap().
String & B::String::operator= (ConstStringPtr pstr)
Pascal string assignemnt.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
pstr The input string.
References get_allocator(), and swap().
String & B::String::assign (const String & str, size_type pos = 0, size_type n = npos)
String assignemnt.
Assigns at most n characters of str starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References get_allocator(), and swap().
Referenced by B::ErrorHandler::AboutToThrow(), GetLine(), B::View::GetText(), B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentWriteStream(), B::NavReplyDialog::PopupMenuItem::PopupMenuItem(), Read(), B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Set(), and B::TabbedView::TabbedView().
String & B::String::assign (const MutableString & str, size_type pos = 0, size_type n = npos)
MutableString assignemnt.
Assigns at most n characters of str starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (CFStringRef cfstr, const from_copy_t & fc)
CFStringRef assignemnt.
Assigns cfstr to this string. The input string's retain count is not incremented.
Parameters
cfstr The source string.
fc An indication that cfstr comes from a Copy or Create function, and therefore that its retain count should not be increased.
References swap().
String & B::String::assign (CFStringRef cfstr, const std::nothrow_t & nt)
CFStringRef assignemnt.
Assigns cfstr to this string. If cfstr is NULL, use an empty string instead.
Parameters
cfstr The source string.
nt An indication that the function should not throw an exception if is NULL.
References swap().
String & B::String::assign (CFStringRef cfstr, const from_copy_t & fc, const std::nothrow_t & nt)
CFStringRef assignemnt.
Assigns cfstr to this string. If cfstr is NULL, use an empty string instead. The input string's retain count is not incremented.
Parameters
cfstr The source string.
fc An indication that cfstr comes from a Copy or Create function, and therefore that its retain count should not be increased.
nt An indication that the function should not throw an exception if is NULL.
References swap().
String & B::String::assign (CFStringRef cfstr, size_type pos, size_type n = npos)
CFStringRef assignemnt.
Assigns at most n characters of cfstr starting with index pos.
Exceptions
Parameters
cfstr The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (const UniChar * ustr, size_type n = npos)
UniChar array assignemnt.
Assigns n characters of ustr. If n is npos, then ustr is assumed to be null-terminated.
Parameters
ustr The input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (size_type n, UniChar c)
UniChar assignemnt.
Assigns num occurrences of character c.
Parameters
n The number of occurrences of c.
c The character to assign.
References get_allocator(), and swap().
String & B::String::assign (const std::wstring & wstr, size_type pos = 0, size_type n = npos)
std::wstring assignemnt.
Assigns at most n characters of wstr starting with index pos.
Exceptions
Parameters
wstr The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (const wchar_t * wcstr, size_type n = npos)
wchar_t array assignemnt.
Assigns at most n characters of wcstr starting with index pos. If n is npos, then wcstr is assumed to be null-terminated.
Parameters
wcstr The input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0, size_type n = npos)
std::string assignemnt.
Assigns at most n characters of sstr starting with index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Exceptions
Parameters
sstr The input string.
encoding The input string's encoding.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (const char * cstr, CFStringEncoding encoding, size_type n = npos)
char array assignemnt.
Assigns at most n characters of cstr starting with index pos. If n is npos, then cstr is assumed to be null-terminated. The input string is assumed to be encoded using the character encoding given in encoding.
Parameters
cstr The input string.
encoding The input string's encoding.
n The number of characters to assign.
References get_allocator(), and swap().
String & B::String::assign (ConstStringPtr pstr, CFStringEncoding encoding)
Pascal string assignemnt.
The input string is assumed to be encoded using the character encoding given in encoding.
Parameters
pstr The input string.
encoding The input string's encoding.
References get_allocator(), and swap().
String & B::String::assign (const std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external)
Blob assignemnt.
Assigns the string from blob. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
blob The source blob.
encoding The character encoding of blob.
external If true, checks for BOM and performs byte-swapping as necessary.
References cf_ref(), get_allocator(), npos, B::OSPtr< T >::release(), B::OSPtr< T >::reset(), and swap().
template<class InputIterator > String & B::String::assign (InputIterator first, InputIterator last)
Range assignment.
Assigns the string with all character of the range [first, last).
Parameters
first The start of the range of characters to assign.
last The end of the range of characters to assign.
References get_allocator(), and swap().
String::size_type B::String::find (UniChar c, size_type pos = 0) const
Finds the first occurrence of given character.
Searches for the first occurrence of the character c, starting at index pos.
Returns
The index of c, or npos if not found.
Parameters
c The character to look for.
pos The starting position for the search.
String::size_type B::String::rfind (UniChar c, size_type pos = 0) const
Finds the last occurrence of given character.
Searches for the last occurrence of the character c, starting at index pos.
Returns
The index of c, or npos if not found.
Parameters
c The character to look for.
pos The starting position for the search.
String::size_type B::String::find (const String & str, size_type pos = 0) const
Finds the first String.
Searches for the first occurrence of the string str, starting at index pos.
Returns
The index of str, or npos if not found.
Parameters
str The string to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::rfind (const String & str, size_type pos = 0) const
Finds the last String.
Searches for the last occurrence of the string str, starting at index pos.
Returns
The index of str, or npos if not found.
Parameters
str The string to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::find (CFStringRef cfstr, size_type pos = 0) const
Finds the first CFStringRef.
Searches for the first occurrence of the string cfstr, starting at index pos.
Returns
The index of cfstr, or npos if not found.
Parameters
cfstr The string to look for.
pos The starting position for the search.
String::size_type B::String::rfind (CFStringRef cfstr, size_type pos = 0) const
Finds the last CFStringRef.
Searches for the last occurrence of the string cfstr, starting at index pos.
Returns
The index of cfstr, or npos if not found.
Parameters
cfstr The string to look for.
pos The starting position for the search.
String::size_type B::String::find (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the first UniChar array.
Searches for the first occurrence of the UniChar array ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of sstr, or npos if not found.
Parameters
ustr The string to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::rfind (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the last UniChar array.
Searches for the last occurrence of the UniChar array ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of sstr, or npos if not found.
Parameters
ustr The string to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::find (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first std::string.
Searches for the first occurrence of the string sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of sstr, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String::size_type B::String::rfind (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last std::string.
Searches for the last occurrence of the string sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of sstr, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String::size_type B::String::find_first_of (const String & str, size_type pos = 0) const
Finds the first character in a set given as a String.
Searches for the first occurrence of a character contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::find_first_not_of (const String & str, size_type pos = 0) const
Finds the first character not in a set given as a String.
Searches for the first occurrence of a character not contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::find_first_of (CFStringRef cfstr, size_type pos = 0) const
Finds the first character in a set given as a CFStringRef.
Searches for the first occurrence of a character contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
String::size_type B::String::find_first_not_of (CFStringRef cfstr, size_type pos = 0) const
Finds the first character not in a set given as a CFStringRef.
Searches for the first occurrence of a character not contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
String::size_type B::String::find_first_of (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the first character in a set given as a UniChar array.
Searches for the first occurrence of a character contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::find_first_not_of (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the first character not in a set given as a UniChar array.
Searches for the first occurrence of a character not contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::find_first_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first character in a set given as a std::string.
Searches for the first occurrence of a character contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String::size_type B::String::find_first_not_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first character not in a set given as a std::string.
Searches for the first occurrence of a character not contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String::size_type B::String::find_last_of (const String & str, size_type pos = 0) const
Finds the last character in a set given as a String.
Searches for the last occurrence of a character contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::find_last_not_of (const String & str, size_type pos = 0) const
Finds the last character not in a set given as a String.
Searches for the last occurrence of a character not contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
String::size_type B::String::find_last_of (CFStringRef cfstr, size_type pos = 0) const
Finds the last character in a set given as a CFStringRef.
Searches for the last occurrence of a character contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
String::size_type B::String::find_last_not_of (CFStringRef cfstr, size_type pos = 0) const
Finds the last character not in a set given as a CFStringRef.
Searches for the last occurrence of a character not contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
String::size_type B::String::find_last_of (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the last character in a set given as a UniChar array.
Searches for the last occurrence of a character contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::find_last_not_of (const UniChar * ustr, size_type pos = 0, size_type n = npos) const
Finds the last character not in a set given as a UniChar array.
Searches for the last occurrence of a character not contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
String::size_type B::String::find_last_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last character in a set given as a std::string.
Searches for the last occurrence of a character contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String::size_type B::String::find_last_not_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last character not in a set given as a std::string.
Searches for the last occurrence of a character not contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
String B::String::substr (size_type pos = 0, size_type n = npos) const
Returns a substring.
Returns a substring of, at most, n characters of the string *this starting with index pos.
Parameters
pos The starting position for the substring.
n The length of the substring.
References cf_ref(), get_allocator(), and String().
Referenced by B::GetDisplayName().
The documentation for this class was generated from the following files:
BString.h
BString.cpp