B: B::AutoUndo Class Reference
B::AutoUndo Class Reference
Undo
Automatic management of undo action groups.
#include <BUndo.h>
Public Types
typedef FunctorUndoAction::FunctorType FunctorType
Shorthand for FunctorUndoAction's functor type.
Public Member Functions
AutoUndo (const String &inName=String(), EventTargetRef inTarget=NULL)
Constructor.
template<class ACTION >
AutoUndo (std::auto_ptr< ACTION > inUndoAction, EventTargetRef inTarget=NULL)
Constructor that adds an initial inUndoAction.
~AutoUndo ()
Destructor.
void Commit ()
Commits the currently open action group.
template<class ACTION >
void Add (std::auto_ptr< ACTION > inUndoAction)
Adds inUndoAction to the currently open action group.
void Add (FunctorType inFunctor)
Adds inFunctor to the currently open action group.
template<class FUNCTOR >
void Add (FUNCTOR inFunctor, typename FUNCTOR::argument_type inArg)
DEPRECATED. Adds inFunctor to the currently open action group.
template<class FUNCTOR >
void Add (FUNCTOR inFunctor, typename FUNCTOR::first_argument_type inArg1, typename FUNCTOR::second_argument_type inArg2)
DEPRECATED. Adds inFunctor to the currently open action group.
Detailed Description
Automatic management of undo action groups.
The class' constructor opens an action group. Once open, the group can be closed in two ways. The normal way is to call the Commit() member function, which as the name implies commits the group. The other way to close the group is to destroy the AutoUndo object without having called Commit(); in this case, the object notices that Commit() hasn't been called and so calls Abort() instead. This means that an exception propagating through the scope where the AutoUndo object was declared will automatically end up abort the group.
An example will show how simple this is in practice:
MyAction()
{
    // Constructing the AutoUndo object will open a group.
    B::AutoUndo autoUndo(B::String("Defrobilisation"));
    // do stuff...
    autoUndo.Add( ... );
    // do more stuff...
    autoUndo.Commit();
    // Because we committed, destroying the AutoUndo object won't do anything.
    // If on the other an exception had been thrown prior to the Commit() call,
    // then the group would have been aborted automatically.
}
See also
Supporting Undo, Undo
Constructor & Destructor Documentation
B::AutoUndo::AutoUndo (const String & inName = String(), EventTargetRef inTarget = NULL)
Constructor.
Opens an action group called inName. All requests sent to this object are directed towards inTarget.
Parameters
inName If empty, a default name is used.
inTarget If NULL, the user input focus is used.
References B::Undo::BeginGroup().
template<class ACTION > B::AutoUndo::AutoUndo (std::auto_ptr< ACTION > inUndoAction, EventTargetRef inTarget = NULL)
Constructor that adds an initial inUndoAction.
Opens an action group named after inUndoAction. All requests sent to this object are directed towards inTarget.
Parameters
inUndoAction The initial undo action.
inTarget If NULL, the user input focus is used.
References B::Undo::BeginGroup().
B::AutoUndo::~AutoUndo ()
Destructor.
Aborts the group if it has not been committed already.
References B::Undo::AbortGroup().
Member Function Documentation
template<class ACTION > void B::AutoUndo::Add (std::auto_ptr< ACTION > inUndoAction)
Adds inUndoAction to the currently open action group.
Note that the action is wrapped in an std::auto_ptr. This means that ownership of inUndoAction is tranferred to this function; it will either be added succesfully to the currently open action group, or will be deleted.
Parameters
inUndoAction The undoable action, wrapped inside an std::auto_ptr.
void B::AutoUndo::Add (FunctorType inFunctor)
Adds inFunctor to the currently open action group.
Parameters
inFunctor A functor.
References B::Undo::Add().
template<class FUNCTOR > void B::AutoUndo::Add (FUNCTOR inFunctor, typename FUNCTOR::argument_type inArg)
DEPRECATED. Adds inFunctor to the currently open action group.
FUNCTOR must be an adaptable unary function object. Its operator () must take one argument of type FUNCTOR::argument_type. Its result is discarded, so a return type of void is acceptable. The value of the argument is given in inArg.
Deprecated:
This function will be removed in a future release. Clients can replace calls to this function with:
Add(AutoUndo::FunctorType(boost::bind(inFunctor, inArg)), inTarget)
Parameters
inFunctor An adaptable unary function object.
inArg The argument to be passed to inFunctor.
template<class FUNCTOR > void B::AutoUndo::Add (FUNCTOR inFunctor, typename FUNCTOR::first_argument_type inArg1, typename FUNCTOR::second_argument_type inArg2)
DEPRECATED. Adds inFunctor to the currently open action group.
FUNCTOR must be an adaptable binnary function object. Its operator () must take two arguments; the first of type FUNCTOR::first_argument_type and the second of type FUNCTOR::second_argument_type. Its result is discarded, so a return type of void is acceptable. The values of the arguments are given in inArg1 and inArg2, respectively.
Deprecated:
This function will be removed in a future release. Clients can replace calls to this function with:
Add(AutoUndo::FunctorType(boost::bind(inFunctor, inArg1, inArg2)), inTarget)
Parameters
inFunctor An adaptable unary function object.
inArg1 The first argument to be passed to inFunctor.
inArg2 The second argument to be passed to inFunctor.
The documentation for this class was generated from the following files:
BUndo.h
BUndo.cpp