B: B::Document< UNDO_POLICY, PRINT_POLICY > Class Template Reference
B::Document< UNDO_POLICY, PRINT_POLICY > Class Template Reference
A concrete Document class.
#include <BDocument.h>
Public Types
typedef UNDO_POLICY UndoPolicyType
typedef PRINT_POLICY PrintPolicyType
typedef Document< UNDO_POLICY, PRINT_POLICY > DocType
typedef DocumentWindow< DocType > WindowType
Public Types inherited from B::AbstractDocument
typedef boost::signal0< void > VoidSignal
Shorthand for a type of signal used by this class.
typedef boost::signal1< void, AbstractDocument * > DocSignal
Shorthand for a type of signal used by this class.
Public Member Functions
Document (AEObjectPtr inContainer, DescType inClassID, SInt32 inUniqueID)
virtual bool OwnsWindow (const Window *inWindow) const
virtual bool OwnsFrontmostDocumentWindow () const
virtual Window * GetFrontMostDocumentWindow () const
virtual String GetDisplayName () const
virtual Url GetUrl () const
virtual String GetDocumentType () const
virtual Icon GetIcon () const
UndoPolicyType & GetUndoPolicy ()
PrintPolicyType & GetPrintPolicy ()
virtual void MakeCurrent ()
virtual bool AskUserToClose (bool inFromUser, Window *inWindow, NavAskSaveChangesAction inContext)
virtual bool AskUserToSave (SaveInfo &ioSaveInfo)
virtual void WriteDocument (SaveInfo &ioSaveInfo)
virtual void WriteDocumentToUrl (SaveInfo &ioSaveInfo)
virtual void WriteComplete (const Url &inOldUrl, const String &inOldDocumentType)
virtual bool AskUserToRevert (Window *inWindow)
virtual void Quitting (OSType inSaveOption)
virtual void PrintDocument (PrintSettings *inPrintSettings, Printer *inPrinter, bool inShowDialog)
virtual void WindowActivated (Window *inWindow)
virtual void WindowDeactivated (Window *inWindow)
virtual DialogModality GetDocumentDialogModality (Window *inWindowHint)
Determines the modality to use for document dialogs & alerts.
virtual String GetName () const
virtual size_t CountElements (DescType inElementType) const
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
Configuration
void SaveClearsUndo (bool clearsIt)
If clearsIt is true, saving the document will clear the undo stack.
Public Member Functions inherited from B::AbstractDocument
virtual bool CloseDocument (OSType inSaveOption, const Url &inUrl=Url(), Window *inWindow=NULL)
virtual void Close ()
virtual void CancelQuitting ()
bool IsQuitting () const
AbstractDocument (AEObjectPtr inContainer, DescType inClassID, SInt32 inUniqueID)
Constructor.
virtual bool IsNew () const
Returns true is the document does not have a backing store.
virtual bool IsModified () const
Returns true if the document has any unsaved changes.
virtual void Modified ()
Registers a change to the document.
virtual void Unmodified ()
Unregisters a change to the document.
virtual SInt32 GetUniqueID () const
Returns the document's unique id. This id is not persistent.
virtual OSType GetCreator () const
Returns the document's creator code.
EventTargetRef GetEventTarget () const
Returns the document's event target.
virtual void InitNewDocument (const String &inName, const String &inDocumentType, const AEDesc &inProperties, const AEDesc &inData, Nib *inNib)
Initialises a new document.
virtual void InitOpenDocument (const Url &inDocumentUrl, const String &inDocumentType, Nib *inNib, bool inForPrinting)
Initialises a document from the contents of a URL.
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
virtual void RevertObject ()
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
DocSignal & GetDirtyStateChangedSignal ()
Sent when the document becomes dirty (or clean). Usually due to model changes, or Save or Save As.
DocSignal & GetUrlChangedSignal ()
Sent when the document's URL has changed. Usually due to a Save or Save As.
DocSignal & GetContentChangedSignal ()
Sent when the document's content changes completely. Usually due to a Revert.
DocSignal & GetClosingSignal ()
Sent when the document is about to be closed.
VoidSignal & GetAsyncActionCancelledSignal ()
Sent when the user has cancelled an async action (i.e. Quit with multiple documents containing unsaved changes).
DocSignal & GetDeleteSignal ()
Sent when the the document should be deleted (IMPORTANT: only the document policy should be listening to this !!).
virtual void SaveDocument (SaveInfo &ioInfo)
Saves the document.
virtual void RevertDocument ()
Reverts the document.
Public Member Functions inherited from B::AEObject
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
Returns the element of the given class with the given unique ID.
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
Returns the element of the given class with the given name.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
Returns the AEObject matching a given property, if any.
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
Reads the value of the property identified by inPropertyID from ioReader.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
Implements the AppleScript "make" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void ActivateObject ()
Implements the AppleScript "activate" event.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
Protected Member Functions
virtual const char * GetWindowNibName () const
virtual void MakeWindows (Nib *inNib)
virtual void ShowWindows ()
virtual void InitDocument (const String &inName, const String &inDocumentType, const AEDesc &inProperties, const AEDesc &inData)
virtual void ReadDocument (const Url &inDocumentUrl, String &ioDocumentType)
virtual void DoneReading (const Url &inDocumentUrl, const String &inDocumentType)
virtual void SaveDocumentWithNavReply (NavReplyRecord &ioReply, const SaveInfo &inSaveInfo)
virtual void ReadDocumentFromFile (const Url &inFileUrl, String &ioDocumentType)
Reads the document from inFileUrl.
virtual void WriteDocumentToFile (SaveInfo &ioSaveInfo)
virtual void WriteDocumentToNewFile (SaveInfo &ioSaveInfo)
virtual void WriteDocumentToExistingFile (SaveInfo &ioSaveInfo)
virtual void WriteDocumentCommon (SaveInfo &ioSaveInfo)
virtual bool CreateDocumentFile (const Url &inFileUrl, FSRef &outFileRef)
virtual std::auto_ptr< std::istream > MakeDocumentReadStream (const Url &inDocumentUrl, const String &inDocumentType) const
Returns an std::istream suitable for reading inDocumentUrl.
virtual std::auto_ptr< std::ostream > MakeDocumentWriteStream (SaveInfo &ioSaveInfo) const
Returns an std::ostream suitable for writing the document.
virtual void ReadDocumentFromStream (std::istream &ioStream, String &ioDocumentType)
Reads the document from ioStream.
virtual void WriteDocumentToStream (std::ostream &ioStream, SaveInfo &ioSaveInfo)
virtual void ReadDocumentFromBuffer (const std::vector< UInt8 > &inBuffer, String &ioDocumentType)
Reads the document from inBuffer.
virtual void WriteDocumentToBuffer (std::vector< UInt8 > &outBuffer, SaveInfo &ioSaveInfo)
virtual void StartSafeFileSave (const FSRef &inDstRef, FSRef &outTempFileRef, bool &outExtensionHidden)
virtual void CompleteSafeFileSave (const FSRef &inDstRef, const FSRef &inTempFileRef, bool inExtensionHidden)
virtual void WriteFileAttributes (SaveInfo &ioSaveInfo)
virtual void RecalcDisplayName ()
virtual void HandleSaveResult (bool inGoodSave, NavReplyRecord &ioNavReply, const SaveInfo &inSaveInfo)
virtual void HandleAskSaveChangesResult (AskSaveChangesDialog::Action inAction, const DocumentSheetState &inState)
virtual void HandleAskDiscardChangesResult (bool inDiscard, const DocumentSheetState &inState)
virtual void HandlePageSetupDialogInit (PrintSession &ioPrintSession)
virtual void HandlePageSetupDialogResult (PrintSession &ioPrintSession, bool inAccepted)
virtual void HandlePrintDialogInit (PrintSession &ioPrintSession)
virtual void HandlePrintDialogResult (PrintSession &ioPrintSession, bool inAccepted)
virtual void HandlePageFormatChanged (PageFormat &ioPageFormat)
virtual void UndoManagerModified ()
virtual void UndoManagerUnmodified ()
Printing
virtual void StartPrinting (PrintSession &ioPrintSession, const PrintSettings &inPrintSettings, const PageFormat &inPageFormat)
virtual void CalcPrintingPageRange (PrintSession &ioPrintSession, const PrintSettings &inPrintSettings, const PageFormat &inPageFormat, size_t &outStartPage, size_t &outEndPage)
virtual void GetPrintingPageRange (size_t &outMinPage, size_t &outMaxPage, bool inForDialog)
virtual void BeginPrintingDocument (PrintSession &ioPrintSession, const PrintSettings &inPrintSettings, const PageFormat &inPageFormat, size_t inStartPage, size_t inEndPage)
virtual void BeginPrintingPage (PrintSession &ioPrintSession, const PageFormat &inPageFormat, size_t inPage)
virtual void PrintPage (PrintSession &ioPrintSession, const PageFormat &inPageFormat, size_t inPage)
Dialog Factory Methods
virtual std::auto_ptr< PutFileDialog > CreateSaveDialog (const DialogModality &inModality, const SaveInfo &inInfo)
Returns a fully configured PutFileDialog.
virtual std::auto_ptr< AskSaveChangesDialog > CreateAskSaveChangesDialog (const DialogModality &inModality, bool inFromUser, AskSaveChangesDialog::Context inContext)
Returns a fully configured AskSaveChangesDialog.
virtual std::auto_ptr< AskDiscardChangesDialog > CreateAskDiscardChangesDialog (const DialogModality &inModality, bool inFromUser)
Returns a fully configured AskDiscardChangesDialog.
Protected Member Functions inherited from B::AbstractDocument
virtual void CloseWindows ()
virtual void CloseFiles ()
virtual void DonePrinting ()
virtual void ClearModified ()
Forces the change count to zero.
virtual void NotifyContentChanged ()
Broadcasts the "content changed" signal.
virtual void NotifyUrlChanged ()
Broadcasts the "url changed" signal.
virtual void NotifyActionCancelled ()
Broadcasts the "async action cancelled" signal.
virtual void MakeSpecifier (AEWriter &ioWriter) const
virtual bool HandleCommand (const HICommandExtended &inHICommand, Window *inWindow=NULL)
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCommandData, Window *inWindow=NULL)
Protected Member Functions inherited from B::AEObject
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Protected Attributes
String mName
String mDisplayName
Window * mWindow
Url mUrl
String mDocumentType
OSType mQuittingSaveOption
bool mShowingCloseUI
bool mSaveClearsUndo
Additional Inherited Members
Static Public Member Functions inherited from B::AEObject
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Static Protected Member Functions inherited from B::AEObject
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Related Functions inherited from B::AEObject
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Detailed Description
template<class UNDO_POLICY, class PRINT_POLICY>
class B::Document< UNDO_POLICY, PRINT_POLICY >
A concrete Document class.
Todo:
Document this class!
Member Function Documentation
template<class UNDO_POLICY , class PRINT_POLICY > bool B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsWindow (const Window * inWindow) const virtual
Return whether the document owns the given window.
Implements B::AbstractDocument.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow().
template<class UNDO_POLICY , class PRINT_POLICY > bool B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow () const virtual
Return whether the document owns the currently active document window.
References B::UNDO_POLICY::Clear(), B::AbstractDocument::ClearModified(), B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentReadStream(), B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsWindow(), B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromFile(), and B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromStream().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::MakeCurrent () virtual
Make this Document the current one.
Override to do what makes sense for a particular kind of Document. In most cases, this means selecting the main window for a Document.
Reimplemented from B::AbstractDocument.
template<class UNDO_POLICY , class PRINT_POLICY > DialogModality B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality (Window * inWindowHint) virtual
Determines the modality to use for document dialogs & alerts.
Parameters
inWindowHint A hint as to the top-most document window. May be NULL.
References B::AbstractDocument::CloseDocument(), B::AEObject::CountElements(), B::AEObject::DoesClassInheritFrom(), B::AEObject::GetAEObjectPtr(), B::AEObject::GetElementByIndex(), B::PrintSettings::GetFirstPage(), B::PrintSettings::GetLastPage(), B::PRINT_POLICY::GetPrintSettings(), B::AbstractDocument::IsModified(), B::AbstractDocument::Modified(), B::PRINT_POLICY::Print(), B::PrintSettings::SetJobName(), B::PrintSession::SetModality(), B::PrintSettings::SetPageRange(), B::DialogModality::Sheet(), and B::AbstractDocument::Unmodified().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskSaveChangesDialog(), B::Document< UNDO_POLICY, PRINT_POLICY >::CreateSaveDialog(), and B::Document< UNDO_POLICY, PRINT_POLICY >::WriteDocumentToBuffer().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromFile (const Url & inFileUrl, String & ioDocumentType) protected virtual
Reads the document from inFileUrl.
Resolves inFileUrl into a file system path, instantiates an std::ifstream with the path, then calls ReadDocumentFromStream() with the stream.
Derived classes may override this function to read the file some other way, such as with Carbon File Manager APIs (FSOpenFork() etc) or UNIX APIs (open() etc).
Parameters
inFileUrl The document's URL, which must be a file: URL.
ioDocumentType The document's type.
References B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentReadStream(), and B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromStream().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow().
template<class UNDO_POLICY , class PRINT_POLICY > std::auto_ptr< std::istream > B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentReadStream (const Url & inDocumentUrl, const String & inDocumentType) const protected virtual
Returns an std::istream suitable for reading inDocumentUrl.
Parameters
inDocumentUrl The document's URL.
inDocumentType The document's type.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow(), and B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromFile().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromStream (std::istream & ioStream, String & ioDocumentType) protected virtual
Reads the document from ioStream.
Reads the entire contents of the stream into an std::vector, then calls ReadDocumentFromBuffer().
Derived classes may override this function to read the stream in a manner better adapted to the document's contents.
Parameters
ioStream The document's input stream.
ioDocumentType The document's type.
References B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromBuffer().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow(), and B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromFile().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::WriteDocumentToStream (std::ostream & ioStream, SaveInfo & ioSaveInfo) protected virtual
Parameters
ioSaveInfo The document's save information.
References B::Document< UNDO_POLICY, PRINT_POLICY >::WriteDocumentToBuffer().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentWriteStream().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromBuffer (const std::vector< UInt8 > & inBuffer, String & ioDocumentType) protected virtual
Reads the document from inBuffer.
Parameters
inBuffer The document's contents.
ioDocumentType The document's type.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::ReadDocumentFromStream().
template<class UNDO_POLICY , class PRINT_POLICY > void B::Document< UNDO_POLICY, PRINT_POLICY >::WriteDocumentToBuffer (std::vector< UInt8 > & outBuffer, SaveInfo & ioSaveInfo) protected virtual
Parameters
ioSaveInfo The document's save information.
References B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskSaveChangesDialog(), B::NavDialog::Enter(), B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), and B::DialogModality::IsModal().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::WriteDocumentToStream().
template<class UNDO_POLICY , class PRINT_POLICY > std::auto_ptr< PutFileDialog > B::Document< UNDO_POLICY, PRINT_POLICY >::CreateSaveDialog (const DialogModality & inModality, const SaveInfo & inInfo) protected virtual
Returns a fully configured PutFileDialog.
Factory function that creates the "Save" (ie PutFile) sheet for this document.
References B::UNDO_POLICY::Clear(), B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog(), B::NavDialog::Enter(), B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), B::AbstractDocument::GetEventTarget(), B::DialogModality::IsModal(), B::Bundle::Main(), B::AbstractDocument::NotifyActionCancelled(), B::AEObject::SendCloseAppleEvent(), B::AEObject::SendSaveAppleEvent(), and B::AbstractDocument::WriteComplete().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskSaveChangesDialog().
The documentation for this class was generated from the following files:
BDocument.h
BDocument.tpl.h