B: B::CommandData Class Reference
B::CommandData Class Reference
Carbon Events
Acts as an accumulator for menu item or control state changes.
#include <BCommandData.h>
Public Member Functions
Constructor
CommandData ()
Constructor.
Inquiries
bool HasData () const
Returns true if the object has any state that needs updating.
Modifiers
void SetEnabled (bool inEnabled)
Changes the command's enabled state.
void SetText (const String &inText)
Changes the command's text.
void SetMark (UniChar inMark)
Change the command's mark character.
void SetChecked (bool checked)
Change the command's mark character to the standard check mark.
void SetVisible (bool visible)
Change the command's visible state.
Refreshing Toolbox Data Structures
void RefreshData (const HICommandExtended &inCommand) const
Updates the toolbox entity identified by inCommand.
Detailed Description
Acts as an accumulator for menu item or control state changes.
Instances of this class are passed to Carbon Event handlers for the kEventClassCommand/kEventCommandUpdateStatus event. The handlers should call appropriate member functions to indicate a menu item's enabled status, text, mark character, etc. When the handler returns, the menu item is updated to reflect the new state.
Constructor & Destructor Documentation
B::CommandData::CommandData ()
Constructor.
The object start out without any state that needs updating.
Member Function Documentation
void B::CommandData::SetEnabled (bool inEnabled)
Changes the command's enabled state.
This applies to both menu items and controls.
Parameters
inEnabled The command's new enabled status.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::HandleUpdateStatus(), B::AbstractDocument::MakeCurrent(), B::AbstractPrintPolicy::Print(), B::MultipleDocumentPolicy< DOC_FACTORY >::QuitApplication(), and B::Window::SetIdealSize().
void B::CommandData::SetText (const String & inText)
Changes the command's text.
This applies to both menu items and controls.
References B::String::cf_ptr().
void B::CommandData::SetMark (UniChar inMark)
Change the command's mark character.
This currently only applies to menu items.
Parameters
inMark The command's new mark character.
void B::CommandData::SetChecked (bool checked)
Change the command's mark character to the standard check mark.
This currently only applies to menu items.
void B::CommandData::SetVisible (bool visible)
Change the command's visible state.
This currently only applies to menu items.
The documentation for this class was generated from the following files:
BCommandData.h
BCommandData.cpp