B: B::PrintSession Class Reference
B::PrintSession Class Reference
Encapsulates a page format for printing.
#include <BPrintSession.h>
Public Types
Types
typedef boost::function2< void, PrintSession &, bool > DialogDoneCallback
The completion callback for the Page Setup and Print dialogs.
Public Member Functions
Constructors / Destructor
PrintSession ()
Default constructor.
~PrintSession ()
Destructor.
Inquiries
void GetPrinters (std::vector< String > &outNames, size_t &outCurrent) const
Returns a list of printers available in this printing session.
Printer GetPrinter () const
Returns the current printer associated with this printing session.
void GetPageFormats (const Printer &inPrinter, std::vector< PageFormat > &outPageFormats) const
Retrieve the paper sizes available on inPrinter.
void GetDocumentFormats (std::vector< String > &outFormats) const
Returns the spool file formats that can be generated for this printing session.
PMDestinationType GetDestinationType (const PrintSettings &inPrintSettings) const
Returns the destination type for a print job.
String GetDestinationFormat (const PrintSettings &inPrintSettings) const
Returns the destination format for a print job.
Url GetDestinationLocation (const PrintSettings &inPrintSettings) const
Returns the destination location for a print job.
void GetOutputFormats (PMDestinationType inDestinationType, std::vector< String > &outOutputFormats) const
Retrieve the destination formats supported by the current print destination.
OSStatus GetError () const
Returns the current result code for the printing session.
CFTypeRef GetData (CFStringRef inKey) const
Returns data the application previously stored in the printing session object.
template<typename T >
OSPtr< T > GetSessionData (CFStringRef inKey) const
Returns data the application previously stored in the printing session object.
Modifiers
void SetModality (const DialogModality &inModality)
Sets the print dialogs' modality.
void SetPrinter (CFStringRef inPrinterName)
Changes the current printer for this printing session to the printer whose name is specified by inName.
void SetPrinter (const Printer &inPrinter)
Changes the current printer for this printing session to the printer specified by inPrinter.
void SetDocumentFormat (CFStringRef inDocFormat, CFStringRef inGraphicsType)
Specifies the spool file format and the graphics context type to use for drawing pages within the print loop.
void SetDestination (const PrintSettings &inPrintSettings, PMDestinationType inDestinationType, const String &inOutputFormat, const Url &inLocation)
Sets the destination location, format, and type for a print job.
void SetError (OSStatus inError)
Sets the current result code for the printing session.
void ShowPrinterPresets (bool showThem)
Controls whether the simplified print dialog will be displayed.
void ShowStatusDialog (bool showIt)
Controls whether the status dialog will be displayed during the print loop.
void SetData (CFStringRef inKey, CFTypeRef inData)
Stores application-specific data in the printing session object.
template<typename T >
void SetSessionData (CFStringRef inKey, OSPtr< T > inData)
Stores application-specific data in the printing session object.
Defaults & Validation
void Default (PageFormat &ioPageFormat)
Assigns default parameter values to ioPageFormat.
void Default (PrintSettings &ioPrintSettings)
Assigns default parameter values to ioPrintSettings.
bool Validate (PageFormat &ioPageFormat)
Updates the values in ioPageFormat and validates them against the current formatting printer.
bool Validate (PrintSettings &ioPrintSettings)
Validates ioPageFormat within the context of the printing session.
PageFormat MakePageFormat ()
Creates a PageFormat object and gives it default values for this printing session.
PrintSettings MakePrintSettings ()
Creates a PrintSettings object and gives it default values for this printing session.
Dialogs
void PageSetupDialog (PageFormat &ioPageFormat, DialogDoneCallback inCallback)
Displays the Page Setup dialog and records the user's selections in ioPageFormat.
void PrintDialog (PrintSettings &ioPrintSettings, const PageFormat &inPageFormat, DialogDoneCallback inCallback)
Displays the Print dialog and records the user's selections in ioPrintSettings.
Print Loop
void BeginDocument (const PrintSettings &inPrintSettings, const PageFormat &inPageFormat)
Begins a print job.
void EndDocument ()
Ends a print job started by BeginDocument().
void BeginPage (const PageFormat &inPageFormat)
Starts a new page for printing in the printing session.
void EndPage ()
Indicates the end of drawing the current page for the printing session.
Graphics::Context GetPageContext ()
Returns the CoreGraphics context for the current page.
Detailed Description
Encapsulates a page format for printing.
Todo:
Document this class!
Member Function Documentation
void B::PrintSession::GetPrinters (std::vector< String > & outNames, size_t & outCurrent) const
Returns a list of printers available in this printing session.
Parameters
outNames An array of printer names.
outCurrent The index of the current printer in outNames.
void B::PrintSession::GetPageFormats (const Printer & inPrinter, std::vector< PageFormat > & outPageFormats) const
Retrieve the paper sizes available on inPrinter.
Parameters
inPrinter The printer whose page formats we want.
outPageFormats An array of page formats.
void B::PrintSession::GetDocumentFormats (std::vector< String > & outFormats) const
Returns the spool file formats that can be generated for this printing session.
Parameters
outFormats An array of spool file format names.
PMDestinationType B::PrintSession::GetDestinationType (const PrintSettings & inPrintSettings) const
Returns the destination type for a print job.
Parameters
inPrintSettings The print settings object.
String B::PrintSession::GetDestinationFormat (const PrintSettings & inPrintSettings) const
Returns the destination format for a print job.
Parameters
inPrintSettings The print settings object.
Url B::PrintSession::GetDestinationLocation (const PrintSettings & inPrintSettings) const
Returns the destination location for a print job.
Parameters
inPrintSettings The print settings object.
void B::PrintSession::GetOutputFormats (PMDestinationType inDestinationType, std::vector< String > & outOutputFormats) const
Retrieve the destination formats supported by the current print destination.
Parameters
inDestinationType The destination type.
outOutputFormats An array of output format names.
CFTypeRef B::PrintSession::GetData (CFStringRef inKey) const
Returns data the application previously stored in the printing session object.
Parameters
inKey CF string uniquely identifying the data of interest.
template<typename T > OSPtr< T > B::PrintSession::GetSessionData (CFStringRef inKey) const
Returns data the application previously stored in the printing session object.
Parameters
inKey CF string uniquely identifying the data of interest.
void B::PrintSession::SetPrinter (CFStringRef inPrinterName)
Changes the current printer for this printing session to the printer whose name is specified by inName.
Parameters
inPrinterName The new printer's name.
Referenced by B::AEEvent< kCoreEventClass, kAEPrint >::~AEEvent().
void B::PrintSession::SetPrinter (const Printer & inPrinter)
Changes the current printer for this printing session to the printer specified by inPrinter.
Parameters
inPrinter The new printer.
void B::PrintSession::SetDocumentFormat (CFStringRef inDocFormat, CFStringRef inGraphicsType)
Specifies the spool file format and the graphics context type to use for drawing pages within the print loop.
Parameters
inDocFormat The desired spool file format
inGraphicsType The desired graphics context type.
void B::PrintSession::SetDestination (const PrintSettings & inPrintSettings, PMDestinationType inDestinationType, const String & inOutputFormat, const Url & inLocation)
Sets the destination location, format, and type for a print job.
Parameters
inPrintSettings The print settings object.
inDestinationType The destination type.
inOutputFormat The destination output format.
inLocation The destination location.
References B::String::cf_ref(), and B::String::empty().
void B::PrintSession::SetError (OSStatus inError)
Sets the current result code for the printing session.
Parameters
inError The new result code.
void B::PrintSession::SetData (CFStringRef inKey, CFTypeRef inData)
Stores application-specific data in the printing session object.
Parameters
inKey CF string uniquely identifying the data of interest.
inData The new value.
template<typename T > void B::PrintSession::SetSessionData (CFStringRef inKey, OSPtr< T > inData)
Stores application-specific data in the printing session object.
Parameters
inKey CF string uniquely identifying the data of interest.
inData The new value.
References B::OSPtr< T >::get().
void B::PrintSession::Default (PageFormat & ioPageFormat)
Assigns default parameter values to ioPageFormat.
Parameters
ioPageFormat The page format object.
Referenced by MakePageFormat(), MakePrintSettings(), and B::AEEvent< kCoreEventClass, kAEPrint >::~AEEvent().
void B::PrintSession::Default (PrintSettings & ioPrintSettings)
Assigns default parameter values to ioPrintSettings.
Parameters
ioPrintSettings The print settings object.
bool B::PrintSession::Validate (PageFormat & ioPageFormat)
Updates the values in ioPageFormat and validates them against the current formatting printer.
Returns
true if the page format had to be changed.
Parameters
ioPageFormat The page format object.
References B::PageFormat::copy(), and B::PageFormat::Equals().
Referenced by B::AbstractPrintPolicy::GetPageFormat(), B::AbstractPrintPolicy::GetPrintSettings(), B::AbstractPrintPolicy::ValidatePageFormat(), and B::AbstractPrintPolicy::ValidatePrintSettings().
bool B::PrintSession::Validate (PrintSettings & ioPrintSettings)
Validates ioPageFormat within the context of the printing session.
Returns
true if the print settings had to be changed.
Parameters
ioPrintSettings The print settings object.
References B::PrintSettings::copy(), and B::PrintSettings::Equals().
void B::PrintSession::BeginDocument (const PrintSettings & inPrintSettings, const PageFormat & inPageFormat)
Begins a print job.
Parameters
inPrintSettings The print settings object.
inPageFormat The page format object.
void B::PrintSession::BeginPage (const PageFormat & inPageFormat)
Starts a new page for printing in the printing session.
Parameters
inPageFormat The page format object.
The documentation for this class was generated from the following files:
BPrintSession.h
BPrintSession.cpp