B: B::OSPtr< T > Class Template Reference
B::OSPtr< T > Class Template Reference
A simple "smart pointer" for reference-counted OS objects.
#include <BOSPtr.h>
Public Member Functions
Constructors / Destructor
OSPtr ()
Default constructor. Initialises the object to NULL.
OSPtr (const OSPtr &ptr)
Copy constructor.
OSPtr (T ptr)
Constructor for a T.
OSPtr (T ptr, const from_copy_t &)
Constructor for a T.
OSPtr (T ptr, const std::nothrow_t &)
Constructor for a T (non-throwing version).
OSPtr (T ptr, const from_copy_t &, const std::nothrow_t &)
Constructor for a T (non-throwing version).
~OSPtr ()
Destructor.
Assignment
OSPtr & operator= (const OSPtr &ptr)
Assignment operator.
Access
T get () const
Returns the underlying OS object.
Modifiers
void reset (const OSPtr &ptr)
Changes the underlying OS object.
void reset (T ptr)
Changes the underlying OS object.
void reset (T ptr, const from_copy_t &)
Changes the underlying OS object.
void reset (T ptr, const std::nothrow_t &)
Changes the underlying OS object (non-throwing variant).
void reset (T ptr, const from_copy_t &, const std::nothrow_t &)
Changes the underlying OS object (non-throwing variant).
void reset ()
Changes the underlying OS object to NULL.
T release ()
Relenquishes ownership of the OS object.
void swap (OSPtr &ptr)
Exchanges the contents of the object with ptr.
Conversions
operator T () const
Returns the underlying OS object.
int operator! () const
Returns true if the underlying OS object is not NULL.
Public Attributes
Template Parameters
typedef T
The template parameter. Should be an OS-defined type.
Related Functions
(Note that these are not member functions.)
template<typename T >
bool operator== (const OSPtr< T > &t1, const OSPtr< T > &t2)
template<typename T >
bool operator== (const OSPtr< T > &t1, T t2)
template<typename T >
bool operator== (T t1, const OSPtr< T > &t2)
template<typename T >
bool operator!= (const OSPtr< T > &t1, const OSPtr< T > &t2)
template<typename T >
bool operator!= (const OSPtr< T > &t1, T t2)
template<typename T >
bool operator!= (T t1, const OSPtr< T > &t2)
Miscellaneous
template<typename T >
void swap (OSPtr< T > &p1, OSPtr< T > &p2)
Detailed Description
template<typename T>
class B::OSPtr< T >
A simple "smart pointer" for reference-counted OS objects.
This class basically manages the object's reference count. It is used liberally in the B framework.
The class may be instantiated with any type for which an instantiation of the TypedOwnershipTrait<T> class template is defined. In practice, this means any CoreFoundation object, as well as printing objects and
- CoreFoundation objects
- Other objects that are CF-compatible (meaning they can be passed to @c CFRetain
  and @c CFRelease).  These days, this includes almost all new ref-counted objects
  in the Mac OS X Carbon/CoreServices/ApplicationServices API sets.
- @c WindowRef and @c WindowGroupRef
- @c MenuRef
- @c IconRef
- @c MouseTrackingRef
- @c Collection
- Common printing objects (@c PMPrintSettings, @c PMPageFormat, @c PMPrinter,
  @c PMPrintSession)
Although this isn't really a smart pointer in the sense that one can dereference it, a number of member functions are named after similar functions in std::auto_ptr<>.
Constructor & Destructor Documentation
template<typename T > B::OSPtr< T >::OSPtr (const OSPtr< T > & ptr)
Copy constructor.
Increments the retain count on the underlying object (if it isn't NULL).
Parameters
ptr The source object.
template<typename T> B::OSPtr< T >::OSPtr (T ptr) explicit
Constructor for a T.
Parameters
ptr The OS object to wrap.
References B::OSPtr< T >::reset().
template<typename T> B::OSPtr< T >::OSPtr (T ptr, const from_copy_t & fc) explicit
Constructor for a T.
Parameters
ptr The OS object to wrap.
fc Indicates that ptr came from a "Create" or "Copy" function.
References B::OSPtr< T >::reset().
template<typename T> B::OSPtr< T >::OSPtr (T ptr, const std::nothrow_t & nt) explicit
Constructor for a T (non-throwing version).
Parameters
ptr The OS object to wrap.
nt indicates that the caller doesn't want the function to throw an exception.
References B::OSPtr< T >::reset().
template<typename T> B::OSPtr< T >::OSPtr (T ptr, const from_copy_t & fc, const std::nothrow_t & nt) explicit
Constructor for a T (non-throwing version).
Parameters
ptr The OS object to wrap.
fc Indicates that ptr came from a "Create" or "Copy" function.
nt indicates that the caller doesn't want the function to throw an exception.
References B::OSPtr< T >::reset().
template<typename T > B::OSPtr< T >::~OSPtr ()
Destructor.
Decrements the retain count on the underlying object (if it isn't NULL).
References B::OSPtr< T >::T.
Member Function Documentation
template<typename T > OSPtr< T > & B::OSPtr< T >::operator= (const OSPtr< T > & ptr)
Assignment operator.
Parameters
ptr The source object.
References B::OSPtr< T >::reset().
template<typename T > void B::OSPtr< T >::reset (const OSPtr< T > & ptr)
Changes the underlying OS object.
Parameters
ptr The OS object to wrap.
References B::OSPtr< T >::T.
Referenced by B::String::assign(), B::PasteboardItem::Contains(), B::ErrorHandler::CopyExceptionMessage(), B::CustomView::Create(), B::CreateImageFromJpegURL(), B::CreateImageFromPngURL(), B::NavReplyDialog::FilterObject(), B::Bundle::FindDocumentTypeForUrl(), B::DescParamHelper::GetCoercedData(), B::PasteboardFlavor::GetData(), B::ImageView::ImageView(), B::Toolbar::Initialize(), B::ToolbarItem::Initialize(), B::Pasteboard::Pasteboard(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::PostprocessMenuBar(), B::Graphics::Context::swap(), B::SplitView::Track(), B::CustomView::TrackingAreaExited(), and B::Drag::~Drag().
template<typename T> void B::OSPtr< T >::reset (T ptr)
Changes the underlying OS object.
Parameters
ptr The OS object to wrap.
template<typename T> void B::OSPtr< T >::reset (T ptr, const from_copy_t &)
Changes the underlying OS object.
Call this function if you have a T that you wish to assign to a OSPtr<T>, for example if you obtained the T from a call to the OS.
The function "consumes" a refcount, meaning that the object's refcount isn't incremented. This is appropriate when an OS object is created (or its refcount otherwise increased) prior to being passed to this function. In CoreFoundation terms, ptr is assumed to have been obtained from a "Create" or "Copy" function.
This function throws an exception if ptr is NULL; this often is a result of a "Create" or "Copy" function that failed.
The previous underlying OS object gets its retain count decremented (if it wasn't NULL).
Exceptions
std::bad_alloc If ptr is NULL.
Parameters
ptr The OS object to wrap.
template<typename T> void B::OSPtr< T >::reset (T ptr, const std::nothrow_t &)
Changes the underlying OS object (non-throwing variant).
Parameters
ptr The OS object to wrap.
template<typename T> void B::OSPtr< T >::reset (T ptr, const from_copy_t & , const std::nothrow_t &)
Changes the underlying OS object (non-throwing variant).
Call this function if you have a T that you wish to assign to a OSPtr<T>, for example if you obtained the T from a call to the OS.
This function "consumes" a refcount, meaning that the object's refcount isn't incremented. This is appropriate when an OS object is created (or its refcount otherwise increased) prior to being passed to this function. In CoreFoundation terms, ptr is assumed to have been obtained from a "Create" or "Copy" function.
This function, unlike one of the other overloads of reset(), will quietly accept a NULL ptr.
The previous underlying OS object gets its retain count decremented (if it wasn't NULL).
Parameters
ptr The OS object to wrap.
template<typename T> void B::OSPtr< T >::reset ()
Changes the underlying OS object to NULL.
The underlying OS object gets its retain count decremented (if it isn't NULL).
References B::OSPtr< T >::T.
Referenced by B::OSPtr< T >::operator=(), and B::OSPtr< T >::OSPtr().
template<typename T > T B::OSPtr< T >::release ()
Relenquishes ownership of the OS object.
The OS object's retain count is not modified.
Returns
The underlying OS object.
References B::OSPtr< T >::T.
Referenced by B::String::assign(), B::ErrorHandler::CopyExceptionMessage(), B::BevelButton::Create(), B::PopupButton::Create(), B::AboutBox::Display(), B::DataBrowser::ReceiveDragOnItem(), and B::PredefinedView::SetupView().
Friends And Related Function Documentation
template<typename T > void swap (OSPtr< T > & p1, OSPtr< T > & p2) related
Exchanges the contents of s1 and s2.
References B::OSPtr< T >::swap().
The documentation for this class was generated from the following files:
BFwd.h
BOSPtr.h