B: B::ToolbarItem Class Reference
B::ToolbarItem Class Reference
Views
Wrapper class for toolbar items.
#include <BToolbarItem.h>
Public Member Functions
Inquiries
String GetIdentifier () const
Returns the toolbar item's unique identifier.
OptionBits GetAttributes () const
Returns the toolbar item's attributes.
String GetLabel () const
Returns the toolbar item's label.
String GetShortHelpText () const
Returns the toolbar item's short help tag text.
String GetLongHelpText () const
Returns the toolbar item's long help tag text.
MenuCommand GetCommandID () const
Returns the toolbar item's command ID.
OSPtr< CGImageRef > GetImage () const
Returns the toolbar item's image.
HIToolbarRef GetToolbar () const
Returns the toolbar item's toolbar.
bool IsEnabled () const
Returns true if the toolbar item is enabled.
Modifiers
void ChangeAttributes (OptionBits inAttrsToSet, OptionBits inAttrsToClear)
Changes the toolbar item's attributes.
void SetLabel (const String &inLabel)
Changes the toolbar item's label.
void SetShortHelpText (const String &inHelpText)
Changes the toolbar item's short help tag text.
void SetLongHelpText (const String &inHelpText)
Changes the toolbar item's long help tag text.
void SetIcon (IconRef inIcon)
Changes the toolbar item's image.
void SetImage (OSPtr< CGImageRef > inImage)
Changes the toolbar item's image.
void SetCommandID (MenuCommand inCommandID)
Changes the toolbar item's command ID.
void Enable (bool inEnabled)
Enables or disables the toolbar item.
Public Member Functions inherited from B::EventTarget
template<>
EventTargetRef GetEventTarget (WindowRef inObj)
template<>
EventTargetRef GetEventTarget (HIViewRef inObj)
template<>
EventTargetRef GetEventTarget (HIObjectRef inObj)
template<>
EventTargetRef GetEventTarget (EventTargetRef inObj)
void SetAccessible (bool inAccessible)
Make the object archivable.
void SetAccessibilityAttribute (CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetAccessibilityAttribute (UInt64 inIdentifier, CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetArchivable (bool inArchivable)
Make the object archivable.
bool IsAccessible () const
Is the object accessible?
bool IsArchivable () const
Is the object archivable?
operator HIObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
HIObjectRef GetObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
Static Public Member Functions
Object Creation
template<class T >
static OSPtr< HIToolbarItemRef > Create (const String &inIdentifier, OptionBits inAttributes, const Bundle &inBundle, const String &inPListName, Nib *inNib, CFTypeRef inConfigData, CFDictionaryRef inCustomData)
Creates an instance of class T.
static OSPtr< HIToolbarItemRef > Create (const String &inClassID, const String &inIdentifier, OptionBits inAttributes, const Bundle &inBundle, const String &inPListName, Nib *inNib, CFTypeRef inConfigData, CFDictionaryRef inCustomData)
Creates an instance of class inClassID.
static void FillInitializationEvent (EventRef ioEvent, const String &inIdentifier, OptionBits inAttributes, CFBundleRef inBundle, CFStringRef inPListName, Nib *inNib, CFDictionaryRef inCustomItemData, CFTypeRef inConfigData)
Instantiation
static EventTarget * Instantiate (HIObjectRef inObjectRef)
Instantiates a ToolbarItem with inObjectRef.
Static Public Member Functions inherited from B::EventTarget
template<class T >
static void Register ()
Registers class T (which must derive from EventTarget) with the HIToolbox.
template<class T >
static void Unregister ()
Unregisters class T (which must derive from EventTarget) from the HIToolbox.
template<class T >
static HIObjectClassRef GetObjectClass ()
Returns the object class associated with type T (which must derive from EventTarget), or NULL.
template<class T >
static OSPtr< HIObjectRef > Create (EventRef inEvent=NULL)
Creates an instance of class T.
static OSPtr< HIObjectRef > Create (CFStringRef inClassID, EventRef inEvent=NULL)
Creates an instance of class inClassID.
template<class T >
static T * InstanceData (HIObjectRef objRef)
Retrieves the C++ object of type T associated with the HIObjectRef objRef.
template<typename T >
static EventTargetRef GetEventTarget (T inObject)
Retrieves the EventTargetRef associated with inObject.
Static Public Attributes
static const CFStringRef kHIObjectClassID = CFSTR("ca.paullalonde.b.toolbaritem")
Class ID.
static const CFStringRef kHIObjectBaseClassID = kHIToolbarItemClassID
Base class ID.
Static Public Attributes inherited from B::EventTarget
static const CFStringRef kHIObjectBaseClassID = NULL
The default base class ID, representing HIObject.
Protected Member Functions
virtual void ReadCustomItemData (CFDictionaryRef inCustomItemData)
bool GetLocalisedString (CFDictionaryRef inDict, CFStringRef inKey, String &outString)
const Bundle & GetBundle () const
Nib * GetNib () const
Constructors / Destructor
ToolbarItem (HIObjectRef inObjectRef)
Constructor.
Handling Events
virtual void Initialize (EventRef inEvent)
Override to extract initialisation arguments from inEvent.
virtual OSPtr< CFTypeRef > GetPersistentData ()
Override to write out configuration info for the item.
virtual OSPtr< HIViewRef > CreateCustomView ()
Override to create a custom view for the item.
virtual bool PerformAction ()
Override to respond to clicks on the item's view.
virtual bool WouldAcceptDrop (DragRef inDragRef)
Override to accept drags onto the item's view.
virtual void AcceptDrop (DragRef inDragRef)
Override to accept drops onto the item's view.
virtual void SelectedStateChanged (WindowRef inWindowRef)
Override to perform some processing whenever the item's selected state changes.
Protected Member Functions inherited from B::EventTarget
EventTarget (HIObjectRef inObjectRef)
Constructor.
virtual ~EventTarget ()
Destructor.
void operator delete (void *ptr)
Protected delete prevents external clients from deleting instances directly.
virtual bool IsEqualTo (HIObjectRef inObjectRef)
Returns true if this is "equal" to inObjectRef.
virtual void PrintDebugInfo ()
Override to print debugging information to stdout.
virtual void Unarchive (HIArchiveRef ioArchive)
Decode the object into the given archive. This is called instead of Initialize().
virtual void Archive (HIArchiveRef ioArchive) const
Encode the object into the given archive.
Additional Inherited Members
Protected Types inherited from B::EventTarget
typedef EventTarget *(* ConstructProcPtr) (HIObjectRef inObjectRef)
Object construction callback.
Static Protected Member Functions inherited from B::EventTarget
static void PrivateRegister (CFStringRef inClassID, CFStringRef inBaseClassID, ConstructProcPtr inConstructor)
Registers class inClassID.
static void PrivateUnregister (CFStringRef inClassID)
Unregisters class inClassID.
static HIObjectClassRef PrivateFindClassObject (CFStringRef inClassID)
Returns the object class associated with type inClassID, or NULL.
static HIObjectRef PrivateCreate (CFStringRef inClassID, EventRef inEvent)
Creates an instance of class inClassID.
Protected Attributes inherited from B::EventTarget
const HIObjectRef mObjectRef
The underlying toolbox object.
Detailed Description
Wrapper class for toolbar items.
Todo:
Document this class!
Constructor & Destructor Documentation
B::ToolbarItem::ToolbarItem (HIObjectRef inObjectRef) protected
Constructor.
Parameters
inObjectRef The underlying toolbox object.
References B::EventHandler::Add(), and B::EventHandler::Init().
Referenced by Instantiate().
Member Function Documentation
template<class T > OSPtr< HIToolbarItemRef > B::ToolbarItem::Create (const String & inIdentifier, OptionBits inAttributes, const Bundle & inBundle, const String & inPListName, Nib * inNib, CFTypeRef inConfigData, CFDictionaryRef inCustomData) static
Creates an instance of class T.
Parameters
T The C/C++ type of the toolbar item. Must be ToolbarItem or derived from ToolbarItem.
References B::Bundle::cf_ref(), and B::String::cf_ref().
EventTarget * B::ToolbarItem::Instantiate (HIObjectRef inObjectRef) static
Instantiates a ToolbarItem with inObjectRef.
Parameters
inObjectRef The underlying toolbox object.
References ToolbarItem().
void B::ToolbarItem::ChangeAttributes (OptionBits inAttrsToSet, OptionBits inAttrsToClear)
Changes the toolbar item's attributes.
Parameters
inAttrsToSet A bitmask of attributes to set.
inAttrsToClear A bitmask of attributes to clear.
void B::ToolbarItem::SetLabel (const String & inLabel)
Changes the toolbar item's label.
Parameters
inLabel The new label.
References B::String::cf_ref().
Referenced by Initialize().
OSPtr< CFTypeRef > B::ToolbarItem::GetPersistentData () protected virtual
Override to write out configuration info for the item.
The default implementation returns NULL.
Referenced by SelectedStateChanged().
OSPtr< HIViewRef > B::ToolbarItem::CreateCustomView () protected virtual
Override to create a custom view for the item.
The default implementation returns NULL.
References B::ViewFactory::GetDefaultSignature().
Referenced by SelectedStateChanged().
bool B::ToolbarItem::PerformAction () protected virtual
Override to respond to clicks on the item's view.
The default implementation does nothing.
Returns
true, if the action was handled.
Referenced by SelectedStateChanged().
bool B::ToolbarItem::WouldAcceptDrop (DragRef inDragRef) protected virtual
Override to accept drags onto the item's view.
The default implementation does nothing.
Returns
true, if the drag is acceptable.
Referenced by SelectedStateChanged().
void B::ToolbarItem::AcceptDrop (DragRef inDragRef) protected virtual
Override to accept drops onto the item's view.
The default implementation does nothing.
Referenced by SelectedStateChanged().
void B::ToolbarItem::SelectedStateChanged (WindowRef inWindowRef) protected virtual
Override to perform some processing whenever the item's selected state changes.
The default implementation does nothing.
Parameters
inWindowRef The window in which in change occurred. May be NULL.
References AcceptDrop(), B_VAR_EXPORT, CreateCustomView(), GetPersistentData(), PerformAction(), and WouldAcceptDrop().
The documentation for this class was generated from the following files:
BToolbarItem.h
BToolbarItem.cpp