B: B::AutoMacResourceHandle Class Reference
B::AutoMacResourceHandle Class Reference
Wrapper around Carbon resource handles.
#include <BMemoryUtilities.h>
Public Types
typedef ::Handle MacHandle
Synonym for classic Mac OS Handle.
Public Member Functions
AutoMacResourceHandle & operator= (AutoMacResourceHandle &ioHandle)
Assignment. Acquires ownership of ioHandle's handle.
Constructors & Destructor
AutoMacResourceHandle (OSType inType, SInt16 inID, bool in1Deep=true)
Constructor. Reads the resource of type inType and ID inID.
AutoMacResourceHandle (AutoMacResourceHandle &ioHandle)
AutoMacResourceHandle constructor. Acquires ownership of ioHandle's handle.
AutoMacResourceHandle (MacHandle inHandle)
Handle constructor. Acquires ownership of inHandle.
~AutoMacResourceHandle ()
Destructor. Releases the resource handle, if any.
Inquiries
size_t size () const
Returns the amount of memory allocated to the underlying resource handle.
MacHandle get_handle () const
Returns the underlying resource handle.
Modifiers
MacHandle release ()
Relenquishes ownership of the underlying resource handle, and returns it.
void reset (MacHandle inHandle=NULL)
Relenquishes ownership of the underlying resource handle, and acquires ownership of inHandle.
void resize (size_t inNewSize)
Changes the amount of memory allocated to the underlying resource handle.
void load ()
Loads the resource handle into memory so it's immediately accessible. It may still need to be locked and/or protected against purging, though.
Detailed Description
Wrapper around Carbon resource handles.
This class provides "resource acquisition is initialization" (RAII) semantics for Carbon resource handles. It features a destructive copy constructor and assignment operator similar in spirit to std::auto_ptr.
Note
This class deals with the raw Handle type, so it isn't type-safe.
Constructor & Destructor Documentation
B::AutoMacResourceHandle::AutoMacResourceHandle (MacHandle inHandle) explicit
Handle constructor. Acquires ownership of inHandle.
Note
If inHandle is an ordinary handle (and not a resource handle), the result is undefined.
References reset().
Member Function Documentation
void B::AutoMacResourceHandle::reset (MacHandle inHandle = NULL)
Relenquishes ownership of the underlying resource handle, and acquires ownership of inHandle.
Note
If inHandle is an ordinary handle (and not a resource handle), the result is undefined.
Referenced by AutoMacResourceHandle(), operator=(), and ~AutoMacResourceHandle().
The documentation for this class was generated from the following files:
BMemoryUtilities.h
BMemoryUtilities.cpp