B: B::GetFileDialog Class Reference
B::GetFileDialog Class Reference
Implements the standard "Open" dialog as per the Aqua HIG.
#include <BNavDialogs.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Member Functions
Setup
void SetDocumentTypes (const Bundle &inBundle)
Allows the user to select any of the document types declared in inBundle's Info.plist file.
template<class InputIterator >
void SetDocumentTypes (const Bundle &inBundle, CFStringRef inTable, InputIterator inFirst, InputIterator inLast)
Allows the user to select any file from the document types contained in the iterator sequence.
void SelectDocumentType (const String &inDocTypeName)
Initially select the pop-up menu item for the given document type.
template<class GET_FILE_DIALOG >
void SetCallback (B_GETFILEDIALOG_CB inFunction)
Sets the dialog's callback.
Public Member Functions inherited from B::NavReplyDialog
virtual ~NavReplyDialog ()
Destructor.
void SetPopupMenuContents (PopupMenuContentsVector &inContents)
Sets the custom elements in the show & format pop-up menus.
void FilterAllFiles ()
Selects the "All Documents" pop-up menu item.
void FilterAllReadableFiles ()
Selects the "All Reaadable Documents" pop-up menu item.
void FilterByName (const String &inFilterName)
Selects the pop-up menu item for the given filter name.
void SetCustomView (Nib &inNib, const char *inViewName)
Sets the top-level custom view.
void GetNavReply (AutoNavReply &outNavReply) const
Returns the dialog's nav reply.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Static Public Member Functions
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
Unlike the simpler Nav dialogs (eg AskSaveChangesDialog), it's not possible to configure the dialog completely with Make() except in the simplest of cases. This is because there are many more configuration options in this dialog.
template<class GET_FILE_DIALOG >
static std::auto_ptr< GET_FILE_DIALOG > Make (const DialogModality &inModality, B_GETFILEDIALOG_CB inFunction=NullCallback< GET_FILE_DIALOG >())
Instantiates and returns a GET_FILE_DIALOG with the given arguments.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class GET_FILE_DIALOG >
static void Start (const DialogModality &inModality, B_GETFILEDIALOG_CB inFunction=NullCallback< GET_FILE_DIALOG >())
Instantiates a GET_FILE_DIALOG with the given arguments, then enters it.
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Protected Member Functions
GetFileDialog ()
Protected default constructor to discourage stack-based instantiation.
void FillPopupMenuWithDocTypes (const Bundle &inBundle, CFStringRef inTable)
Overrides from NavReplyDialog
virtual NavDialogRef CreateDialog ()
virtual void HandleReply (NavUserAction inUserAction, NavReplyRecord &ioNavReply)
virtual bool FilterObjectByAllReadableFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
virtual bool FilterObjectByFilterName (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
virtual void PopupMenuSelect (const NavMenuItemSpec &inMenuItemSpec)
Protected Member Functions inherited from B::NavReplyDialog
NavReplyDialog ()
Protected default constructor to discourage stack-based instantiation.
View * FindCustomViewByID (int inID) const
View * FindCustomViewByID (OSType inSignature, int inID) const
virtual bool Preview (NavCBRecPtr ioParams)
Preview hook.
virtual void NegotiateCustomArea (Size &ioSize)
Override this function to negotiate an area in the dialog for custom UI elements.
virtual void DialogResized (Rect &ioCustomBounds, Rect &ioPreviewBounds)
Override this to do some processing when the dialog is resized.
virtual void LocationChanged (const AEDesc &inNewLocation)
Override this to do some processing when the location displayed in the browser list changes.
virtual void GoneToDesktop ()
Override this to do some processing when the desktop is displayed in the dialog.
virtual void SelectionChanged (const AEDescList &inNewSelection)
Override this to do some processing when the selection in the browser list changes.
virtual void AdjustPreview (bool visible)
Override this to do some processing when preview area is turned on or off.
virtual void SelectionOpened ()
Override this to do some processing when the selection in the browser list is opened.
virtual void DialogAccepted ()
Override this to do some processing when the user performs a confirming action.
virtual void DialogCancelled ()
Override this to do some processing when the user performs a cancelling action.
virtual bool FilterObject (const AEDesc &inItem, const NavFileOrFolderInfo &inInfo, NavFilterModes inFilterMode)
Determines whether the object denoted by inItem, inInfo and inFilterMode should be displayed.
virtual bool FilterObjectByAllFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when "All Documents" is selected in the pop-up menu.
virtual void SelectFilter (FilterKind inFilterKind, const String &inFilterName=String())
Changes the current filter.
virtual void HandleUserAction (NavUserAction inUserAction)
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
virtual void DialogStarting (NavCBRec &ioParams)
void ShowDesktop ()
Tells the dialog to display the desktop.
void SortBy (NavSortKeyField inField)
Tells the dialog to sort the browser list according to inField.
void SortOrder (NavSortOrder inOrder)
Tells the dialog to sort the browser list in ascending or descending order, according to inOrder.
void ScrollHome ()
Tells the dialog to scroll the browser list to the top.
void ScrollEnd ()
Tells the dialog to scroll the browser list to the bottom.
void ScrollPageUp ()
Tells the dialog to scroll the browser list up a page.
void ScrollPageDown ()
Tells the dialog to scroll the browser list down a page.
void GetLocation (AEDesc &outLocation)
Tells the dialog to return the location displayed in the browser list.
void SetLocation (const AEDesc &inLocation)
Tells the dialog to change the location displayed in the browser list.
void GetSelection (AEDesc &outSelection)
Tells the dialog to return the selection in the browser list.
void SetSelection (const AEDesc &inSelection)
Tells the dialog to change the selection in the browser list.
void ShowSelection ()
Tells the dialog to reveal the selection in the browser list.
void OpenSelection ()
Tells the dialog to open the selected item in the browser list.
void EjectVolume (short inVRefNum)
Tells the dialog to eject the volume identified by inVRefNum.
bool IsPreviewShowing ()
Returns true if the preview area is currently available.
void SelectCustomType (const NavMenuItemSpec &inSpec)
Tells the dialog to choose the custom pop-up menu item identified by inSpec.
void SelectAllType (MenuItemIndex inItem)
Tells the dialog to choose the standard pop-up menu item identified by inItem.
void SelectEditFileName (const struct ControlEditTextSelectionRec &inSelection)
Tells the dialog to change the selection in the file name field.
void BrowserSelectAll ()
Tells the dialog to select all items in the browser list.
void GotoParent ()
Tells the dialog to navigate to the parent item of the current selection.
void SetActionState (NavActionState inActionState)
Tells the dialog to prevent the user from performing certain actions, such clicking the Cancel button.
void BrowserRedraw ()
Tells the dialog to refresh its browser list.
bool RunReplyDialog (NavUserAction inConfirmAction, AutoNavReply &outNavReply)
Runs the dialog, returning the nav reply if the user confirmed the dialog.
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Running Dialogs
These are convenience functions for displaying nav dialogs in an application-modal fashion. Because they don't return until the nav dialog is dismissed, the chosen action is returned as the function result.
bool Run (AutoNavReply &outNavReply, bool inUnused)
Displays the nav dialog in an application-modal fashion.
template<class GET_FILE_DIALOG >
static bool Run (AutoNavReply &outNavReply)
Instantiates a GET_FILE_DIALOG, then enters a modal event loop for it.
Additional Inherited Members
Public Types inherited from B::NavReplyDialog
enum FilterKind {
kFilterName = 1, kFilterAllFiles, kFilterAllAppFiles, kFilterAllReadableFiles,
kFilterSeparator
}
< Types of file system object filtering.
typedef std::vector< PopupMenuItem > PopupMenuContentsVector
The entire contents of the filtering pop-up menu.
Static Protected Member Functions inherited from B::NavReplyDialog
static NavObjectFilterUPP GetObjectFilterUPP ()
Returns the UPP to use for filtering file system objects.
static NavPreviewUPP GetPreviewUPP ()
Returns the UPP to use for previewing.
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Protected Attributes inherited from B::NavReplyDialog
PopupMenuContentsVector mPopupMenuContents
FilterKind mCurrentFilterKind
The filter type of the currently selected item in the file type pop-up menu.
String mCurrentFilterName
The filter name of the currently selected item in the file type pop-up menu.
Detailed Description
Implements the standard "Open" dialog as per the Aqua HIG.
Unlike the simpler nav dialogs derived directly from NavDialog, GetFileDialog doesn't allow for passing arguments (beyond the DialogModality and callback) to the Make/Start/Run functions. That's because the configuration of this dialog can be quite complex; so the task has been left to clients.
GetFileDialog's configuration functions all have to do with the file type pop-up menu. This is because Navigation Services' filtering API is inordinately hard to use, since it's based on matching files with creators & file types, and on Mac OS X that's not very useful.
A number of factors affect the file type pop-up menu:
The kNavNoTypePopup flag. This flag controls the visibility of the pop-up menu and takes precedence over other options. If the flag is set, then each file is matched against all of the entries in the document types array. The flag can be changed with SetFlag()/ClearFlag().
The document types array. This array is set with SetDocumentTypes(). There are various scenarios, depending on the number of elements in the array:
If the array is empty, then all files will match successfully, regardless of extension or file type.
If the array contains only one element, then the pop-up menu is not displayed (unless other factors cause it to be displayed) and files are matched against the element.
If the array contains more than one element, then the pop-up menu is displayed and contains one item per element. When one of the items in the pop-up menu is selected, the files are matched against the corresponding document type entry. In addition, an item called "All Readable Documents" is prepended to the pop-up menu which causes the files to be matched against all of the document type entries.
See also
Dialogs, Alerts and Navigation Services
Member Function Documentation
void B::GetFileDialog::SetDocumentTypes (const Bundle & inBundle)
Allows the user to select any of the document types declared in inBundle's Info.plist file.
Sets the document types array to all of the document types in inBundle. The array is then used to populate the file type pop-up menu. The document types' localised names are assumed to reside in the "InfoPlist.strings" file within inBundle. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup). Finally, the current filter is changed to match files matching any of the doc types.
Parameters
InputIterator Template parameter. An input iterator yielding a Bundle::DocumentType object.
Parameters
inBundle The bundle in which to look for localised document type names.
References B::Bundle::begin(), and B::Bundle::end().
template<class InputIterator > void B::GetFileDialog::SetDocumentTypes (const Bundle & inBundle, CFStringRef inTable, InputIterator inFirst, InputIterator inLast)
Allows the user to select any file from the document types contained in the iterator sequence.
Sets the document types array to be equal to the iterator sequence [inFirst, inLast). The array is then used to populate the file type pop-up menu. inBundle and inTable are used to read the localised strings for each document type. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup). Finally, the current filter is changed to match files matching any of the doc types.
Parameters
InputIterator Template parameter. An input iterator yielding a Bundle::DocumentType object.
Parameters
inBundle The bundle in which to look for localised document type names.
inTable The table in which to look for localised document type names (may be NULL).
inFirst The start of the sequence of document type objects.
inLast The end of the sequence of document type objects.
template<class GET_FILE_DIALOG > void B::GetFileDialog::SetCallback (B_GETFILEDIALOG_CB inFunction)
Sets the dialog's callback.
Todo:
Complete this!
Parameters
GET_FILE_DIALOG Template parameter. The class of the instantiated dialog. Must be GetFileDialog or a class derived from GetFileDialog.
template<class GET_FILE_DIALOG > std::auto_ptr< GET_FILE_DIALOG > B::GetFileDialog::Make (const DialogModality & inModality, B_GETFILEDIALOG_CB inFunction = NullCallback<GET_FILE_DIALOG>()) static
Instantiates and returns a GET_FILE_DIALOG with the given arguments.
Instantiates a dialog of class GET_FILE_DIALOG. The instance of GET_FILE_DIALOG is then configured with the given arguments. Finally the dialog is returned, ready to be displayed via Enter().
Parameters
GET_FILE_DIALOG Template parameter. The class of the instantiated window. Must be GetFileDialog or a class derived from GetFileDialog.
Returns
The GET_FILE_DIALOG object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inModality The dialog's modality.
inFunction A callback that is invoked when the dialog is dismissed.
template<class GET_FILE_DIALOG > void B::GetFileDialog::Start (const DialogModality & inModality, B_GETFILEDIALOG_CB inFunction = NullCallback<GET_FILE_DIALOG>()) static
Instantiates a GET_FILE_DIALOG with the given arguments, then enters it.
Instantiates a nav dialog of class GET_FILE_DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog, call Make() then Enter().
Parameters
GET_FILE_DIALOG Template parameter. The class of the instantiated window. Must be GetFileDialog or a class derived from GetFileDialog.
See also
Make(), NavDialog::Enter()
Parameters
inModality The dialog's modality.
inFunction A callback that is invoked when the dialog is dismissed.
template<class GET_FILE_DIALOG > bool B::GetFileDialog::Run (AutoNavReply & outNavReply) static
Instantiates a GET_FILE_DIALOG, then enters a modal event loop for it.
Instantiates a nav dialog of class GET_FILE_DIALOG, as per Make(). Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
GET_FILE_DIALOG Template parameter. The class of the instantiated window. Must be GetFileDialog or a class derived from GetFileDialog.
Returns
true if the user selected at least one file.
See also
Make(), Run()
Parameters
outNavReply The nav reply; only valid if the function returns true.
References B::DialogModality::Modal().
bool B::GetFileDialog::FilterObjectByAllReadableFiles (const FSRef & inRef, const LSItemInfoRecord & inInfo, NavFilterModes inFilterMode) protected virtual
This implementation attempts to match the file against all of the document type entries given in SetDocType().
Directories are always shown. However, nothing special is done currently with aliases, packages, etc.
Parameters
inRef Contains the file system object to filter.
inInfo Pertinent info about inRef.
inFilterMode Specifies where this object will appear in the dialog.
Reimplemented from B::NavReplyDialog.
References B::Bundle::FindDocumentTypeForFileInfo().
bool B::GetFileDialog::FilterObjectByFilterName (const FSRef & inRef, const LSItemInfoRecord & inInfo, NavFilterModes inFilterMode) protected virtual
Directories are always shown. However, nothing special is done currently with aliases, packages, etc.
Parameters
inRef Contains the file system object to filter.
inInfo Pertinent info about inRef.
inFilterMode Specifies where this object will appear in the dialog.
Reimplemented from B::NavReplyDialog.
References B::Bundle::DoesFileInfoMatchDocumentType().
void B::GetFileDialog::FillPopupMenuWithDocTypes (const Bundle & inBundle, CFStringRef inTable) protected
Uses mDocTypes to populate the file type pop-up menu. inBundle and inTable are used to read the localised strings for each document type. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup). Finally, the current filter is changed to match files matching any of the doc types.
Parameters
inBundle The bundle in which to look for localised document type names.
inTable The table in which to look for localised document type names (may be NULL).
References BLocalizedStringFromTable, B::NavReplyDialog::kFilterAllReadableFiles, B::NavReplyDialog::PopupMenuItem::PopupMenuItem(), and B::NavReplyDialog::SetPopupMenuContents().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp