B: B::AskSaveChangesDialog Class Reference
B::AskSaveChangesDialog Class Reference
Implements the standard "Save Changes" alert as per the Aqua HIG.
#include <BNavDialogs.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Types
Constants
enum Context { kClosing = kNavSaveChangesClosingDocument, kQuitting = kNavSaveChangesQuittingApplication, kOther = kNavSaveChangesOther }
Enumerates the possible reasons for invoking this dialog.
enum Action { kSave = kNavUserActionSaveChanges, kDontSave = kNavUserActionDontSaveChanges, kCancel = kNavUserActionCancel }
Enumerates the possible results of this dialog.
Public Member Functions
Setup
void SetContext (Context inContext)
Sets the dialog's "context" (i.e. is this for a Close or a Quit).
template<class ASK_SAVE_CHANGES_DIALOG >
void SetCallback (B_ASKSAVECHANGES_CB inFunction)
Sets the dialog's callback.
Retrieving Results
Action GetAction () const
Returns the action that dismissed the dialog. Only useful in app-modal scenario.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Static Public Member Functions
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
template<class ASK_SAVE_CHANGES_DIALOG >
static std::auto_ptr< ASK_SAVE_CHANGES_DIALOG > Make (const DialogModality &inModality, const String &inFileName, Context inContext, B_ASKSAVECHANGES_CB inFunction=NullCallback< ASK_SAVE_CHANGES_DIALOG >())
Instantiates and returns an ASK_SAVE_CHANGES_DIALOG with the given arguments.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class ASK_SAVE_CHANGES_DIALOG >
static void Start (const DialogModality &inModality, const String &inFileName, Context inContext, B_ASKSAVECHANGES_CB inFunction=NullCallback< ASK_SAVE_CHANGES_DIALOG >())
Instantiates an ASK_SAVE_CHANGES_DIALOG with the given arguments, then enters it.
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Protected Member Functions
AskSaveChangesDialog ()
Protected default constructor to discourage stack-based instantiation.
void Configure (const DialogModality &inModality, const String &inFileName, Context inContext)
Helper function for configuring the dialog.
Overrides from NavDialog
virtual NavDialogRef CreateDialog ()
virtual void HandleUserAction (NavUserAction inUserAction)
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual void DialogStarting (NavCBRec &ioParams)
Override this to do some processing after the dialog is created and initialised, but before it's displayed.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
Low-level function to handle Nav dialog events. There's normally no need to override this function.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Running Dialogs
These are convenience functions for displaying nav dialogs in an application-modal fashion. Because they don't return until the nav dialog is dismissed, the chosen action is returned as the function result.
Action Run ()
Displays the nav dialog in an application-modal fashion.
template<class ASK_SAVE_CHANGES_DIALOG >
static Action Run (const String &inFileName, Context inContext)
Instantiates an ASK_SAVE_CHANGES_DIALOG, then enters a modal event loop for it.
Additional Inherited Members
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Detailed Description
Implements the standard "Save Changes" alert as per the Aqua HIG.
Beyond the usual DialogModality and callback arguments that are common to all nav dialogs, the Make/Start/Run functions also take as arguments:
The display name of the file that's about to be closed.
An value in the Context enumeration, which indicates why the file is being closed. The dialog's result is a value in the Action enumeration. An enum is used here because this dialog has three buttons, not just the usual OK/Cancel button pair.
See also
Dialogs, Alerts and Navigation Services
Member Enumeration Documentation
enum B::AskSaveChangesDialog::Context
Enumerates the possible reasons for invoking this dialog.
Enumerator
kClosing
The dialog is being invoked because a document is being closed.
kQuitting
The dialog is being invoked because the application is quitting.
kOther
The dialog is being invoked for some other reason.
enum B::AskSaveChangesDialog::Action
Enumerates the possible results of this dialog.
Enumerator
kSave
The user clicked the "Save" button.
kDontSave
The user clicked the "Don't Save" button.
kCancel
The user clicked the "Cancel" button.
Member Function Documentation
void B::AskSaveChangesDialog::SetContext (Context inContext)
Sets the dialog's "context" (i.e. is this for a Close or a Quit).
It's important to call this function because it affects the text displayed in the alert.
Parameters
inContext The context in which we're being called.
Referenced by Configure().
template<class ASK_SAVE_CHANGES_DIALOG > void B::AskSaveChangesDialog::SetCallback (B_ASKSAVECHANGES_CB inFunction)
Sets the dialog's callback.
Todo:
Complete this!
Parameters
ASK_SAVE_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskSaveChangesDialog or a class derived from AskSaveChangesDialog.
template<class ASK_SAVE_CHANGES_DIALOG > std::auto_ptr< ASK_SAVE_CHANGES_DIALOG > B::AskSaveChangesDialog::Make (const DialogModality & inModality, const String & inFileName, Context inContext, B_ASKSAVECHANGES_CB inFunction = NullCallback<ASK_SAVE_CHANGES_DIALOG>()) static
Instantiates and returns an ASK_SAVE_CHANGES_DIALOG with the given arguments.
Instantiates a nav dialog of class ASK_SAVE_CHANGES_DIALOG. The instance of ASK_SAVE_CHANGES_DIALOG is then configured with the given arguments. Finally the dialog is returned, ready to be displayed via Enter().
Parameters
ASK_SAVE_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskSaveChangesDialog or a class derived from AskSaveChangesDialog.
Returns
The ASK_SAVE_CHANGES_DIALOG object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to save.
inContext The context in which we're being called.
inFunction A callback that is invoked when the dialog is dismissed.
template<class ASK_SAVE_CHANGES_DIALOG > void B::AskSaveChangesDialog::Start (const DialogModality & inModality, const String & inFileName, Context inContext, B_ASKSAVECHANGES_CB inFunction = NullCallback<ASK_SAVE_CHANGES_DIALOG>()) static
Instantiates an ASK_SAVE_CHANGES_DIALOG with the given arguments, then enters it.
Instantiates a nav dialog of class ASK_SAVE_CHANGES_DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog, call Make() then Enter().
Parameters
ASK_SAVE_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskSaveChangesDialog or a class derived from AskSaveChangesDialog.
See also
Make(), NavDialog::Enter()
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to save.
inContext The context in which we're being called.
inFunction A callback that is invoked when the dialog is dismissed.
template<class ASK_SAVE_CHANGES_DIALOG > AskSaveChangesDialog::Action B::AskSaveChangesDialog::Run (const String & inFileName, Context inContext) static
Instantiates an ASK_SAVE_CHANGES_DIALOG, then enters a modal event loop for it.
Instantiates a nav dialog of class ASK_SAVE_CHANGES_DIALOG, as per Make(). Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
ASK_SAVE_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskSaveChangesDialog or a class derived from AskSaveChangesDialog.
Returns
The Action that dismissed the nav dialog.
See also
Make(), Run()
Parameters
inFileName The display name of the file we're being asked to save.
inContext The context in which we're being called.
References B::DialogModality::Modal().
void B::AskSaveChangesDialog::HandleUserAction (NavUserAction inUserAction) protected virtual
Parameters
inUserAction The user action.
Implements B::NavDialog.
void B::AskSaveChangesDialog::Configure (const DialogModality & inModality, const String & inFileName, Context inContext) protected
Helper function for configuring the dialog.
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to save.
inContext The context in which we're being called.
References kCancel, kDontSave, kSave, SetContext(), B::NavDialog::SetFileName(), and B::NavDialog::SetModality().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp