B: B::AutoTypedHandle< T > Class Template Reference
B::AutoTypedHandle< T > Class Template Reference
Type-safe wrapper around Carbon Handle type.
#include <BMemoryUtilities.h>
Public Types
typedef ::Handle MacHandle
Synonym for classic Mac OS Handle.
Template Parameters
typedef anything T
The language type.
Public Member Functions
AutoTypedHandle & operator= (AutoTypedHandle &ioHandle)
Assignment. Acquires ownership of ioHandle's handle.
Constructors & Destructor
AutoTypedHandle ()
Default constructor. Creates a handle the size of a T.
AutoTypedHandle (AutoTypedHandle &ioHandle)
AutoTypedHandle constructor. Acquires ownership of ioHandle's resource handle.
AutoTypedHandle (T **inHandle)
T constructor. Acquires ownership of inHandle.
~AutoTypedHandle ()
Destructor. Releases the handle, if any.
Inquiries
size_t size () const
Returns the amount of memory allocated to the underlying handle.
T ** get () const
Returns properly typed underlying handle.
MacHandle get_handle () const
Returns the underlying handle as a ::Handle.
Modifiers
T ** release ()
Relenquishes ownership of the underlying handle, and returns it.
void reset (T **inHandle=NULL)
Relenquishes ownership of the underlying handle, and acquires ownership of inHandle.
void resize (size_t inNewSize)
Changes the amount of memory allocated to the underlying handle.
Detailed Description
template<typename T>
class B::AutoTypedHandle< T >
Type-safe wrapper around Carbon Handle type.
This class provides "resource acquisition is initialization" (RAII) semantics for Carbon Handles. It features a destructive copy constructor and assignment operator similar in spirit to std::auto_ptr.
It's assumed that the handles given to objects of this type match the template parameter T. T can be any POD (aka Plain Old Data) type.
Member Function Documentation
template<typename T > void B::AutoTypedHandle< T >::reset (T ** inHandle = NULL)
Relenquishes ownership of the underlying handle, and acquires ownership of inHandle.
Note
If inHandle is a resource handle (and not an ordinary handle), the result is undefined.
Referenced by B::AutoTypedHandle< T >::AutoTypedHandle(), B::AutoMacPtr::get_ptr(), B::AutoTypedPtr< T >::get_ptr(), B::AutoTypedHandle< T >::operator=(), and B::AutoTypedHandle< T >::~AutoTypedHandle().
The documentation for this class was generated from the following file:
BMemoryUtilities.h