B: B::PRINT_POLICY Class Reference
B::PRINT_POLICY Class Reference
Undo
Template for a Print Policy class.
#include <BPrintPolicyConcept.h>
Public Types
Types
typedef boost::function1< void, PrintSession & > DialogInitCallback
The type of the callback that is invoked before the Page Setup dialog is displayed.
typedef boost::function2< void, PrintSession &, bool > DialogResultCallback
The type of the callback that is invoked after the Page Setup dialog has been displayed.
typedef boost::signal1< void, PageFormat & > PageFormatChangedSignal
The type of the signal that is triggered whenever the page format is changed.
typedef boost::signal1< void, PrintSettings & > PrintSettingsChangedSignal
The type of the signal that is triggered whenever the print settings are changed.
Public Member Functions
Constructor & Destructor
PRINT_POLICY (EventTargetRef inTarget, const Bundle &inBundle)
Constructor.
~PRINT_POLICY ()
Destructor.
Setup
void SetPageSetupDialogInitCallback (DialogInitCallback inCallback)
Sets the callback that is invoked before the Page Setup dialog is displayed.
void SetPageSetupDialogResultCallback (DialogResultCallback inCallback)
Sets the callback that is invoked after the Page Setup dialog has been displayed.
void SetPrintDialogInitCallback (DialogInitCallback inCallback)
Sets the callback that is invoked before the Print dialog is displayed.
void SetPrintDialogResultCallback (DialogResultCallback inCallback)
Sets the callback that is invoked after the Print dialog has been displayed.
PageFormatChangedSignal & GetPageFormatChangedSignal ()
Returns a signal that is triggered whenever the page format is changed.
PrintSettingsChangedSignal & GetPrintSettingsChangedSignal ()
Returns a signal that is triggered whenever the print settings are changed.
void EnablePrintCommand (bool enable)
Enables the Print menu command.
Inquiries
PageFormat & GetPageFormat ()
Returns the policy's page format object.
PrintSettings & GetPrintSettings ()
Returns the policy's print settings object.
Validation
void ValidatePageFormat ()
Validates the embedded page format object.
void ValidatePrintSettings ()
Validates the embedded print settings object.
Printing
void Print (PrintSettings *inPrintSettings, Printer *inPrinter, bool inShowDialog)
Initiates the printing process.
Detailed Description
Template for a Print Policy class.
PRINT_POLICY isn't a class; rather, its specifies the required interface for a class in order for it to be useable as a template parameter. So for example, if a class Foo is declared like so:
template <class PRINT_POLICY> Foo { ... };
and class Bar implements the interface described herein, then one can instantiate Foo with Bar:
class MyFoo : public Foo<Bar> { ... };
Conceptually, PRINT_POLICY maintains two stacks of action groups, one for Undo and the other for Redo. Both stacks can be arbitrarily deep, or they can have a fixed maximal size. Attempting to push an undo group onto a stack that is already at its maximum size will cause the action group at the bottom of the stack to be discarded.
The next question is, what's an action group? It's an ordered collection of one or more undo actions (objects derived from UndoAction). Action groups may be nested. They are populated by having a client call BeginGroup(), which creates a new empty group and "opens" it. The client then calls Add() one or more times, which has the effect of appending each UndoAction to the open group. The idea is that as the client is modifying its state, it passes to Add() objects that are capable of restoring that state. If the client's processing proceeds normally, it closes the group by calling CommitGroup(). This pushes the group onto either the Undo or Redo stack. On the other hand, if an error occurs in the client while it was modifying its state (eg, an exception is thrown), then the client closes the group by calling AbortGroup() instead. AbortGroup() executes each undo action in the currently open group (as well as nested groups etc) before discarding the group. Thus the trio of functions BeginGroup() / CommitGroup() / AbortGroup() are analogous to similarly-named transaction functions in the database world.
When a user issues and Undo or a Redo menu command, the top-most action group on the corresponding stack is executed, then it is discarded. Typically, the act of executing the group will trigger further calls to Add(), this time for Redo actions.
Note that the above description applies to PRINT_POLICY generally. Some concrete implementations may collapse one or more aspects of the policy. For example, a "null" policy might have stub implementations for CommitGroup() and AbortGroup(), among others.
In addition to the "class" interface presented below, PRINT_POLICY must also implement two other interfaces: one for Apple Events and the other for Carbon Events.
Apple Event Interface
This interface is required to support Undo & Redo via AppleScript.
kAEMiscStandards / kAEUndo
Because this Apple Event doesn't have a direct parameter (which means we don't know who exactly is supposed to receive it), the event is translated into a kEventClassCommand / kEventCommandProcess Carbon Event for the kHICommandUndo command and sent to the user input focus.
kAEMiscStandards / kAERedo
Because this Apple Event doesn't have a direct parameter (which means we don't know who exactly is supposed to receive it), the event is translated into a kEventClassCommand / kEventCommandProcess Carbon Event for the kHICommandRedo command and sent to the user input focus.
Carbon Event Interface
This interface is required to support decoupling the Undo Policy from its clients. One will usually want to isolate code that performs undoable state changes from the exact implementation of the Undo Policy. This is done by having such code use the functions of the Undo class to open and close groups and add undoable actions, rather than using the Policy's member functions directly. The Undo class translates its requests into Carbon Events which are then handled in the Undo Policy.
kEventClassB / kEventBUndoBegin
This is equivalent to calling BeginGroup(). An optional parameter specifies the action group's name.
Parameters:
kEventParamBUndoName (in, typeCFStringRef)
The action group's name. This parameter is optional; if absent a default name is used.
kEventClassB / kEventBUndoCommit
This is equivalent to calling CommitGroup().
kEventClassB / kEventBUndoAbort
This is equivalent to calling AbortGroup().
kEventClassB / kEventBUndoAdd
This is equivalent to calling Add().
Parameters:
kEventParamBUndoAction (in, typeBUndoAction)
The undoable action, of a type derived from UndoAction.
kEventClassB / kEventBUndoEnable
This is equivalent to calling Enable().
Parameters:
kEventParamBUndoEnable (in, typeBoolean)
The argument to pass to Enable().
Currently, two classes take undo policies as template parameters: Application and Document.
There are currently 3 examples of implementations of PRINT_POLICY:
NullUndoPolicy, for applications that don't need to support Undo.
MultipleUndoPolicy, for applications that need separate Undo and Redo stacks of arbitrary size.
SingleUndoPolicy, for applications that need only a simple 1-level-deep Undo.
Constructor & Destructor Documentation
B::PRINT_POLICY::PRINT_POLICY (EventTargetRef inTarget, const Bundle & inBundle)
Constructor.
Typically installs Carbon Event handlers on inTarget.
Parameters
inTarget The event target onto which the object can install handlers.
inBundle The bundle from which to retrieve resources.
Member Function Documentation
void B::PRINT_POLICY::EnablePrintCommand (bool enable)
Enables the Print menu command.
By disabling the Print menu command, one gets a print policy that only stores a PageFormat object.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Application().
PageFormat& B::PRINT_POLICY::GetPageFormat ()
Returns the policy's page format object.
Note
This is a modifiable reference. Changes to it will change the page format embedded in the policy.
PrintSettings& B::PRINT_POLICY::GetPrintSettings ()
Returns the policy's print settings object.
Note
This is a modifiable reference. Changes to it will change the page format embedded in the policy.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality().
void B::PRINT_POLICY::ValidatePageFormat ()
Validates the embedded page format object.
Note
If validation results in changes to the page format object, the PageFormatChanged signal is triggered.
void B::PRINT_POLICY::ValidatePrintSettings ()
Validates the embedded print settings object.
Note
If validation results in changes to the print settings object, the PrintSettingsChanged signal is triggered.
void B::PRINT_POLICY::Print (PrintSettings * inPrintSettings, Printer * inPrinter, bool inShowDialog)
Initiates the printing process.
Note
If inShowDialog is true, displays the Print dialog, then invokes the print dialog's result callback; else, invokes the callback without displaying the dialog.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality().
The documentation for this class was generated from the following file:
BPrintPolicyConcept.h