B: B::AutoTrackingArea Class Reference
B::AutoTrackingArea Class Reference
Lifecycle management for HIViewTrackingAreaRefs.
#include <BAutoTrackingArea.h>
Classes
struct Ref
Helper class.
Public Member Functions
Constructors / Destructor
AutoTrackingArea ()
Default constructor.
AutoTrackingArea (HIViewRef inViewRef, HIShapeRef inShapeRef, HIViewTrackingAreaID inID=0)
Constructor from HIToolbox objects.
AutoTrackingArea (AutoTrackingArea &ioTrackingArea)
Copy constructor. Transfers ownership of ioTrackingArea's HIViewTrackingAreaRef.
AutoTrackingArea (HIViewTrackingAreaRef inTrackingArea)
HIViewTrackingAreaRef constructor. Takes ownership of inTrackingArea.
~AutoTrackingArea ()
Destructor.
Assignment
AutoTrackingArea & operator= (AutoTrackingArea &ioTrackingArea)
Assignment operator. Transfers ownership of ioTrackingArea's HIViewTrackingAreaRef.
AutoTrackingArea & assign (HIViewRef inViewRef, HIShapeRef inShapeRef, HIViewTrackingAreaID inID=0)
Assignment from HIToolbox objects.
Inquiries
HIViewTrackingAreaID GetID () const
Modifiers
void SetShape (HIShapeRef inShapeRef)
Conversions
operator HIViewTrackingAreaRef () const
HIViewTrackingAreaRef conversion operator.
HIViewTrackingAreaRef get () const
Returns the underlying HIViewTrackingAreaRef.
HIViewTrackingAreaRef release ()
Relinquishes ownership of underlying HIViewTrackingAreaRef.
void reset (HIViewTrackingAreaRef inTrackingArea=NULL)
Relinquishes ownership of underlying HIViewTrackingAreaRef, then takes ownership of inTrackingArea.
Special Conversions
These declarations are here to enable copies and assignment. They are similar to std::auto_ptr_ref. See "The C++ Standard Library" by Nicolai Josuttis for an explanation of why they are necessary.
AutoTrackingArea (Ref ref)
Helper class constructor.
AutoTrackingArea & operator= (Ref ref)
Helper class assignment.
operator Ref ()
Helper class conversion.
Detailed Description
Lifecycle management for HIViewTrackingAreaRefs.
AutoTrackingArea is class that helps to manage the lifecycle of HIViewTrackingAreaRefs. It's similar in spirit to std::auto_ptr. Like that class, this one as ownership-transfer semantics.
Note
Because of ambiguities caused by the various conversion operators, it's not possible to copy-construct an AutoTrackingArea using another AutoTrackingArea returned as a function result. For example, the following code won't work:
AutoTrackingArea newRegion(MyFunctionReturningTrackingArea());
You may change your code to this, which does work:
AutoTrackingArea newArea(NULL);
newArea = MyFunctionReturningTrackingArea();
Member Function Documentation
HIViewTrackingAreaRef B::AutoTrackingArea::release ()
Relinquishes ownership of underlying HIViewTrackingAreaRef.
Returns
The previously-owned HIViewTrackingAreaRef, or NULL.
Referenced by get(), operator Ref(), and operator=().
The documentation for this class was generated from the following files:
BAutoTrackingArea.h
BAutoTrackingArea.cpp