B: B::Printer Class Reference
B::Printer Class Reference
Encapsulates a printer.
#include <BPrinter.h>
Public Member Functions
Constructors / Destructor
Printer (const Printer &inPrinter)
Copy constructor.
Printer (const OSPtr< PMPrinter > &inPrinter)
OSPtr<PMPrinter> constructor.
Printer (PMPrinter inPrinter)
PMPrinter constructor.
Printer (PMPrinter inPrinter, const from_copy_t &)
PMPrinter constructor.
~Printer ()
Destructor.
Assignment
Printer & operator= (const Printer &inPrinter)
Copy assignment.
Printer & operator= (const OSPtr< PMPrinter > &inPrinter)
Copy assignment.
Copying
Printer copy () const
Creates a distinct (i.e., non-shared) copy of the printer.
void swap (Printer &ioPrinter)
Exchanges the contents of *this and ioPrinter.
Inquiries
String GetName () const
Returns the printer's name.
String GetIdentifier () const
Returns the printer's unique identifier.
bool IsDefault () const
Returns true if this is the default printer.
bool IsFavorite () const
Returns true if the printer is in the user's favorite printer list.
String GetLocation () const
Returns the printer's location.
String GetMakeAndModel () const
Returns an informative string about the printer's make and model.
Url GetDescriptionUrl () const
Returns the printer's description file.
Url GetDeviceUrl () const
Returns the printer's device.
void GetLanguageInfo (PMLanguageInfo &outInfo) const
Returns information about the printer's imaging language.
bool IsPostScript () const
Returns true if this is a PostScript printer.
unsigned CountResolutions () const
Returns the number of resolution settings supported by the printer.
PMResolution GetResolution (unsigned index) const
Returns a resolution setting based on an index into the range of settings supported by the printer.
PMResolution GetTaggedResolution (PMTag inTag) const
Returns a "logical" resolution setting for the printer.
PMPrinterState GetState () const
Returns the printer's location.
Friends
class PrintSession
Detailed Description
Encapsulates a printer.
Todo:
Document this class!
Constructor & Destructor Documentation
B::Printer::Printer (const Printer & inPrinter)
Copy constructor.
Parameters
inPrinter The input printer.
B::Printer::Printer (const OSPtr< PMPrinter > & inPrinter) explicit
OSPtr<PMPrinter> constructor.
Parameters
inPrinter The input printer.
B::Printer::Printer (PMPrinter inPrinter) explicit
PMPrinter constructor.
Parameters
inPrinter The input printer.
B::Printer::Printer (PMPrinter inPrinter, const from_copy_t & fc) explicit
PMPrinter constructor.
Parameters
inPrinter The input printer.
Member Function Documentation
Printer & B::Printer::operator= (const Printer & inPrinter)
Copy assignment.
Parameters
inPrinter The input printer.
Printer & B::Printer::operator= (const OSPtr< PMPrinter > & inPrinter)
Copy assignment.
Parameters
inPrinter The input printer.
References swap().
void B::Printer::swap (Printer & ioPrinter)
Exchanges the contents of *this and ioPrinter.
Parameters
ioPrinter The input printer.
References B::OSPtr< T >::swap().
Referenced by operator=().
PMResolution B::Printer::GetResolution (unsigned index) const
Returns a resolution setting based on an index into the range of settings supported by the printer.
Note
index is zero-based, not 1-based. The acceptable range for index is therefore [0, CountResolutions()).
The documentation for this class was generated from the following files:
BPrinter.h
BPrinter.cpp