B: B::RuntimeOSStatusException Class Reference
B::RuntimeOSStatusException Class Reference
Error Handling
Low-level MacOS-error-code exception class.
#include <BException.h>
Public Member Functions
RuntimeOSStatusException (const RuntimeOSStatusException &ex) throw ()
Copy constructor.
RuntimeOSStatusException (OSStatus inStatus) throw ()
OSStatus constructor.
RuntimeOSStatusException (std::istream &istr)
Stream constructor.
virtual ~RuntimeOSStatusException () throw ()
Destructor.
RuntimeOSStatusException & operator= (const RuntimeOSStatusException &ex) throw ()
Copy assignment.
virtual OSStatus GetStatus () const throw ()
Returns the OS-defined error code.
virtual const char * what () const throw ()
Returns the exception's textual description.
void Write (std::ostream &ostr) const
Writes out the exception's internal state to ostr.
Public Member Functions inherited from B::OSStatusException
virtual ~OSStatusException () throw ()
Destructor.
Detailed Description
Low-level MacOS-error-code exception class.
This class contains an OS-defined error code. Typically an exception of this class is thrown after an OS-defined function returns a non-zero result code.
In all instances of this class, what() returns "B::RuntimeOSStatusException".
Constructor & Destructor Documentation
B::RuntimeOSStatusException::RuntimeOSStatusException (const RuntimeOSStatusException & ex) throw ()
Copy constructor.
Parameters
ex The original exception.
Referenced by B::ErrnoException::Write().
B::RuntimeOSStatusException::RuntimeOSStatusException (OSStatus inStatus) throw () explicit
OSStatus constructor.
Parameters
inStatus The error code.
B::RuntimeOSStatusException::RuntimeOSStatusException (std::istream & istr) explicit
Stream constructor.
Derived classes should override this function if they contain internal state. They should call the base class implementation prior to reading in their own state.
Parameters
istr The input stream.
Member Function Documentation
RuntimeOSStatusException & B::RuntimeOSStatusException::operator= (const RuntimeOSStatusException & ex) throw ()
Copy assignment.
Parameters
ex The original exception.
Referenced by B::AEObjectSupport::ObjectResolutionException::operator=().
void B::RuntimeOSStatusException::Write (std::ostream & ostr) const
Writes out the exception's internal state to ostr.
Derived classes should override this function if they contain internal state. They should call the base class implementation prior to writing out their own state.
Referenced by B::AEObjectSupport::ObjectResolutionException::Write(), and B::FSExchangeObjectsException::Write().
The documentation for this class was generated from the following files:
BException.h
BException.cpp