B: B::ExceptionStringHolder Class Reference
B::ExceptionStringHolder Class Reference
Error Handling
Exception helper class.
#include <BException.h>
Public Member Functions
ExceptionStringHolder () throw ()
Default constructor.
ExceptionStringHolder (const ExceptionStringHolder &inHolder) throw ()
Copy constructor.
ExceptionStringHolder (CFStringRef inString) throw ()
CFStringRef constructor.
ExceptionStringHolder (CFStringRef inString, CFStringRef inFallback) throw ()
CFStringRef + fallback constructor.
ExceptionStringHolder (const std::string &str)
std::string constructor.
ExceptionStringHolder (std::istream &istr)
Stream constructor.
~ExceptionStringHolder () throw ()
Destructor.
ExceptionStringHolder & operator= (const ExceptionStringHolder &ex) throw ()
Copy assignment.
CFStringRef cf_ref () const
Returns the held string.
const char * GetString (const char *inFallback) const throw ()
Returns the held string.
void Read (std::istream &istr)
Reads in the holder's internal state from istr.
void Write (std::ostream &ostr) const
Writes out the holder's internal state to ostr.
Protected Attributes
CFStringRef mString
char * mCachedBuff
Detailed Description
Exception helper class.
This class can be embedded within an exceptions object as a member variable. It holds a CFStringRef, which is converted on-demand into a const char* via GetString().
The class' member functions are set up so that they cannot throw at an inopportune time (i.e. during construction). Its throw-specs are consistent with those of std:exception and its derived classes.
Constructor & Destructor Documentation
B::ExceptionStringHolder::ExceptionStringHolder (const ExceptionStringHolder & inHolder) throw ()
Copy constructor.
Parameters
inHolder The original exception.
B::ExceptionStringHolder::ExceptionStringHolder (CFStringRef inString) throw () explicit
CFStringRef constructor.
Parameters
inString The error message.
B::ExceptionStringHolder::ExceptionStringHolder (CFStringRef inString, CFStringRef inFallback) throw () explicit
CFStringRef + fallback constructor.
Parameters
inString The error message; may be NULL.
inFallback The error message to use if inString is NULL.
B::ExceptionStringHolder::ExceptionStringHolder (const std::string & str) explicit
std::string constructor.
The input string is assumed to be encoded as UTF-8.
Parameters
str The error message.
References B::String::cf_ref().
B::ExceptionStringHolder::ExceptionStringHolder (std::istream & istr) explicit
Stream constructor.
The entire contents of istr are read into the object's string.
The input stream is assumed to be encoded as UTF-8.
Parameters
istr Input stream containing the error message.
References Read().
Member Function Documentation
ExceptionStringHolder & B::ExceptionStringHolder::operator= (const ExceptionStringHolder & ex) throw ()
Copy assignment.
Parameters
ex The original exception.
const char * B::ExceptionStringHolder::GetString (const char * inFallback) const throw ()
Returns the held string.
The returned string is encoded as UTF-8.
References B::String::copy().
void B::ExceptionStringHolder::Read (std::istream & istr)
Reads in the holder's internal state from istr.
The entire contents of istr are read into the object's string.
The input stream is assumed to be encoded as UTF-8.
Parameters
istr Input stream containing the error message.
References B::String::cf_ref().
Referenced by ExceptionStringHolder().
void B::ExceptionStringHolder::Write (std::ostream & ostr) const
Writes out the holder's internal state to ostr.
The output stream is assumed to be encoded as UTF-8.
References B::String::Write().
Referenced by B::PropertyListCreateException::Write().
The documentation for this class was generated from the following files:
BException.h
BException.cpp