B: B::PutFileDialog Class Reference
B::PutFileDialog Class Reference
Implements the standard "Save" dialog as per the Aqua HIG.
#include <BNavDialogs.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Member Functions
Setup
void SetDocumentTypes (const Bundle &inBundle, const String &inDefaultType=String())
Allows the user to select any of the document types declared in inBundle's Info.plist file.
template<class InputIterator >
void SetDocumentTypes (const Bundle &inBundle, CFStringRef inTable, InputIterator inFirst, InputIterator inLast, const String &inDefaultType=String())
Allows the user to select any file from the document types contained in the iterator sequence.
void SelectDocumentType (const String &inDocTypeName)
Initially select the pop-up menu item for the given document type.
virtual void SetSaveInfo (const SaveInfo &inSaveInfo)
template<class PUT_FILE_DIALOG >
void SetCallback (B_PUTFILEDIALOG_CB inFunction)
Public Member Functions inherited from B::NavReplyDialog
virtual ~NavReplyDialog ()
Destructor.
void SetPopupMenuContents (PopupMenuContentsVector &inContents)
Sets the custom elements in the show & format pop-up menus.
void FilterAllFiles ()
Selects the "All Documents" pop-up menu item.
void FilterAllReadableFiles ()
Selects the "All Reaadable Documents" pop-up menu item.
void FilterByName (const String &inFilterName)
Selects the pop-up menu item for the given filter name.
void SetCustomView (Nib &inNib, const char *inViewName)
Sets the top-level custom view.
void GetNavReply (AutoNavReply &outNavReply) const
Returns the dialog's nav reply.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Static Public Member Functions
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
Unlike the simpler Nav dialogs (eg AskSaveChangesDialog), it's not possible to configure the dialog completely with Make() except in the simplest of cases. This is because there are many more configuration options in this dialog.
template<class PUT_FILE_DIALOG >
static std::auto_ptr< PUT_FILE_DIALOG > Make (const DialogModality &inModality, const String &inFileName, B_PUTFILEDIALOG_CB inFunction=NullCallback< PUT_FILE_DIALOG >())
Instantiates and returns a PUT_FILE_DIALOG with the given arguments.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class PUT_FILE_DIALOG >
static void Start (const DialogModality &inModality, const String &inFileName, B_PUTFILEDIALOG_CB inFunction=NullCallback< PUT_FILE_DIALOG >())
Instantiates a PUT_FILE_DIALOG with the given arguments, then enters it.
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Protected Member Functions
PutFileDialog ()
Protected default constructor to discourage stack-based instantiation.
void FillPopupMenuWithDocTypes (const Bundle &inBundle, CFStringRef inTable, const String &inDefaultType)
Dialog Control
SaveInfo & GetSaveInfo ()
void HideExtension (bool showIt)
bool IsExtensionHidden ()
String GetEditFileName ()
Tells the dialog to return the editable file name.
void SetEditFileName (const String &inFileName)
Tells the dialog to change the editable file name.
Overrides from NavDialog
virtual NavDialogRef CreateDialog ()
virtual void HandleReply (NavUserAction inUserAction, NavReplyRecord &ioNavReply)
virtual void PopupMenuSelect (const NavMenuItemSpec &inMenuItemSpec)
virtual void DialogStarting (NavCBRec &ioParams)
Protected Member Functions inherited from B::NavReplyDialog
NavReplyDialog ()
Protected default constructor to discourage stack-based instantiation.
View * FindCustomViewByID (int inID) const
View * FindCustomViewByID (OSType inSignature, int inID) const
virtual bool Preview (NavCBRecPtr ioParams)
Preview hook.
virtual void NegotiateCustomArea (Size &ioSize)
Override this function to negotiate an area in the dialog for custom UI elements.
virtual void DialogResized (Rect &ioCustomBounds, Rect &ioPreviewBounds)
Override this to do some processing when the dialog is resized.
virtual void LocationChanged (const AEDesc &inNewLocation)
Override this to do some processing when the location displayed in the browser list changes.
virtual void GoneToDesktop ()
Override this to do some processing when the desktop is displayed in the dialog.
virtual void SelectionChanged (const AEDescList &inNewSelection)
Override this to do some processing when the selection in the browser list changes.
virtual void AdjustPreview (bool visible)
Override this to do some processing when preview area is turned on or off.
virtual void SelectionOpened ()
Override this to do some processing when the selection in the browser list is opened.
virtual void DialogAccepted ()
Override this to do some processing when the user performs a confirming action.
virtual void DialogCancelled ()
Override this to do some processing when the user performs a cancelling action.
virtual bool FilterObject (const AEDesc &inItem, const NavFileOrFolderInfo &inInfo, NavFilterModes inFilterMode)
Determines whether the object denoted by inItem, inInfo and inFilterMode should be displayed.
virtual bool FilterObjectByAllFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when "All Documents" is selected in the pop-up menu.
virtual bool FilterObjectByAllReadableFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when "All Readable Documents" is selected in the pop-up menu.
virtual bool FilterObjectByFilterName (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when a document type is selected in the pop-up menu.
virtual void SelectFilter (FilterKind inFilterKind, const String &inFilterName=String())
Changes the current filter.
virtual void HandleUserAction (NavUserAction inUserAction)
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
void ShowDesktop ()
Tells the dialog to display the desktop.
void SortBy (NavSortKeyField inField)
Tells the dialog to sort the browser list according to inField.
void SortOrder (NavSortOrder inOrder)
Tells the dialog to sort the browser list in ascending or descending order, according to inOrder.
void ScrollHome ()
Tells the dialog to scroll the browser list to the top.
void ScrollEnd ()
Tells the dialog to scroll the browser list to the bottom.
void ScrollPageUp ()
Tells the dialog to scroll the browser list up a page.
void ScrollPageDown ()
Tells the dialog to scroll the browser list down a page.
void GetLocation (AEDesc &outLocation)
Tells the dialog to return the location displayed in the browser list.
void SetLocation (const AEDesc &inLocation)
Tells the dialog to change the location displayed in the browser list.
void GetSelection (AEDesc &outSelection)
Tells the dialog to return the selection in the browser list.
void SetSelection (const AEDesc &inSelection)
Tells the dialog to change the selection in the browser list.
void ShowSelection ()
Tells the dialog to reveal the selection in the browser list.
void OpenSelection ()
Tells the dialog to open the selected item in the browser list.
void EjectVolume (short inVRefNum)
Tells the dialog to eject the volume identified by inVRefNum.
bool IsPreviewShowing ()
Returns true if the preview area is currently available.
void SelectCustomType (const NavMenuItemSpec &inSpec)
Tells the dialog to choose the custom pop-up menu item identified by inSpec.
void SelectAllType (MenuItemIndex inItem)
Tells the dialog to choose the standard pop-up menu item identified by inItem.
void SelectEditFileName (const struct ControlEditTextSelectionRec &inSelection)
Tells the dialog to change the selection in the file name field.
void BrowserSelectAll ()
Tells the dialog to select all items in the browser list.
void GotoParent ()
Tells the dialog to navigate to the parent item of the current selection.
void SetActionState (NavActionState inActionState)
Tells the dialog to prevent the user from performing certain actions, such clicking the Cancel button.
void BrowserRedraw ()
Tells the dialog to refresh its browser list.
bool RunReplyDialog (NavUserAction inConfirmAction, AutoNavReply &outNavReply)
Runs the dialog, returning the nav reply if the user confirmed the dialog.
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Running Dialogs
These are convenience functions for displaying nav dialogs in an application-modal fashion. Because they don't return until the nav dialog is dismissed, the chosen action is returned as the function result.
bool Run (AutoNavReply &outNavReply)
Displays the nav dialog in an application-modal fashion.
template<class PUT_FILE_DIALOG >
static bool Run (const String &inFileName, AutoNavReply &outNavReply)
Instantiates a PUT_FILE_DIALOG, then enters a modal event loop for it.
Additional Inherited Members
Public Types inherited from B::NavReplyDialog
enum FilterKind {
kFilterName = 1, kFilterAllFiles, kFilterAllAppFiles, kFilterAllReadableFiles,
kFilterSeparator
}
< Types of file system object filtering.
typedef std::vector< PopupMenuItem > PopupMenuContentsVector
The entire contents of the filtering pop-up menu.
Static Protected Member Functions inherited from B::NavReplyDialog
static NavObjectFilterUPP GetObjectFilterUPP ()
Returns the UPP to use for filtering file system objects.
static NavPreviewUPP GetPreviewUPP ()
Returns the UPP to use for previewing.
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Protected Attributes inherited from B::NavReplyDialog
PopupMenuContentsVector mPopupMenuContents
FilterKind mCurrentFilterKind
The filter type of the currently selected item in the file type pop-up menu.
String mCurrentFilterName
The filter name of the currently selected item in the file type pop-up menu.
Detailed Description
Implements the standard "Save" dialog as per the Aqua HIG.
Beyond the usual DialogModality and callback arguments, the Make/Start/Run functions also take as an argument the suggest name of the file that's about to be saved. Note that this must be the actual file name, not the file's display name as is the case for AskSaveChangesDialog and AskDiscardChangesDialog. The dialog returns true if the user clicked the Save button; else it returns false. Note that there are important configuration functions that aren't called when invoking Start() or Run(), so a bit more work is required on the part of clients wishing to use them.
PutFileDialog's configuration functions all have to do with the file type pop-up menu. They are very similar to the functions in GetFileDialog:
SetDocumentTypes() allows one to specify the document types displayed in the pop-up menu. Unlike the version in GetFileDialog however, this one can optionally take an extra string argument containing the "default" document type. The default document type is placed at the top of the pop-up menu and a separator is inserted between it and the other menu items.
SelectDocumentType() allows one to specify the "current" document type.
Note that unlike GetFileDialog, changing the contents of the pop-up menu or the currently selected item doesn't affect the filtering of file system objects in the browser portion of the dialog.
See also
Dialogs, Alerts and Navigation Services
Member Function Documentation
void B::PutFileDialog::SetDocumentTypes (const Bundle & inBundle, const String & inDefaultType = String())
Allows the user to select any of the document types declared in inBundle's Info.plist file.
Sets the document types array to all of the document types in inBundle. The array is then used to populate the file type pop-up menu. The document types' localised names are assumed to reside in the "InfoPlist.strings" file within inBundle. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup).
If inDefaultType is non-empty, it's assumed to contain the "default" document type. The document type in question is then moved to the beginning of the doc types array, and a separator is inserted between it and the other document types.
Parameters
inBundle The bundle in which to look for localised document type names.
inDefaultType The default document type.
References B::Bundle::begin(), and B::Bundle::end().
template<class InputIterator > void B::PutFileDialog::SetDocumentTypes (const Bundle & inBundle, CFStringRef inTable, InputIterator inFirst, InputIterator inLast, const String & inDefaultType = String())
Allows the user to select any file from the document types contained in the iterator sequence.
Sets the document types array to be equal to the iterator sequence [inFirst, inLast). The array is then used to populate the file type pop-up menu. inBundle and inTable are used to read the localised strings for each document type. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup).
If inDefaultType is non-empty, it's assumed to contain the "default" document type. The document type in question is then moved to the beginning of the doc types array, and a separator is inserted between it and the other document types.
Parameters
InputIterator Template parameter. An input iterator yielding a Bundle::DocumentType object.
Parameters
inBundle The bundle in which to look for localised document type names.
inTable The table in which to look for localised document type names (may be NULL).
inFirst The start of the sequence of document type objects.
inLast The end of the sequence of document type objects.
inDefaultType The default document type.
template<class PUT_FILE_DIALOG > void B::PutFileDialog::SetCallback (B_PUTFILEDIALOG_CB inFunction)
Todo:
Complete this!
Parameters
PUT_FILE_DIALOG Template parameter. The class of the instantiated window. Must be PutFileDialog or a class derived from PutFileDialog.
template<class PUT_FILE_DIALOG > std::auto_ptr< PUT_FILE_DIALOG > B::PutFileDialog::Make (const DialogModality & inModality, const String & inFileName, B_PUTFILEDIALOG_CB inFunction = NullCallback<PUT_FILE_DIALOG>()) static
Instantiates and returns a PUT_FILE_DIALOG with the given arguments.
Instantiates a dialog of class PUT_FILE_DIALOG. The instance of PUT_FILE_DIALOG is then configured with the given arguments. Finally the dialog is returned, ready to be displayed via Enter().
Parameters
PUT_FILE_DIALOG Template parameter. The class of the instantiated window. Must be PutFileDialog or a class derived from PutFileDialog.
Parameters
inModality The dialog's modality.
inFileName The name of the file we're being asked to save.
inFunction A callback that is invoked when the dialog is dismissed.
template<class PUT_FILE_DIALOG > void B::PutFileDialog::Start (const DialogModality & inModality, const String & inFileName, B_PUTFILEDIALOG_CB inFunction = NullCallback<PUT_FILE_DIALOG>()) static
Instantiates a PUT_FILE_DIALOG with the given arguments, then enters it.
Instantiates a nav dialog of class PUT_FILE_DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog, call Make() then Enter().
Parameters
PUT_FILE_DIALOG Template parameter. The class of the instantiated window. Must be PutFileDialog or a class derived from PutFileDialog.
See also
Make(), NavDialog::Enter()
Parameters
inModality The dialog's modality.
inFileName The name of the file we're being asked to save.
inFunction A callback that is invoked when the dialog is dismissed.
template<class PUT_FILE_DIALOG > bool B::PutFileDialog::Run (const String & inFileName, AutoNavReply & outNavReply) static
Instantiates a PUT_FILE_DIALOG, then enters a modal event loop for it.
Instantiates a nav dialog of class PUT_FILE_DIALOG, as per Make(). Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
PUT_FILE_DIALOG Template parameter. The class of the instantiated window. Must be PutFileDialog or a class derived from PutFileDialog.
Returns
true if the user confirmed the dialog.
See also
Make(), Run()
Parameters
inFileName The name of the file we're being asked to save.
outNavReply The nav reply; only valid if the function returns true.
References B::DialogModality::Modal().
void B::PutFileDialog::FillPopupMenuWithDocTypes (const Bundle & inBundle, CFStringRef inTable, const String & inDefaultType) protected
Uses mDocTypes to populate the file type pop-up menu. inBundle and inTable are used to read the localised strings for each document type. If the array has more than one element, the menu is forced to be displayed; note that this can be overridden by a subsequent call to SetFlags(kNavNoTypePopup).
If inDefaultType is non-empty, it's assumed to contain the "default" document type. The document type in question is then moved to the beginning of the doc types array, and a separator is inserted between it and the other document types.
Parameters
inBundle The bundle in which to look for localised document type names.
inTable The table in which to look for localised document type names (may be NULL).
inDefaultType The default type, which appears at the top of the pop-up menu.
References B::String::empty(), B::Bundle::DocumentType::mName, and B::NavReplyDialog::SetPopupMenuContents().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp