B: B::DialogModality Class Reference
B::DialogModality Class Reference
Helper object representing a dialog's modality.
#include <BDialogModality.h>
Public Member Functions
Constructors / Destructor
DialogModality (WindowModality inModality, WindowRef inParent)
Constructor.
Inquiries
WindowModality GetModality () const
Returns the modality.
WindowRef GetParent () const
Returns the sheet's parent, if any.
bool IsModeless () const
Do we specify a modeless dialog?
bool IsModal () const
Do we specify an application-modal dialog?
bool IsSheet () const
Do we specify a sheet?
Static Public Member Functions
Instantiation
These are convenience routines that return object of the requested modality.
static DialogModality Modeless ()
Instantiates an object of modality kWindowModalityNone (i.e., a modeless dialog).
static DialogModality Modal ()
Instantiates an object of modality kWindowModalityAppModal (i.e., a modal dialog).
static DialogModality Sheet (WindowRef inParent)
Instantiates an object of modality kWindowModalityWindowModal (i.e., a sheet).
Detailed Description
Helper object representing a dialog's modality.
This class encapsulates a WindowModality / WindowRef pair, and may be used to specify a dialog's modality. Dialog modality is what distinguishes a modeless dialog from an application-modal dialog from a sheet. This class is used by Alert, Dialog, and NavDialog.
You will typically construct a DialogModality object in one of two ways:
If you know which modality you want, call one of the static instantiation functions. For example, Modal() will return an object specifying application-modal modality.
If you get a WindowModality and possibly a WindowRef handed to you by someone else, use DialogModality's constructor directly.
Note
This class doesn't support kWindowModalitySystemModal. Mac OS X maps system-modal dialogs onto application-modal dialogs anyway, so it's not a problem.
Constructor & Destructor Documentation
B::DialogModality::DialogModality (WindowModality inModality, WindowRef inParent) explicit
Constructor.
Parameters
inModality The modality. One of kWindowModalityNone, kWindowModalityAppModal, or kWindowModalityWindowModal.
inParent The sheet's parent. Must be non-NULL if inModality is kWindowModalityWindowModal.
Referenced by IsSheet(), Modal(), Modeless(), and Sheet().
Member Function Documentation
DialogModality B::DialogModality::Sheet (WindowRef inParent) static
Instantiates an object of modality kWindowModalityWindowModal (i.e., a sheet).
Parameters
inParent The sheet's parent. Must be non-NULL.
References DialogModality().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality().
The documentation for this class was generated from the following files:
BDialogModality.h
BDialogModality.cpp