B: B::PageFormat Class Reference
B::PageFormat Class Reference
Encapsulates a page format for printing.
#include <BPageFormat.h>
Public Member Functions
Constructors / Destructor
PageFormat ()
Default constructor. Creates an empty page format.
PageFormat (const PageFormat &inPageFormat)
Copy constructor.
PageFormat (const OSPtr< PMPageFormat > &inPageFormat)
OSPtr<PMPageFormat> constructor.
PageFormat (PMPageFormat inPageFormat)
PMPageFormat constructor.
PageFormat (PMPageFormat inPageFormat, const from_copy_t &)
PMPageFormat constructor.
~PageFormat ()
Destructor.
Assignment
PageFormat & operator= (const PageFormat &inPageFormat)
Copy assignment.
PageFormat & operator= (const OSPtr< PMPageFormat > &inPageFormat)
Copy assignment.
Copying
PageFormat copy () const
Creates a distinct (i.e., non-shared) copy of the page format.
void swap (PageFormat &ioPageFormat)
Exchanges the contents of *this and ioPageFormat.
Serialisation
OSPtr< CFDataRef > Serialize () const
Serializes the page format to the given vector.
void Deserialize (const OSPtr< CFDataRef > &inBlob)
Deserializes the page format from the given vector.
Inquiries
PMOrientation GetOrientation () const
Returns the current setting for page orientation.
void GetResolution (PMResolution &outResolution) const
Returns the current application drawing resolution.
double GetScale () const
Returns the scaling factor currently applied to the page and paper rectangles.
PMRect GetAdjustedPageRect () const
Returns the page size, taking into account orientation, application drawing resolution, and scaling settings.
PMRect GetAdjustedPaperRect () const
Returns the paper size, taking into account orientation, application drawing resolution, and scaling settings.
PMRect GetUnadjustedPageRect () const
Returns the size of the imageable area in points, unaffected by orientation, resolution, or scaling.
PMRect GetUnadjustedPaperRect () const
Returns a rectangle that specifies the size of the paper in points, unaffected by rotation, resolution, or scaling.
void GetExtendedData (OSType dataID, size_t size, void *outData) const
Returns extended page format data previously stored by your application.
size_t GetExtendedDataSize (OSType dataID) const
Returns the size of extended page format data previously stored by your application.
template<typename T >
void GetExtendedData (OSType dataID, T &outData) const
Returns extended page format data previously stored by your application in a type-safe manner.
bool Equals (const PageFormat &inPageFormat) const
Compares the page format to the given page format, and returns true if they are equal.
Modifiers
void SetOrientation (PMOrientation inOrientation)
Sets the page orientation for printing.
void SetResolution (const PMResolution &inResolution)
Sets the current application drawing resolution.
void SetScale (double inScale)
Sets the scaling factor for the page and paper rectangles.
void SetExtendedData (OSType dataID, size_t size, const void *inData)
Sets the extended page format data previously stored by your application.
template<typename T >
void SetExtendedData (OSType dataID, const T &inData)
Sets extended page format data previously stored by your application in a type-safe manner.
Friends
class PrintSession
Detailed Description
Encapsulates a page format for printing.
Todo:
Document this class!
Constructor & Destructor Documentation
B::PageFormat::PageFormat (const PageFormat & inPageFormat)
Copy constructor.
Parameters
inPageFormat The input format.
B::PageFormat::PageFormat (const OSPtr< PMPageFormat > & inPageFormat) explicit
OSPtr<PMPageFormat> constructor.
Parameters
inPageFormat The input format.
B::PageFormat::PageFormat (PMPageFormat inPageFormat) explicit
PMPageFormat constructor.
Parameters
inPageFormat The input format.
B::PageFormat::PageFormat (PMPageFormat inPageFormat, const from_copy_t & fc) explicit
PMPageFormat constructor.
Parameters
inPageFormat The input format.
Member Function Documentation
PageFormat & B::PageFormat::operator= (const PageFormat & inPageFormat)
Copy assignment.
Parameters
inPageFormat The input format.
PageFormat & B::PageFormat::operator= (const OSPtr< PMPageFormat > & inPageFormat)
Copy assignment.
Parameters
inPageFormat The input format.
void B::PageFormat::swap (PageFormat & ioPageFormat)
Exchanges the contents of *this and ioPageFormat.
Parameters
ioPageFormat The input format.
References B::OSPtr< T >::swap().
Referenced by SetExtendedData().
void B::PageFormat::GetExtendedData (OSType dataID, size_t size, void * outData) const
Returns extended page format data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
size The size of the data.
outData A pointer to the buffer that will hold the data.
Referenced by GetExtendedData().
size_t B::PageFormat::GetExtendedDataSize (OSType dataID) const
Returns the size of extended page format data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
template<typename T > void B::PageFormat::GetExtendedData (OSType dataID, T & outData) const
Returns extended page format data previously stored by your application in a type-safe manner.
Parameters
dataID Four-character constant identifying the data of interest.
outData Holds the output value.
References GetExtendedData().
void B::PageFormat::SetExtendedData (OSType dataID, size_t size, const void * inData)
Sets the extended page format data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
size The size of the data.
inData The new value.
Referenced by SetExtendedData().
template<typename T > void B::PageFormat::SetExtendedData (OSType dataID, const T & inData)
Sets extended page format data previously stored by your application in a type-safe manner.
Parameters
dataID Four-character constant identifying the data of interest.
inData The new value.
References SetExtendedData(), and swap().
The documentation for this class was generated from the following files:
BPageFormat.h
BPageFormat.cpp