B: B::AutoRegion Class Reference
B::AutoRegion Class Reference
Lifecycle management for RgnHandles.
#include <BAutoRegion.h>
Classes
struct Ref
Helper class.
Public Member Functions
Constructors / Destructor
AutoRegion ()
Default constructor. Allocates an empty region.
AutoRegion (AutoRegion &ioRegion)
Copy constructor. Transfers ownership of ioRegion's RgnHandle.
AutoRegion (RgnHandle inRegion)
RgnHandle constructor. Takes ownership of inRegion.
~AutoRegion ()
Destructor.
Assignment
AutoRegion & operator= (AutoRegion &ioRegion)
Assignment operator. Transfers ownership of ioRegion's RgnHandle.
Conversions
operator RgnHandle () const
RgnHandle conversion operator.
RgnHandle get () const
Returns the underlying RgnHandle.
RgnHandle release ()
Relinquishes ownership of underlying RgnHandle.
void reset (RgnHandle inRegion=NULL)
Relinquishes ownership of underlying RgnHandle, then takes ownership of inRegion.
Special Conversions
These declarations are here to enable copies and assignment. They are similar to std::auto_ptr_ref. See "The C++ Standard Library" by Nicolai Josuttis for an explanation of why they are necessary.
AutoRegion (Ref ref)
Helper class constructor.
AutoRegion & operator= (Ref ref)
Helper class assignment.
operator Ref ()
Helper class conversion.
Detailed Description
Lifecycle management for RgnHandles.
AutoRegion is class that helps to manage the lifecycle of RgnHandles. It's similar in spirit to std::auto_ptr. Like that class, this one has ownership-transfer semantics.
Note
Because of ambiguities caused by the various conversion operators, it's not possible to copy-construct an AutoRegion using another AutoRegion returned as a function result. For example, the following code won't work:
AutoRegion newRegion(MyFunctionReturningAutoRegion());
You may change your code to this, which does work:
AutoRegion newRegion(NULL);
newRegion = MyFunctionReturningAutoRegion();
Member Function Documentation
RgnHandle B::AutoRegion::release ()
Relinquishes ownership of underlying RgnHandle.
Returns
The previously-owned RgnHandle, or NULL.
Referenced by get(), operator Ref(), and operator=().
The documentation for this class was generated from the following files:
BAutoRegion.h
BAutoRegion.cpp