B: B::CustomView Class Reference
B::CustomView Class Reference abstract
Views
Base class for custom derivatives of HIView.
#include <BCustomView.h>
Public Types
enum EViewFlags {
kViewNone = 0x00000000, kViewOpaque = 0x00000001, kViewFocus = 0x00000002, kViewFocusOnClick = 0x00000004,
kViewContainer = 0x00000008, kViewDragAndDrop = 0x00000010, kViewScrollable = 0x00000020, kViewCommands = 0x00000040,
kViewHit = 0x00000080, kViewTracking = 0x00000100, kViewTrackingArea = 0x00000200, kViewLiveFeedback = 0x00000400,
kViewClickActivation = 0x00000800, kViewNoDrawing = 0x00010000, kViewNoClicking = 0x00020000, kViewInvalOnActivate = 0x00100000,
kViewInvalOnHilite = 0x00200000, kViewInvalOnEnable = 0x00400000, kViewInvalOnValue = 0x00800000, kViewInvalOnTitle = 0x01000000,
kViewInvalOnFocus = 0x02000000
}
Flags controlling view behaviour.
enum EViewPartFocus { kFocusAlways = 1, kFocusNever, kFocusFull }
The focus behaviour of a view part.
typedef std::pair< HIViewPartCode, EViewPartFocus > ViewPart
Associates a view part (identified by its part code) and a focus behaviour.
typedef std::vector< ViewPart > ViewPartVector
Defines all of a view's parts and their focus behaviour.
Static Public Member Functions
Object Creation
template<class T >
static OSPtr< HIViewRef > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, Collection inCollection)
Creates an instance of class T.
template<class T >
static OSPtr< HIViewRef > Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, EventRef inEvent)
Creates an instance of class T.
static OSPtr< HIViewRef > Create (CFStringRef inClassID, const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, EventRef inEvent)
Creates an instance of class inClassID.
Conversions
static CustomView * FromViewRef (HIViewRef inViewRef)
Returns the CustomView object belonging to inViewRef, or NULL.
Static Public Member Functions inherited from B::EventTarget
template<class T >
static void Register ()
Registers class T (which must derive from EventTarget) with the HIToolbox.
template<class T >
static void Unregister ()
Unregisters class T (which must derive from EventTarget) from the HIToolbox.
template<class T >
static HIObjectClassRef GetObjectClass ()
Returns the object class associated with type T (which must derive from EventTarget), or NULL.
template<class T >
static OSPtr< HIObjectRef > Create (EventRef inEvent=NULL)
Creates an instance of class T.
static OSPtr< HIObjectRef > Create (CFStringRef inClassID, EventRef inEvent=NULL)
Creates an instance of class inClassID.
template<class T >
static T * InstanceData (HIObjectRef objRef)
Retrieves the C++ object of type T associated with the HIObjectRef objRef.
template<typename T >
static EventTargetRef GetEventTarget (T inObject)
Retrieves the EventTargetRef associated with inObject.
Static Public Attributes
static const CFStringRef kHIObjectBaseClassID = kHIViewClassID
The default HIObject base class for views.
Static Public Attributes inherited from B::EventTarget
static const CFStringRef kHIObjectBaseClassID = NULL
The default base class ID, representing HIObject.
Protected Member Functions
Constructor / Destructor
CustomView (HIObjectRef inObjectRef, EViewFlags inViewFlags)
Constructor.
Inquiries
These functions are for the benefit of derived classes, and may be used to retrieve a part of the view's state that is managed by the HIToolbox.
HIViewRef GetViewRef () const
Returns the view's underlying HIViewRef.
HIViewID GetViewID () const
Returns the view's full HIViewID.
Rect GetBounds () const
Returns the view's bounds.
Rect GetFrame () const
Returns the view's bounds.
int GetValue () const
Returns the view's current value.
int GetMinimum () const
Returns the view's minimum value.
int GetMaximum () const
Returns the view's maximum value.
String GetTitle () const
Returns the view's title, if any.
bool IsFocused () const
Returns whether the view is focused.
bool IsHighlighted () const
Returns whether the view is highlighted.
bool IsActive () const
Returns whether the view is active.
bool IsEnabled () const
Returns whether the view is enabled.
bool IsVisible () const
Returns whether the view is visible.
bool IsCommandSentToUserFocus () const
Returns whether the view sends commands to the user focus.
bool IsContainer () const
Returns whether the view may contain other views.
bool IsCompositing () const
Returns whether the view is currently in a composited window.
WindowRef GetOwner () const
Returns the view's enclosing window, if any.
HIViewPartCode GetFocusPart () const
Returns the view's currently focused part, if any.
HIViewPartCode GetHighlightPart () const
Returns the view's currently highlighted part, if any.
void DebugPrint () const
Prints debugging information to stdout.
Overridables
virtual void InitializeView (Collection inCollection)
View initialisation.
virtual void DisposeView ()
View cleanup.
virtual const ViewPartVector & GetViewParts () const
Returns the view parts defined by this view.
virtual ControlKind GetKind () const =0
Returns the view's ControlKind.
virtual UInt32 CalcControlFeatures () const
Computes the Control Manager control features for this view.
virtual void Draw (HIViewPartCode inPart, CGContextRef inContext, const Shape *inDrawShape)
Draws the view.
virtual Shape GetStructureShape () const
Returns the view's structure shape.
virtual Shape GetContentShape () const
Returns the view's content shape.
virtual Shape GetOpaqueShape () const
Returns the view's opaque shape.
virtual Shape GetClickableShape () const
Returns the view's clickable shape.
virtual Shape GetPartShape (HIViewPartCode inPart) const
Returns the shape of one of the view's parts.
virtual bool GetViewShape (HIViewPartCode inPart, Shape &outShape) const
High-level function that returns the shape of one of the view's parts.
virtual Rect GetStructureBounds () const
Returns the bounds of the view's structure shape.
virtual Rect GetContentBounds () const
Returns the bounds of the view's content shape.
virtual Rect GetOpaqueBounds () const
Returns the bounds of the view's opaque shape.
virtual Rect GetClickableBounds () const
Returns the bounds of the view's clickable shape.
virtual Rect GetPartBounds (HIViewPartCode inPart) const
Returns the bounds of the shape of one of the view's parts.
virtual bool GetViewBounds (HIViewPartCode inPart, Rect &outBounds) const
High-level function that returns the bounds of the shape of one of the view's parts.
virtual HIViewPartCode HitTest (const Point &inMouseLoc) const
Returns the view part containing inMouseLoc, if any.
virtual void Hit (HIViewPartCode inPart, UInt32 inKeyModifiers)
The view was hit in inPart.
virtual HIViewPartCode Track (const Point &inMouseLoc, UInt32 inClickCount, UInt32 &ioKeyModifiers)
Perform mouse tracking.
virtual ClickActivationResult GetClickActivation (const Point &inMouseLoc, UInt32 inKeyModifiers, EventMouseButton inMouseButton, UInt32 inClickCount, UInt32 inMouseChord)
Determines whether the view's containing window should be activated when clicked in the background.
virtual HIViewPartCode SetFocusPart (HIViewPartCode inPart, bool inFocusEverything)
High-level function that handles focus-change requests.
virtual bool SetData (HIViewPartCode inPart, ResType inDataTag, const void *inDataPtr, size_t inDataSize)
Changes a piece of view data.
virtual bool GetData (HIViewPartCode inPart, ResType inDataTag, void *inDataPtr, size_t &ioDataSize) const
Retrieves a piece of view data.
virtual Rect GetOptimalBounds () const
Retrieves the view's optimal bounds.
virtual std::pair< Size, Size > GetMinMaxSize () const
Retrieves the view's minimal and maximal sizes.
virtual float GetBaseline () const
Retrieves the view's text baseline.
virtual bool BoundsChanged (UInt32 inAttributes, const Rect &inPreviousBounds, const Rect &inCurrentBounds)
Notifies the view that its bounds have changed.
virtual void OwningWindowChanged (WindowRef inOriginalWindow, WindowRef inCurrentWindow)
Notifies the view that its owning window has changed.
virtual void HighlightChanged (HIViewPartCode inOldHilitePart, HIViewPartCode inNewHilitePart)
Notifies the view that its highlight state has changed.
virtual void FocusChanging (HIViewPartCode inOldFocusPart, HIViewPartCode inNewFocusPart)
Notifies the view that its focus state has changed.
virtual void ActivateStateChanged (bool inActive)
Notifies the view that its active state has changed.
virtual void VisibilityChanged ()
Notifies the view that its visibility has changed.
virtual void ValueFieldChanged ()
Notifies the view that one of its value/minimum/maximum fields has changed.
virtual void TitleChanged ()
Notifies the view that its title has changed.
virtual void EnabledStateChanged ()
Notifies the view that its enabled state has changed.
virtual void AddedSubview (HIViewRef inSubview)
Notifies the view that a view has been added as one of its children.
virtual void RemovingSubview (HIViewRef inSubview)
Notifies the view that one of its subviews is about to be removed.
virtual bool DragEnter (DragRef inDragRef)
Notifies the view that the user has dragged something into it.
virtual void DragWithin (DragRef inDragRef)
Notifies the view that the user is moving within it during a drag.
virtual void DragLeave (DragRef inDragRef)
Notifies the view that the user is moving out of it during a drag.
virtual bool DragReceive (DragRef inDragRef)
Notifies the view that the user has dropped something onto it.
virtual bool TextInput (const UniChar *inText, size_t inLength, EventRef inKeyboardEvent)
Notifies the view that the user has entered some text.
virtual void GetScrollInfo (Size &outImageSize, Size &outViewSize, Size &outLineSize, Point &outOrigin) const
Retrieves the view's scroll information.
virtual void ScrollTo (const Point &inOrigin)
Tells the view to move its origin.
virtual bool HandleCommand (const HICommandExtended &inHICommand)
Handles an HICommand.
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
Returns the status of an HICommand.
virtual void TrackingAreaEntered (HIViewTrackingAreaRef inTrackingRef, const Point &inMouseLocation, UInt32 inKeyModifiers)
The mouse has just entered the tracking region identified by inTrackingRef.
virtual void TrackingAreaExited (HIViewTrackingAreaRef inTrackingRef, const Point &inMouseLocation, UInt32 inKeyModifiers)
The mouse has just left the tracking region identified by inTrackingRef.
Protected Member Functions inherited from B::EventTarget
EventTarget (HIObjectRef inObjectRef)
Constructor.
virtual ~EventTarget ()
Destructor.
void operator delete (void *ptr)
Protected delete prevents external clients from deleting instances directly.
virtual void Initialize (EventRef inEvent)
Override to extract initialisation arguments from inEvent.
virtual bool IsEqualTo (HIObjectRef inObjectRef)
Returns true if this is "equal" to inObjectRef.
virtual void PrintDebugInfo ()
Override to print debugging information to stdout.
virtual void Unarchive (HIArchiveRef ioArchive)
Decode the object into the given archive. This is called instead of Initialize().
virtual void Archive (HIArchiveRef ioArchive) const
Encode the object into the given archive.
Protected Attributes
const EViewFlags mViewFlags
The view's flags.
bool mAwakened
Protected Attributes inherited from B::EventTarget
const HIObjectRef mObjectRef
The underlying toolbox object.
Utility
static void AwakenView (HIViewRef inView, Nib *inFromNib)
Tell inView to awaken.
bool HandleChooseKey (HIViewPartCode inPart, const UniChar *inText, size_t inLength, EventRef inKeyboardEvent)
Handles translating a "space" key press into a click.
HIViewPartCode FindNextPart (HIViewPartCode inStartPart, bool inFocusEverything) const
Returns the next focusable part after inStartPart, if any.
HIViewPartCode FindPreviousPart (HIViewPartCode inStartPart, bool inFocusEverything) const
Returns the focusable part before inStartPart, if any.
bool FindPart (HIViewPartCode inPart) const
Returns true if inPart is a known part.
void ScrollInfoChanged () const
Notifies the view's superview that its scroll information has changed.
static HIViewTrackingAreaID GetTrackingAreaID (HIViewTrackingAreaRef inTrackingRef)
Returns the given tracking area's ID.
static void SetTrackingAreaShape (HIViewTrackingAreaRef inTrackingRef, const Shape &inShape)
Changes the given tracking area's shape.
Modifiers
These functions are for the benefit of derived classes, and may be used to change a part of the view's state that is managed by the HIToolbox.
void SetFrame (const Rect &inNewFrame)
void MoveFrameBy (float deltaX, float deltaY)
void MoveFrameTo (float x, float y)
void ResizeFrameBy (float deltaWidth, float deltaHeight)
void ResizeFrameTo (float width, float height)
void SetOrigin (const HIPoint &inOrigin)
Changes the view's origin (useful for scrollable views).
void SetValue (int inValue)
Changes the view's current value.
void SetMinimum (int inMininum)
Changes the view's minimum value.
void SetMaximum (int inMaximum)
Changes the view's maximum value.
void SetTitle (const String &inTitle)
Changes the view's title.
void SetHighlight (HIViewPartCode inPart)
Changes the view's highlighted part.
void Activate (bool inActivate)
Changes the view's active state.
void Enable (bool inEnable)
Changes the view's enabled state.
void Show (bool inShow)
Changes the view's visible state.
void SendCommandToUserFocus (bool inSendIt)
Changes the destination of HICommands generated by the view.
void Reshape ()
Notifies the HIView system that the view's contours have changed.
void Invalidate ()
Invalidates the entire view.
void Invalidate (const Rect &inRect)
Invalidates a portion of the view.
void Invalidate (const Shape &inShape)
Invalidates a portion of the view.
void Invalidate (const MutableShape &inShape)
Invalidates a portion of the view.
void InvalidatePart (HIViewPartCode inPart)
Invalidates one of the view's parts.
void AddSubview (HIViewRef subview)
Adds a subview to this view.
static void RemoveSubview (HIViewRef subview)
Removes a subview.
Additional Inherited Members
Public Member Functions inherited from B::EventTarget
template<>
EventTargetRef GetEventTarget (WindowRef inObj)
template<>
EventTargetRef GetEventTarget (HIViewRef inObj)
template<>
EventTargetRef GetEventTarget (HIObjectRef inObj)
template<>
EventTargetRef GetEventTarget (EventTargetRef inObj)
void SetAccessible (bool inAccessible)
Make the object archivable.
void SetAccessibilityAttribute (CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetAccessibilityAttribute (UInt64 inIdentifier, CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetArchivable (bool inArchivable)
Make the object archivable.
bool IsAccessible () const
Is the object accessible?
bool IsArchivable () const
Is the object archivable?
operator HIObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
HIObjectRef GetObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
Protected Types inherited from B::EventTarget
typedef EventTarget *(* ConstructProcPtr) (HIObjectRef inObjectRef)
Object construction callback.
Static Protected Member Functions inherited from B::EventTarget
static void PrivateRegister (CFStringRef inClassID, CFStringRef inBaseClassID, ConstructProcPtr inConstructor)
Registers class inClassID.
static void PrivateUnregister (CFStringRef inClassID)
Unregisters class inClassID.
static HIObjectClassRef PrivateFindClassObject (CFStringRef inClassID)
Returns the object class associated with type inClassID, or NULL.
static HIObjectRef PrivateCreate (CFStringRef inClassID, EventRef inEvent)
Creates an instance of class inClassID.
Detailed Description
Base class for custom derivatives of HIView.
This class regroups a lot of the functionality commonly required to implement a custom HIView (i.e., an object known to the HIToolbox which "derives" from the HIToolbox class kHIViewClassID). The supported functionality includes:
Drawing
Hit-testing
Mouse tracking
Hit handling
Retrieving part shapes & bounds
Retrieving min/max/optimal view sizes.
Focus, including text input
Getting & setting view data
Automatic view invalidation when certain state changes occur.
Drag & drop
Scrolling
Commands
Mouse-region tracking.
Objects of classes derived from CustomView may be instantiated via HIObjectCreate() or CreateCustomControl().
CustomView doesn't have much in the way of a public interface. That's because once a CustomView is instantiated, its public interface is via its HIViewRef, and not the C++ object. Communication between the view and its clients is therefore done via the HIView & Control Manager APIs. View-specific information may be communicated via GetControlData() & SetControlData().
The most important piece of information that derived classes provide to CustomView is the EViewFlags. This is bitfield that tells CustomView what kind of functionality is required by the derived class. For example, if the kViewDragAndDrop flag is set, the drag&drop-related Carbon Event handlers will be installed on the HIView. The view flags also tell CustomView which state changes will cause the view to be invalidated. For example, if the kViewInvalOnValue flag is set, then changing the view's value will automatically cause the view to redraw itself.
Obviously, if a derived class needs to handle a Carbon Event that isn't supported directly by CustomView, then it can declare an EventHandler member variable and add handlers to it.
Besides overriding functions that define the view's behaviour with respect to user interface events, there are some informational functions that will often need to be overriden as well. These include GetControlKind(), GetViewParts(), and possibly also CalcViewFeatures() and CalcControlFeatures().
Member Enumeration Documentation
enum B::CustomView::EViewFlags
Flags controlling view behaviour.
Many of these flags affect the Carbon Events handled by the view. Others determine which state changes cause the view to be redrawn.
These flags may be combined in a bitwise fashion.
Enumerator
kViewNone
Default flag value.
kViewOpaque
The view contains no translucent areas.
kViewFocus
The view can acquire the user input focus.
kViewFocusOnClick
The view can acquire the user input focus.
kViewContainer
The view can embed other views within itself.
kViewDragAndDrop
The view supports drag & drop.
kViewScrollable
The view can be placed in an HIScrollView.
kViewCommands
The view supports HICommands. This usually (but not necessarily) only makes sense if the view can also get the focus.
kViewHit
The view wants the ControlHit event.
kViewTracking
The view performs its own mouse tracking.
kViewTrackingArea
The view makes use of view tracking areas.
kViewLiveFeedback
The view implements the live feedback protocol.
kViewClickActivation
The view wants to be asked what to do when it's clicked when its containing window is inactive.
kViewNoDrawing
The view doesn't draw at all.
kViewNoClicking
The view doesn't respond to clicks.
kViewInvalOnActivate
Automatically invalidate the view when its active state changes.
kViewInvalOnHilite
Automatically invalidate the view when its hilited state changes.
kViewInvalOnEnable
Automatically invalidate the view when its enabled state changes.
kViewInvalOnValue
Automatically invalidate the view when one of its value/min/max fields changes.
kViewInvalOnTitle
Automatically invalidate the view when its title changes.
kViewInvalOnFocus
Automatically invalidate the view when its focused part changes.
enum B::CustomView::EViewPartFocus
The focus behaviour of a view part.
The focus behaviour of each part of a view can be specified individually via one of the EPartFocus enums.
Enumerator
kFocusAlways
The part is always focusable.
kFocusNever
The part is never focusable.
kFocusFull
The part is only focusable in full keyboard access mode.
Constructor & Destructor Documentation
B::CustomView::CustomView (HIObjectRef inObjectRef, EViewFlags inViewFlags) protected
Constructor.
Typically the constructor is called indirectly from HIObjectCreate.
inSignature and inKind are combined to form the view's ControlKind, which can later be returned from GetControlData().
inViewParts is a vector of part definitions. This vector is used in two ways. First, when hit-testing,
Each element of the vector contains a part code and
Parameters
inObjectRef The view's HIObjectRef.
inViewFlags The view's flags.
References B::EventHandler::Add(), B::EventHandler::Init(), kViewClickActivation, kViewCommands, kViewContainer, kViewDragAndDrop, kViewFocus, kViewHit, kViewNoDrawing, kViewScrollable, kViewTracking, kViewTrackingArea, mViewFlags, and B::ToolboxObjectProperty< SIG, TAG, T, ToolboxObjectPropertyViewObjectTraits >::Set().
Referenced by B::SplitView::Instantiate().
Member Function Documentation
template<class T > OSPtr< HIViewRef > B::CustomView::Create (const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, Collection inCollection) static
Creates an instance of class T.
Parameters
T The C/C++ type of the view. Must be CustomView or derived from CustomView.
Parameters
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inCollection Initialisation data for the new view; may be NULL.
Referenced by Create().
template<class T > OSPtr< HIViewRef > B::CustomView::Create (const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, EventRef inEvent) static
Creates an instance of class T.
Parameters
T The C/C++ type of the view. Must be CustomView or derived from CustomView.
Parameters
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inEvent Initialisation data for the new view; may be NULL.
References Create().
OSPtr< HIViewRef > B::CustomView::Create (CFStringRef inClassID, const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, EventRef inEvent) static
Creates an instance of class inClassID.
Parameters
inClassID The new view's class.
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inEvent Initialisation data for the new view; may be NULL.
References ActivateStateChanged(), AddedSubview(), AwakenView(), BoundsChanged(), CalcControlFeatures(), DisposeView(), DragEnter(), DragLeave(), DragReceive(), DragWithin(), Draw(), EnabledStateChanged(), FocusChanging(), GetBaseline(), GetClickActivation(), GetData(), GetFocusPart(), GetMinMaxSize(), GetOptimalBounds(), GetScrollInfo(), GetViewBounds(), GetViewShape(), HandleCommand(), HandleUpdateStatus(), HighlightChanged(), Hit(), HitTest(), InitializeView(), OwningWindowChanged(), RemovingSubview(), B::OSPtr< T >::reset(), ScrollTo(), B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Set(), SetData(), SetFocusPart(), TextInput(), TitleChanged(), Track(), TrackingAreaEntered(), TrackingAreaExited(), ValueFieldChanged(), and VisibilityChanged().
void B::CustomView::AwakenView (HIViewRef inView, Nib * inFromNib) static
Tell inView to awaken.
Note
This function is not recursive.
Parameters
inView The view to awaken.
inFromNib The nib from which to load other resources. May be NULL.
References FromViewRef(), kViewDragAndDrop, and mViewFlags.
Referenced by B::View::AwakenViewAndChildren(), Create(), and TrackingAreaExited().
void B::CustomView::InitializeView (Collection inCollection) protected virtual
View initialisation.
Perform any initialisation of the view. Derived classes may override this to set up the view's initial state. Such overrides should call the base class implementation prior to performing work of their own.
inCollection contains any initialisation parameters. If the collection contains any of the Apple-defined initialisation tags (kControlCollectionTagValue etc) they will be used to initialise the view's state. The collection may contain other tags as well, defined and interpreted by the derived class.
Note that Interface Builder currently always instantiates custom views via CreateCustomControl(), and fills in the collection with both standard and custom tags prior to instantiation.
The default implementation sets some internal flags, changes the view's HIViewFeatures to reflect the view flags (Panther only), and enables drag & drop on the view if its kViewDragAndDrop view flag is set.
Parameters
inCollection A collection containing initialisation parameters.
Reimplemented in B::HybridView.
References kViewDragAndDrop, and mViewFlags.
Referenced by Create(), B::HybridView::InitializeView(), and B::SplitView::Instantiate().
void B::CustomView::DisposeView () protected virtual
View cleanup.
Perform any cleanup of the view. Derived classes may override this to release resources. Such overrides should call the base class implementation after performing work of their own.
The default implementation does nothing.
References kViewContainer, kViewFocus, kViewFocusOnClick, kViewLiveFeedback, kViewNoClicking, kViewNoDrawing, kViewOpaque, and mViewFlags.
Referenced by Create().
const CustomView::ViewPartVector & B::CustomView::GetViewParts () const protected virtual
Returns the view parts defined by this view.
Derived classes need to override this function in order to return their vector of view parts.
The vector is used in two ways. First, it is used for hit-testing. The default implementation of HitTest() iterates over the vector, generating the shape of each part, and hit-testing the shape. Thus it's fairly important that the ordering of the parts in the vector take this into consideration. Second, it's used when advancing the focus. The ordering of parts in the vector is the order in which they will acquire the focus (or the reverse ordering, if the user is shift-tabbing).
Returns
CustomView::PartVector& A reference to the view's part vector.
Referenced by FindNextPart(), FindPart(), FindPreviousPart(), and HitTest().
ControlKind B::CustomView::GetKind () const protected pure virtual
Returns the view's ControlKind.
A view's ControlKind identifies the type of view (eg push button, static text etc) to the toolbox and to the rest of B. It is very important that all custom views have unique ControlKinds. The ControlKind contains a signature field, so the first step is to use a unique registered-with-Apple creator code for that. You can then attribute unique integer values to each of your custom views, and put them in the kind field of the ControlKind structure.
This is a pure virtual function, which all derived classes must override.
Referenced by GetData().
UInt32 B::CustomView::CalcControlFeatures () const protected virtual
Computes the Control Manager control features for this view.
The default implementation converts the view's flags into flags understood by the Control Manager (kControlSupportsDataAccess etc).
Derived classes may override this function to add additional flags which aren't currently handled by CustomView (eg, kControlIdlesWithTimer).
This function is used as a fallback when the HIViewFeatures functions can't be called, either because of build-time constraints (ie the build can't take advantage of Panther features) or run-time constraints (ie the application is running on a pre-Panther system).
Returns
UInt32 Control Feature Bits
References kViewClickActivation, kViewContainer, kViewDragAndDrop, kViewFocus, kViewFocusOnClick, kViewLiveFeedback, kViewTracking, and mViewFlags.
Referenced by Create().
void B::CustomView::Draw (HIViewPartCode inPart, CGContextRef inContext, const Shape * inDrawShape) protected virtual
Draws the view.
Derived classes need to override this function in order to draw their content. Note that if the kViewNoDrawing view flag is turned on, then this function won't be called at all.
The default implementation does nothing.
Parameters
inPart The view part to draw, or kHIViewNoPart to draw everything.
inContext The CoreGraphics context in which to draw, or NULL.
inDrawShape A shape for constraining drawing. May be NULL.
Referenced by Create().
Shape B::CustomView::GetStructureShape () const protected virtual
Returns the view's structure shape.
The structure shape needs to encompass the view in its entirety, including any translucent areas. Derived classes will normally need to override this function.
The default implementation returns a shape that matches the view bounds.
References GetBounds().
Referenced by GetClickableShape(), GetContentShape(), GetOpaqueShape(), GetPartShape(), GetStructureBounds(), and GetViewShape().
Shape B::CustomView::GetContentShape () const protected virtual
Returns the view's content shape.
The content shape is the area of the view in which subviews may be placed. Container views may want to override this function.
This function is only called if the kViewContainer view flag is set.
The default implementation returns a shape that matches the structure shape.
References GetStructureShape().
Referenced by GetContentBounds(), and GetViewShape().
Shape B::CustomView::GetOpaqueShape () const protected virtual
Returns the view's opaque shape.
The opaque shape is the area of the view where no part of any view underneath shows through. Derived classes with completely opaque areas may want to override this function.
This function is only called if the kViewOpaque view flag is not set.
The default implementation returns a shape that matches the structure shape.
References GetStructureShape().
Referenced by GetOpaqueBounds(), and GetViewShape().
Shape B::CustomView::GetClickableShape () const protected virtual
Returns the view's clickable shape.
Derived classes won't normally need to override this function. It's here for completeness.
The default implementation returns a shape that matches the structure shape.
References GetStructureShape().
Referenced by GetClickableBounds(), and GetViewShape().
Shape B::CustomView::GetPartShape (HIViewPartCode inPart) const protected virtual
Returns the shape of one of the view's parts.
This function is only called for parts that are contained in the view's part vector. Any non-trivial view will need to override this function.
The default implementation returns a shape that matches the structure shape.
Parameters
inPart The part for which to return the shape.
References GetStructureShape().
Referenced by GetPartBounds(), GetViewShape(), and HitTest().
bool B::CustomView::GetViewShape (HIViewPartCode inPart, Shape & outShape) const protected virtual
High-level function that returns the shape of one of the view's parts.
This is a template method that dispatches to one of the other shape-retrieval functions, depending on the value of inPart.
Derived classes will rarely need to override this function.
Returns
bool Indicates whether the request was handled succesfully.
Parameters
inPart The part for which to return the shape.
outShape The output shape.
References FindPart(), GetClickableShape(), GetContentShape(), GetOpaqueShape(), GetPartShape(), GetStructureShape(), kViewContainer, kViewOpaque, and mViewFlags.
Referenced by Create().
Rect B::CustomView::GetStructureBounds () const protected virtual
Returns the bounds of the view's structure shape.
The structure bounds needs to encompass the view in its entirety, including any translucent areas.
The default implementation simply retrieves the structure shape, then extracts the shape's bounds. Derived classes may override this behaviour if they have a simpler way of obtaining the same information.
References GetStructureShape().
Referenced by GetViewBounds().
Rect B::CustomView::GetContentBounds () const protected virtual
Returns the bounds of the view's content shape.
The content bounds is the area of the view in which subviews may be placed. Container views may want to override this function.
This function is only called if the kViewContainer view flag is set.
The default implementation simply retrieves the content shape, then extracts the shape's bounds. Derived classes may override this behaviour if they have a simpler way of obtaining the same information.
References GetContentShape().
Referenced by GetViewBounds().
Rect B::CustomView::GetOpaqueBounds () const protected virtual
Returns the bounds of the view's opaque shape.
The opaque bounds is the area of the view where no part of any view underneath shows through. Derived classes with completely opaque areas may want to override this function.
This function is only called if the kViewOpaque view flag is not set.
The default implementation simply retrieves the opaque shape, then extracts the shape's bounds. Derived classes may override this behaviour if they have a simpler way of obtaining the same information.
References GetOpaqueShape().
Referenced by GetViewBounds().
Rect B::CustomView::GetClickableBounds () const protected virtual
Returns the bounds of the view's clickable shape.
Derived classes won't normally need to override this function. It's here for completeness.
The default implementation simply retrieves the clickable shape, then extracts the shape's bounds. Derived classes may override this behaviour if they have a simpler way of obtaining the same information.
References GetClickableShape().
Referenced by GetViewBounds().
Rect B::CustomView::GetPartBounds (HIViewPartCode inPart) const protected virtual
Returns the bounds of the shape of one of the view's parts.
This function is only called for parts that are contained in the view's part vector.
The default implementation simply retrieves the part's shape, then extracts the shape's bounds. Derived classes may override this behaviour if they have a simpler way of obtaining the same information.
Parameters
inPart The part for which to return the bounds.
References GetPartShape().
Referenced by GetViewBounds().
bool B::CustomView::GetViewBounds (HIViewPartCode inPart, Rect & outBounds) const protected virtual
High-level function that returns the bounds of the shape of one of the view's parts.
This is a template method that dispatches to one of the other bounds-retrieval functions, depending on the value of inPart.
Derived classes will rarely need to override this function.
Returns
bool Indicates whether the request was handled succesfully.
Parameters
inPart The part for which to return the bounds.
outBounds The output bounds.
References FindPart(), GetClickableBounds(), GetContentBounds(), GetOpaqueBounds(), GetPartBounds(), GetStructureBounds(), kViewContainer, kViewOpaque, and mViewFlags.
Referenced by Create().
HIViewPartCode B::CustomView::HitTest (const Point & inMouseLoc) const protected virtual
Returns the view part containing inMouseLoc, if any.
The default implementation iterates over all of the view's parts, retrieves the shape of each one and hit-test against the shape.
Derived classes may override this function if necessary.
Returns
HIViewPartCode The view part containing inMouseLoc, or kHIViewNoPart.
Parameters
inMouseLoc The mouse location to test for.
References GetPartShape(), and GetViewParts().
Referenced by Create(), and B::SplitView::Track().
void B::CustomView::Hit (HIViewPartCode inPart, UInt32 inKeyModifiers) protected virtual
The view was hit in inPart.
This function is called after a click has been succesfully tracked.
This function is only called if the kViewHit view flag is turned on. Note that it's only necessary to turn the flag on if the HIToolbox's default behaviour (i.e. sending the view's CommandID if it has one to either itself or the user input focus) is inappropriate.
The default implementation does nothing.
Parameters
inPart The view part that was hit.
inKeyModifiers The keyboard modifiers that were pressed at the time the mouse was released.
Referenced by Create().
HIViewPartCode B::CustomView::Track (const Point & inMouseLoc, UInt32 inClickCount, UInt32 & ioKeyModifiers) protected virtual
Perform mouse tracking.
This function is called to perform mouse tracking. This will usually involve:
Determining which view part was clicked.
Entering a tracking loop for the view part, highlighting and unhighlighting the part as appropriate.
Returning the part if the mouse button is raised in the original part, or kHIViewNoPart otherwise.
This function is only called if the kViewTracking view flag is turned on. Note that for simple views (i.e., views whose view part shapes don't change during tracking, or that don't need to track at a finer granularity than a view part), the HIToolbox's default behaviour is probably sufficient.
Returns
HIViewPartCode The view part where the tracking occurred, or kHIViewNoPart.
Reimplemented in B::SplitView.
Referenced by Create().
ClickActivationResult B::CustomView::GetClickActivation (const Point & inMouseLoc, UInt32 inKeyModifiers, EventMouseButton inMouseButton, UInt32 inClickCount, UInt32 inMouseChord) protected virtual
Determines whether the view's containing window should be activated when clicked in the background.
This function allows the view to determine what happens when it is clicked while its containing window is inactive.
The default implementation behaves the same was as if there wasn't a handler for this event. Namely, the window is activated and the click is swallowed.
Referenced by Create().
HIViewPartCode B::CustomView::SetFocusPart (HIViewPartCode inPart, bool inFocusEverything) protected virtual
High-level function that handles focus-change requests.
This is a template method that dispatches to one of the other focus-retrieval functions, depending on the value of inPart. Derived classes may override this function if necessary.
This function is only called if the kViewFocus view flag is turned on.
The default implementation dispatches to some utility routines, depending on the value of inPart.
Parameters
inPart The part to focus. May be one of the focusing meta-parts (i.e., kHIViewFocusNextPart or kHIViewFocusPrevPart).
inFocusEverything If true, full keyboard access is turned on.
References FindNextPart(), FindPart(), and FindPreviousPart().
Referenced by Create().
bool B::CustomView::SetData (HIViewPartCode inPart, ResType inDataTag, const void * inDataPtr, size_t inDataSize) protected virtual
Changes a piece of view data.
The default implementation does nothing. Derived classes may override this function, but should call the base class implementation for data tags they don't recognise.
Parameters
inPart The view part to change, or kHIViewEntireView.
inDataTag The tag identifying the view data.
inDataPtr A pointer to the view data.
inDataSize The view data's size.
Referenced by Create(), and B::SplitView::Track().
bool B::CustomView::GetData (HIViewPartCode inPart, ResType inDataTag, void * inDataPtr, size_t & ioDataSize) const protected virtual
Retrieves a piece of view data.
The default implementation only handles kControlKindTag. Derived classes may override this function, but should call the base class implementation for data tag they don't recognise.
Parameters
inPart The view part to change, or kHIViewEntireView.
inDataTag The tag identifying the view data.
inDataPtr A pointer to receive the view data.
ioDataSize The view data's size.
References GetKind().
Referenced by Create(), and B::SplitView::Track().
Rect B::CustomView::GetOptimalBounds () const protected virtual
Retrieves the view's optimal bounds.
The default implementation returns the view's current bounds.
Derived classes may override this function to return something more appropriate.
References GetBounds().
Referenced by Create().
std::pair< Size, Size > B::CustomView::GetMinMaxSize () const protected virtual
Retrieves the view's minimal and maximal sizes.
The default implementation returns the view's current size.
Derived classes may override this function to return something more appropriate.
References GetBounds().
Referenced by Create().
float B::CustomView::GetBaseline () const protected virtual
Retrieves the view's text baseline.
The default implementation returns 0.0.
Derived classes may override this function to return something more appropriate.
Referenced by Create().
bool B::CustomView::BoundsChanged (UInt32 inAttributes, const Rect & inPreviousBounds, const Rect & inCurrentBounds) protected virtual
Notifies the view that its bounds have changed.
Derived classes may override this function to perform some processing whenever a view's bounds is changed. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation currently does nothing.
Returns
true if the object handled the bounds change completely; else false.
Referenced by Create().
void B::CustomView::OwningWindowChanged (WindowRef inOriginalWindow, WindowRef inCurrentWindow) protected virtual
Notifies the view that its owning window has changed.
Derived classes may override this function to perform some processing whenever a view's owning window is changed. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation refreshes some internal flags.
Referenced by Create(), B::HybridView::InitializeView(), and B::SplitView::Track().
void B::CustomView::HighlightChanged (HIViewPartCode inOldHilitePart, HIViewPartCode inNewHilitePart) protected virtual
Notifies the view that its highlight state has changed.
Derived classes may override this function to perform some processing whenever a view's highlight changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation invalidates the view if the kViewInvalOnHilite view flag is set.
References Invalidate(), kViewInvalOnHilite, and mViewFlags.
Referenced by Create().
void B::CustomView::FocusChanging (HIViewPartCode inOldFocusPart, HIViewPartCode inNewFocusPart) protected virtual
Notifies the view that its focus state has changed.
Derived classes may override this function to perform some processing whenever a view's focused part changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation changes the focused part, then invalidates the view if the kViewInvalOnFocus view flag is set.
References Invalidate(), kViewInvalOnFocus, and mViewFlags.
Referenced by Create().
void B::CustomView::ActivateStateChanged (bool inActive) protected virtual
Notifies the view that its active state has changed.
Derived classes may override this function to perform some processing whenever a view's active state changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation invalidates the view if the kViewInvalOnActivate view flag is set.
References Invalidate(), kViewInvalOnActivate, and mViewFlags.
Referenced by Create().
void B::CustomView::VisibilityChanged () protected virtual
Notifies the view that its visibility has changed.
Derived classes may override this function to perform some processing whenever a view's visible state changes. If they do so, they should call the base class implementation prior to performing their own processing.
Referenced by Create().
void B::CustomView::ValueFieldChanged () protected virtual
Notifies the view that one of its value/minimum/maximum fields has changed.
Derived classes may override this function to perform some processing whenever one of a view's value fields changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation invalidates the view if the kViewInvalOnValue view flag is set.
References Invalidate(), kViewInvalOnValue, and mViewFlags.
Referenced by Create(), and B::SplitView::Track().
void B::CustomView::TitleChanged () protected virtual
Notifies the view that its title has changed.
Derived classes may override this function to perform some processing whenever a view's title changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation invalidates the view if the kViewInvalOnTitle view flag is set.
References Invalidate(), kViewInvalOnTitle, and mViewFlags.
Referenced by Create().
void B::CustomView::EnabledStateChanged () protected virtual
Notifies the view that its enabled state has changed.
Derived classes may override this function to perform some processing whenever a view's enabled state changes. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation invalidates the view if the kViewInvalOnEnable view flag is set.
References Invalidate(), kViewInvalOnEnable, and mViewFlags.
Referenced by Create().
void B::CustomView::AddedSubview (HIViewRef inSubview) protected virtual
Notifies the view that a view has been added as one of its children.
Derived classes may override this function to perform some processing whenever a subview is added to it. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation does nothing.
Referenced by Create().
void B::CustomView::RemovingSubview (HIViewRef inSubview) protected virtual
Notifies the view that one of its subviews is about to be removed.
Derived classes may override this function to perform some processing whenever a subview is removed from it. If they do so, they should call the base class implementation prior to performing their own processing.
The default implementation does nothing.
Referenced by Create().
bool B::CustomView::DragEnter (DragRef inDragRef) protected virtual
Notifies the view that the user has dragged something into it.
This function is called to determine if a drag is of interest to a view. If it is, the function should return true. The other drag-related functions (DragWithin(), DragLeave(), and possibly DragReceive()) will then be called. If one the other hand the function returns false, then none of those functions will be called.
Note that in order for this function to be called in the first place, the kViewDragAndDrop view flag must be set.
Derived classes that support drag & drop need to override this function. The default implementation always returns false.
Returns
bool An indication of whether the view is interested in this drag.
Parameters
inDragRef The drag to query.
Referenced by Create().
void B::CustomView::DragWithin (DragRef inDragRef) protected virtual
Notifies the view that the user is moving within it during a drag.
This function is only called if (1) the kViewDragAndDrop view flag is turned on, and (2) a previous call to DragEnter() for the same DragRef returned true.
Derived classes that support drag & drop may want to override this function. The default implementation does nothing.
Parameters
inDragRef The drag to query.
Referenced by Create().
void B::CustomView::DragLeave (DragRef inDragRef) protected virtual
Notifies the view that the user is moving out of it during a drag.
This function is only called if (1) the kViewDragAndDrop view flag is turned on, and (2) a previous call to DragEnter() for the same DragRef returned true.
Derived classes that support drag & drop may want to override this function. The default implementation does nothing.
Parameters
inDragRef The drag to query.
Referenced by Create().
bool B::CustomView::DragReceive (DragRef inDragRef) protected virtual
Notifies the view that the user has dropped something onto it.
This function is only called if (1) the kViewDragAndDrop view flag is turned on, and (2) a previous call to DragEnter() for the same DragRef returned true.
Derived classes that support drag & drop may want to override this function. The default implementation always returns false.
Returns
bool An indication of whether the drop was successful.
Parameters
inDragRef The drag to query.
Referenced by Create().
bool B::CustomView::TextInput (const UniChar * inText, size_t inLength, EventRef inKeyboardEvent) protected virtual
Notifies the view that the user has entered some text.
This function is normally called only if the kViewFocus view flag is turned on, and if the view is currently within the chain of Carbon Event handlers leading up from the user input focus. Practically speaking, this means that either the view or one of its subviews has the focus.
Derived classes that support text input need to override this function. It's very important that overrides return false for text they do not handle. This lets the view's superview handle the text instead.
The default implementation always returns false.
Returns
bool An indication of whether the text was handled.
Parameters
inText The entered characters.
inLength The number of entered characters.
inKeyboardEvent The keyboard event that generated the characters.
Referenced by Create().
void B::CustomView::GetScrollInfo (Size & outImageSize, Size & outViewSize, Size & outLineSize, Point & outOrigin) const protected virtual
Retrieves the view's scroll information.
This function is only called if the kViewScrollable view flag is turned on. It needs to return scrolling-related information.
The default implementation returns reasonable values, but derived classes that support scrolling will need to override it.
Parameters
outImageSize The size of the view's model.
outViewSize The size of the view's visible area. This is normally the size of its bounds.
outLineSize The size of scrolling increment, in both X and Y directions.
outOrigin The view's current origin.
References GetBounds().
Referenced by Create().
void B::CustomView::ScrollTo (const Point & inOrigin) protected virtual
Tells the view to move its origin.
This function is only called if the kViewScrollable view flag is turned on.
The default implementation does nothing. Derived classes that support scrolling will need to override it.
Parameters
inOrigin The new origin for the view.
Referenced by Create().
bool B::CustomView::HandleCommand (const HICommandExtended & inHICommand) protected virtual
Handles an HICommand.
This function is only called if the kViewCommands view flag is turned on.
The default implementation does nothing. Derived classes that support commands will need to override it.
Parameters
inHICommand The command to execute.
Referenced by Create().
bool B::CustomView::HandleUpdateStatus (const HICommandExtended & inHICommand, CommandData & ioCmdData) protected virtual
Returns the status of an HICommand.
This function is only called if the kViewCommands view flag is turned on.
The default implementation does nothing. Derived classes that support commands will need to override it.
Parameters
inHICommand The command about which to return status.
ioCmdData The command's status.
Referenced by Create().
void B::CustomView::TrackingAreaEntered (HIViewTrackingAreaRef inTrackingRef, const Point & inMouseLocation, UInt32 inKeyModifiers) protected virtual
The mouse has just entered the tracking region identified by inTrackingRef.
This function is only called if the kViewTrackingArea view flag is turned on.
The default implementation does nothing. Derived classes that support mouse-tracking regions will need to override it.
Referenced by Create().
void B::CustomView::TrackingAreaExited (HIViewTrackingAreaRef inTrackingRef, const Point & inMouseLocation, UInt32 inKeyModifiers) protected virtual
The mouse has just left the tracking region identified by inTrackingRef.
This function is only called if the kViewTrackingArea view flag is turned on.
The default implementation does nothing. Derived classes that support mouse-tracking regions will need to override it.
References AwakenView(), and B::OSPtr< T >::reset().
Referenced by Create().
bool B::CustomView::HandleChooseKey (HIViewPartCode inPart, const UniChar * inText, size_t inLength, EventRef inKeyboardEvent) protected
Handles translating a "space" key press into a click.
This function checks that the text input is a single space character and if so simulates a click on view part inPart of the view.
Derived classes that support text input may call this to support clicking buttons via the keyboard.
Parameters
inPart The view part to "click".
inText The entered characters.
inLength The number of entered characters.
inKeyboardEvent The keyboard event that generated the characters.
References B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Get().
HIViewPartCode B::CustomView::FindNextPart (HIViewPartCode inStartPart, bool inFocusEverything) const protected
Returns the next focusable part after inStartPart, if any.
Parameters
inStartPart The currently focused part, if any.
inFocusEverything If true, full keyboard access is turned on.
References GetViewParts().
Referenced by SetFocusPart().
HIViewPartCode B::CustomView::FindPreviousPart (HIViewPartCode inStartPart, bool inFocusEverything) const protected
Returns the focusable part before inStartPart, if any.
Parameters
inStartPart The currently focused part, if any.
inFocusEverything If true, full keyboard access is turned on.
References GetViewParts().
Referenced by SetFocusPart().
bool B::CustomView::FindPart (HIViewPartCode inPart) const protected
Returns true if inPart is a known part.
Parameters
inPart The view part to check.
References GetViewParts().
Referenced by GetViewBounds(), GetViewShape(), and SetFocusPart().
void B::CustomView::ScrollInfoChanged () const protected
Notifies the view's superview that its scroll information has changed.
Derived classes that support scrolling may call this when one of their image size, view size, line size, or origin changes.
References B::EventBase::Send().
The documentation for this class was generated from the following files:
BCustomView.h
BCustomView.cpp