B: B::Alert Class Reference
B::Alert Class Reference
Alert dialogs and sheets.
#include <BAlert.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Friends
class ModalityHandler
Types
enum Button {
kOK = kHICommandOK, kCancel = kHICommandCancel, kOther = kHICommandOther, kHelp = 'help',
kNone = 0
}
Enumerates an alert's buttons according to their position in the alert.
typedef AlertStdCFStringAlertParamRec Params
Shorthand for Alert configuration struct.
Constructors & Destructor
Alert ()
Default constructor.
virtual ~Alert ()
Destructor.
Inquiries
const Params & GetParams () const
Returns the alert's params struct.
AlertType GetType () const
Returns the alert's type.
const String & GetMessageText () const
Returns the alert's message text.
const String & GetInformativeText () const
Returns the alert's informative text.
Button GetButtonHit () const
Returns the alert's dismissing button. Only valid in a modal scenario.
Setup
void SetMessageText (const String &inMessageText)
Sets the error text, which is the highlighted text in the alert.
void SetInformativeText (const String &inInformativeText)
Sets the explanatory text, which is the secondary text in the alert.
void SetModality (const DialogModality &inModality)
Sets the alert's modality.
void SetCloseOnDismiss (bool inCloseOnDismiss)
Determines whether the dialog gets closed (i.e. destroyed) after it's dismissed.
template<class ALERT >
void SetCallback (B_ALERT_CB inFunction)
Installs a callback that will be called once the alert is dismissed.
void ShowButton (Button whichButton, bool showIt)
Controls the visibility of one of the alert's buttons.
void SetButtonText (Button whichButton, const String &inText)
Sets the caption of one of the alert's buttons.
void SetDefaultButton (Button whichButton)
Identifies the default button, which is drawn highlighted and reacts to the Return and Enter keys.
void SetCancelButton (Button whichButton)
Identifies the cancel button, which reacts to the Escape and Command-period keys.
void SetHelpBook (const String &inHelpBook)
Sets the help book name in which to look for help.
void SetHelpUrl (const Url &inHelpUrl)
Sets the url of the help page to display.
void SetParamFlags (OptionBits flags)
Sets some flags controlling the alert.
void ClearParamFlags (OptionBits flags)
Clears some flags controlling the alert.
void SetPosition (UInt16 inPosition)
Places the alert on the screen (app-modal only).
void SetAlertType (AlertType inAlertType)
Sets the alert type, which determines the icon.
Making Alerts
In B parlance, "Making" an alert means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
template<class ALERT >
static std::auto_ptr< ALERT > Make (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, B_ALERT_CB inFunction=NullCallback< ALERT >())
Instantiates and returns an ALERT with the given arguments.
template<class ALERT >
static std::auto_ptr< ALERT > Make (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, bool inIsCautionAlert, bool inShowCancelButton, B_ALERT_CB inFunction=NullCallback< ALERT >())
template<class ALERT >
static std::auto_ptr< ALERT > Make (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String &inOKButtonText, const String &inCancelButtonText, const String &inOtherButtonText, B_ALERT_CB inFunction=NullCallback< ALERT >())
Entering Alerts
In B parlance, "Entering" an alert means to display it according to its modality, i.e. if it's application-modal then the function doesn't return until the alert is dismissed.
void Enter ()
Displays the alert according to its modality.
template<class ALERT >
static void Enter (std::auto_ptr< ALERT > inAlertPtr)
Displays the given alert according to its modality, taking control of the alert's lifetime.
Starting Alerts
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class ALERT >
static void Start (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, B_ALERT_CB inFunction=NullCallback< ALERT >())
Instantiates an ALERT with the given arguments, then enters it.
template<class ALERT >
static void Start (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, bool inIsCautionAlert, bool inShowCancelButton, B_ALERT_CB inFunction=NullCallback< ALERT >())
template<class ALERT >
static void Start (const String &inMessageText, const String &inInformativeText, const DialogModality &inModality, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String &inOKButtonText, const String &inCancelButtonText, const String &inOtherButtonText, B_ALERT_CB inFunction=NullCallback< ALERT >())
Running Alerts
These are convenience functions for displaying alerts in an application-modal fashion. Because they don't return until the alert is dismissed, the dismissing button is returned as the function result.
Button Run ()
Displays the alert in an application-modal fashion.
template<class ALERT >
static Button Run (const String &inMessageText, const String &inInformativeText)
Instantiates an ALERT, then enters a modal event loop for it.
template<class ALERT >
static Button Run (const String &inMessageText, const String &inInformativeText, bool inIsCautionAlert, bool inShowCancelButton)
template<class ALERT >
static Button Run (const String &inMessageText, const String &inInformativeText, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String &inOKButtonText, const String &inCancelButtonText, const String &inOtherButtonText)
Overridables
virtual void ShowHelp ()
Called in response to click on the help button.
virtual void DismissAlert (Button inButton)
Called in response to click in a dismissing button.
Detailed Description
Alert dialogs and sheets.
This class is a wrapper around standard HIToolbox alerts and alert sheets. It presents a uniform interface regardless of an alert's modality (i.e. application-modal vs. sheet).
See also
Dialogs, Alerts and Navigation Services
Member Enumeration Documentation
enum B::Alert::Button
Enumerates an alert's buttons according to their position in the alert.
Enumerator
kOK
The OK button (rightmost).
kCancel
The Cancel button (second from right).
kOther
The Other (sometimes called "Don't Save") button (third from right).
kHelp
The Help button.
kNone
Sentinel value.
Constructor & Destructor Documentation
B::Alert::Alert ()
Default constructor.
Sets default values for everything, which gives us a note alert with no error or explanatory text, using the default buttons and button titles.
References B::Bundle::GetHelpBook(), B::HelpUtilities::HasHelpBook(), and B::Bundle::Main().
Member Function Documentation
void B::Alert::SetMessageText (const String & inMessageText)
Sets the error text, which is the highlighted text in the alert.
Parameters
inMessageText The message text, which is the principal text in the alert.
Referenced by DismissAlert(), and GetButtonHit().
void B::Alert::SetInformativeText (const String & inInformativeText)
Sets the explanatory text, which is the secondary text in the alert.
Parameters
inInformativeText The informative text, which is the secondary text in the alert. May be empty, in which case no informative text is displayed.
Referenced by DismissAlert(), and GetButtonHit().
void B::Alert::SetModality (const DialogModality & inModality)
Sets the alert's modality.
Only application-modal alerts and alert sheets are supported. An exception is thrown if any other modality (eg modeless) is passed in.
Parameters
inModality The alert's modality.
References B::DialogModality::GetModality(), and B::DialogModality::GetParent().
Referenced by DismissAlert(), Enter(), GetButtonHit(), and Run().
template<class ALERT > void B::Alert::SetCallback (B_ALERT_CB inFunction)
Installs a callback that will be called once the alert is dismissed.
Todo:
Complete this!
Parameters
ALERT Template parameter. The class of the instantiated alert. Must be Alert or a class derived from Alert.
Referenced by GetButtonHit().
void B::Alert::ShowButton (Button whichButton, bool showIt)
Controls the visibility of one of the alert's buttons.
When first made visible, the button uses its default caption. By default, only the OK button is visible.
If whichButton is kNone, the function does nothing.
References kCancel, kHelp, kOK, kOther, and SetButtonText().
Referenced by DismissAlert(), GetButtonHit(), SetHelpBook(), and SetHelpUrl().
void B::Alert::SetButtonText (Button whichButton, const String & inText)
Sets the caption of one of the alert's buttons.
This function makes whichButton visible if it isn't already.
If whichButton is kHelp or kNone, the function does nothing.
References B::String::cf_ref(), B::String::empty(), kCancel, kHelp, kOK, and kOther.
Referenced by DismissAlert(), GetButtonHit(), and ShowButton().
void B::Alert::SetDefaultButton (Button whichButton)
Identifies the default button, which is drawn highlighted and reacts to the Return and Enter keys.
If whichButton is kNone, the alert won't react to the Return and Enter keys.
References kCancel, kHelp, kNone, kOK, and kOther.
Referenced by DismissAlert(), and GetButtonHit().
void B::Alert::SetCancelButton (Button whichButton)
Identifies the cancel button, which reacts to the Escape and Command-period keys.
If whichButton is kNone, the alert won't react to the Escape and Command-period keys.
References kCancel, kHelp, kNone, kOK, and kOther.
Referenced by DismissAlert(), and GetButtonHit().
void B::Alert::SetHelpBook (const String & inHelpBook)
Sets the help book name in which to look for help.
By default, the help book is set to the main bundle's help book, if any.
Calling this function changes the alert in the following ways:
It implicitly makes the Help button visible.
If the user clicks the Help button, then the Help Viewer application is automatically opened in order to display the help pointed to by the help book / help url pair.
References kHelp, and ShowButton().
Referenced by GetButtonHit().
void B::Alert::SetHelpUrl (const Url & inHelpUrl)
Sets the url of the help page to display.
Calling this function changes the alert in the following ways:
It implicitly makes the Help button visible.
If the user clicks the Help button, then the Help Viewer application is automatically opened in order to display the help pointed to by the help book / help url pair.
References kHelp, and ShowButton().
Referenced by GetButtonHit().
void B::Alert::SetPosition (UInt16 inPosition)
Places the alert on the screen (app-modal only).
Parameters
inPosition Enumerated value denoting the alert's location on the screen. May take on one of the following values:
kWindowDefaultPosition
kWindowCenterMainScreen
kWindowAlertPositionMainScreen
kWindowStaggerMainScreen
kWindowCenterParentWindow
kWindowAlertPositionParentWindow
kWindowStaggerParentWindow
kWindowCenterParentWindowScreen
kWindowAlertPositionParentWindowScreen
kWindowStaggerParentWindowScreen
Referenced by GetButtonHit().
void B::Alert::SetAlertType (AlertType inAlertType)
Sets the alert type, which determines the icon.
Parameters
inAlertType The alert type.
Referenced by DismissAlert(), and GetButtonHit().
template<class ALERT > std::auto_ptr< ALERT > B::Alert::Make (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
Instantiates and returns an ALERT with the given arguments.
Instantiates an alert of class ALERT. The instance of ALERT is then configured with the given arguments. Finally the alert is returned, ready to be displayed via Enter().
The function performs only basic configuration of the alert. In particular, the alert will only display the OK button (which will also be the default button). If the caller requires that other buttons be displayed, or that the default button not be the OK button, then it should perform additional configuration prior to display.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The ALERT object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inFunction A callback that is invoked when the alert is dismissed.
Referenced by GetButtonHit().
template<class ALERT > std::auto_ptr< ALERT > B::Alert::Make (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, bool inIsCautionAlert, bool inShowCancelButton, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This variant performs additional configuration of the alert. With it one can generate any of the three basic alert types (note, caution & stop), as long as the button text and keyboard equivalents don't need to be customised.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The ALERT object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
inFunction A callback that is invoked when the alert is dismissed.
template<class ALERT > std::auto_ptr< ALERT > B::Alert::Make (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String & inOKButtonText, const String & inCancelButtonText, const String & inOtherButtonText, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This variant performs additional configuration of the alert. With it one can generate almost any alert that doesn't require a help button.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The ALERT object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
inShowOtherButton Should the Other button be displayed?
inDefaultButton Which is the default button (i.e. the one that reacts to the Return and Enter keys)?
inCancelButton Which is the cancel button (i.e. the one that reacts to the Escape and Command-period keys)?
inOKButtonText The text of the OK button. If empty, the default text is used instead.
inCancelButtonText The text of the Cancel button. Ignored unless inShowCancelButton is true.
inOtherButtonText The text of the Other button. Ignored unless inShowOtherButton is true.
inFunction A callback that is invoked when the alert is dismissed.
template<class ALERT > void B::Alert::Enter (std::auto_ptr< ALERT > inAlertPtr) static
Displays the given alert according to its modality, taking control of the alert's lifetime.
Parameters
inAlertPtr The alert to enter.
template<class ALERT > void B::Alert::Start (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
Instantiates an ALERT with the given arguments, then enters it.
Instantiates an alert of class ALERT, as per Make(). The alert is then displayed via Enter(). Whether the alert has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The alert is automatically disposed upon dismissal. If you would rather hang on to the alert (to reuse it later without having to read it in from the nib file again), call Make(), then Enter().
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
See also
Make(), Enter()
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inFunction A callback that is invoked when the alert is dismissed.
References Enter().
Referenced by GetButtonHit().
template<class ALERT > void B::Alert::Start (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, bool inIsCautionAlert, bool inShowCancelButton, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This variant performs additional configuration of the alert. With it one can generate any of the three basic alert types (note, caution & stop), as long as the button text and keyboard equivalents don't need to be customised.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
See also
Make()
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
inFunction A callback that is invoked when the alert is dismissed.
References Enter().
template<class ALERT > void B::Alert::Start (const String & inMessageText, const String & inInformativeText, const DialogModality & inModality, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String & inOKButtonText, const String & inCancelButtonText, const String & inOtherButtonText, B_ALERT_CB inFunction = NullCallback<ALERT>()) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This variant performs additional configuration of the alert. With it one can generate any of the three basic alert types (note, caution & stop), as long as the button text and keyboard equivalents don't need to be customised.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
See also
Make()
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inModality The alert's modality.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
inShowOtherButton Should the Other button be displayed?
inDefaultButton Which is the default button (i.e. the one that reacts to the Return and Enter keys)?
inCancelButton Which is the cancel button (i.e. the one that reacts to the Escape and Command-period keys)?
inOKButtonText The text of the OK button. If empty, the default text is used instead.
inCancelButtonText The text of the Cancel button. Ignored unless inShowCancelButton is true.
inOtherButtonText The text of the Other button. Ignored unless inShowOtherButton is true.
inFunction A callback that is invoked when the alert is dismissed.
References Enter().
Alert::Button B::Alert::Run ()
Displays the alert in an application-modal fashion.
Sets the alert to be application-modal, enters is, then returns the dismissing button once the alert has been dismissed.
Returns
An enumerated value of type Button, indicating which button dismissed the alert dialog.
References Enter(), GetButtonHit(), B::DialogModality::Modal(), SetCloseOnDismiss(), and SetModality().
Referenced by GetButtonHit().
template<class ALERT > Alert::Button B::Alert::Run (const String & inMessageText, const String & inInformativeText) static
Instantiates an ALERT, then enters a modal event loop for it.
Instantiates an alert object of class ALERT. The instance of ALERT is then configured with the given arguments.
The alert's modality is set to application-modal. After instantiation, the alert is entered. Control does not return from this function until the alert is dismissed.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The Button that dismissed the alert.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
References B::DialogModality::Modal().
template<class ALERT > Alert::Button B::Alert::Run (const String & inMessageText, const String & inInformativeText, bool inIsCautionAlert, bool inShowCancelButton) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Instantiates an alert object of class ALERT. The instance of ALERT is then configured with the given arguments.
The alert's modality is set to application-modal. After instantiation, the alert is entered. Control does not return from this function until the alert is dismissed.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The Button that dismissed the alert.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
References B::DialogModality::Modal().
template<class ALERT > Alert::Button B::Alert::Run (const String & inMessageText, const String & inInformativeText, bool inIsCautionAlert, bool inShowCancelButton, bool inShowOtherButton, Button inDefaultButton, Button inCancelButton, const String & inOKButtonText, const String & inCancelButtonText, const String & inOtherButtonText) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Instantiates an alert object of class ALERT. The instance of ALERT is then configured with the given arguments.
The alert's modality is set to application-modal. After instantiation, the alert is entered. Control does not return from this function until the alert is dismissed.
Parameters
ALERT Template parameter. The class of the instantiated window. Must be Alert or a class derived from Alert.
Returns
The Button that dismissed the alert.
Parameters
inMessageText The alert's principal text.
inInformativeText The alert's secondary text. May be empty.
inIsCautionAlert Is this a "caution" alert?
inShowCancelButton Should the Cancel button be displayed?
inShowOtherButton Should the Other button be displayed?
inDefaultButton Which is the default button (i.e. the one that reacts to the Return and Enter keys)?
inCancelButton Which is the cancel button (i.e. the one that reacts to the Escape and Command-period keys)?
inOKButtonText The text of the OK button. If empty, the default text is used instead.
inCancelButtonText The text of the Cancel button. Ignored unless inShowCancelButton is true.
inOtherButtonText The text of the Other button. Ignored unless inShowOtherButton is true.
References B::DialogModality::Modal().
void B::Alert::DismissAlert (Button inButton) protected virtual
Called in response to click in a dismissing button.
Todo:
Complete this!
References B::String::empty(), GetInformativeText(), GetMessageText(), kCancel, kHelp, kNone, kOK, kOther, B::InteractWithUserDialog::Run(), SetAlertType(), SetButtonText(), SetCancelButton(), SetDefaultButton(), SetInformativeText(), SetMessageText(), SetModality(), ShowButton(), and ShowHelp().
Referenced by GetButtonHit().
The documentation for this class was generated from the following files:
BAlert.h
BAlert.cpp