B: B::HelpUtilities Class Reference
B::HelpUtilities Class Reference
Helper class that interfaces to Carbon Help Manager.
#include <BHelpUtilities.h>
Static Public Member Functions
Inquiries
static bool HasHelpBook ()
Returns true if the main bundle contains a help book.
static bool HasHelpBook (const Bundle &inBundle)
Returns true if inBundle contains a help book.
Help Book Registration
static void RegisterHelpBook ()
Registers the help book in the main bundle.
static void RegisterHelpBook (const Bundle &inBundle)
Registers the help book in inBundle.
Help Display
static void GotoPage (const Url &inUrl)
Displays the page in the main bundle's help book that is identified by inUrl.
static void GotoPage (const Bundle &inBundle, const Url &inUrl)
Displays the page in inBundle's help book that is identified by inUrl.
static void GotoPage (const String &inBookName, const Url &inUrl)
Displays the page in help book inBookName that is identified by inUrl.
static void GotoPage (const String &inBookName, const String &inPath, const String &inAnchor)
Displays the page in help book inBookName that is identified by inPath and inAnchor.
Table of Contents
static void GotoTOC (AHTOCType inTOCType=kAHTOCTypeUser)
Searching for Content
static void Search (const String &inSearchText)
Searches for occurrences of inSearchText within the main bundle's help book.
static void Search (const Bundle &inBundle, const String &inSearchText)
Searches for occurrences of inSearchText within inBundle's help book.
static void Search (const String &inBookName, const String &inSearchText)
Searches for occurrences of inSearchText within the help book inBookName.
static void SearchAll (const String &inSearchText)
Searches for occurrences of inSearchText within all registered help books.
Searching for Anchors
static void Lookup (const String &inAnchor)
Searches for anchors matching inAnchor within the main bundle's help book.
static void Lookup (const Bundle &inBundle, const String &inAnchor)
Searches for anchors matching inAnchor within inBundle's help book.
static void Lookup (const String &inBookName, const String &inAnchor)
Searches for anchors matching inAnchor within the help book inBookName.
static void LookupAll (const String &inAnchor)
Searches for anchors matching inAnchor within all registered help books.
Detailed Description
Helper class that interfaces to Carbon Help Manager.
This class contains a number of utility functions for registering help books, and for looking up or searching help content.
Member Function Documentation
bool B::HelpUtilities::HasHelpBook (const Bundle & inBundle) static
Returns true if inBundle contains a help book.
Parameters
inBundle The bundle in which to look for a help book name.
References B::String::empty(), and B::Bundle::GetHelpBook().
void B::HelpUtilities::RegisterHelpBook (const Bundle & inBundle) static
Registers the help book in inBundle.
Parameters
inBundle The bundle to register. It's assumed to contain a help book.
References B::Bundle::Location().
void B::HelpUtilities::GotoPage (const Bundle & inBundle, const Url & inUrl) static
Displays the page in inBundle's help book that is identified by inUrl.
inUrl is assumed to contain a relative file URL, and may optionally contain a fragment which identifies the anchor to display.
Parameters
inBundle The bundle containing the help book in which to look for inUrl.
inUrl The url for the page.
References B::Bundle::GetHelpBook(), and GotoPage().
void B::HelpUtilities::GotoPage (const String & inBookName, const Url & inUrl) static
Displays the page in help book inBookName that is identified by inUrl.
inUrl is assumed to contain a file URL relative to the help book's location, and may optionally contain a fragment which identifies the anchor to display.
Parameters
inBookName The help book in which to look for inUrl.
inUrl The url for the page.
References GotoPage().
void B::HelpUtilities::GotoPage (const String & inBookName, const String & inPath, const String & inAnchor) static
Displays the page in help book inBookName that is identified by inPath and inAnchor.
Parameters
inBookName The help book in which to look for inUrl.
inPath The path of the help page, relative to the help book's location.
inAnchor The anchor within the page.
References B::String::cf_ref(), and B::String::empty().
void B::HelpUtilities::GotoTOC (AHTOCType inTOCType = kAHTOCTypeUser) static
Parameters
inTOCType The table-of-contents to display.
void B::HelpUtilities::Search (const String & inSearchText) static
Searches for occurrences of inSearchText within the main bundle's help book.
Parameters
inSearchText The text to search for.
References B::Bundle::Main().
Referenced by Search().
void B::HelpUtilities::Search (const Bundle & inBundle, const String & inSearchText) static
Searches for occurrences of inSearchText within inBundle's help book.
Parameters
inBundle The bundle containing the help book in which to look for inSearchText.
inSearchText The text to search for.
References B::Bundle::GetHelpBook(), and Search().
void B::HelpUtilities::Search (const String & inBookName, const String & inSearchText) static
Searches for occurrences of inSearchText within the help book inBookName.
Parameters
inBookName The help book in which to look for inSearchText.
inSearchText The text to search for.
References B::String::cf_ref().
void B::HelpUtilities::SearchAll (const String & inSearchText) static
Searches for occurrences of inSearchText within all registered help books.
Parameters
inSearchText The text to search for.
References B::String::cf_ref().
void B::HelpUtilities::Lookup (const String & inAnchor) static
Searches for anchors matching inAnchor within the main bundle's help book.
Parameters
inAnchor The anchor to look for.
References B::Bundle::Main().
Referenced by Lookup().
void B::HelpUtilities::Lookup (const Bundle & inBundle, const String & inAnchor) static
Searches for anchors matching inAnchor within inBundle's help book.
Parameters
inBundle The bundle containing the help book in which to look for inAnchor.
inAnchor The anchor to look for.
References B::Bundle::GetHelpBook(), and Lookup().
void B::HelpUtilities::Lookup (const String & inBookName, const String & inAnchor) static
Searches for anchors matching inAnchor within the help book inBookName.
Parameters
inBookName The help book in which to look for inAnchor.
inAnchor The anchor to look for.
References B::String::cf_ref().
void B::HelpUtilities::LookupAll (const String & inAnchor) static
Searches for anchors matching inAnchor within all registered help books.
Parameters
inAnchor The anchor to look for.
References B::String::cf_ref().
The documentation for this class was generated from the following files:
BHelpUtilities.h
BHelpUtilities.cpp