B: B::AEObjectSupport Class Reference
B::AEObjectSupport Class Reference
Apple Events
This class provides essential support for the Apple Event Object Model (AEOM) in the B framework.
#include <BAEObjectSupport.h>
Classes
class ObjectResolutionException
Public Member Functions
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void ForwardDefaultEvent (const AEDesc &, const AppleEvent &inEvent, AEWriter &ioResultWriter, OBJ *inObj, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void ForwardDefaultEventWithDirectObj (const AEDesc &inDirectObject, const AppleEvent &inEvent, AEWriter &ioResultWriter, OBJ *inObj, void(OBJ::*inObjMember)(const AEDesc &, AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void ForwardClassEvent (const AEToken &inToken, const AppleEvent &inEvent, AEWriter &ioResultWriter, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void ForwardClassEventToObject (const AppleEvent &inEvent, AEWriter &ioResultWriter, OBJ *inObj, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
Constructor / Destructor
AEObjectSupport ()
Constructor.
virtual ~AEObjectSupport ()
Destructor.
Event Registration
virtual void DefineEvent (AEEventClass inEventClass, AEEventID inEventID, AEInfo::EventDOBehavior inEventDOBehavior, AEInfo::EventResultAction inEventResultAction, AEInfo::DefaultEventHandler inHandler)
Tells AEObjectSupport to install an Apple Event handler for a given event.
void DefineEvent (AEEventClass inEventClass, AEEventID inEventID, AEInfo::EventDOBehavior inEventDOBehavior, AEInfo::EventResultAction inEventResultAction)
void DefineEvent (AEEventClass inEventClass, AEEventID inEventID)
virtual bool IsEventDefined (AEEventClass inEventClass, AEEventID inEventID) const
Returns true if the given event is known to AEObjectSupport.
void SetClassEventHandler (DescType inClassID, AEEventClass inEventClass, AEEventID inEventID, AEInfo::ClassEventHandler inClassHandler)
Installs a handler for a given Apple Event and a given AEObject class.
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void SetClassEventHandler (DescType inClassID, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void SetClassEventHandler (OBJ *inObj, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void SetClassEventHandler (DescType inClassID, OBJ *inObj, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
void SetDefaultEventHandler (AEEventClass inEventClass, AEEventID inEventID, AEInfo::DefaultEventHandler inDefaultHandler)
Installs a default handler for a given Apple Event.
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void SetDefaultEventHandler (OBJ *inObj, void(OBJ::*inObjMember)(AEEvent< EVT_CLASS, EVT_ID > &))
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ >
void SetDefaultEventHandler (OBJ *inObj, void(OBJ::*inObjMember)(const AEDesc &, AEEvent< EVT_CLASS, EVT_ID > &))
Activating AEOM Support
void RegisterScriptingDefinitions (const Bundle &inBundle, const String &inSDefName=String())
Tell AEObjectSupport to read in the terminology.
Static Public Member Functions
Accessing The Sole Instance
static const AEObjectSupport & Get ()
Returns the AEObjectSupport singleton.
Friends
class ErrorDescLink
Comparison Registration
static bool CompareStrings (DescType inOperator, const String &inString1, const String &inString2)
Compare two strings according to inComparisonOp.
static bool CompareStrings (const String &inString1, const String &inString2)
Compare two strings for equality.
void SetComparer (DescType inDescriptorType, AEInfo::DescriptorComparer inComparer)
template<DescType TYPE>
void SetSimpleComparer (boost::function3< bool, DescType, typename DescParam< TYPE >::ValueType, typename DescParam< TYPE >::ValueType > inFunction)
template<DescType TYPE>
void SetNumericComparer ()
Utility
static AEObjectPtr Resolve (const AEDesc &inObjSpecifier)
Attempts to convert an Apple Event descriptor into an AEObject.
static OSStatus Resolve (const AEDesc &inObjSpecifier, AEObjectPtr &outObject)
static void AddCachedInfoToAppleEventReply (AppleEvent &ioReply, OSStatus status)
Serialises cached exception information into ioReply.
static void RethrowExceptionFromAppleEventReply (const AppleEvent &inReply, OSStatus inStatus)
Throws the exception contained in inReply.
static void CoerceDesc (const AEDesc &inObjectSpecifier, DescType inDesiredType, AEDesc &outDesc)
static void CoerceDesc (const AEDesc &inObjectSpecifier, DescType inDesiredType, void *outBuffer, size_t inBufferSize)
static OSStatus CoerceDesc (const AEDesc &inObjectSpecifier, DescType inDesiredType, AEDesc &outDesc, const std::nothrow_t &)
static OSStatus CoerceDesc (const AEDesc &inObjectSpecifier, DescType inDesiredType, void *outBuffer, size_t inBufferSize, const std::nothrow_t &)
bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID) const
Returns true if inClassID is or derives from inBaseClassID.
SInt32 CountAllElements (ConstAEObjectPtr inContainer) const
Convenient-but-inefficient way of counting all of an object's elements.
const AEInfo::ClassInfo * FindClassInfo (DescType inClassID) const
const AEInfo::ClassInfo & GetClassInfo (DescType inClassID) const
const AEInfo::PropertyInfo * FindPropertyInfo (const AEInfo::ClassInfo &inClass, DescType inPropertyName) const
const AEInfo::PropertyInfo & GetPropertyInfo (const AEInfo::ClassInfo &inClass, DescType inPropertyName) const
bool DoesCurrentEventContainHook (int key) const
void AddCurrentEventHook (int key, std::auto_ptr< AEEventHook > eventHook)
Detailed Description
This class provides essential support for the Apple Event Object Model (AEOM) in the B framework.
AEObjectSupport is class with which an application will interact directly mostly at application initialisation time. The interaction follows these phases:
Construction. AEObjectSupport is a singleton, so only one global instance may be created during the lifetime of the application.
Event Definition (optional). Here the caller may inform AEObjectSupport of any application-defined AppleEvents that it needs to be aware of (so it knows how do things like resolving the event direct parameter). AEObjectSupport contains built-in definitions for the vast majority of events in the Required, Core, and Miscellaneous Standards Suite, so this phase is only required when defining your own custom AppleEvents.
Event Handler Registration (optional). Most event handlers are class specific, however it may sometimes be convenient to register events that aren't tied to a class. This can happen if an Apple Event has no direct parameter, or if it's not of a type resolvable into an AEObject. One example is the "open" Apple Event taking a file as a direct parameter.
Class Registration. This involves getting the class to declare the information required by AEObjectSupport in order to properly dispatch events to instances of the class. This is typically done by calling Register().
Activation. The Start() function actually initialises MOSL, which in turn sets up the necessary Apple Event handlers and object accessors.
Steady state. Once AEObjectSupport has been started, the application can receive AppleEvents and resolve object specifiers. The application typically doesn't interact directly with it any more.
Todo:
Complete documentation
Member Function Documentation
void B::AEObjectSupport::DefineEvent (AEEventClass inEventClass, AEEventID inEventID, AEInfo::EventDOBehavior inEventDOBehavior, AEInfo::EventResultAction inEventResultAction, AEInfo::DefaultEventHandler inHandler) virtual
Tells AEObjectSupport to install an Apple Event handler for a given event.
Parameters
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
inEventDOBehavior Determines how we handle the direct parameter.
inEventResultAction Determines how we handle the result.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::AEObjectSupport::DefineEvent (AEEventClass inEventClass, AEEventID inEventID, AEInfo::EventDOBehavior inEventDOBehavior, AEInfo::EventResultAction inEventResultAction)
Parameters
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
inEventDOBehavior Determines how we handle the direct parameter.
inEventResultAction Determines how we handle the result.
void B::AEObjectSupport::DefineEvent (AEEventClass inEventClass, AEEventID inEventID)
Parameters
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
bool B::AEObjectSupport::IsEventDefined (AEEventClass inEventClass, AEEventID inEventID) const virtual
Returns true if the given event is known to AEObjectSupport.
Parameters
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::RegisterAppleEvents(), B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents(), and B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents().
void B::AEObjectSupport::SetClassEventHandler (DescType inClassID, AEEventClass inEventClass, AEEventID inEventID, AEInfo::ClassEventHandler inClassHandler)
Installs a handler for a given Apple Event and a given AEObject class.
Parameters
inClassID The class ID of the handler.
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
inClassHandler The callback.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents(), B::AEObject::Resolve(), and SetClassEventHandler().
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ > void B::AEObjectSupport::SetClassEventHandler (DescType inClassID, void(OBJ::*)(AEEvent< EVT_CLASS, EVT_ID > &) inObjMember)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows your class to register a callback for handling an Apple Event. The particular event is identified by the EVT_CLASS and EVT_ID template parameters.
Call this function if the Apple Event in question takes a direct parameter. The callback, inObjMember, will point to a member function of class OBJ, and will take as its sole argument a template instantiation of AEEvent for EVT_OBJ and EVT_ID.
The target object (the one used to call the member function) will be obtained by resolving the event's direct parameter, which is why this function is only suitable for Apple Events that take object-specifier direct parameters.
Parameters
EVT_CLASS Template parameter. The Apple Event class of the event.
EVT_ID Template parameter. The Apple Event id of the event.
OBJ Template parameter. The class of the object that will handle the event. This should be a derivative of AEObject.
Parameters
inClassID The class ID of the handler.
inObjMember Pointer-to-member (from class OBJ) taking the template specialisation of AEEvent<EVT_OBJ, EVT_ID>.
References SetClassEventHandler().
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ > void B::AEObjectSupport::SetClassEventHandler (OBJ * inObj, void(OBJ::*)(AEEvent< EVT_CLASS, EVT_ID > &) inObjMember)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows your class to register a callback for handling an Apple Event. The particular event is identified by the EVT_CLASS and EVT_ID template parameters.
Call this function if the Apple Event in question does not take a direct parameter. The callback, inObjMember, will point to a member function of class OBJ, and will take as its sole argument a template instantiation of AEEvent for EVT_OBJ and EVT_ID.
The target object (the one used to call the member function) will be inObj, which is why this function is only suitable for AppleEvents that do not take object-specifier direct parameters.
Parameters
EVT_CLASS Template parameter. The Apple Event class of the event.
EVT_ID Template parameter. The Apple Event id of the event.
OBJ Template parameter. The class of the object that will handle the event. This should be a derivative of AEObject.
Parameters
inObj The default object (the one that will receive all the the events).
inObjMember Pointer-to-member (from class OBJ) taking the template specialisation of AEEvent<EVT_OBJ, EVT_ID>.
References SetClassEventHandler().
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ > void B::AEObjectSupport::SetClassEventHandler (DescType inClassID, OBJ * inObj, void(OBJ::*)(AEEvent< EVT_CLASS, EVT_ID > &) inObjMember)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Allows your class to register a callback for handling an Apple Event. The particular event is identified by the EVT_CLASS and EVT_ID template parameters.
Call this function if the Apple Event in question does not take a direct parameter. The callback, inObjMember, will point to a member function of class OBJ, and will take as its sole argument a template instantiation of AEEvent for EVT_OBJ and EVT_ID.
The target object (the one used to call the member function) will be inObj, which is why this function is only suitable for AppleEvents that do not take object-specifier direct parameters.
Parameters
EVT_CLASS Template parameter. The Apple Event class of the event.
EVT_ID Template parameter. The Apple Event id of the event.
OBJ Template parameter. The class of the object that will handle the event. This should be a derivative of AEObject.
Parameters
inClassID The class ID of the handler.
inObj The default object (the one that will receive all the the events).
inObjMember Pointer-to-member (from class OBJ) taking the template specialisation of AEEvent<EVT_OBJ, EVT_ID>.
References SetClassEventHandler().
void B::AEObjectSupport::SetDefaultEventHandler (AEEventClass inEventClass, AEEventID inEventID, AEInfo::DefaultEventHandler inDefaultHandler)
Installs a default handler for a given Apple Event.
Parameters
inEventClass The Apple Event's class.
inEventID The Apple Event's ID.
inDefaultHandler The callback.
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::RegisterAppleEvents(), and SetDefaultEventHandler().
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ > void B::AEObjectSupport::SetDefaultEventHandler (OBJ * inObj, void(OBJ::*)(AEEvent< EVT_CLASS, EVT_ID > &) inObjMember)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References SetDefaultEventHandler().
template<AEEventClass EVT_CLASS, AEEventID EVT_ID, class OBJ > void B::AEObjectSupport::SetDefaultEventHandler (OBJ * inObj, void(OBJ::*)(const AEDesc &, AEEvent< EVT_CLASS, EVT_ID > &) inObjMember)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::DescParam< TYPE >::Get(), and SetDefaultEventHandler().
bool B::AEObjectSupport::CompareStrings (DescType inComparisonOp, const String & inString1, const String & inString2) static
Compare two strings according to inComparisonOp.
The strings are compared in an AppleScript-like fashion (case-insensitive, localised, etc).
References B::String::cf_ref(), B::AEDescriptor::Clear(), B::AEWriter::Close(), B::AEWriter::CloseList(), B::AEDescriptor::Empty(), B::DescParam< TYPE >::Get(), B::AEDescriptor::GetType(), B::AEWriter::OpenList(), and B::AEWriter::WriteDesc().
Referenced by B::AEObject::GetElementByName(), and B::Window::SetIdealSize().
AEObjectPtr B::AEObjectSupport::Resolve (const AEDesc & inObjSpecifier) static
Attempts to convert an Apple Event descriptor into an AEObject.
If inObjSpecifier is a null descriptor, the function returns AEObject's default object; else, it attempts to resolve the descriptor.
Errors may be returned if resolution fails (eg the specifier names a non-existent object, or the descriptor isn't an object specifier at all).
Parameters
inObjSpecifier The Apple Event descriptor (hopefully containing an object specifier).
References B::AEObject::GetDefaultObject().
Referenced by B::DescParamHelper::GetCoercedData(), B::AEObject::Resolve(), and B::AEObject::ResolveBoundsToken().
OSStatus B::AEObjectSupport::Resolve (const AEDesc & inObjSpecifier, AEObjectPtr & outObject) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If inObjSpecifier is a null descriptor, the function returns AEObject's default object; else, it attempts to resolve the descriptor.
Errors may be returned if resolution fails (eg the specifier names a non-existent object, or the descriptor isn't an object specifier at all).
Parameters
inObjSpecifier The Apple Event descriptor (hopefully containing an object specifier).
References B::AEObject::GetDefaultObject().
bool B::AEObjectSupport::DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID) const
Returns true if inClassID is or derives from inBaseClassID.
Parameters
inClassID The class ID; must match the application's AppleScript dictionary.
inBaseClassID The base class ID; must match the application's AppleScript dictionary.
SInt32 B::AEObjectSupport::CountAllElements (ConstAEObjectPtr inContainer) const
Convenient-but-inefficient way of counting all of an object's elements.
Parameters
inContainer The container.
References B::AEWriter::Close(), B::AEObject::DoesClassInheritFrom(), B::ErrorHandler::GetStatus(), and B::AEDescriptor::GetType().
Referenced by B::AEObject::CountElements().
const AEInfo::ClassInfo * B::AEObjectSupport::FindClassInfo (DescType inClassID) const
Given a class ID, return its class info object (or NULL).
const AEInfo::PropertyInfo * B::AEObjectSupport::FindPropertyInfo (const AEInfo::ClassInfo & inClass, DescType inPropertyName) const
Given a ClassInfo and a property name, return its property info object (or NULL). This function performs a lookup in the given class, as well as all of the class's ancestors.
const AEInfo::PropertyInfo & B::AEObjectSupport::GetPropertyInfo (const AEInfo::ClassInfo & inClass, DescType inPropertyName) const
Given a ClassInfo and a property name, return its property info object. If the property isn't found, an exception is thrown. This function performs a lookup in the given class, as well as all of the class's ancestors.
Referenced by B::AEObject::Resolve().
The documentation for this class was generated from the following files:
BAEObjectSupport.h
BAEObjectSupport.cpp