B: B::AbstractDocument Class Reference
B::AbstractDocument Class Reference abstract
The base class representing documents.
#include <BAbstractDocument.h>
Public Types
Types
typedef boost::signal0< void > VoidSignal
Shorthand for a type of signal used by this class.
typedef boost::signal1< void, AbstractDocument * > DocSignal
Shorthand for a type of signal used by this class.
Public Member Functions
virtual void MakeCurrent ()
virtual bool CloseDocument (OSType inSaveOption, const Url &inUrl=Url(), Window *inWindow=NULL)
virtual void Close ()
virtual void Quitting (OSType inSaveOption)
virtual void CancelQuitting ()
bool IsQuitting () const
Constructor & Destructor
AbstractDocument (AEObjectPtr inContainer, DescType inClassID, SInt32 inUniqueID)
Constructor.
Inquiries
virtual bool IsNew () const
Returns true is the document does not have a backing store.
virtual bool IsModified () const
Returns true if the document has any unsaved changes.
virtual void Modified ()
Registers a change to the document.
virtual void Unmodified ()
Unregisters a change to the document.
virtual SInt32 GetUniqueID () const
Returns the document's unique id. This id is not persistent.
virtual String GetName () const
Returns the document's name.
virtual String GetDisplayName () const
Returns the document's display name.
virtual OSType GetCreator () const
Returns the document's creator code.
EventTargetRef GetEventTarget () const
Returns the document's event target.
virtual String GetDocumentType () const =0
Returns the document's type.
virtual Url GetUrl () const =0
Returns the document's URL.
virtual bool OwnsWindow (const Window *inWindow) const =0
Returns true if inWindow belongs to the document. This is a pure virtual function, which all derived classes must override.
Initialisation
virtual void InitNewDocument (const String &inName, const String &inDocumentType, const AEDesc &inProperties, const AEDesc &inData, Nib *inNib)
Initialises a new document.
virtual void InitOpenDocument (const Url &inDocumentUrl, const String &inDocumentType, Nib *inNib, bool inForPrinting)
Initialises a document from the contents of a URL.
Overrides From AEObject
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
virtual void RevertObject ()
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
Signals
DocSignal & GetDirtyStateChangedSignal ()
Sent when the document becomes dirty (or clean). Usually due to model changes, or Save or Save As.
DocSignal & GetUrlChangedSignal ()
Sent when the document's URL has changed. Usually due to a Save or Save As.
DocSignal & GetContentChangedSignal ()
Sent when the document's content changes completely. Usually due to a Revert.
DocSignal & GetClosingSignal ()
Sent when the document is about to be closed.
VoidSignal & GetAsyncActionCancelledSignal ()
Sent when the user has cancelled an async action (i.e. Quit with multiple documents containing unsaved changes).
DocSignal & GetDeleteSignal ()
Sent when the the document should be deleted (IMPORTANT: only the document policy should be listening to this !!).
Public Member Functions inherited from B::AEObject
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual size_t CountElements (DescType inElementType) const
Returns the number of elements of the given class.
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
Returns the element of the given class with the given index.
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
Returns the element of the given class with the given unique ID.
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
Returns the element of the given class with the given name.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
Returns the AEObject matching a given property, if any.
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
Reads the value of the property identified by inPropertyID from ioReader.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
Implements the AppleScript "make" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void ActivateObject ()
Implements the AppleScript "activate" event.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
Protected Member Functions
virtual void MakeWindows (Nib *inNib)
virtual void ShowWindows ()
virtual void CloseWindows ()
virtual void InitDocument (const String &inName, const String &inDocumentType, const AEDesc &inProperties, const AEDesc &inData)
virtual void ReadDocument (const Url &inDocumentUrl, String &ioDocumentType)
virtual void DoneReading (const Url &inDocumentUrl, const String &inDocumentType)
virtual void CloseFiles ()
virtual bool AskUserToClose (bool inFromUser, Window *inWindow, NavAskSaveChangesAction inContext)
virtual bool AskUserToSave (SaveInfo &ioSaveInfo)
virtual bool AskUserToRevert (Window *inWindow)
virtual void DonePrinting ()
Utility
virtual void ClearModified ()
Forces the change count to zero.
virtual void NotifyContentChanged ()
Broadcasts the "content changed" signal.
virtual void NotifyUrlChanged ()
Broadcasts the "url changed" signal.
virtual void NotifyActionCancelled ()
Broadcasts the "async action cancelled" signal.
virtual void MakeSpecifier (AEWriter &ioWriter) const
Carbon Event handlers
!
virtual bool HandleCommand (const HICommandExtended &inHICommand, Window *inWindow=NULL)
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCommandData, Window *inWindow=NULL)
Protected Member Functions inherited from B::AEObject
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Friends
class EventHelper
Saving
virtual void SaveDocument (SaveInfo &ioInfo)
Saves the document.
virtual void RevertDocument ()
Reverts the document.
virtual void PrintDocument (PrintSettings *inPrintSettings, Printer *inPrinter, bool inShowDialog)
Prints the document.
virtual void WriteDocumentToUrl (SaveInfo &ioSaveInfo)
Saves the document to a new location or with a new type.
virtual void WriteDocument (SaveInfo &ioSaveInfo)
Saves the document to its current location and with its current type.
virtual void WriteComplete (const Url &inOldUrl, const String &inOldDocumentType)
Performs post-save tidying up.
Additional Inherited Members
Static Public Member Functions inherited from B::AEObject
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Static Protected Member Functions inherited from B::AEObject
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Related Functions inherited from B::AEObject
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Detailed Description
The base class representing documents.
Todo:
Complete documentation.
Constructor & Destructor Documentation
B::AbstractDocument::AbstractDocument (AEObjectPtr inContainer, DescType inClassID, SInt32 inUniqueID)
Constructor.
Parameters
inContainer The object's container (as seen in AppleScript).
inClassID The object's class ID; must match the application's AppleScript dictionary.
inUniqueID The document's unique id number.
Member Function Documentation
void B::AbstractDocument::Modified () virtual
Registers a change to the document.
If the change count goes from zero to non-zero (meaning that the document is becoming dirty), the function broadcasts the kDirtyStateChangeNotification notification.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality().
void B::AbstractDocument::Unmodified () virtual
Unregisters a change to the document.
If the change count goes from non-zero to zero (meaning that the document is becoming clean), the function broadcasts the kDirtyStateChangeNotification notification.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality().
SInt32 B::AbstractDocument::GetUniqueID () const virtual
Returns the document's unique id. This id is not persistent.
The document's id identifies it within the application; this is the value returned as the "id" property in AppleScript.
The default implementation returns id given when the document was constructed.
Reimplemented from B::AEObject.
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::CreateAskReviewDocumentsDialog(), MakeCurrent(), and PrintDocument().
String B::AbstractDocument::GetName () const virtual
Returns the document's name.
This is the string returned as the "name" property in AppleScript.
The default implementation returns the last portion of the document's url's path.
Reimplemented from B::AEObject.
References GetUrl().
Referenced by MakeCurrent().
String B::AbstractDocument::GetDisplayName () const virtual
Returns the document's display name.
The document's display name is what is shown to the user in window title bars, etc. It's different from the normal name because the Aqua HIG contains the notion of users being able to "hide" a file name's extension.
The default implementation calls through to the OS to compute the display name from the document's URL.
References GetUrl().
OSType B::AbstractDocument::GetCreator () const virtual
Returns the document's creator code.
The creator code is a way of tagging files as "belonging" to a given application. It's optional in Mac OS X, but was very much used in the pre-X days, so it can be convenient to set a file's creator for interoperability reasons.
The default implementation returns the main bundle's creator code.
References B::Bundle::Main().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentWriteStream().
virtual String B::AbstractDocument::GetDocumentType () const pure virtual
Returns the document's type.
The document type will normally be listed in the application's Info.plist file.
This is a pure virtual function, which all derived classes must override.
Referenced by CloseDocument(), MakeCurrent(), RevertDocument(), SaveDocument(), and WriteComplete().
virtual Url B::AbstractDocument::GetUrl () const pure virtual
Returns the document's URL.
This URL is used to identify the document within the B framework, so any data set describable by a URL can potentially be put in a document.
This is a pure virtual function, which all derived classes must override.
Referenced by CloseDocument(), B::MultipleDocumentPolicy< DOC_FACTORY >::CreateAskReviewDocumentsDialog(), GetDisplayName(), GetName(), IsNew(), MakeCurrent(), RevertDocument(), SaveDocument(), and WriteComplete().
void B::AbstractDocument::InitNewDocument (const String & inName, const String & inDocumentType, const AEDesc & inProperties, const AEDesc & inData, Nib * inNib) virtual
Initialises a new document.
The function takes the following steps:
Creates an initial data set for the document, using inProperties and inData as appropriate.
Creates the document's window(s).
Displays the window(s).
Parameters
inName The document's name.
inDocumentType The document's type.
inProperties The document's initial properties (if typeNull, no properties are specified).
inData The document's intrinsic data (if typeNull, no data is specified).
inNib The nib from which to instantiate the document's UI.
References NotifyContentChanged().
void B::AbstractDocument::InitOpenDocument (const Url & inDocumentUrl, const String & inDocumentType, Nib * inNib, bool inForPrinting) virtual
Initialises a document from the contents of a URL.
The function takes the following steps:
Creates an initial data set for the document from the contents of inDocumentUrl.
Creates the document's window(s).
If the document isn't being opened just for printing (i.e., inForPrinting is false), displays the window(s).
References NotifyContentChanged().
void B::AbstractDocument::SaveDocument (SaveInfo & ioInfo) virtual
Saves the document.
This is a high-level function that can be used to perform a "Save" or a "Save As", depending on the arguments. The function displays any necessary UI (putting up a Save sheet, for example), then calls lower-level functions to write out the document to a URL.
If the function is called with the default arguments, then it operates like a "Save". If it's is called with either a document type or a URL, then it operates like a "Save As". In either case, if the document has never been saved, it operates like a "Save As".
Note that it's possible for the file not to have been saved yet when this function returns. This can happen if the save requires user input, and that input is obtained via non-modal means such as a sheet.
Parameters
ioInfo The document's save information.
References AskUserToSave(), GetDocumentType(), GetUrl(), IsNew(), WriteComplete(), WriteDocument(), and WriteDocumentToUrl().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog(), and MakeCurrent().
void B::AbstractDocument::PrintDocument (PrintSettings * inPrintSettings, Printer * inPrinter, bool inShowDialog) virtual
Prints the document.
Parameters
inPrintSettings The print settings to use. May be NULL.
inPrinter The printer to print to. May be NULL.
inShowDialog Should we display the print dialog?
References B::AEObject::BuildUniqueIDSpecifier(), CloseDocument(), B::AEObject::GetClassID(), B::AEObject::GetContainer(), and GetUniqueID().
Referenced by PrintObject().
void B::AbstractDocument::MakeCurrent () virtual
Make this AbstractDocument the current one.
Override to do what makes sense for a particular kind of AbstractDocument. In most cases, this means selecting the main window for a AbstractDocument.
Reimplemented in B::Document< UNDO_POLICY, PRINT_POLICY >.
References AskUserToRevert(), AskUserToSave(), CloseDocument(), B::String::empty(), GetDocumentType(), GetName(), GetUniqueID(), GetUrl(), IsModified(), IsNew(), RevertDocument(), SaveDocument(), B::AEObject::SendSaveAppleEvent(), B::CommandData::SetEnabled(), B::AEWriter::Write(), and B::AEObject::WriteProperty().
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::QuitApplication().
bool B::AbstractDocument::CloseDocument (OSType inSaveOption, const Url & inUrl = Url(), Window * inWindow = NULL) virtual
Close a Document. The behaviour is largely determined by inSaveOption:
kAEYes: If inUrl isn't NULL, perform a "Save As"; else, if the document has been modified, perform a "Save". Then close the document.
kAENo: Close the document without saving.
kAEAsk: If the document isn't modified, close it without saving; else, ask the user what to do.
The function returns true if the close was completed prior to returning.
References AskUserToClose(), AskUserToSave(), GetDocumentType(), GetUrl(), IsModified(), IsNew(), WriteComplete(), WriteDocument(), and WriteDocumentToUrl().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::GetDocumentDialogModality(), MakeCurrent(), and PrintDocument().
void B::AbstractDocument::PrintObject (PrintSettings * inSettings, Printer * inPrinter, bool inShowDialog) virtual
Parameters
inSettings The print settings to use. May be NULL.
inPrinter The printer to print to. May be NULL.
inShowDialog Should we display the print dialog?
Reimplemented from B::AEObject.
References PrintDocument().
bool B::AbstractDocument::AskUserToClose (bool inFromUser, Window * inWindow, NavAskSaveChangesAction inContext) protected virtual
Returns
true if any UI has been confirmed or infirmed by the user (in other words, the UI was displayed modally); else @ false.
Referenced by CloseDocument(), and GetDeleteSignal().
bool B::AbstractDocument::AskUserToSave (SaveInfo & ioSaveInfo) protected virtual
Returns
true if any UI has been confirmed or infirmed by the user (in other words, the UI was displayed modally); else @ false.
Referenced by CloseDocument(), GetDeleteSignal(), MakeCurrent(), and SaveDocument().
bool B::AbstractDocument::AskUserToRevert (Window * inWindow) protected virtual
Returns
true if any UI has been confirmed or infirmed by the user (in other words, the UI was displayed modally); else @ false.
Referenced by GetDeleteSignal(), and MakeCurrent().
void B::AbstractDocument::WriteDocumentToUrl (SaveInfo & ioSaveInfo) protected virtual
Saves the document to a new location or with a new type.
Parameters
ioSaveInfo The document's save information.
Referenced by CloseDocument(), GetDeleteSignal(), and SaveDocument().
void B::AbstractDocument::WriteDocument (SaveInfo & ioSaveInfo) protected virtual
Saves the document to its current location and with its current type.
Parameters
ioSaveInfo The document's save information.
Referenced by CloseDocument(), GetDeleteSignal(), and SaveDocument().
void B::AbstractDocument::WriteComplete (const Url & inOldUrl, const String & inOldDocumentType) protected virtual
Performs post-save tidying up.
Currently, the function performs these actions:
Clears the change count, which will trigger a broadcast of the kDirtyStateChangeNotification notification.
Optionally clears the document's undo stack.
If the document's url or type has changed, issues the kUrlChangedNotification notification.
Derived classes that wish to perform additional operations when a document is saved should override this function.
References ClearModified(), GetDocumentType(), GetUrl(), and NotifyUrlChanged().
Referenced by CloseDocument(), B::Document< UNDO_POLICY, PRINT_POLICY >::CreateSaveDialog(), GetDeleteSignal(), and SaveDocument().
void B::AbstractDocument::ClearModified () protected virtual
Forces the change count to zero.
If the change count was previously non-zero, the function broadcasts the kDirtyStateChangeNotification notification.
Referenced by GetDeleteSignal(), B::Document< UNDO_POLICY, PRINT_POLICY >::OwnsFrontmostDocumentWindow(), and WriteComplete().
The documentation for this class was generated from the following files:
BAbstractDocument.h
BAbstractDocument.cpp