B: B::MultipleDocumentPolicy< DOC_FACTORY > Class Template Reference
B::MultipleDocumentPolicy< DOC_FACTORY > Class Template Reference
A document policy for applications supporting multiple open documents.
#include <BMultipleDocumentPolicy.h>
Public Types
Types
The document policy's document factory. Must conform to the DOC_FACTORY protocol.
typedef DOC_FACTORY FactoryType
See DOC_POLICY for description.
Public Member Functions
Constructor & Destructor
MultipleDocumentPolicy (AEObjectPtr inApplication, const Bundle &inBundle, Nib *inAppNib)
See DOC_POLICY for description.
virtual ~MultipleDocumentPolicy ()
See DOC_POLICY for description.
Setup
virtual void Init ()
See DOC_POLICY for description.
virtual void RegisterAppleEvents (AEObjectSupport &ioObjectSupport)
See DOC_POLICY for description.
Inquiries
FactoryType & GetFactory ()
Returns the document policy's document factory.
Apple Event Handlers
virtual void OpenApplication ()
See DOC_POLICY for description.
virtual void ReopenApplication ()
See DOC_POLICY for description.
virtual void QuitApplication (OSType inSaveOption=kAEAsk)
See DOC_POLICY for description.
virtual AEObjectPtr OpenNewDocument (DescType inDocClass, const AEDesc &inProperties, const AEDesc &inData)
See DOC_POLICY for description.
Document Access
virtual SInt32 CountDocuments (DescType inDocClass) const
See DOC_POLICY for description.
virtual AEObjectPtr GetDocumentByIndex (DescType inDocClass, unsigned inIndex) const
See DOC_POLICY for description.
virtual AEObjectPtr GetDocumentByName (DescType inDocClass, const String &inName) const
See DOC_POLICY for description.
virtual AEObjectPtr GetDocumentByUniqueID (DescType inDocClass, SInt32 inUniqueID) const
See DOC_POLICY for description.
Protected Member Functions
Nib * GetAppNib () const
virtual std::auto_ptr< GetFileDialog > CreateGetFileDialog (UInt32 inCommandID, const DialogModality &inModality)
Creates the "open file" dialog.
virtual std::auto_ptr< AskReviewDocumentsDialog > CreateAskReviewDocumentsDialog (const DialogModality &inModality, UInt32 inDocumentCount)
virtual void OpenDocument (const AEDesc &inDirectObject, AEEvent< kCoreEventClass, kAEOpenDocuments > &ioEvent)
virtual void PrintDocument (const AEDesc &inDirectObject, AEEvent< kCoreEventClass, kAEPrintDocuments > &ioEvent)
virtual bool HandleCommand (const HICommandExtended &inHICommand)
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
virtual void HandleGetFileResult (bool inGood, const NavReplyRecord &inNavReply)
virtual void AddDocument (boost::shared_ptr< AbstractDocument > inDocumentPtr)
virtual void RemoveDocument (AbstractDocument *inDocument)
void AddRecentDocument (AbstractDocument *inDocument)
virtual void AddRecentDocumentUrl (const Url &inUrl)
virtual void ClearRecentDocuments ()
void ReadRecentDocuments ()
void SaveRecentDocuments ()
void SendOpenDocumentsAppleEvent (const AEDescList &inDocList)
void SendOpenDocumentAppleEvent (const Url &inUrl)
virtual void GetInfoForNewDocument (UInt32 inCommand, DescType &outClass, AEDesc &outProperties, AEDesc &outData)
String CreateUniqueDocumentName (const String &inTemplate1, const String &inTemplate2, const String &inExtension)
String CreateNewDocumentName (const String &inTemplate1, const String &inTemplate2, int inIndex, const String &inExtension)
UInt32 CountModifiedDocuments () const
UInt32 CountUnsavedModifiedDocuments () const
template<class PRED >
UInt32 CountDocumentsMatching (PRED pred) const
template<class PRED >
AbstractDocument * FindDocumentMatching (PRED pred) const
DescType FindDefaultDocClass () const
OSType FindDefaultFileTypeForDocClass (DescType inDocClass) const
String FindDefaultExtensionForDocClass (DescType inDocClass) const
void DocumentClosing (AbstractDocument *inDocument)
void DocumentDelete (AbstractDocument *inDocument)
void DocumentUrlChanged (AbstractDocument *inDocument)
void DocumentAsyncActionCancelled ()
Detailed Description
template<class DOC_FACTORY>
class B::MultipleDocumentPolicy< DOC_FACTORY >
A document policy for applications supporting multiple open documents.
Use it as the DOC_POLICY template parameter of Application.
See also
DOC_POLICY.
Todo:
Complete documentation.
Member Function Documentation
template<class DOC_FACTORY > void B::MultipleDocumentPolicy< DOC_FACTORY >::OpenApplication () virtual
See DOC_POLICY for description.
Perform actions at application start up when launched without any documents.
Override if you wish to perform some default action, such as creating a new, untitled document
template<class DOC_FACTORY > void B::MultipleDocumentPolicy< DOC_FACTORY >::ReopenApplication () virtual
See DOC_POLICY for description.
Respond to Reopen Application Apple Event
The system sends the reopen application Apple Event when the user resumes an application that has no open windows.
References B::MultipleDocumentPolicy< DOC_FACTORY >::CreateGetFileDialog(), B::NavDialog::Enter(), and B::DialogModality::Modal().
template<class DOC_FACTORY > AEObjectPtr B::MultipleDocumentPolicy< DOC_FACTORY >::OpenNewDocument (DescType inDocClass, const AEDesc & inProperties, const AEDesc & inData) virtual
See DOC_POLICY for description.
Create a new AbstractDocument and pass back an Apple Event Model object representing that AbstractDocument
References BLocalizedStringFromTable, B::Bundle::end(), B::Bundle::FindDocumentTypeByOSAClass(), B::Bundle::FindDocumentTypeForUrl(), and B::DOC_FACTORY::Instantiate().
template<class DOC_FACTORY > std::auto_ptr< GetFileDialog > B::MultipleDocumentPolicy< DOC_FACTORY >::CreateGetFileDialog (UInt32 inCommandID, const DialogModality & inModality) protected virtual
Creates the "open file" dialog.
The default implementation activates the file type pop-up menu if the document policy's bundle contains more than one document type.
References B::MultipleDocumentPolicy< DOC_FACTORY >::SendOpenDocumentsAppleEvent().
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::ReopenApplication().
template<class DOC_FACTORY > std::auto_ptr< AskReviewDocumentsDialog > B::MultipleDocumentPolicy< DOC_FACTORY >::CreateAskReviewDocumentsDialog (const DialogModality & inModality, UInt32 inDocumentCount) protected virtual
The dialog must be configured to be application-modal.
References B::MutableArray< T >::cf_ptr(), B::String::cf_ref(), B::AbstractDocument::GetAsyncActionCancelledSignal(), B::AbstractDocument::GetClosingSignal(), B::AbstractDocument::GetDeleteSignal(), B::AbstractDocument::GetUniqueID(), B::AbstractDocument::GetUrl(), B::AbstractDocument::GetUrlChangedSignal(), B::MutableArray< T >::push_back(), B::MultipleDocumentPolicy< DOC_FACTORY >::QuitApplication(), and B::MultipleDocumentPolicy< DOC_FACTORY >::SendOpenDocumentAppleEvent().
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::QuitApplication().
template<class DOC_FACTORY > void B::MultipleDocumentPolicy< DOC_FACTORY >::SendOpenDocumentsAppleEvent (const AEDescList & inDocList) protected
Self-send an Apple Event to open a list of documents.
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::CreateGetFileDialog().
template<class DOC_FACTORY > void B::MultipleDocumentPolicy< DOC_FACTORY >::SendOpenDocumentAppleEvent (const Url & inUrl) protected
Self-send an Apple Event to open a single document.
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::CreateAskReviewDocumentsDialog().
The documentation for this class was generated from the following files:
BMultipleDocumentPolicy.h
BMultipleDocumentPolicy.tpl.h