B: B::AskDiscardChangesDialog Class Reference
B::AskDiscardChangesDialog Class Reference
Implements the standard "Discard Changes" alert.
#include <BNavDialogs.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Member Functions
Setup
template<class ASK_DISCARD_CHANGES_DIALOG >
void SetCallback (B_ASKDISCARDCHANGES_CB inFunction)
Sets the dialog's callback.
Retrieving Results
bool GetAction () const
Returns true if the user clicked the Discard button. Only useful in app-modal scenario.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Static Public Member Functions
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
template<class ASK_DISCARD_CHANGES_DIALOG >
static std::auto_ptr< ASK_DISCARD_CHANGES_DIALOG > Make (const DialogModality &inModality, const String &inFileName, B_ASKDISCARDCHANGES_CB inFunction=NullCallback< ASK_DISCARD_CHANGES_DIALOG >())
Instantiates and returns a ASK_DISCARD_CHANGES_DIALOG with the given arguments.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class ASK_DISCARD_CHANGES_DIALOG >
static void Start (const DialogModality &inModality, const String &inFileName, B_ASKDISCARDCHANGES_CB inFunction=NullCallback< ASK_DISCARD_CHANGES_DIALOG >())
Instantiates an ASK_DISCARD_CHANGES_DIALOG with the given arguments, then enters it.
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Protected Member Functions
AskDiscardChangesDialog ()
Protected default constructor to discourage stack-based instantiation.
void Configure (const DialogModality &inModality, const String &inFileName)
Helper function for configuring the dialog.
Overrides from NavDialog
virtual NavDialogRef CreateDialog ()
virtual void HandleUserAction (NavUserAction inUserAction)
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual void DialogStarting (NavCBRec &ioParams)
Override this to do some processing after the dialog is created and initialised, but before it's displayed.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
Low-level function to handle Nav dialog events. There's normally no need to override this function.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Running Dialogs
These are convenience functions for displaying nav dialogs in an application-modal fashion. Because they don't return until the nav dialog is dismissed, the chosen action is returned as the function result.
bool Run ()
Displays the nav dialog in an application-modal fashion.
template<class ASK_DISCARD_CHANGES_DIALOG >
static bool Run (const String &inFileName)
Instantiates an ASK_SAVE_CHANGES_DIALOG, then enters a modal event loop for it.
Additional Inherited Members
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Detailed Description
Implements the standard "Discard Changes" alert.
This dialog is useful for implementing the Revert command.
Beyond the usual DialogModality and callback arguments, the Make/Start/Run functions also take as an argument the display name of the file that's about to be closed. The dialog returns true if the user clicked the Discard button; else it returns false.
See also
Dialogs, Alerts and Navigation Services
Member Function Documentation
template<class ASK_DISCARD_CHANGES_DIALOG > void B::AskDiscardChangesDialog::SetCallback (B_ASKDISCARDCHANGES_CB inFunction)
Sets the dialog's callback.
Todo:
Complete this!
Parameters
ASK_DISCARD_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskDiscardChangesDialog or a class derived from AskDiscardChangesDialog.
bool B::AskDiscardChangesDialog::GetAction () const
Returns true if the user clicked the Discard button. Only useful in app-modal scenario.
Only useful in app-modal scenario.
References B::NavDialog::GetCreationOptions(), B::NavDialog::GetEventContext(), B::NavDialog::GetEventUPP(), and B::NavDialog::GetUserAction().
template<class ASK_DISCARD_CHANGES_DIALOG > std::auto_ptr< ASK_DISCARD_CHANGES_DIALOG > B::AskDiscardChangesDialog::Make (const DialogModality & inModality, const String & inFileName, B_ASKDISCARDCHANGES_CB inFunction = NullCallback<ASK_DISCARD_CHANGES_DIALOG>()) static
Instantiates and returns a ASK_DISCARD_CHANGES_DIALOG with the given arguments.
Instantiates a dialog of class ASK_DISCARD_CHANGES_DIALOG. The instance of ASK_DISCARD_CHANGES_DIALOG is then configured with the given arguments. Finally the dialog is returned, ready to be displayed via Enter().
Parameters
ASK_DISCARD_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskDiscardChangesDialog or a class derived from AskDiscardChangesDialog.
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to revert.
inFunction A callback that is invoked when the dialog is dismissed.
template<class ASK_DISCARD_CHANGES_DIALOG > void B::AskDiscardChangesDialog::Start (const DialogModality & inModality, const String & inFileName, B_ASKDISCARDCHANGES_CB inFunction = NullCallback<ASK_DISCARD_CHANGES_DIALOG>()) static
Instantiates an ASK_DISCARD_CHANGES_DIALOG with the given arguments, then enters it.
Instantiates a nav dialog of class ASK_DISCARD_CHANGES_DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog, call Make() then Enter().
Parameters
ASK_DISCARD_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskDiscardChangesDialog or a class derived from AskDiscardChangesDialog.
See also
Make(), NavDialog::Enter()
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to save.
inFunction A callback that is invoked when the dialog is dismissed.
bool B::AskDiscardChangesDialog::Run ()
Displays the nav dialog in an application-modal fashion.
Returns
true if the user clicked the Discard button.
References B::NavDialog::RunDialog().
template<class ASK_DISCARD_CHANGES_DIALOG > bool B::AskDiscardChangesDialog::Run (const String & inFileName) static
Instantiates an ASK_SAVE_CHANGES_DIALOG, then enters a modal event loop for it.
Instantiates a nav dialog of class ASK_DISCARD_CHANGES_DIALOG, as per Make(). Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
ASK_DISCARD_CHANGES_DIALOG Template parameter. The class of the instantiated window. Must be AskDiscardChangesDialog or a class derived from AskDiscardChangesDialog.
Returns
true if the user clicked the Discard button.
See also
Make(), Run()
Parameters
inFileName The display name of the file we're being asked to save.
References B::DialogModality::Modal().
void B::AskDiscardChangesDialog::HandleUserAction (NavUserAction inUserAction) protected virtual
Parameters
inUserAction The user action.
Implements B::NavDialog.
void B::AskDiscardChangesDialog::Configure (const DialogModality & inModality, const String & inFileName) protected
Helper function for configuring the dialog.
Parameters
inModality The dialog's modality.
inFileName The display name of the file we're being asked to revert.
References B::NavDialog::SetFileName(), and B::NavDialog::SetModality().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp