B: B::ViewFactory Class Reference
B::ViewFactory Class Reference
Views
Instantiates subclasses of View that match a given HIViewRef.
#include <BViewFactory.h>
Public Types
Types
typedef View *(* FactoryProc) (HIViewRef inViewRef)
The factory function prototype.
Public Member Functions
Constructor / Destructor
ViewFactory ()
Default constructor.
Inquiries
bool IsDefault () const
Is this the default view factory?
Registration
template<class VIEW >
void Register (CFStringRef inClassID, SInt32 inID)
Registers the class VIEW for HIViewRefs with the given class ID and inID.
template<class VIEW >
void Register (CFStringRef inClassID)
Registers the class VIEW for HIViewRefs with the given class ID and any id.
void Register (CFStringRef inClassID, const HIViewID &inID, FactoryProc inProc)
Registers inProc for HIViewRefs identified by inClassID and inID.
void Unregister (CFStringRef inClassID, const HIViewID &inID)
Unregisters HIViewRefs identified by inClassID and inID.
Instantiation
View * Instantiate (HIViewRef inViewRef) const
Creates a View object tied to inViewRef.
Static Public Member Functions
Default Factory
static ViewFactory & Default ()
Returns the singleton default view factory.
Defaults
static OSType GetDefaultSignature ()
Returns the default signature.
static void SetDefaultSignature (OSType inSig)
Sets the default signature.
static FactoryProc GetDefaultFactoryProc ()
Returns the default factory function.
static void SetDefaultFactoryProc (FactoryProc inProc)
Sets the default factory function.
Detailed Description
Instantiates subclasses of View that match a given HIViewRef.
ViewFactory manages a set of triples <ControlKind, HIViewID, FactoryProc>. ControlKind identifies the type of view, eg push button, scroll bar, etc. HIViewID identifies a particular view within a window. Finally, FactoryProc is a function that instantiates a C/C++ object (derived from View) appropriate for the ControlKind / HIViewID pair.
ViewFactory maintains a singleton instance of itself, called the default view factory. It contains application-wide triples. This allows triples for a specific context (such as a particular window) to be isolated from more general- purpose triples.
A ViewFactory is initialised by calling its Register() member functions. They construct the collection of triples. Once initialised, View objects are instantiated by calling the Instantiate() member function.
Instantiate() works by attempting to find a match in its collection of triples for the HIViewRef it's given as an argument. It starts by looking for a complete match on the HIViewRef's ControlKind and HIViewID. If no match is found, it looks for a partial match on ControlKind and HIViewID.id. If no match is found, it looks for a partial match on ControlKind only. If there is still no match, the process is repeated with the default view factory. At the end of all this, if there was a match, then the matched triple's FactoryProc is called to instantiate the view object; else, a default function is called instead.
Member Typedef Documentation
typedef View*(* B::ViewFactory::FactoryProc) (HIViewRef inViewRef)
The factory function prototype.
The function takes an existing HIToolbox view (aka HIViewRef) and instantiates a subclass of View tied to it.
Parameters
inViewRef The HIViewRef.
Returns
The newly instantiated View. Never returns NULL (an exception is thrown if something goes wrong).
Member Function Documentation
template<class VIEW > void B::ViewFactory::Register (CFStringRef inClassId, SInt32 inViewId)
Registers the class VIEW for HIViewRefs with the given class ID and inID.
Parameters
VIEW Template parameter. The C/C++ class of the view object. Must be View or a class derived from View.
Use this function when registering a View subclass for a specific view (which is usually, but not necessarily, in a specific window).
Because this function uses the default signature, it needs to have been set prior to calling this function.
Class VIEW needs the following members:
// The factory function.
static View*    Instantiate(HIViewRef inViewRef);
Parameters
inClassId The view's class ID.
inViewId The view's ID.
Referenced by Register().
template<class VIEW > void B::ViewFactory::Register (CFStringRef inClassId)
Registers the class VIEW for HIViewRefs with the given class ID and any id.
Parameters
VIEW Template parameter. The C/C++ class of the view object. Must be View or a class derived from View.
Use this function when registering a View subclass for all HIViewRefs matching VIEW's class ID.
Class VIEW needs the following members:
// The factory function.
static View*    Instantiate(HIViewRef inViewRef);
Parameters
inClassId The view's class ID.
References Register().
View * B::ViewFactory::Instantiate (HIViewRef inViewRef) const
Creates a View object tied to inViewRef.
Returns
The newly instantiated View. Never returns NULL (an exception is thrown if something goes wrong).
References Default(), B::View::GetViewFromRef(), and IsDefault().
Referenced by B::Window::operator delete(), B::NavReplyDialog::Preview(), and B::PredefinedView::SetupView().
void B::ViewFactory::SetDefaultSignature (OSType inSig) static
Sets the default signature.
The default signature is used when registering View subclasses by ID only. It allows registration code to be more concise, by avoiding having to pass in the signature of each View instance.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
void B::ViewFactory::SetDefaultFactoryProc (FactoryProc inProc) static
Sets the default factory function.
The default factory is used when no matching factory function has been found for a given HIViewRef. It's meant to be a factory of last resort.
The documentation for this class was generated from the following files:
BViewFactory.h
BViewFactory.cpp