B: B::Bundle Class Reference
B::Bundle Class Reference
Wrapper class around CFBundle.
#include <BBundle.h>
Classes
struct DocumentType
Public Types
typedef std::vector< DocumentType > DocumentTypeArray
typedef DocumentTypeArray::const_iterator Iterator
Used to iterate over the CFBundleDocumentTypes array.
Public Member Functions
Constructors & Destructor
Bundle ()
Default constructor. Initialises itself with the main bundle.
Bundle (const Bundle &bundle)
Copy constructor.
Bundle (const Url &url)
Creates a bundle from the given url.
Bundle (const String &identifier)
Initialises itself with the bundle having the given identifer.
Bundle (OSPtr< CFBundleRef > cfbundle)
Initialises itself with the OSPtr<CFBundleRef>.
Bundle (CFBundleRef cfbundle)
Initialises itself with the CFBundleRef.
Bundle (CFBundleRef cfbundle, const from_copy_t &)
Initialises itself with the CFBundleRef.
~Bundle ()
Destructor. Releases the underlying CFBundleRef.
Assignment
Bundle & operator= (const Bundle &bundle)
Assignment operator.
Bundle & operator= (const Url &url)
Bundle & operator= (const String &identifier)
Bundle & operator= (OSPtr< CFBundleRef > cfbundle)
Bundle & Assign (const Bundle &bundle)
Assignment. The new bundle is retained, and the old one is released.
Bundle & Assign (const Url &url)
Bundle & Assign (const String &identifier)
Bundle & Assign (OSPtr< CFBundleRef > cfbundle)
Bundle & Assign (CFBundleRef cfbundle)
Bundle & Assign (CFBundleRef cfbundle, const from_copy_t &)
void swap (Bundle &bundle)
Exchange the contents of two bundles.
Bundle Identification
String Identifier () const
Returns the bundle's unique identifier.
OSType PackageCreator () const
Returns the bundle's creator.
OSType PackageType () const
Returns the bundle's file type.
Info.plist keys
String Name () const
Returns the bundle's name.
String ExecutableName () const
Returns the name of the bundle's executable.
UInt32 BuildNumber () const
Returns the bundle's version.
String DevelopmentRegion () const
Returns the bundle's development region.
String DictionaryVersion () const
Returns the bundle's dictionary version.
OSPtr< CFArrayRef > GetDocumentTypes () const
Returns the bundle's document types array.
String Copyright () const
String GetInfo () const
String GetInfoHTML () const
String ShortVersionString () const
String GetHelpBook () const
String MainNib () const
Returns the name of the application's main nib file (minus the .nib extension).
String InfoString (CFStringRef inKey) const
Returns a string-valued property list key.
template<typename T >
OSPtr< T > InfoKey (CFStringRef inKey) const
Returns a property list key, cast to the given type.
Locations Within The Bundle
Url Location () const
Returns the bundle's URL.
Url Resources () const
Returns the URL of the bundle's Resources directory.
Url PrivateFrameworks () const
Returns the URL of the bundle's PrivateFrameworks directory.
Url SharedFrameworks () const
Returns the URL of the bundle's SharedFrameworks directory.
Url SharedSupport () const
Returns the URL of the bundle's SharedSupport directory.
Url PlugIns () const
Returns the URL of the bundle's PlugIns directory.
Url Executable () const
Returns the URL of the bundle's executable.
Url AuxiliaryExecutable (const String &inName) const
Returns the URL of file name in the same directory as the bundle's executable.
Resources & Strings
Returns the Url of a file under the bundle's Resources directory with the given name and type in the given subDirectory.
Url Resource (const String &name, const String &type=String(), const String &subDirectory=String()) const
void Resources (std::vector< Url > &urls, const String &type, const String &subDirectory=String()) const
Fills urls with the Urls of all files under the bundle's Resources directory with the given type in the given subDirectory.
String GetLocalisedString (CFStringRef inKey, CFStringRef inValue, CFStringRef inTableName) const
Returns the localised version of inKey.
Conversions
CFBundleRef cf_ref () const
Returns the object's underlying CFBundleRef.
Comparisons
bool operator== (const Bundle &bundle) const
Tests two bundle objects for equality.
bool operator!= (const Bundle &bundle) const
Tests two bundle objects for inequality.
Static Public Member Functions
Singleton Access
static const Bundle & Main ()
Returns the "main" bundle.
static void SetMainBundle (const Bundle &inBundle)
Changes the "main" bundle.
Document Types
static Iterator FindDocumentTypeByOSAClass (Iterator inFirst, Iterator inLast, DescType inDocClass)
Returns the document type matching inDocClass.
static Iterator FindDocumentTypeForUrl (Iterator inFirst, Iterator inLast, const Url &inUrl)
Returns the document type matching the extension and/or file type of inUrl.
static Iterator FindDocumentTypeForFileInfo (Iterator inFirst, Iterator inLast, CFStringRef inExtension, OSType inFileType)
Returns the document type matching inTypeName.
static Iterator FindDocumentTypeForMIMEType (Iterator inFirst, Iterator inLast, const String &inMIMEType)
Returns the document type matching inMIMEType.
static Iterator FindDocumentTypeForTypeName (Iterator inFirst, Iterator inLast, const String &inTypeName)
Returns the document type matching inTypeName.
static bool DoesFileInfoMatchDocumentType (CFStringRef inExtension, OSType inFileType, const DocumentType &inDocumentType)
Determines if inExtension or inFileType match inDocumentType.
static bool DoesMIMETypeMatchDocumentType (CFStringRef inMIMEType, const DocumentType &inDocumentType)
Determines if inMIMEType match inDocumentType.
static void MakeDocumentTypes (OSPtr< CFArrayRef > inDocumentTypesArray, std::vector< DocumentType > &outDocumentTypesVector)
Converts a document types array into a vector for DocumentType structures.
Iterator begin () const
Returns an iterator pointing to beginning of the DocumentType array.
Iterator end () const
Returns an iterator pointing to beginning of the DocumentType array.
Iterator FindDocumentTypeByOSAClass (DescType inDocClass) const
Returns the document type matching inDocClass.
Iterator FindDocumentTypeForUrl (const Url &inUrl) const
Returns the document type matching the extension and/or file type of inUrl.
Iterator FindDocumentTypeForFileInfo (CFStringRef inExtension, OSType inFileType) const
Returns the document type matching the given extension and/or filename.
Iterator FindDocumentTypeForMIMEType (const String &inMIMEType) const
Returns the document type matching inMIMEType.
Iterator FindDocumentTypeForTypeName (const String &inTypeName) const
Returns the document type matching inTypeName.
Detailed Description
Wrapper class around CFBundle.
The member functions essentially mirror the CFBundle API, except that arguments and returned values are higher-level (i.e. String instead of CFStringRef).
There are also quite a number of functions for enumerating the contents of the CFBundleDocumentTypes array. Elements of that array are returned as DocumentType structures, allowing for more convenient access.
A number of related #defines provide support for localised strings, and are designed to integrate with Apple's localisation tools such as genstrings. They are:
- #BLocalizedString
- #BLocalizedStringFromTable
- #BLocalizedStringFromTableInBundle
- #BLocalizedStringWithDefaultValue
Constructor & Destructor Documentation
B::Bundle::Bundle ()
Default constructor. Initialises itself with the main bundle.
Note that this retrieves the (pre-existing) main bundle, it doesn't create a new bundle.
B::Bundle::Bundle (const Bundle & bundle)
Copy constructor.
Parameters
bundle The source bundle.
B::Bundle::Bundle (const Url & url) explicit
Creates a bundle from the given url.
Will throw an exception if the bundle can't be created (perhaps because url is bogus or doesn't point at the right location or you don't have permission to access it).
Parameters
url The new bundle's location.
B::Bundle::Bundle (const String & identifier) explicit
Initialises itself with the bundle having the given identifer.
Note that this retrieves a pre-existing bundle, it doesn't create a new one.
Parameters
identifier The bundle's unique identifier.
References B::String::cf_ref().
B::Bundle::Bundle (OSPtr< CFBundleRef > cfbundle) explicit
Initialises itself with the OSPtr<CFBundleRef>.
Parameters
cfbundle A pre-existing bundle.
B::Bundle::Bundle (CFBundleRef cfbundle) explicit
Initialises itself with the CFBundleRef.
Parameters
cfbundle A pre-existing bundle.
B::Bundle::Bundle (CFBundleRef cfbundle, const from_copy_t &) explicit
Initialises itself with the CFBundleRef.
Parameters
cfbundle A pre-existing bundle.
Member Function Documentation
void B::Bundle::SetMainBundle (const Bundle & inBundle) static
Changes the "main" bundle.
Call this function when building a plug-in of some kind, where the CF main bundle (as returned by CFBundleGetMainBundle()) does not correspond to the bundle containing the executable of interest.
Note
This function must be called very early in the initialisation process, prior to anyone calling Bundle::Main().
Bundle & B::Bundle::operator= (const Url & url)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Assign().
Bundle & B::Bundle::operator= (const String & identifier)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Assign().
Bundle & B::Bundle::operator= (OSPtr< CFBundleRef > cfbundle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Assign().
Bundle & B::Bundle::Assign (const Url & url)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References swap().
Bundle & B::Bundle::Assign (const String & identifier)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References swap().
Bundle & B::Bundle::Assign (OSPtr< CFBundleRef > cfbundle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References swap().
Bundle & B::Bundle::Assign (CFBundleRef cfbundle)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References swap().
Bundle & B::Bundle::Assign (CFBundleRef cfbundle, const from_copy_t & fc)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References swap().
String B::Bundle::Identifier () const
Returns the bundle's unique identifier.
This is a required key, so the function should never fail for well-formed bundles.
String B::Bundle::Name () const
Returns the bundle's name.
This is a required key, so the function should never fail for well-formed bundles.
References InfoString().
Referenced by PackageType(), and B::AboutBox::~AboutBox().
String B::Bundle::ExecutableName () const
Returns the name of the bundle's executable.
This is a required key, so the function should never fail for well-formed bundles.
References InfoString().
Referenced by PackageType().
UInt32 B::Bundle::BuildNumber () const
Returns the bundle's version.
This is a required key, so the function should never fail for well-formed bundles.
Referenced by PackageType().
String B::Bundle::DevelopmentRegion () const
Returns the bundle's development region.
This is an optional key, so if it's absent the function returns an empty string.
Referenced by PackageType().
String B::Bundle::DictionaryVersion () const
Returns the bundle's dictionary version.
This is a required key, so the function should never fail for well-formed bundles.
References InfoString().
Referenced by PackageType().
OSPtr< CFArrayRef > B::Bundle::GetDocumentTypes () const
Returns the bundle's document types array.
This is an optional key, so if it's absent the function returns NULL.
Referenced by begin(), end(), and PackageType().
String B::Bundle::Copyright () const
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by PackageType(), and B::AboutBox::~AboutBox().
String B::Bundle::GetInfo () const
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by PackageType().
String B::Bundle::GetInfoHTML () const
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by PackageType().
String B::Bundle::ShortVersionString () const
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by PackageType(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication(), and B::AboutBox::~AboutBox().
String B::Bundle::GetHelpBook () const
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by B::Alert::Alert(), B::HelpUtilities::GotoPage(), B::HelpUtilities::HasHelpBook(), B::HelpButton::Instantiate(), B::HelpUtilities::Lookup(), PackageType(), and B::HelpUtilities::Search().
String B::Bundle::MainNib () const
Returns the name of the application's main nib file (minus the .nib extension).
This key is used primarily for Cocoa applications, but since we use nibs too then it's convenient for us to usurp it.
This is an optional key, so if it's absent the function returns an empty string.
References InfoString().
Referenced by PackageType().
String B::Bundle::InfoString (CFStringRef inKey) const
Returns a string-valued property list key.
If inKey is absent, the function returns an empty string.
Calling this function for a key that isn't a string results in undefined behaviour.
Parameters
inKey The key to look for.
References B::OSPtr< T >::get().
Referenced by Copyright(), DictionaryVersion(), ExecutableName(), GetHelpBook(), GetInfo(), GetInfoHTML(), MainNib(), Name(), PackageType(), and ShortVersionString().
template<typename T > OSPtr< T > B::Bundle::InfoKey (CFStringRef inKey) const
Returns a property list key, cast to the given type.
The function looks first in InfoPlist.strings, then in Info.plist. If inKey is absent, the function returns a NULL OSPtr.
Specifying a template type T that doesn't match the type of the key results in undefined behaviour.
Parameters
T Template parameter. A CoreFoundation type (i.e., one that responds properly to CFRetain() & CFRelease().
Parameters
inKey The key to look for.
Referenced by PackageType().
Url B::Bundle::Resources () const
Returns the URL of the bundle's Resources directory.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
Referenced by PackageType().
Url B::Bundle::PrivateFrameworks () const
Returns the URL of the bundle's PrivateFrameworks directory.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
Referenced by PackageType().
Url B::Bundle::SharedFrameworks () const
Returns the URL of the bundle's SharedFrameworks directory.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
Referenced by PackageType().
Url B::Bundle::SharedSupport () const
Returns the URL of the bundle's SharedSupport directory.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
Referenced by PackageType().
Url B::Bundle::PlugIns () const
Returns the URL of the bundle's PlugIns directory.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
Referenced by PackageType().
Url B::Bundle::AuxiliaryExecutable (const String & inName) const
Returns the URL of file name in the same directory as the bundle's executable.
This is strictly an operation on URLs. A succesful return doesn't imply that the directory actually exists.
References B::String::cf_ref().
Referenced by PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeByOSAClass (DescType inDocClass) const
Returns the document type matching inDocClass.
Returns end() if inDocClass couldn't be found.
Parameters
inDocClass The document class we're looking for.
References begin(), and end().
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::OpenNewDocument(), and PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeByOSAClass (Iterator inFirst, Iterator inLast, DescType inDocClass) static
Returns the document type matching inDocClass.
Returns inLast if inDocClass couldn't be found.
Parameters
inFirst The start of the sequence to look at.
inLast The end of the sequence to look at.
inDocClass The document class we're looking for.
Bundle::Iterator B::Bundle::FindDocumentTypeForUrl (const Url & inUrl) const
Returns the document type matching the extension and/or file type of inUrl.
Returns end() if a document type matching the extension and/or file file of inUrl couldn't be found.
Parameters
inUrl The url for which to find a matching document type.
References begin(), and end().
Referenced by B::MultipleDocumentPolicy< DOC_FACTORY >::OpenNewDocument(), and PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeForUrl (Iterator inFirst, Iterator inLast, const Url & inUrl) static
Returns the document type matching the extension and/or file type of inUrl.
Returns inLast() if a document type matching the extension and/or file file of inUrl couldn't be found.
Parameters
inFirst The start of the sequence to look at.
inLast The end of the sequence to look at.
inUrl The url for which to find a matching document type.
References FindDocumentTypeForFileInfo(), and B::OSPtr< T >::reset().
Bundle::Iterator B::Bundle::FindDocumentTypeForFileInfo (CFStringRef inExtension, OSType inFileType) const
Returns the document type matching the given extension and/or filename.
Returns end() if a document type matching inExtension and/or inFileType couldn't be found.
Parameters
inExtension The extension for which to find a matching document type. May be NULL.
inFileType The file type for which to find a matching document type.
References begin(), and end().
Referenced by B::GetFileDialog::FilterObjectByAllReadableFiles(), FindDocumentTypeForUrl(), and PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeForFileInfo (Iterator inFirst, Iterator inLast, CFStringRef inExtension, OSType inFileType) static
Returns the document type matching inTypeName.
Returns inLast() if a document type matching inExtension and/or inFileType couldn't be found.
Parameters
inFirst The start of the sequence to look at.
inLast The end of the sequence to look at.
inExtension The extension for which to find a matching document type. May be NULL.
inFileType The file type for which to find a matching document type.
Bundle::Iterator B::Bundle::FindDocumentTypeForMIMEType (const String & inMIMEType) const
Returns the document type matching inMIMEType.
Returns end() if a document type matching the MIME type inTypeName couldn't be found.
Parameters
inMIMEType The document type name we're looking for.
References begin(), and end().
Referenced by PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeForMIMEType (Iterator inFirst, Iterator inLast, const String & inMIMEType) static
Returns the document type matching inMIMEType.
Returns end() if a document type matching the MIME type inTypeName couldn't be found.
Parameters
inFirst The start of the sequence to look at.
inLast The end of the sequence to look at.
inMIMEType The document type name we're looking for.
Bundle::Iterator B::Bundle::FindDocumentTypeForTypeName (const String & inTypeName) const
Returns the document type matching inTypeName.
Returns end() if a document type matching the type name inTypeName couldn't be found.
Parameters
inTypeName The document type name we're looking for.
References begin(), and end().
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::MakeDocumentWriteStream(), and PackageType().
Bundle::Iterator B::Bundle::FindDocumentTypeForTypeName (Iterator inFirst, Iterator inLast, const String & inTypeName) static
Returns the document type matching inTypeName.
Returns end() if a document type matching the type name inTypeName couldn't be found.
Parameters
inFirst The start of the sequence to look at.
inLast The end of the sequence to look at.
inTypeName The document type name we're looking for.
void B::Bundle::MakeDocumentTypes (OSPtr< CFArrayRef > inDocumentTypesArray, std::vector< DocumentType > & outDocumentTypesVector) static
Converts a document types array into a vector for DocumentType structures.
Parameters
inDocumentTypesArray The array of document types entries.
outDocumentTypesVector The output DocumentType structures.
References B::String::cf_ref(), B::String::empty(), B::Bundle::DocumentType::mContentTypes, B::Bundle::DocumentType::mExportableTypes, B::Bundle::DocumentType::mExtensions, B::Bundle::DocumentType::mIconFile, B::Bundle::DocumentType::mIsPackage, B::Bundle::DocumentType::mMIMETypes, B::Bundle::DocumentType::mName, B::Bundle::DocumentType::mOSAClass, B::Bundle::DocumentType::mOSTypes, and B::Bundle::DocumentType::mRole.
Referenced by begin(), end(), and PackageType().
Url B::Bundle::Resource (const String & name, const String & type = String(), const String & subDirectory = String()) const
Parameters
name The resource's file name.
type If non-empty, specifies an extension for the file.
subDirectory If non-empty, specifies a subdirectory under Resources or Resources/<lang>.lproj
References B::String::cf_ref(), and B::String::empty().
Referenced by B::Toolbar::Initialize(), B::ToolbarItem::Initialize(), and PackageType().
void B::Bundle::Resources (std::vector< Url > & urls, const String & type, const String & subDirectory = String()) const
Fills urls with the Urls of all files under the bundle's Resources directory with the given type in the given subDirectory.
Parameters
type All of the returned files will have this extension.
subDirectory If non-empty, specifies a subdirectory under Resources or Resources/<lang>.lproj
References B::String::cf_ref(), and B::String::empty().
The documentation for this class was generated from the following files:
BBundle.h
BBundle.cpp