B: B::DocumentWindow< DOCUMENT > Class Template Reference
B::DocumentWindow< DOCUMENT > Class Template Reference
Document-related window class.
#include <BDocumentWindow.h>
Public Types
enum { kDocWindowKind = 'DocW' }
typedef DocumentWindow< DOCUMENT > DocWindow
Public Member Functions
virtual void CloseWindow (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
virtual bool ClosesDocument () const
virtual void ClosesDocument (bool inClosesDoc)
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
DOCUMENT * GetDocument () const
Constructors
DocumentWindow (WindowRef inWindowRef, DOCUMENT *inDocument, DescType inClassID=kDocWindowKind)
Constructor. In B, Window objects are created after their WindowRef.
Public Member Functions inherited from B::Window
void Select ()
void Show (bool showIt)
void Transition (WindowTransitionEffect inEffect, WindowTransitionAction inAction, Rect *inRect=NULL, Window *inParent=NULL)
void Reposition (WindowPositionMethod inMethod, Window *inParent=NULL)
virtual void Close ()
bool IsComposited () const
bool IsVisible () const
bool IsZoomable () const
bool IsZoomed () const
bool IsCollapseable () const
bool IsCollapsed () const
bool IsCloseable () const
bool IsResizeable () const
bool IsFloating () const
bool IsModal () const
String GetName () const
HIViewRef GetContentView () const
operator WindowRef () const
Returns the object's underlying WindowRef.
WindowRef GetWindowRef () const
Returns the object's underlying WindowRef.
HIObjectRef GetObjectRef () const
Returns the object's underlying HIObjectRef.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
void SetMinimumSize (const Size &inMinimumSize)
void SetMaximumSize (const Size &inMaximumSize)
void SetIdealSize (const Size &inIdealSize)
void SetTitle (const String &inTitle)
void SetAlternateTitle (const String &inTitle)
void SetProxy (const Icon &inIcon)
void SetProxy (const Url &inUrl)
void SetProxy (OSType inCreator, OSType inFileType)
void ClearProxy ()
void SetModified (bool inModified)
void Zoom (bool inZoomItOut)
void Collapse (bool inCollapse)
Rect GetContentViewBounds () const
Rect GetStructureBounds () const
Point GetStructureOrigin () const
Size GetStructureSize () const
Rect GetContentBounds () const
Point GetContentOrigin () const
Size GetContentSize () const
void SetStructureBounds (const Rect &inBounds)
void MoveStructureTo (const Point &inOrigin)
void MoveStructureBy (float inDeltaX, float inDeltaY)
void ResizeStructureTo (const Size &inSize)
void ResizeStructureBy (float inDeltaWidth, float inDeltaHeight)
void SetContentBounds (const Rect &inBounds)
void ResizeContentTo (const Size &inSize)
void ResizeContentBy (float inDeltaWidth, float inDeltaHeight)
void MoveContentTo (const Point &inOrigin)
void MoveContentBy (float inDeltaX, float inDeltaY)
void SetToolbar (OSPtr< HIToolbarRef > inToolbar)
void ShowToolbar (bool inShowIt, bool inAnimate)
bool IsToolbarVisible () const
void AddToWindowList ()
void RemoveFromWindowList ()
bool IsInWindowList () const
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inFileUrl=Url())
virtual void ActivateObject ()
virtual void DebugPrint () const
template<class VIEW >
void Register (CFStringRef inClassId, SInt32 inID)
Registers the class VIEW for HIViewRefs with the given class ID and inID.
template<class VIEW >
void Register (CFStringRef inClassId)
Registers the class VIEW for HIViewRefs with the given class ID and any id.
template<class VIEW >
VIEW * FindView (int inID) const
Returns the view matching the main bundle's signature and inID.
template<class VIEW >
VIEW * FindView (OSType inSignature, int inID) const
template<class VIEW >
VIEW * FindView (int inID, const std::nothrow_t &) const
Returns the view matching the main bundle's signature and inID, or NULL.
template<class VIEW >
VIEW * FindView (OSType inSignature, int inID, const std::nothrow_t &) const
Public Member Functions inherited from B::AEObject
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual SInt32 GetUniqueID () const
Returns the object's unique id.
virtual size_t CountElements (DescType inElementType) const
Returns the number of elements of the given class.
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
Returns the element of the given class with the given index.
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
Returns the element of the given class with the given unique ID.
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
Returns the element of the given class with the given name.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
Implements the AppleScript "make" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
Implements the AppleScript "print" event.
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
Implements the AppleScript "save" event.
virtual void RevertObject ()
Implements the AppleScript "revert" event.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
Protected Member Functions
virtual void Awaken (Nib *inFromNib)
virtual void LoadWindowTitle ()
virtual void LoadModified ()
virtual void LoadProxyIcon ()
virtual void LoadContent ()
virtual String GetWindowTitle ()
virtual String GetWindowAlternateTitle ()
virtual void MakeSpecifier (AEWriter &ioWriter) const
virtual void HandleActivated ()
virtual void HandleDeactivated ()
void DocumentClosing (AbstractDocument *inDocument)
void DocumentUrlChanged (AbstractDocument *inDocument)
void DocumentDirtyStateChanged (AbstractDocument *inDocument)
void DocumentContentChanged (AbstractDocument *inDocument)
Object Destruction
virtual ~DocumentWindow ()
Destructor.
Protected Member Functions inherited from B::Window
void PostCreateWindow (Nib *inFromNib)
virtual void RegisterViews ()
View * Instantiate (HIViewRef inViewRef) const
virtual bool ShouldWindowClose ()
virtual Size GetIdealSize () const
virtual void HandleShowing ()
virtual void HandleHiding ()
virtual void HandleShown ()
virtual void HandleHidden ()
virtual bool HandleFocusAcquired ()
virtual bool HandleFocusRelinquish ()
virtual bool HandleZoomed ()
virtual bool HandleResizeCompleted ()
virtual bool HandleDragCompleted ()
virtual bool HandleTransitionCompleted (void *inUserData)
virtual bool HandleCollapsed ()
virtual bool HandleExpanded ()
virtual bool HandleCommand (const HICommandExtended &inHICommand)
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
virtual void HandleSheetOpened (WindowRef inSheetWindowRef)
virtual void HandleSheetClosed (WindowRef inSheetWindowRef)
Window (WindowRef inWindowRef, AEObjectPtr inContainer, DescType inClassID=cWindow)
Constructor. In B, Window objects are created after their WindowRef.
virtual ~Window ()
Destructor.
void operator delete (void *p)
Operator delete.
Protected Member Functions inherited from B::AEObject
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Protected Attributes
DOCUMENT * mDocument
Additional Inherited Members
Static Public Member Functions inherited from B::Window
static Window * FromWindowRef (WindowRef inWindowRef)
static SInt32 CountWindowsOfClass (DescType inClassID)
static Window * GetWindowOfClassByIndex (DescType inClassID, unsigned inIndex)
static Window * GetWindowOfClassByName (DescType inClassID, const String &inName)
static Window * GetWindowOfClassByUniqueID (DescType inClassID, SInt32 inUniqueID)
template<class WINDOW >
static boost::shared_ptr< WINDOW > CreateFromNib (Nib &inNib, const char *inWindowName, AEObjectPtr inContainer)
Create a window and its views from a nib.
template<class WINDOW , typename STATE >
static boost::shared_ptr< WINDOW > CreateFromNibWithState (Nib &inNib, const char *inWindowName, AEObjectPtr inContainer, STATE inState)
Create a window and its views from a nib.
template<class WINDOW , typename STATE >
static boost::shared_ptr< WINDOW > CreateFromNibWithState (Nib &inNib, const char *inWindowName, STATE inState)
Static Public Member Functions inherited from B::AEObject
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Static Protected Member Functions inherited from B::AEObject
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Related Functions inherited from B::AEObject
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Detailed Description
template<class DOCUMENT>
class B::DocumentWindow< DOCUMENT >
Document-related window class.
Todo:
Document this class!
Member Function Documentation
template<class DOCUMENT > void B::DocumentWindow< DOCUMENT >::MakeSpecifier (AEWriter & ioWriter) const protected virtual
Make an Object Specifier for a Window
Reimplemented from B::Window.
References B::AEObject::BuildIndexSpecifier(), B::AEObject::GetClassID(), B::AEObject::GetIndex(), B::AEObject::GetPropertyObject(), and B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Set().
The documentation for this class was generated from the following files:
BDocumentWindow.h
BDocumentWindow.tpl.h