B: B::UNDO_POLICY Class Reference
B::UNDO_POLICY Class Reference
Undo
Template for an Undo Policy class.
#include <BUndoPolicyConcept.h>
Public Types
Types
typedef boost::signal0< void > Signal
Shorthand for the type of signal used by the undo policy.
Public Member Functions
Constructor & Destructor
UNDO_POLICY (EventTargetRef inTarget, const Bundle &inBundle)
Constructor.
~UNDO_POLICY ()
Destructor.
Setup
void RegisterAppleEvents (AEObjectSupport &ioObjectSupport)
Installs Apple Event handlers for Undo-related AppleEvents.
Inquiries
bool IsUndoing () const
Returns true if we are currently in the process of undoing an action group.
bool IsRedoing () const
Returns true if we are currently in the process of redoing an action group.
bool IsEnabled () const
Returns true if the undo mechanism is enabled.
bool CanUndo () const
Returns true if there is at least one action in the undo stack.
bool CanRedo () const
Returns true if there is at least one action in the redo stack.
unsigned GetMaxLevels () const
Returns the maximum size of the undo/redo stacks.
String GetUndoText () const
Returns a string describing the action group at the top of the undo stack.
String GetRedoText () const
Returns a string describing the action group at the top of the redo stack.
Modifiers
void Enable (bool inEnable)
Enables or disables the undo mechanism.
void SetMaxLevels (unsigned inMaxLevels)
Sets the maximum size of the undo/redo stacks.
void SetActionGroupName (const String &inName)
Sets the name of the currently open action group.
void Clear ()
Empties the undo and redo stacks.
Action Groups
Action groups allow any number of undoable actions to be committed or aborted as a unit. This is important in order to make the accumulation of actions resilient in the presence of exceptions.
void BeginGroup (const String &inName)
Opens an action group called inName.
void CommitGroup ()
Commits the currently open action group.
void AbortGroup ()
Aborts the currently open action group.
Adding Actions
These functions adds a single undoable action to the currently open action group. If no group is open, a new group with a default name is opened.
void Add (std::auto_ptr< UndoAction > inUndoAction)
Adds inUndoAction to the currently open action group.
void Add (FunctorUndoAction::FunctorType inFunctor)
Adds inFunctor to the currently open action group.
Undo & Redo
void Undo ()
Executes the action group at the top of the undo stack.
void Redo ()
Executes the action group at the top of the redo stack.
Signals
Signal & GetUndoSignal ()
This signal is sent when an Undo is performed.
Signal & GetRedoSignal ()
This signal is sent when an Redo is performed.
Signal & GetActionSignal ()
This signal is sent when an action is added.
Detailed Description
Template for an Undo Policy class.
UNDO_POLICY isn't a class; rather, its specifies the required interface for a class in order for it to be useable as a template parameter. So for example, if a class Foo is declared like so:
template <class UNDO_POLICY> Foo { ... };
and class Bar implements the interface described herein, then one can instantiate Foo with Bar:
class MyFoo : public Foo<Bar> { ... };
Conceptually, UNDO_POLICY maintains two stacks of action groups, one for Undo and the other for Redo. Both stacks can be arbitrarily deep, or they can have a fixed maximal size. Attempting to push an undo group onto a stack that is already at its maximum size will cause the action group at the bottom of the stack to be discarded.
The next question is, what's an action group? It's an ordered collection of one or more undo actions (objects derived from UndoAction). Action groups may be nested. They are populated by having a client call BeginGroup(), which creates a new empty group and "opens" it. The client then calls Add() one or more times, which has the effect of appending each UndoAction to the open group. The idea is that as the client is modifying its state, it passes to Add() objects that are capable of restoring that state. If the client's processing proceeds normally, it closes the group by calling CommitGroup(). This pushes the group onto either the Undo or Redo stack. On the other hand, if an error occurs in the client while it was modifying its state (eg, an exception is thrown), then the client closes the group by calling AbortGroup() instead. AbortGroup() executes each undo action in the currently open group (as well as nested groups etc) before discarding the group. Thus the trio of functions BeginGroup() / CommitGroup() / AbortGroup() are analogous to similarly-named transaction functions in the database world.
When a user issues and Undo or a Redo menu command, the top-most action group on the corresponding stack is executed, then it is discarded. Typically, the act of executing the group will trigger further calls to Add(), this time for Redo actions.
Note that the above description applies to UNDO_POLICY generally. Some concrete implementations may collapse one or more aspects of the policy. For example, a "null" policy might have stub implementations for CommitGroup() and AbortGroup(), among others.
In addition to the "class" interface presented below, UNDO_POLICY must also implement two other interfaces: one for Apple Events and the other for Carbon Events.
Apple Event Interface
This interface is required to support Undo & Redo via AppleScript.
kAEMiscStandards / kAEUndo
Because this Apple Event doesn't have a direct parameter (which means we don't know who exactly is supposed to receive it), the event is translated into a kEventClassCommand / kEventCommandProcess Carbon Event for the kHICommandUndo command and sent to the user input focus.
kAEMiscStandards / kAERedo
Because this Apple Event doesn't have a direct parameter (which means we don't know who exactly is supposed to receive it), the event is translated into a kEventClassCommand / kEventCommandProcess Carbon Event for the kHICommandRedo command and sent to the user input focus.
Carbon Event Interface
This interface is required to support decoupling the Undo Policy from its clients. One will usually want to isolate code that performs undoable state changes from the exact implementation of the Undo Policy. This is done by having such code use the functions of the Undo class to open and close groups and add undoable actions, rather than using the Policy's member functions directly. The Undo class translates its requests into Carbon Events which are then handled in the Undo Policy.
kEventClassB / kEventBUndoBegin
This is equivalent to calling BeginGroup(). An optional parameter specifies the action group's name.
Parameters:
kEventParamBUndoName (in, typeCFStringRef)
The action group's name. This parameter is optional; if absent a default name is used.
kEventClassB / kEventBUndoCommit
This is equivalent to calling CommitGroup().
kEventClassB / kEventBUndoAbort
This is equivalent to calling AbortGroup().
kEventClassB / kEventBUndoAdd
This is equivalent to calling Add().
Parameters:
kEventParamBUndoAction (in, typeBUndoAction)
The undoable action, of a type derived from UndoAction.
kEventClassB / kEventBUndoEnable
This is equivalent to calling Enable().
Parameters:
kEventParamBUndoEnable (in, typeBoolean)
The argument to pass to Enable().
Currently, two classes take undo policies as template parameters: Application and Document.
There are currently 3 examples of implementations of UNDO_POLICY:
NullUndoPolicy, for applications that don't need to support Undo.
MultipleUndoPolicy, for applications that need separate Undo and Redo stacks of arbitrary size.
SingleUndoPolicy, for applications that need only a simple 1-level-deep Undo.
Constructor & Destructor Documentation
B::UNDO_POLICY::UNDO_POLICY (EventTargetRef inTarget, const Bundle & inBundle)
Constructor.
Typically installs Carbon Event handlers on inTarget.
Parameters
inTarget The event target onto which the object can install handlers.
inBundle The bundle from which to retrieve resources.
Member Function Documentation
void B::UNDO_POLICY::RegisterAppleEvents (AEObjectSupport & ioObjectSupport)
Installs Apple Event handlers for Undo-related AppleEvents.
Note that this should only ever be called for the Undo Policy object that is attached to the Application object. That's because there is only one application-wide Apple Event handler for the Undo and Redo events.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents().
bool B::UNDO_POLICY::IsEnabled () const
Returns true if the undo mechanism is enabled.
"Enabled" in this context means that undo actions can be added to the undo or redo stacks.
String B::UNDO_POLICY::GetUndoText () const
Returns a string describing the action group at the top of the undo stack.
The string is in a form suitable for placing in a menu.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
String B::UNDO_POLICY::GetRedoText () const
Returns a string describing the action group at the top of the redo stack.
The string is in a form suitable for placing in a menu.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::Enable (bool inEnable)
Enables or disables the undo mechanism.
Each call with inEnable = false prevents undoable actions from being added to the open action group; each call with inEnable = true allows it to happen again. Each call to Enable(false) must be balanced with a call to Enable(true).
Parameters
inEnable true to enable the undo mechanism, false to disable it.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::SetMaxLevels (unsigned inMaxLevels)
Sets the maximum size of the undo/redo stacks.
If a transaction is committed and there are already inMaxLevels transactions stored in the Undo Policy, the oldest transaction is discarded.
Parameters
inMaxLevels The maximum size of the undo & redo stacks. Value of UINT_MAX results in an unlimited stack size.
void B::UNDO_POLICY::BeginGroup (const String & inName)
Opens an action group called inName.
Parameters
inName The group's name. If it's empty, a default value is used. The name is visible to the user and so should be localised.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::CommitGroup ()
Commits the currently open action group.
Exceptions
std::logic_error If there isn't an open action group.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::AbortGroup ()
Aborts the currently open action group.
Exceptions
std::logic_error If there isn't an open action group.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::Add (std::auto_ptr< UndoAction > inUndoAction)
Adds inUndoAction to the currently open action group.
Parameters
inUndoAction An undoable action. It's wrapped in an std::auto_ptr to emphasise the fact that ownership is transferred to the policy object.
Referenced by B::UndoPolicyEvents< UNDO_POLICY >::RegisterAppleEvents().
void B::UNDO_POLICY::Add (FunctorUndoAction::FunctorType inFunctor)
Adds inFunctor to the currently open action group.
Parameters
inFunctor A functor taking no arguments and returning no result.
The documentation for this class was generated from the following file:
BUndoPolicyConcept.h