B: B::NullDocumentPolicy Class Reference
B::NullDocumentPolicy Class Reference
A document policy for applications that don't have documents.
#include <BNullDocumentPolicy.h>
Public Types
Types
typedef NullDocumentFactory FactoryType
The null document policy gets a null document factory.
Public Member Functions
Constructor & Destructor
NullDocumentPolicy (AEObjectPtr, const Bundle &, Nib *)
See DOC_POLICY for description.
Setup
void Init ()
See DOC_POLICY for description.
void RegisterAppleEvents (AEObjectSupport &)
See DOC_POLICY for description.
Inquiries
FactoryType & GetFactory ()
See DOC_POLICY for description.
AppleEvent Handlers
void OpenApplication ()
See DOC_POLICY for description.
void ReopenApplication ()
See DOC_POLICY for description.
void QuitApplication (OSType=kAEAsk)
See DOC_POLICY for description.
AEObjectPtr OpenNewDocument (DescType, const AEDesc &, const AEDesc &)
See DOC_POLICY for description.
Document Access
SInt32 CountDocuments (DescType) const
See DOC_POLICY for description.
AEObjectPtr GetDocumentByIndex (DescType, unsigned) const
See DOC_POLICY for description.
AEObjectPtr GetDocumentByName (DescType, const String &) const
See DOC_POLICY for description.
AEObjectPtr GetDocumentByUniqueID (DescType, SInt32) const
See DOC_POLICY for description.
Detailed Description
A document policy for applications that don't have documents.
Use it as the DOC_POLICY template parameter of Application.
All of the member functions of NullDocumentPolicy either do nothing or throw an exception, as appropriate.
See also
DOC_POLICY.
Member Function Documentation
AEObjectPtr B::NullDocumentPolicy::OpenNewDocument (DescType , const AEDesc & , const AEDesc &)
See DOC_POLICY for description.
Since this document policy doesn't instantiate documents, this implementation throws an exception.
Referenced by ReopenApplication().
SInt32 B::NullDocumentPolicy::CountDocuments (DescType) const
See DOC_POLICY for description.
Since this document policy doesn't instantiate documents, this implementation throws an exception.
Referenced by ReopenApplication().
AEObjectPtr B::NullDocumentPolicy::GetDocumentByIndex (DescType , unsigned) const
See DOC_POLICY for description.
Since this document policy doesn't instantiate documents, this implementation throws an exception.
Referenced by ReopenApplication().
AEObjectPtr B::NullDocumentPolicy::GetDocumentByName (DescType , const String &) const
See DOC_POLICY for description.
Since this document policy doesn't instantiate documents, this implementation throws an exception.
Referenced by ReopenApplication().
AEObjectPtr B::NullDocumentPolicy::GetDocumentByUniqueID (DescType , SInt32) const
See DOC_POLICY for description.
Since this document policy doesn't instantiate documents, this implementation throws an exception.
Referenced by ReopenApplication().
The documentation for this class was generated from the following files:
BNullDocumentPolicy.h
BNullDocumentPolicy.cpp