B: B::AskReviewDocumentsDialog Class Reference
B::AskReviewDocumentsDialog Class Reference
Implements the standard "Review Changes" alert as per the Aqua HIG.
#include <BNavDialogs.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Types
Constants
enum Action { kReview = kNavUserActionReviewDocuments, kDiscard = kNavUserActionDiscardDocuments, kCancel = kNavUserActionCancel }
Enumerates the possible results of this dialog.
Public Member Functions
Setup
void SetDocumentCount (UInt32 inDocumentCount)
Specifies the number of modified documents.
template<class ASK_REVIEW_DOCUMENTS_DIALOG >
void SetCallback (B_ASKREVIEWDOCS_CB inFunction)
Sets the dialog's callback.
Retrieving Results
Action GetAction () const
Returns the action that dismissed the dialog. Only useful in app-modal scenario.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Static Public Member Functions
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an std::auto_ptr<>) that controls its lifetime.
template<class ASK_REVIEW_DOCUMENTS_DIALOG >
static std::auto_ptr< ASK_REVIEW_DOCUMENTS_DIALOG > Make (const DialogModality &inModality, UInt32 inDocumentCount, B_ASKREVIEWDOCS_CB inFunction=NullCallback< ASK_REVIEW_DOCUMENTS_DIALOG >())
Instantiates and returns an ASK_REVIEW_DOCUMENTS_DIALOG with the given arguments.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class ASK_REVIEW_DOCUMENTS_DIALOG >
static void Start (const DialogModality &inModality, UInt32 inDocumentCount, B_ASKREVIEWDOCS_CB inFunction=NullCallback< ASK_REVIEW_DOCUMENTS_DIALOG >())
Instantiates an ASK_REVIEW_DOCUMENTS_DIALOG with the given arguments, then enters it.
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Protected Member Functions
AskReviewDocumentsDialog ()
Protected default constructor to discourage stack-based instantiation.
void Configure (const DialogModality &inModality, UInt32 inDocumentCount)
Helper function for configuring the dialog.
Overrides from NavDialog
virtual NavDialogRef CreateDialog ()
virtual void HandleUserAction (NavUserAction inUserAction)
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual void DialogStarting (NavCBRec &ioParams)
Override this to do some processing after the dialog is created and initialised, but before it's displayed.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
Low-level function to handle Nav dialog events. There's normally no need to override this function.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Running Dialogs
These are convenience functions for displaying nav dialogs in an application-modal fashion. Because they don't return until the nav dialog is dismissed, the chosen action is returned as the function result.
Action Run ()
Displays the nav dialog in an application-modal fashion.
template<class ASK_REVIEW_DOCUMENTS_DIALOG >
static Action Run (UInt32 inDocumentCount)
Instantiates an ASK_REVIEW_DOCUMENTS_DIALOG, then enters a modal event loop for it.
Additional Inherited Members
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Detailed Description
Implements the standard "Review Changes" alert as per the Aqua HIG.
Beyond the usual DialogModality and callback arguments, the Make/Start/Run functions also take as an argument the number of documents containing unsaved changes (i.e., the number of "dirty" documents). The dialog's result is a value in the Action enumeration. An enum is used here because this dialog has three buttons, not just the usual OK/Cancel button pair.
Note
Developers will rarely need to invoke this dialog, because MultipleDocumentPolicy already does so automatically.
The Aqua HIG specify that this dialog should only be displayed if there is more than one modified document.
The Aqua HIG specify that this alert should always be application-modal; support for sheets is included for completeness only.
See also
Dialogs, Alerts and Navigation Services
Member Enumeration Documentation
enum B::AskReviewDocumentsDialog::Action
Enumerates the possible results of this dialog.
Enumerator
kReview
The user clicked the "Review Changes" button.
kDiscard
The user clicked the "Discard Changes" button.
kCancel
The user clicked the "Cancel" button.
Member Function Documentation
void B::AskReviewDocumentsDialog::SetDocumentCount (UInt32 inDocumentCount)
Specifies the number of modified documents.
Parameters
inDocumentCount The number of modified documents. Should be > 1.
Referenced by Configure().
template<class ASK_REVIEW_DOCUMENTS_DIALOG > void B::AskReviewDocumentsDialog::SetCallback (B_ASKREVIEWDOCS_CB inFunction)
Sets the dialog's callback.
Todo:
Complete this!
Parameters
ASK_REVIEW_DOCUMENTS_DIALOG Template parameter. The class of the instantiated window. Must be AskReviewDocumentsDialog or a class derived from AskReviewDocumentsDialog.
template<class ASK_REVIEW_DOCUMENTS_DIALOG > std::auto_ptr< ASK_REVIEW_DOCUMENTS_DIALOG > B::AskReviewDocumentsDialog::Make (const DialogModality & inModality, UInt32 inDocumentCount, B_ASKREVIEWDOCS_CB inFunction = NullCallback<ASK_REVIEW_DOCUMENTS_DIALOG>()) static
Instantiates and returns an ASK_REVIEW_DOCUMENTS_DIALOG with the given arguments.
Instantiates a dialog of class ASK_REVIEW_DOCUMENTS_DIALOG. The instance of ASK_REVIEW_DOCUMENTS_DIALOG is then configured with the given arguments. Finally the dialog is returned, ready to be displayed via Enter().
Parameters
ASK_REVIEW_DOCUMENTS_DIALOG Template parameter. The class of the instantiated window. Must be AskReviewDocumentsDialog or a class derived from AskReviewDocumentsDialog.
Returns
The ASK_REVIEW_DOCUMENTS_DIALOG object, wrapped in an std::auto_ptr<>. This implies that control over the object's lifetime is given to the caller.
Parameters
inModality The dialog's modality.
inDocumentCount The number of modified documents. Should be > 1.
inFunction A callback that is invoked when the dialog is dismissed.
template<class ASK_REVIEW_DOCUMENTS_DIALOG > void B::AskReviewDocumentsDialog::Start (const DialogModality & inModality, UInt32 inDocumentCount, B_ASKREVIEWDOCS_CB inFunction = NullCallback<ASK_REVIEW_DOCUMENTS_DIALOG>()) static
Instantiates an ASK_REVIEW_DOCUMENTS_DIALOG with the given arguments, then enters it.
Instantiates a nav dialog of class ASK_REVIEW_DOCUMENTS_DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog, call Make() then Enter().
Parameters
ASK_REVIEW_DOCUMENTS_DIALOG Template parameter. The class of the instantiated window. Must be AskReviewDocumentsDialog or a class derived from AskReviewDocumentsDialog.
See also
Make(), NavDialog::Enter()
Parameters
inModality The dialog's modality.
inDocumentCount The number of modified documents. Should be > 1.
inFunction A callback that is invoked when the dialog is dismissed.
template<class ASK_REVIEW_DOCUMENTS_DIALOG > AskReviewDocumentsDialog::Action B::AskReviewDocumentsDialog::Run (UInt32 inDocumentCount) static
Instantiates an ASK_REVIEW_DOCUMENTS_DIALOG, then enters a modal event loop for it.
Instantiates a nav dialog of class ASK_REVIEW_DOCUMENTS_DIALOG, as per Make(). Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
ASK_REVIEW_DOCUMENTS_DIALOG Template parameter. The class of the instantiated window. Must be AskReviewDocumentsDialog or a class derived from AskReviewDocumentsDialog.
Returns
The Action that dismissed the nav dialog.
See also
Make(), Run()
Parameters
inDocumentCount The number of modified documents. Should be > 1.
References B::DialogModality::Modal().
void B::AskReviewDocumentsDialog::HandleUserAction (NavUserAction inUserAction) protected virtual
Parameters
inUserAction The user action.
Implements B::NavDialog.
void B::AskReviewDocumentsDialog::Configure (const DialogModality & inModality, UInt32 inDocumentCount) protected
Helper function for configuring the dialog.
Parameters
inModality The dialog's modality.
inDocumentCount The number of modified documents. Should be > 1.
References kCancel, kDiscard, kReview, SetDocumentCount(), and B::NavDialog::SetModality().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp