B: B::PrintSettings Class Reference
B::PrintSettings Class Reference
Encapsulates a print settings for printing.
#include <BPrintSettings.h>
Public Member Functions
Constructors / Destructor
PrintSettings ()
Default constructor. Creates an empty print settings.
PrintSettings (const PrintSettings &inPrintSettings)
Copy constructor.
PrintSettings (const OSPtr< PMPrintSettings > &inPrintSettings)
OSPtr<PMPrintSettings> constructor.
PrintSettings (PMPrintSettings inPrintSettings)
PMPrintSettings constructor.
PrintSettings (PMPrintSettings inPrintSettings, const from_copy_t &)
PMPrintSettings constructor.
~PrintSettings ()
Destructor.
Assignment
PrintSettings & operator= (const PrintSettings &inPrintSettings)
Copy assignment.
PrintSettings & operator= (const OSPtr< PMPrintSettings > &inPrintSettings)
Copy assignment.
Copying
PrintSettings copy () const
Creates a distinct (i.e., non-shared) copy of the print settings.
void swap (PrintSettings &ioPrintSettings)
Exchanges the contents of *this and ioPrintSettings.
Serialisation
OSPtr< CFDataRef > Serialize () const
Serializes the print settings to the given vector.
void Deserialize (const OSPtr< CFDataRef > &inBlob)
Deserializes the print settings from the given vector.
Inquiries
size_t GetFirstPage () const
Returns the number of the first page to be printed.
size_t GetLastPage () const
Returns the number of the last page to be printed.
void GetPageRange (size_t &outMinPage, size_t &outMaxPage) const
Returns the valid range of pages that can be printed.
size_t GetCopies () const
Returns the number of copies that the user requests to be printed.
String GetJobName () const
Returns the name of the print job.
bool GetCollate () const
Returns whether the pages will be collated.
void GetExtendedData (OSType dataID, size_t size, void *outData) const
Returns extended print settings data previously stored by your application.
size_t GetExtendedDataSize (OSType dataID) const
Returns the size of extended print settings data previously stored by your application.
template<typename T >
void GetExtendedData (OSType dataID, T &outData) const
Returns extended print settings data previously stored by your application in a type-safe manner.
bool Equals (const PrintSettings &inPrintSettings) const
Compares the print settings to the given print settings, and returns true if they are equal.
Modifiers
void SetFirstPage (size_t inFirstPage)
Sets the default page number of the first page to be printed.
void SetLastPage (size_t inLastPage)
Sets the page number of the last page to be printed.
void SetPageRange (size_t inFirstPage, size_t inLastPage)
Sets the valid range of pages that can be printed.
void SetPageRangeAll ()
Sets the valid range of pages to "all".
void SetCopies (size_t inCopies)
Sets the default value to be displayed in the Print dialog for the number of copies to be printed.
void SetJobName (const String &inName)
Sets the name of the print job.
void SetCollate (bool inCollate)
Sets whether the pages will be collated.
void SetExtendedData (OSType dataID, size_t size, const void *inData)
Sets the extended print settings data previously stored by your application.
template<typename T >
void SetExtendedData (OSType dataID, const T &inData)
Sets extended print settings data previously stored by your application in a type-safe manner.
Friends
class PrintSession
Detailed Description
Encapsulates a print settings for printing.
Todo:
Document this class!
Constructor & Destructor Documentation
B::PrintSettings::PrintSettings (const PrintSettings & inPrintSettings)
Copy constructor.
Parameters
inPrintSettings The input print settings.
B::PrintSettings::PrintSettings (const OSPtr< PMPrintSettings > & inPrintSettings) explicit
OSPtr<PMPrintSettings> constructor.
Parameters
inPrintSettings The input print settings.
B::PrintSettings::PrintSettings (PMPrintSettings inPrintSettings) explicit
PMPrintSettings constructor.
Parameters
inPrintSettings The input print settings.
B::PrintSettings::PrintSettings (PMPrintSettings inPrintSettings, const from_copy_t & fc) explicit
PMPrintSettings constructor.
Parameters
inPrintSettings The input print settings.
Member Function Documentation
PrintSettings & B::PrintSettings::operator= (const PrintSettings & inPrintSettings)
Copy assignment.
Parameters
inPrintSettings The input print settings.
PrintSettings & B::PrintSettings::operator= (const OSPtr< PMPrintSettings > & inPrintSettings)
Copy assignment.
Parameters
inPrintSettings The input print settings.
void B::PrintSettings::swap (PrintSettings & ioPrintSettings)
Exchanges the contents of *this and ioPrintSettings.
Parameters
ioPrintSettings The input print settings.
References B::OSPtr< T >::swap().
Referenced by SetExtendedData().
void B::PrintSettings::GetExtendedData (OSType dataID, size_t size, void * outData) const
Returns extended print settings data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
size The size of the data.
outData A pointer to the buffer that will hold the data.
Referenced by GetExtendedData().
size_t B::PrintSettings::GetExtendedDataSize (OSType dataID) const
Returns the size of extended print settings data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
template<typename T > void B::PrintSettings::GetExtendedData (OSType dataID, T & outData) const
Returns extended print settings data previously stored by your application in a type-safe manner.
Parameters
dataID Four-character constant identifying the data of interest.
outData Holds the output value.
References GetExtendedData().
void B::PrintSettings::SetExtendedData (OSType dataID, size_t size, const void * inData)
Sets the extended print settings data previously stored by your application.
Parameters
dataID Four-character constant identifying the data of interest.
size The size of the data.
inData The new value.
Referenced by SetExtendedData().
template<typename T > void B::PrintSettings::SetExtendedData (OSType dataID, const T & inData)
Sets extended print settings data previously stored by your application in a type-safe manner.
Parameters
dataID Four-character constant identifying the data of interest.
inData The new value.
References SetExtendedData(), and swap().
The documentation for this class was generated from the following files:
BPrintSettings.h
BPrintSettings.cpp