B: B::Icon Class Reference
B::Icon Class Reference
Wrapper class around IconRefs.
#include <BIcon.h>
Public Member Functions
Constructors & Destructor
Icon ()
Default constructor. The icon is set to NULL.
Icon (const Icon &inIcon)
Copy constructor.
Icon (IconRef inIconRef, bool inFromCreateOrCopy)
Initialises the object with an IconRef.
Icon (const Url &inFileUrl)
Initialises the object with the icon of a file system entity.
Icon (const FSRef &inFileRef)
Initialises the object with the icon of a file system entity.
Icon (OSType inIconType)
Initialises the object with a system icon.
Icon (OSType inCreator, OSType inIconType, SInt16 inVRefNum=kOnSystemDisk)
Initialises the object with a creator & file type.
Icon (OSType inCreator, OSType inFileType, CFStringRef inExtension, CFStringRef inMIMEType)
Initialises the object one or more of inCreator, inFileType, inExtension and inMIMEType.
~Icon ()
Destructor. Releases the underlying IconRef.
Assignment
Icon & operator= (const Icon &inIcon)
Assignment operator.
Icon & operator= (const Url &inFileUrl)
Icon & operator= (OSType inIconType)
Icon & Assign (const Icon &inIcon)
Assignment. The new bundle is retained, and the old one is released.
Icon & Assign (IconRef inIconRef, bool inFromCreateOrCopy)
Icon & Assign (const Url &inFileUrl)
Icon & Assign (const FSRef &inFileRef)
Icon & Assign (OSType inIconType)
Icon & Assign (OSType inCreator, OSType inIconType, SInt16 inVRefNum=kOnSystemDisk)
Icon & Assign (OSType inCreator, OSType inFileType, CFStringRef inExtension, CFStringRef inMIMEType)
Inquiries
bool Empty () const
Returns true if the underlying IconRef is NULL.
SInt16 GetLabel () const
Returns the icon's label.
Conversions
operator IconRef () const
Returns the object's underlying IconRef.
AutoRegion GetRegion (const Rect &inRect, IconAlignmentType inAlignment=kAlignNone) const
Converts the icon into a region.
IconFamilyHandle GetIconFamily (IconSelectorValue inWhichIcons) const
Converts the icon into an IconFamilyHandle.
Drawing
void Draw (const Rect &inRect, SInt16 inLabel=0, IconAlignmentType inAlignment=kAlignNone, IconTransformType inTransform=kTransformNone) const
Draws the icon in the current GrafPort.
void Draw (CGContextRef inContext, const Rect &inRect, SInt16 inLabel=0, IconAlignmentType inAlignment=kAlignNone, IconTransformType inTransform=kTransformNone) const
Draws the icon in the given CoreGraphics context.
void DrawFlipped (CGContextRef inContext, const Rect &inRect, SInt16 inLabel=0, IconAlignmentType inAlignment=kAlignNone, IconTransformType inTransform=kTransformNone) const
Draws the icon upside down in the given CoreGraphics context.
Hit-Testing
bool Contains (const Point &inTestPoint, const Rect &inRect, IconAlignmentType inAlignment=kAlignNone) const
Determines if inTestPoint is within the icon.
bool Intersects (const Rect &inTestRect, const Rect &inRect, IconAlignmentType inAlignment=kAlignNone) const
Determines if inTestRect intersects the icon.
Static Public Member Functions
Registration
static Icon Register (OSType inCreator, OSType inIconType, const Url &inIcnsFileUrl)
Associates a .icns file with the (inCreator, inIconType) pair.
static Icon Register (OSType inCreator, OSType inIconType, IconFamilyHandle inIconFamily)
Associates icon family data with the (inCreator, inIconType) pair.
static void Unregister (OSType inCreator, OSType inIconType)
Associates a 'icns' resource with the (inCreator, inIconType) pair.
Detailed Description
Wrapper class around IconRefs.
The class properly maintains reference counts on the underlying IconRef.
Todo:
Complete class description!
Constructor & Destructor Documentation
B::Icon::Icon ()
Default constructor. The icon is set to NULL.
An Icon initialised in this way isn't really useable, since there's no underlying IconRef. It's allowed mainly to permit instances of Icon to be placed in containers, and other situations which require a default constructor.
Referenced by Register().
B::Icon::Icon (const Icon & inIcon)
Copy constructor.
Parameters
inIcon The source icon.
References Assign().
B::Icon::Icon (IconRef inIconRef, bool inFromCreateOrCopy) explicit
Initialises the object with an IconRef.
Parameters
inIconRef A pre-existing icon.
inFromCreateOrCopy Are we acquiring ownership of the inIconRef?
References Assign().
B::Icon::Icon (const Url & inFileUrl) explicit
Initialises the object with the icon of a file system entity.
Use this constructor when you need the icon of an existing file or folder.
Parameters
inFileUrl The location of the file or folder.
References Assign().
B::Icon::Icon (const FSRef & inFileRef) explicit
Initialises the object with the icon of a file system entity.
Use this constructor when you need the icon of an existing file or folder.
Parameters
inFileRef The location of the file or folder.
References Assign().
B::Icon::Icon (OSType inIconType) explicit
Initialises the object with a system icon.
Use this constructor when you need a system icon.
Parameters
inIconType The type for the icon.
References Assign().
B::Icon::Icon (OSType inCreator, OSType inIconType, SInt16 inVRefNum = kOnSystemDisk) explicit
Initialises the object with a creator & file type.
Use this constructor when you need an icon that is already registered.
Parameters
inCreator The creator code for the icon.
inIconType The type for the icon.
inVRefNum Hint on where to look for the icon.
References Assign().
B::Icon::Icon (OSType inCreator, OSType inFileType, CFStringRef inExtension, CFStringRef inMIMEType) explicit
Initialises the object one or more of inCreator, inFileType, inExtension and inMIMEType.
Use this constructor when you need an icon that is already registered.
Parameters
inCreator The creator for the icon; may be 0.
inFileType The filetype for the icon; may be 0.
inExtension The extension for the icon; may be NULL.
inMIMEType The MIME type for the icon; may be NULL.
References Assign().
Member Function Documentation
Icon & B::Icon::operator= (const Url & inFileUrl)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Assign().
Icon & B::Icon::operator= (OSType inIconType)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Assign().
Icon & B::Icon::Assign (IconRef inIconRef, bool inFromCreateOrCopy)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inIconRef A pre-existing icon.
inFromCreateOrCopy Are we acquiring ownership of the inIconRef?
Icon & B::Icon::Assign (const Url & inFileUrl)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inFileUrl The location of the file or folder.
References Assign().
Icon & B::Icon::Assign (const FSRef & inFileRef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inFileRef The location of the file or folder.
Icon& B::Icon::Assign (OSType inIconType)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Icon & B::Icon::Assign (OSType inCreator, OSType inIconType, SInt16 inVRefNum = kOnSystemDisk)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inCreator The creator code for the icon.
inIconType The type for the icon.
inVRefNum Hint on where to look for the icon.
Icon & B::Icon::Assign (OSType inCreator, OSType inFileType, CFStringRef inExtension, CFStringRef inMIMEType)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inCreator The creator for the icon; may be 0.
inFileType The filetype for the icon; may be 0.
inExtension The extension for the icon; may be NULL.
inMIMEType The MIME type for the icon; may be NULL.
SInt16 B::Icon::GetLabel () const
Returns the icon's label.
The label contains a useful value only if the icon was obtained from a file-system entity.
Referenced by DrawFlipped().
AutoRegion B::Icon::GetRegion (const Rect & inRect, IconAlignmentType inAlignment = kAlignNone) const
Converts the icon into a region.
The conversion is made by assuming the icon is drawn at the location given in inRect, with the alignment given in inAlignment.
Parameters
inRect The bounds for drawing.
inAlignment The icon's alignment within inRect.
void B::Icon::Draw (const Rect & inRect, SInt16 inLabel = 0, IconAlignmentType inAlignment = kAlignNone, IconTransformType inTransform = kTransformNone) const
Draws the icon in the current GrafPort.
Parameters
inRect The bounds for drawing.
inLabel The icon's label.
inAlignment The icon's alignment within inRect.
inTransform The icon's transform.
void B::Icon::Draw (CGContextRef inContext, const Rect & inRect, SInt16 inLabel = 0, IconAlignmentType inAlignment = kAlignNone, IconTransformType inTransform = kTransformNone) const
Draws the icon in the given CoreGraphics context.
This function inverts the Y-axis prior to drawing. It's suitable for use in HIViews, which assume a Quickdraw-like orientation of the Y axis.
Parameters
inContext The context to draw in.
inRect The bounds for drawing.
inLabel The icon's label.
inAlignment The icon's alignment within inRect.
inTransform The icon's transform.
References DrawFlipped().
void B::Icon::DrawFlipped (CGContextRef inContext, const Rect & inRect, SInt16 inLabel = 0, IconAlignmentType inAlignment = kAlignNone, IconTransformType inTransform = kTransformNone) const
Draws the icon upside down in the given CoreGraphics context.
This function draws the icon using the current transformation matrix of inContext. This usually means that the icon will draw upside down, because CoreGraphics' Y-axis goes up instead of down like Quickdraw.
Parameters
inContext The context to draw in.
inRect The bounds for drawing.
inLabel The icon's label.
inAlignment The icon's alignment within inRect.
inTransform The icon's transform.
References GetLabel().
Referenced by Draw().
bool B::Icon::Contains (const Point & inTestPoint, const Rect & inRect, IconAlignmentType inAlignment = kAlignNone) const
Determines if inTestPoint is within the icon.
The test is made by assuming the icon is drawn at the location given in inRect, with the alignment given in inAlignment.
Parameters
inTestPoint The point to test.
inRect The bounds for drawing.
inAlignment The icon's alignment within inRect.
bool B::Icon::Intersects (const Rect & inTestRect, const Rect & inRect, IconAlignmentType inAlignment = kAlignNone) const
Determines if inTestRect intersects the icon.
The test is made by assuming the icon is drawn at the location given in inRect, with the alignment given in inAlignment.
Parameters
inTestRect The rect to test.
inRect The bounds for drawing.
inAlignment The icon's alignment within inRect.
Icon B::Icon::Register (OSType inCreator, OSType inIconType, const Url & inIcnsFileUrl) static
Associates a .icns file with the (inCreator, inIconType) pair.
Parameters
inCreator The creator code for the icon.
inIconType The type for the icon.
inIcnsFileUrl The location of the .icns file.
References Icon().
Referenced by Register().
Icon B::Icon::Register (OSType inCreator, OSType inIconType, IconFamilyHandle inIconFamily) static
Associates icon family data with the (inCreator, inIconType) pair.
Parameters
inCreator The creator code for the icon.
inIconType The type for the icon.
inIconFamily The icon data.
References Icon(), and Register().
void B::Icon::Unregister (OSType inCreator, OSType inIconType) static
Associates a 'icns' resource with the (inCreator, inIconType) pair.
Removes the association between the (inCreator, inIconType) pair and icon data.
Parameters
inCreator The creator code for the icon.
inIconType The type for the icon.
The documentation for this class was generated from the following files:
BIcon.h
BIcon.cpp