B: B::ContextualMenu Class Reference
B::ContextualMenu Class Reference
Helper class implementing a contextual menu.
#include <BContextualMenu.h>
Public Member Functions
ContextualMenu (MenuRef inMenuRef)
Public Member Functions inherited from B::Menu
Menu (MenuRef inMenuRef)
operator MenuRef () const
Returns the object's underlying HIViewRef.
MenuRef GetMenuRef () const
Returns the object's underlying HIViewRef.
HIObjectRef GetObjectRef () const
Returns the object's underlying HIObjectRef.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
Protected Member Functions
virtual void HandleEnableItems ()
MenuItemIndex GetFirstItem ()
Returns the first menu item after the help item, if any.
void ShowHideCommands (MenuItemIndex firstItem)
void HideLeadingSeparators (MenuItemIndex firstItem)
void HideTrailingSeparators (MenuItemIndex firstItem)
void HideAdjacentSeparators (MenuItemIndex firstItem)
void ShowItem (MenuItemIndex item)
void HideItem (MenuItemIndex item)
Protected Member Functions inherited from B::Menu
virtual void HandleDispose ()
Additional Inherited Members
Static Public Member Functions inherited from B::Menu
static Menu * Instantiate (MenuRef inMenuRef)
static Menu * FromMenuRef (MenuRef inMenuRef)
Protected Attributes inherited from B::Menu
MenuRef mMenuRef
Detailed Description
Helper class implementing a contextual menu.
Todo:
Document this class!
Member Function Documentation
MenuItemIndex B::ContextualMenu::GetFirstItem () protected
Returns the first menu item after the help item, if any.
Determining the first "real" item in a contextual menu can be tricky, because passing kCMHelpItemRemoveHelp will remove the help item entirely. So we follow this heuristic: if the first menu item has a command ID, it's taken to be the first item; else, the first item is the one following the first separator line.
This depends on the fact that the Menu Manager doesn't attach a command ID when it prepends a "help" item onto a contextual menu.
References B::MenuItemProperty< SIG, TAG, T >::Get(), B::MenuItemProperty< SIG, TAG, T >::Remove(), and B::MenuItemProperty< SIG, TAG, T >::Set().
The documentation for this class was generated from the following files:
BContextualMenu.h
BContextualMenu.cpp