B: B::InteractWithUserDialog Class Reference
B::InteractWithUserDialog Class Reference
Requests the user's attention.
#include <BNavDialogs.h>
Public Member Functions
Constructor & Destructor
InteractWithUserDialog ()
Default constructor. Will use the default settings (see below).
InteractWithUserDialog (const NMRec &inNMRec, const String &inText)
Constructor. Will use the given settings.
Dialog Display
void Run (long timeout=kAEDefaultTimeout)
Requests the user's attention.
Static Public Member Functions
Default Values
These functions control how the user will be alerted, in cases where a InteractWithUserDialog is instantiated via its default constructor. The idea is that the application fills these in once, then calls the default constructor when needed.
static void SetText (const String &inText)
This will cause an alert to be displayed containing inText.
static void SetMark (bool inShowMark)
This will cause an mark character to appear in the Application menu.
static void SetIcon (Handle inIcon)
This will cause an icon to blink in the Application menu.
static void SetSound (Handle inSound)
This will cause a sound to be played.
Detailed Description
Requests the user's attention.
Use this dialog whenever you need the user to supply some information, but the application may not be in the foreground. This dialog checks if the app is in the foreground and if so doesn't do anything. If not, it calls attention to itself in a number of ways (explained below) so that the user brings the app to the foreground. If the user doesn't respond within the given timeout period, an InteractionTimeoutException is thrown.
Here's an example. Assume MyDeleteUserData needs the user to confirm the deletion:
MyDeleteUserData()
{
    // Notify the user that we need their attention.
    InteractWithUserDialog().Run();
    // If we got here, it's because the user brought us to the foreground.
    if (MyConfirmDeletionAlert())
    {
        // perform the deletion
    }
}
Note
This isn't actually a NavServices dialog, but rather a simple interface to the Notification Manager.
Instances of Dialog, Alert, and NavDialog call this class as necessary, so developers will rarely need to call it directly.
Constructor & Destructor Documentation
B::InteractWithUserDialog::InteractWithUserDialog ()
Default constructor. Will use the default settings (see below).
The object's internal Notification Manager data structure is initialised from the default settings.
B::InteractWithUserDialog::InteractWithUserDialog (const NMRec & inNMRec, const String & inText)
Constructor. Will use the given settings.
This constructor allows the caller to override the default settings. This would be useful if most of the time the default settings are acceptable, but in certain cases a different way of notifying the user is required.
Note
inText must be convertible to the application text encoding (as returned by GetApplicationTextEncoding()), because the Notification Manager doesn't understand Unicode.
Parameters
inNMRec Holds most of the settings except the text. This structure is copied into the object.
inText The string to display, if any.
References B::String::copy().
Member Function Documentation
void B::InteractWithUserDialog::Run (long timeout = kAEDefaultTimeout)
Requests the user's attention.
Checks if the application is already in the foreground, and if so returns immediately. If it's not in the foreground, then it will attempt to obtain the user's attention so that the user brings the application to the foreground. The exact method by which this is done is determined by the object's settings:
- In all cases, the application's icon will start bouncing in the dock.
- If the settings contain a string, an alert containing the string will be
  displayed.
- If the settings contain a sound, the sound is played.
If the user brings the application to the foreground within the alloted timeout period, then the function returns and the application can perform its normal processing. If on the other hand the timeout expires first, then function throws an IteractionTimeoutException; the application must then abandon its processing.
Parameters
timeout The amount of time the application is willing to wait.
Referenced by B::NavDialog::DialogEnding(), B::Alert::DismissAlert(), B::Dialog::HandleCommand(), B::AbstractPrintPolicy::Print(), and B::AbstractPrintPolicy::ValidatePrintSettings().
void B::InteractWithUserDialog::SetText (const String & inText) static
This will cause an alert to be displayed containing inText.
Calling this function with a non-empty string will cause an alert containing the string to be displayed whenever Run() is called.
Note
inText must be convertible to the application text encoding (as returned by GetApplicationTextEncoding()), because the Notification Manager doesn't understand Unicode.
Parameters
inText The string to display.
References B::String::copy().
void B::InteractWithUserDialog::SetMark (bool inShowMark) static
This will cause an mark character to appear in the Application menu.
Deprecated:
It's not clear that this function has any effect under Aqua.
void B::InteractWithUserDialog::SetIcon (Handle inIcon) static
This will cause an icon to blink in the Application menu.
Deprecated:
It's not clear that this function has any effect under Aqua.
void B::InteractWithUserDialog::SetSound (Handle inSound) static
This will cause a sound to be played.
Parameters
inSound The sound to play. Must be in sound resource ('snd ') format.
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp