B: B::Undo Class Reference
B::Undo Class Reference
Undo
Client interface to the Undo mechanism.
#include <BUndo.h>
Public Types
Types
typedef FunctorUndoAction::FunctorType FunctorType
Shorthand for FunctorUndoAction's functor type.
Static Public Member Functions
Action Groups
Action groups allow any number of undoable actions to be committed or aborted as a unit. This is important in order to make the accumulation of actions resilient in the presence of exceptions.
static void BeginGroup (const String &inName=String(), EventTargetRef inTarget=NULL)
Opens an action group called inName.
static void CommitGroup (EventTargetRef inTarget=NULL)
Commits the currently open action group.
static void AbortGroup (EventTargetRef inTarget=NULL)
Aborts the currently open action group.
Adding Actions
These functions add a single undoable action to the currently open group of undoable actions. If no group is open, a new group with a default name is opened.
template<class ACTION >
static void Add (std::auto_ptr< ACTION > inUndoAction, EventTargetRef inTarget=NULL)
Adds inUndoAction to the currently open action group.
static void Add (FunctorType inFunctor, EventTargetRef inTarget=NULL)
Adds inFunctor to the currently open action group.
template<class FUNCTOR >
static void Add (FUNCTOR inFunctor, typename FUNCTOR::argument_type inArg, EventTargetRef inTarget=NULL)
DEPRECATED. Adds the adapable unary functor inFunctor to the currently open action group.
template<class FUNCTOR >
static void Add (FUNCTOR inFunctor, typename FUNCTOR::first_argument_type inArg, typename FUNCTOR::second_argument_type inArg2, EventTargetRef inTarget=NULL)
DEPRECATED. Adds the adapable binary functor inFunctor to the currently open action group.
Modifiers
static void Enable (bool inEnable, EventTargetRef inTarget=NULL)
Enables or disables the undo mechanism.
Detailed Description
Client interface to the Undo mechanism.
All member functions take an EventTargetRef as an argument. Because implementations of UNDO_POLICY are attached to an EventTargetRef, this argument serves to direct requests to a given UNDO_POLICY implementation. By default, the request is sent to the user input focus, and travels up the handler chain from there.
See also
Supporting Undo, Undo, UNDO_POLICY
Member Function Documentation
void B::Undo::BeginGroup (const String & inName = String(), EventTargetRef inTarget = NULL) static
Opens an action group called inName.
Parameters
inName If empty, a default name is used.
inTarget If NULL, the request is sent to the user input focus.
Referenced by B::AutoUndo::AutoUndo().
void B::Undo::CommitGroup (EventTargetRef inTarget = NULL) static
Commits the currently open action group.
Parameters
inTarget If NULL, the request is sent to the user input focus.
References B::EventBase::Send().
Referenced by B::AutoUndo::Commit().
void B::Undo::AbortGroup (EventTargetRef inTarget = NULL) static
Aborts the currently open action group.
Parameters
inTarget If NULL, the request is sent to the user input focus.
References B::EventBase::Send().
Referenced by B::AutoUndo::~AutoUndo().
template<class ACTION > void B::Undo::Add (std::auto_ptr< ACTION > inUndoAction, EventTargetRef inTarget = NULL) static
Adds inUndoAction to the currently open action group.
Note that the action is wrapped in an std::auto_ptr. This means that ownership of inUndoAction is tranferred to this function; it will either be added succesfully to the currently open action group, or will be deleted.
Parameters
inUndoAction The undoable action, wrapped inside an std::auto_ptr.
inTarget If NULL, the request is sent to the user input focus.
Referenced by Add(), and B::AutoUndo::Add().
void B::Undo::Add (FunctorType inFunctor, EventTargetRef inTarget = NULL) static
Adds inFunctor to the currently open action group.
Parameters
inFunctor A functor taking no arguments and returning no result.
inTarget If NULL, the request is sent to the user input focus.
References B::EventBase::Send().
template<class FUNCTOR > void B::Undo::Add (FUNCTOR inFunctor, typename FUNCTOR::argument_type inArg, EventTargetRef inTarget = NULL) static
DEPRECATED. Adds the adapable unary functor inFunctor to the currently open action group.
FUNCTOR must be an adaptable unary function object. Its operator () must take one argument of type FUNCTOR::argument_type. Its result is discarded, so a return type of void is acceptable. The value of the argument is given in inArg.
Deprecated:
This function will be removed in a future release. Clients can replace calls to this function with:
Add(Undo::FunctorType(boost::bind(inFunctor, inArg)), inTarget)
Parameters
inFunctor An adaptable unary function object.
inArg The argument to be passed to inFunctor.
inTarget If NULL, the request is sent to the user input focus.
References Add().
template<class FUNCTOR > void B::Undo::Add (FUNCTOR inFunctor, typename FUNCTOR::first_argument_type inArg1, typename FUNCTOR::second_argument_type inArg2, EventTargetRef inTarget = NULL) static
DEPRECATED. Adds the adapable binary functor inFunctor to the currently open action group.
FUNCTOR must be an adaptable binnary function object. Its operator () must take two arguments; the first of type FUNCTOR::first_argument_type and the second of type FUNCTOR::second_argument_type. Its result is discarded, so a return type of void is acceptable. The values of the arguments are given in inArg1 and inArg2, respectively.
Deprecated:
This function will be removed in a future release. Clients can replace calls to this function with:
Add(Undo::FunctorType(boost::bind(inFunctor, inArg1, inArg2)), inTarget)
Parameters
inFunctor An adaptable unary function object.
inArg1 The first argument to be passed to inFunctor.
inArg2 The second argument to be passed to inFunctor.
inTarget If NULL, the request is sent to the user input focus.
References Add().
void B::Undo::Enable (bool inEnable, EventTargetRef inTarget = NULL) static
Enables or disables the undo mechanism.
Parameters
inEnable Indicates whether to enable or disable the undo mechanism.
inTarget If NULL, the request is sent to the user input focus.
Referenced by B::AutoDisableUndo::AutoDisableUndo(), and B::AutoDisableUndo::~AutoDisableUndo().
The documentation for this class was generated from the following files:
BUndo.h
BUndo.cpp