B: B::AutoMacHandle Class Reference
B::AutoMacHandle Class Reference
Wrapper around Carbon Handle type.
#include <BMemoryUtilities.h>
Public Types
typedef ::Handle MacHandle
Synonym for classic Mac OS Handle.
Public Member Functions
AutoMacHandle & operator= (AutoMacHandle &ioHandle)
Assignment. Acquires ownership of ioHandle's handle.
Constructors & Destructor
AutoMacHandle ()
Default constructor. Creates a zero-sized handle.
AutoMacHandle (AutoMacHandle &ioHandle)
AutoMacHandle constructor. Acquires ownership of ioHandle's handle.
AutoMacHandle (MacHandle inHandle)
Handle constructor. Acquires ownership of inHandle.
AutoMacHandle (size_t inSize)
Size constructor. Creates a handle of size inSize.
~AutoMacHandle ()
Destructor. Releases the handle, if any.
Inquiries
size_t size () const
Returns the amount of memory allocated to the underlying handle.
MacHandle get_handle () const
Returns the underlying handle.
Modifiers
MacHandle release ()
Relenquishes ownership of the underlying handle, and returns it.
void reset (MacHandle inHandle=NULL)
Relenquishes ownership of the underlying handle, and acquires ownership of inHandle.
void resize (size_t inNewSize)
Changes the amount of memory allocated to the underlying handle.
Detailed Description
Wrapper around Carbon Handle type.
This class provides "resource acquisition is initialization" (RAII) semantics for Carbon Handles. It features a destructive copy constructor and assignment operator similar in spirit to std::auto_ptr.
Note
This class deals with the raw Handle type, so it isn't type-safe.
Constructor & Destructor Documentation
B::AutoMacHandle::AutoMacHandle (MacHandle inHandle) explicit
Handle constructor. Acquires ownership of inHandle.
Note
If inHandle is a resource handle (and not an ordinary handle), the result is undefined.
References reset().
Member Function Documentation
void B::AutoMacHandle::reset (MacHandle inHandle = NULL)
Relenquishes ownership of the underlying handle, and acquires ownership of inHandle.
Note
If inHandle is a resource handle (and not an ordinary handle), the result is undefined.
Referenced by AutoMacHandle(), B::CreateImageFromURL(), get_handle(), B::AutoTypedHandle< T >::get_handle(), operator=(), and ~AutoMacHandle().
The documentation for this class was generated from the following files:
BMemoryUtilities.h
BMemoryUtilities.cpp