B: B::EventBase Class Reference
B::EventBase Class Reference
Carbon Events
Common base class for representing Carbon Events.
#include <BEvent.h>
Public Member Functions
Constructors & Destructor
EventBase (UInt32 inClassID, UInt32 inKind)
Creates a new Carbon Event.
EventBase (EventHandlerCallRef inHandlerCallRef, EventRef inEvent)
Creates a object wrapping an existing Carbon Event.
virtual ~EventBase ()
Destructor. Releases the embedded EventRef.
Inquiries
bool IsIncoming () const
Returns true if this is an incoming event.
Conversions
operator EventRef ()
Returns the EventRef embedded within the object.
Sending
void Send (EventTargetRef inTarget, OptionBits inOptions=0)
Sends the event to an event target.
OSStatus Send (EventTargetRef inTarget, const std::nothrow_t &, OptionBits inOptions=0)
Sends the event to an event target without throwing an exception.
void Send (HIObjectRef inObject, OptionBits inOptions=0)
OSStatus Send (HIObjectRef inObject, const std::nothrow_t &, OptionBits inOptions=0)
void Send (WindowRef inWindow, OptionBits inOptions=0)
OSStatus Send (WindowRef inWindow, const std::nothrow_t &, OptionBits inOptions=0)
void Send (HIViewRef inView, OptionBits inOptions=0)
OSStatus Send (HIViewRef inView, const std::nothrow_t &, OptionBits inOptions=0)
void Send (MenuRef inMenu, OptionBits inOptions=0)
OSStatus Send (MenuRef inMenu, const std::nothrow_t &, OptionBits inOptions=0)
void SendToApp (OptionBits inOptions=0)
OSStatus SendToApp (const std::nothrow_t &, OptionBits inOptions=0)
void SendToUserFocus (OptionBits inOptions=0)
OSStatus SendToUserFocus (const std::nothrow_t &, OptionBits inOptions=0)
Posting
void Post (EventPriority inPriority=kEventPriorityStandard)
Posts the event to the main event queue.
Forwarding
bool Forward ()
Forwards an incoming event to the next event handler in the chain.
OSStatus Forward (const std::nothrow_t &)
Forwards an incoming event to the next event handler in the chain without throwing an exception.
Synchronisation
virtual void Update ()
Sets output parameters.
virtual void Retrieve ()
Retrieves output parameters.
Static Public Member Functions
Utility
static OSStatus StoreExceptionIntoCarbonEvent (EventRef inEvent, const std::exception &ex)
static void RethrowExceptionFromCarbonEvent (EventRef inEvent, OSStatus inStatus)
Detailed Description
Common base class for representing Carbon Events.
This class contains member functions and variables that are independent of the specifics of a particular event. Its main purpose is to serve as a common base class for the various template instantiations of Event. It is rarely if ever used by itself.
EventBase can be instantiated as either an incoming or outgoing event. Incoming events are those given to a Carbon Event handler; they have an associated EventHandlerCallRef. They rarely, if ever, need to be instantiated directly because the EventHandler machinery takes care of it. Outgoing events are instantiated by the developer for sending elsewhere.
See also
Handling Carbon Events
Constructor & Destructor Documentation
B::EventBase::EventBase (UInt32 inClassID, UInt32 inKind)
Creates a new Carbon Event.
Use this constructor to create a Carbon Event prior to sending or posting it.
Parameters
inClassID The Carbon Event's class ID.
inKind The Carbon Event's kind.
Referenced by Retrieve().
B::EventBase::EventBase (EventHandlerCallRef inHandlerCallRef, EventRef inEvent)
Creates a object wrapping an existing Carbon Event.
Use this constructor when handling incoming Carbon Events.
Parameters
inHandlerCallRef The caller ref representing a location in the chain of event handlers.
inEvent The Carbon Event. It gets retained by the constructor.
B::EventBase::~EventBase () virtual
Destructor. Releases the embedded EventRef.
Releases the embedded EventRef.
Member Function Documentation
bool B::EventBase::IsIncoming () const
Returns true if this is an incoming event.
Note
Incoming EventBase objects are instantiated as a result of a Carbon Event handler invocation.
Returns
Boolean indication of 'incoming' state.
Referenced by Forward().
void B::EventBase::Send (EventTargetRef inTarget, OptionBits inOptions = 0)
Sends the event to an event target.
There are a number of overloads of this function. They only differ in the type of the argument, which always implicitly refers to an event target.
inOptions may be any value acceptable to SendEventToEventTargetWithOptions(). Currently these are 0 (default propagation rule), kEventTargetDontPropagate and kEventTargetSendToAllHandlers.
Parameters
inTarget The event target to which the event is initially sent.
inOptions The options to use when sending.
References Retrieve().
Referenced by B::Undo::AbortGroup(), B::Undo::Add(), B::Undo::CommitGroup(), B::CustomView::ScrollInfoChanged(), Send(), SendToApp(), SendToUserFocus(), and B::Window::SetIdealSize().
OSStatus B::EventBase::Send (EventTargetRef inTarget, const std::nothrow_t & , OptionBits inOptions = 0)
Sends the event to an event target without throwing an exception.
There are a number of overloads of this function. They only differ in the type of the first argument, which always implicitly refers to an event target.
inOptions may be any value acceptable to SendEventToEventTargetWithOptions(). Currently these are 0 (default propagation rule), kEventTargetDontPropagate and kEventTargetSendToAllHandlers.
Returns
An OS status code.
Exceptions
none
Parameters
inTarget The event target to which the event is initially sent.
inOptions The options to use when sending.
References Retrieve().
void B::EventBase::Send (HIObjectRef inObject, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::Send (HIObjectRef inObject, const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::Send (WindowRef inWindow, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::Send (WindowRef inWindow, const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::Send (HIViewRef inView, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::Send (HIViewRef inView, const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::Send (MenuRef inMenu, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::Send (MenuRef inMenu, const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::SendToApp (OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::SendToApp (const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::SendToUserFocus (OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
OSStatus B::EventBase::SendToUserFocus (const std::nothrow_t & nt, OptionBits inOptions = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References Send().
void B::EventBase::Post (EventPriority inPriority = kEventPriorityStandard)
Posts the event to the main event queue.
The event will only be dispatched once the event loop is run.
Parameters
inPriority The event's priority in the event queue.
Referenced by B::Document< UNDO_POLICY, PRINT_POLICY >::CreateAskDiscardChangesDialog().
bool B::EventBase::Forward ()
Forwards an incoming event to the next event handler in the chain.
Returns
A boolean indication of whether an event handler further up the chain handled the event.
References IsIncoming(), and Retrieve().
OSStatus B::EventBase::Forward (const std::nothrow_t &)
Forwards an incoming event to the next event handler in the chain without throwing an exception.
Returns
An OS status code.
Exceptions
none
References IsIncoming(), and Retrieve().
void B::EventBase::Update () virtual
Sets output parameters.
This function is called after a Carbon Event has been handled, but prior to returning control to the toolbox.
Derived classes should override this if they need to return output parameters to the caller. The idea is that the outputs are cached as member variables of the derived class, and written to the Carbon Event via SetEventParameter() from within this function.
Referenced by B::Event< CLASS, KIND >::Event(), and Retrieve().
void B::EventBase::Retrieve () virtual
Retrieves output parameters.
This function is called after a Carbon Event has been sent, but prior to returning control to the sender.
Derived classes should override this if they need to return output parameters to the caller. The idea is that the outputs from the Carbon Event are obtained via GetEventParameter() and stored as member variables of the derived class from within this function.
References B::ViewUtils::ConvertFromGlobal(), B::Event< CLASS, KIND >::Event(), EventBase(), B::ExceptionStreamer::Get(), B::ErrorHandler::Get(), B::EventParamAndType< kEventParamDirectObject, TYPE >::Get(), B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Get(), B::EventParamAndType< NAME, TYPE >::Get(), B::ErrorHandler::GetStatus(), B::EventParamAndType< NAME, TYPE >::Set(), B::EventParamAndType< kEventParamDirectObject, TYPE >::Set(), B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Set(), and Update().
Referenced by B::Event< CLASS, KIND >::Event(), Forward(), and Send().
The documentation for this class was generated from the following files:
BEvent.h
BEvent.cpp