B: B::MutableString Class Reference
B::MutableString Class Reference
Adapter class for changeable strings.
#include <BMutableString.h>
Public Types
Types
typedef String::value_type value_type
The type of the characters.
typedef String::size_type size_type
The unsigned integral type for size values and indices.
typedef String::difference_type difference_type
The signed integral type for difference values.
typedef String::reference reference
The signed integral type for difference values.
typedef String::const_reference const_reference
The type of constant character references.
typedef String::pointer pointer
The type of character pointers.
typedef String::const_pointer const_pointer
The type of character pointers.
typedef String::iterator iterator
The type of iterators.
typedef String::const_iterator const_iterator
The type of constant iterators.
typedef String::reverse_iterator reverse_iterator
The type of reverse iterators.
typedef String::const_reverse_iterator const_reverse_iterator
The type of constant reverse iterators.
typedef String::allocator_type allocator_type
The type of the allocator.
Public Member Functions
Constructors / Destructor
MutableString ()
Default constructor.
MutableString (const MutableString &str)
Copy constructor.
MutableString (CFAllocatorRef allocator)
Allocator constructor.
MutableString (const MutableString &str, size_type pos, size_type n=String::npos, CFAllocatorRef allocator=NULL)
MutableString constructor.
MutableString (const String &str)
String constructor.
MutableString (const String &str, size_type pos, size_type n=String::npos, CFAllocatorRef allocator=NULL)
String constructor.
MutableString (CFStringRef cfstr)
CFStringRef constructor.
MutableString (CFStringRef cfstr, size_type pos, size_type n=String::npos, CFAllocatorRef allocator=NULL)
CFStringRef constructor.
MutableString (const UniChar *ustr, size_type n=String::npos, CFAllocatorRef allocator=NULL)
UniChar array constructor.
MutableString (size_type n, UniChar c, CFAllocatorRef allocator=NULL)
UniChar constructor.
MutableString (const std::wstring &wstr, size_type pos=0, size_type n=String::npos, CFAllocatorRef allocator=NULL)
std::wstring constructor.
MutableString (const wchar_t *wcstr, size_type n=String::npos, CFAllocatorRef allocator=NULL)
wchar_t array constructor.
MutableString (const std::string &sstr, CFStringEncoding encoding=kCFStringEncodingASCII, size_type pos=0, size_type n=String::npos, CFAllocatorRef allocator=NULL)
std::string constructor.
MutableString (const char *cstr, CFStringEncoding encoding=kCFStringEncodingASCII, size_type n=String::npos, CFAllocatorRef allocator=NULL)
char* array constructor.
MutableString (ConstStringPtr pstr, CFStringEncoding encoding=kCFStringEncodingASCII, CFAllocatorRef allocator=NULL)
Pascal string constructor.
MutableString (const std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external, CFAllocatorRef allocator=NULL)
Blob constructor.
MutableString (const OSPtr< CFStringRef > &cfstr)
OSPtr<CFStringRef> constructor.
MutableString (const OSPtr< CFMutableStringRef > &cfstr)
OSPtr<CFMutableStringRef> constructor.
template<class InputIterator >
MutableString (InputIterator first, InputIterator last, CFAllocatorRef allocator=NULL)
Range constructor.
~MutableString ()
Destructor.
Operations for Size and Capacity
size_type size () const
Returns the number of characters in the string.
size_type length () const
Returns the number of characters in the string.
bool empty () const
Returns whether the string is empty.
size_type max_size () const
Returns the maximum number of characters a string could contain.
size_type capacity () const
Returns the number of characters the string could contain without reallocation.
void reserve (size_type n=0)
Non-binding request to resize the internal storage to max(n, size()).
Comparisons
int compare (const MutableString &str) const
Compares the string to str.
int compare (size_type pos1, size_type n1, const MutableString &str) const
Compares the string to str.
int compare (size_type pos1, size_type n1, const MutableString &str, size_type pos2, size_type n2) const
Compares the string to str.
int compare (CFStringRef cfstr) const
Compares the string to cfstr.
int compare (size_type pos1, size_type n1, CFStringRef cfstr) const
Compares the string to cfstr.
int compare (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2) const
Compares the string to cfstr.
int compare (const UniChar *ustr) const
Compares the string to ustr.
int compare (size_type pos1, size_type n1, const UniChar *ustr) const
Compares the string to ustr.
int compare (size_type pos1, size_type n1, const UniChar *ustr, size_type n2) const
Compares the string to ustr.
int compare (const std::string &sstr, CFStringEncoding encoding) const
Compares the string to sstr.
int compare (size_type pos1, size_type n1, const std::string &sstr, CFStringEncoding encoding) const
Compares the string to sstr.
int compare (size_type pos1, size_type n1, const std::string &sstr, CFStringEncoding encoding, size_type pos2, size_type n2) const
Compares the string to sstr.
Character Access
const_reference operator[] (size_type pos) const
Returns the character at index pos.
reference operator[] (size_type pos)
Returns a modifiable reference to the character at index pos.
const_reference at (size_type pos) const
Returns the character at index pos.
reference at (size_type pos)
Returns a modifiable reference to the character at index pos.
Generating CFMutableStringRefs and Character Arrays.
Because of the fundamental differences in underlying storage between MutableString and std::basic_string<>, it's impossible to provide direct counterparts to std::basic_string<>c_str() and std::basic_string<>data(). cf_ref() is analogous to c_str().
The various overloads of copy() allow conversions from MutableString to a number of output types.
CFMutableStringRef cf_ref () const
Returns the underlying CFStringRef.
OSPtr< CFMutableStringRef > cf_ptr () const
Returns a "smart pointer" to the underlying CFStringRef.
size_type copy (UniChar *ustr, size_type n, size_type pos=0) const
Copies the string to a UniChar array.
size_type copy (wchar_t *wcstr, size_type n, size_type pos=0) const
Copies the string to a wchar_t array.
size_type copy (char *cstr, size_type n, size_type &pos, CFStringEncoding encoding) const
Copies at most n bytes, starting at index pos in *this, into the buffer pointed to by cstr.
void copy (CFMutableStringRef cfstr) const
Copies the string to a CFMutableStringRef.
void copy (std::wstring &wstr) const
Copies the string to a std::wstring.
void copy (std::string &sstr, CFStringEncoding encoding) const
Copies the string to a std::string.
void copy (StringPtr pstr, size_type n, CFStringEncoding encoding) const
Copies the string to a Pascal String.
void copy (std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external, char loss_byte=0) const
Copies the string to a blob.
Assignment
The various overloads of operator = and assign() replace the string's contents with the given input string. However, the string's CFMutableStringRef does not change.
MutableString & operator= (const MutableString &str)
MutableString assignemnt.
MutableString & operator= (const String &str)
String assignemnt.
MutableString & operator= (CFStringRef cfstr)
CFStringRef assignemnt.
MutableString & operator= (const OSPtr< CFStringRef > &cfstr)
OSPtr<CFStringRef> assignemnt.
MutableString & operator= (const OSPtr< CFMutableStringRef > &cfstr)
OSPtr<CFMutableStringRef> assignemnt.
MutableString & operator= (const UniChar *ustr)
Null-terminated UniChar array assignemnt.
MutableString & operator= (UniChar c)
UniChar assignemnt.
MutableString & operator= (const std::wstring &wstr)
std::wstring assignemnt.
MutableString & operator= (const wchar_t *ustr)
Null-terminated wchar_t array assignemnt.
MutableString & operator= (const std::string &sstr)
std::string assignemnt.
MutableString & operator= (const char *cstr)
Null-terminated char array assignemnt.
MutableString & operator= (ConstStringPtr pstr)
Pascal string assignemnt.
MutableString & assign (const MutableString &str, size_type pos=0, size_type n=String::npos)
MutableString assignemnt.
MutableString & assign (const String &str, size_type pos=0, size_type n=String::npos)
String assignemnt.
MutableString & assign (CFStringRef cfstr, size_type pos=0, size_type n=String::npos)
CFStringRef assignemnt.
MutableString & assign (const UniChar *ustr, size_type n=String::npos)
UniChar array assignemnt.
MutableString & assign (size_type n, UniChar c)
UniChar assignemnt.
MutableString & assign (const std::wstring &wstr, size_type pos=0, size_type n=String::npos)
std::wstring assignemnt.
MutableString & assign (const wchar_t *wcstr, size_type n=String::npos)
wchar_t array assignemnt.
MutableString & assign (const std::string &sstr, CFStringEncoding encoding, size_type pos=0, size_type n=String::npos)
std::string assignemnt.
MutableString & assign (const char *cstr, CFStringEncoding encoding, size_type n=String::npos)
char array assignemnt.
MutableString & assign (ConstStringPtr pstr, CFStringEncoding encoding)
Pascal string assignemnt.
MutableString & assign (const std::vector< UInt8 > &blob, CFStringEncoding encoding, bool external)
Blob assignemnt.
template<class InputIterator >
MutableString & assign (InputIterator first, InputIterator last)
Range assignment.
void swap (MutableString &str)
Exchanges the contents of the string with str.
Appending Characters
MutableString & operator+= (const MutableString &str)
Appends a MutableString.
MutableString & operator+= (const String &str)
Appends a String.
MutableString & operator+= (CFStringRef cfstr)
Appends a CFStringRef.
MutableString & operator+= (const UniChar *ustr)
Appends a null-terminated UniChar array.
MutableString & operator+= (UniChar c)
Appends a UniChar.
MutableString & operator+= (const std::string &sstr)
Appends a std::string.
MutableString & append (const MutableString &str, size_type pos=0, size_type n=String::npos)
Appends a MutableString.
MutableString & append (const String &str, size_type pos=0, size_type n=String::npos)
Appends a String.
MutableString & append (CFStringRef cfstr, size_type pos=0, size_type n=String::npos)
Appends a CFStringRef.
MutableString & append (const UniChar *ustr, size_type n=String::npos)
Appends a UniChar array.
MutableString & append (size_type n, UniChar c)
Appends UniChars.
template<class InputIterator >
MutableString & append (InputIterator first, InputIterator last)
Appends a range.
void push_back (UniChar c)
Appends a single character.
Inserting Characters
MutableString & insert (size_type pos1, const MutableString &str, size_type pos2=0, size_type n=String::npos)
Inserts a MutableString.
MutableString & insert (size_type pos1, const String &str, size_type pos2=0, size_type n=String::npos)
Inserts a String.
MutableString & insert (size_type pos1, CFStringRef cfstr, size_type pos2=0, size_type n=String::npos)
Inserts a CFStringRef.
MutableString & insert (size_type pos, const UniChar *ustr, size_type n=String::npos)
Inserts a UniChar array.
MutableString & insert (size_type pos, size_type n, UniChar c)
Inserts UniChars.
iterator insert (iterator it, UniChar c)
Inserts a UniChar.
void insert (iterator it, size_t n, UniChar c)
Inserts UniChars.
template<class InputIterator >
void insert (iterator it, InputIterator first, InputIterator last)
Inserts a range.
Erasing Characters
MutableString & erase ()
Removes all characters.
MutableString & erase (size_type pos, size_type n=String::npos)
Removes a range of characters.
iterator erase (iterator it)
Removes one character.
iterator erase (iterator first, iterator last)
Removes a range of characters.
void clear ()
Removes all characters.
Changing the Size
void resize (size_type n)
Resizes the string, inserting '\0' characters as necessary.
void resize (size_type n, UniChar c)
Resizes the string, inserting c characters as necessary.
Replacing Characters
MutableString & replace (size_type pos1, size_type n1, const MutableString &str)
Replaces characters with a MutableString.
MutableString & replace (size_type pos1, size_type n1, const MutableString &str, size_type pos2, size_type n2)
Replaces characters with a MutableString.
MutableString & replace (size_type pos1, size_type n1, const String &str)
Replaces characters with a String.
MutableString & replace (size_type pos1, size_type n1, const String &str, size_type pos2, size_type n2)
Replaces characters with a String.
MutableString & replace (size_type pos1, size_type n1, CFStringRef cfstr)
Replaces characters with a CFStringRef.
MutableString & replace (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2)
Replaces characters with a CFStringRef.
MutableString & replace (size_type pos1, size_type n1, const UniChar *ustr, size_type n2=String::npos)
Replaces characters with a UniChar array.
MutableString & replace (size_type pos1, size_type n1, size_type n, UniChar c)
Replaces characters with UniChars.
MutableString & replace (iterator it1, iterator it2, const MutableString &str)
Replaces characters with a MutableString.
MutableString & replace (iterator it1, iterator it2, const String &str)
Replaces characters with a String.
MutableString & replace (iterator it1, iterator it2, CFStringRef cfstr)
Replaces characters with a CFStringRef.
MutableString & replace (iterator it1, iterator it2, const UniChar *ustr, size_type n2=String::npos)
Replaces characters with a UniChar array.
MutableString & replace (iterator it1, iterator it2, size_type n, UniChar c)
Replaces characters with UniChars.
template<class InputIterator >
MutableString & replace (iterator it1, iterator it2, InputIterator first, InputIterator last)
Replaces characters with a range.
Finding a Character
size_type find (UniChar c, size_type pos=0) const
Finds the first occurrence of given character.
size_type rfind (UniChar c, size_type pos=0) const
Finds the last occurrence of given character.
Finding a Substring
size_type find (const MutableString &str, size_type pos=0) const
Finds the first MutableString.
size_type rfind (const MutableString &str, size_type pos=0) const
Finds the last MutableString.
size_type find (CFStringRef cfstr, size_type pos=0) const
Finds the first CFStringRef.
size_type rfind (CFStringRef cfstr, size_type pos=0) const
Finds the last CFStringRef.
size_type find (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the first UniChar array.
size_type rfind (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the last UniChar array.
size_type find (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first std::string.
size_type rfind (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last std::string.
Finding the First of a Set of Characters
size_type find_first_of (const MutableString &str, size_type pos=0) const
Finds the first character in a set given as a MutableString.
size_type find_first_not_of (const MutableString &str, size_type pos=0) const
Finds the first character not in a set given as a MutableString.
size_type find_first_of (CFStringRef cfstr, size_type pos=0) const
Finds the first character in a set given as a CFStringRef.
size_type find_first_not_of (CFStringRef cfstr, size_type pos=0) const
Finds the first character not in a set given as a CFStringRef.
size_type find_first_of (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the first character in a set given as a UniChar array.
size_type find_first_not_of (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the first character not in a set given as a UniChar array.
size_type find_first_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first character in a set given as a std::string.
size_type find_first_not_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the first character not in a set given as a std::string.
Finding the Last of a Set of Characters
size_type find_last_of (const MutableString &str, size_type pos=0) const
Finds the last character in a set given as a MutableString.
size_type find_last_not_of (const MutableString &str, size_type pos=0) const
Finds the last character not in a set given as a MutableString.
size_type find_last_of (CFStringRef cfstr, size_type pos=0) const
Finds the last character in a set given as a CFStringRef.
size_type find_last_not_of (CFStringRef cfstr, size_type pos=0) const
Finds the last character not in a set given as a CFStringRef.
size_type find_last_of (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the last character in a set given as a UniChar array.
size_type find_last_not_of (const UniChar *ustr, size_type pos=0, size_type n=String::npos) const
Finds the last character not in a set given as a UniChar array.
size_type find_last_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last character in a set given as a std::string.
size_type find_last_not_of (const std::string &sstr, CFStringEncoding encoding, size_type pos=0) const
Finds the last character not in a set given as a std::string.
Substrings
MutableString substr (size_type pos=0, size_type n=String::npos) const
Returns a substring.
Generating Iterators
const_iterator begin () const
Returns a constant random access iterator for the beginning of the string.
iterator begin ()
Returns a random access iterator for the beginning of the string.
const_iterator end () const
Returns a constant random access iterator for the end of the string.
iterator end ()
Returns a random access iterator for the end of the string.
const_reverse_iterator rbegin () const
Returns a constant random access iterator for the beginning of a reverse iteration of the string.
reverse_iterator rbegin ()
Returns a random access iterator for the beginning of a reverse iteration of the string.
const_reverse_iterator rend () const
Returns a constant random access iterator for the end of a reverse iteration of the string.
reverse_iterator rend ()
Returns a random access iterator for the end of a reverse iteration of the string.
Allocator Support
allocator_type get_allocator () const
Returns the string's allocator.
I/O Support
std::ostream & Write (std::ostream &ostr, CFStringEncoding encoding) const
Write the characters of str to ostr.
std::istream & Read (std::istream &istr, CFStringEncoding encoding)
Reads the characters of the next word from istr into the string.
std::istream & GetLine (std::istream &istr, char delim, CFStringEncoding encoding)
Reads the characters of the next line from istr into the string.
Related Functions
(Note that these are not member functions.)
String Concatenation
MutableString operator+ (const MutableString &s1, const MutableString &s2)
Input/Output Functions
String only supports I/O to char streams (i.e., std::basic_ostream<char,char_traits<char>>).
std::ostream & operator<< (std::ostream &os, const MutableString &str)
std::istream & operator>> (std::istream &is, MutableString &str)
std::istream & getline (std::istream &is, MutableString &str, char delim)
std::istream & getline (std::istream &is, MutableString &str)
String Comparisons
bool operator== (const MutableString &s1, const MutableString &s2)
bool operator!= (const MutableString &s1, const MutableString &s2)
bool operator< (const MutableString &s1, const MutableString &s2)
bool operator<= (const MutableString &s1, const MutableString &s2)
bool operator> (const MutableString &s1, const MutableString &s2)
bool operator>= (const MutableString &s1, const MutableString &s2)
Miscellaneous
void swap (MutableString &s1, MutableString &s2)
Detailed Description
Adapter class for changeable strings.
MutableString provides a wrapper around a CoreFoundation CFMutableStringRef object, giving it an interface similar (nearly identical in fact) to std::string. This makes it possible to use MutableString with STL algorithms, with standard streams, etc.
Unlike String, MutableString does not share CFMutableStringRefs between its instances. Each MutableString gets its own independent CFMutableStringRef. The one exception to this is the OSPtr<CFMutableStringRef> constructor, which can optionally share its argument instead of copying it.
Other notable differences with std::basic_string<...>:
- There are no template parameters, because CFStrings only have one underlying
  character type, namely @c UniChar.  One can think of MutableString as
  analogous to <tt>std::basic_string<UniChar,char_traits<UniChar>,CFAllocatorRef></tt>.
- There are many more conversions.  This reflects MutableString's role as an
  adapter between CoreFoundation and the Standard C++ Library.  For example, one
  may construct instances of MutableString with any of the following types:
    - String
    - MutableString
    - <tt>CFStringRef</tt>
    - <tt>const UniChar*</tt>
    - <tt>std::string</tt>
    - <tt>std::wstring</tt>
    - <tt>const char*</tt>
    - <tt>const wchar_t*</tt>
    - <tt>UniChar</tt>
    - <tt>ConstStringPtr</tt>
    - <tt>std::vector<UInt8></tt>
- Likewise, one may copy() a MutableString into one of the following data
  structures:
    - <tt>CFMutableStringRef</tt>
    - <tt>std::string</tt>
    - <tt>std::wstring</tt>
    - <tt>char*</tt>
    - <tt>wchar_t*</tt>
    - <tt>UniChar*</tt>
    - <tt>StringPtr</tt>
    - <tt>std::vector<UInt8></tt>
- The functions that manipulate the string's underlying storage (capacity() and
  reserve()) do nothing, because there's no equivalent concept in CoreFoundation.
- The allocator type is fixed as @c CFAllocatorRef.  The allocator type is not a
  template parameter, however allocators @e are passed as arguments to
  constructors and can be retrieved via get_allocator().
- The underlying @c CFMutableStringRef's storage is not accessible, so it's not
  possible to take the address of an element of a MutableString.  MutableString
  is incompatible with the STL in this respect.
Constructor & Destructor Documentation
B::MutableString::MutableString ()
Default constructor.
Creates an empty string using the default allocator.
Referenced by operator+(), B::operator+(), and substr().
B::MutableString::MutableString (const MutableString & str)
Copy constructor.
Creates a string as a copy of str, using str's allocator.
Parameters
str The source string.
References cf_ref(), and get_allocator().
B::MutableString::MutableString (CFAllocatorRef allocator) explicit
Allocator constructor.
Creates an empty string using allocator.
Parameters
allocator The new object's allocator.
B::MutableString::MutableString (const MutableString & str, size_type pos, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
MutableString constructor.
Creates a string that is initialised by, at most, the first n characters of str starting with index pos.
Parameters
str The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
References cf_ref().
B::MutableString::MutableString (const String & str) explicit
String constructor.
Creates a string as a copy of str, using str's allocator.
Parameters
str The source string.
References B::String::cf_ref(), and B::String::get_allocator().
B::MutableString::MutableString (const String & str, size_type pos, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
String constructor.
Creates a string that is initialised by, at most, the first n characters of str starting with index pos.
Parameters
str The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (CFStringRef cfstr) explicit
CFStringRef constructor.
Creates a string as a copy of cfstr, using cfstr's allocator.
Parameters
cfstr The source string.
B::MutableString::MutableString (CFStringRef cfstr, size_type pos, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
CFStringRef constructor.
Creates a new string that is initialised by, at most, the first n characters of cfstr starting with index pos.
Parameters
cfstr The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const UniChar * ustr, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
UniChar array constructor.
Creates a string that is initialised by, at most, the first n characters of ustr. If n is String::npos, then ustr is assumed to be null-terminated; else, NULL ('\0') characters have no special meaning.
Parameters
ustr The source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (size_type n, UniChar c, CFAllocatorRef allocator = NULL) explicit
UniChar constructor.
Creates a string that is initialised by n occurrences of character c.
Parameters
n The number of occurrences of c.
c The character to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const std::wstring & wstr, size_type pos = 0, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
std::wstring constructor.
Creates a string that is initialised by, at most, the first n characters of wstr starting with index pos.
Parameters
wstr The source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const wchar_t * wcstr, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
wchar_t array constructor.
Creates a string that is initialised by, at most, the first n characters of wcstr. If n is String::npos, then wcstr is assumed to be null-terminated; else, NULL (L'\0') characters have no special meaning.
Parameters
wcstr The source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const std::string & sstr, CFStringEncoding encoding = kCFStringEncodingASCII, size_type pos = 0, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
std::string constructor.
Creates a string that is initialised by, at most, the first n characters of sstr starting with index pos. The source string is assumed to be encoded using the character encoding given in encoding.
Note
The default value for encoding is kCFStringEncodingASCII. This allows the caller to pass in a string literal without having to worry about specifying an encoding. It also will be more likely to catch errors (erroneous encodings).
Parameters
sstr The source string.
encoding The character encoding of the source string.
pos The starting position for the copy within the source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const char * cstr, CFStringEncoding encoding = kCFStringEncodingASCII, size_type n = String::npos, CFAllocatorRef allocator = NULL) explicit
char* array constructor.
Creates a string that is initialised by, at most, the first n characters of cstr. If n is String::npos, then cstr is assumed to be null-terminated; else, NULL ('\0') characters have no special meaning. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
cstr The source string.
encoding The character encoding of the source string.
n The number of characters to copy.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (ConstStringPtr pstr, CFStringEncoding encoding = kCFStringEncodingASCII, CFAllocatorRef allocator = NULL) explicit
Pascal string constructor.
Creates a string that is initialised by pstr. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
pstr The source string.
encoding The character encoding of the source string.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external, CFAllocatorRef allocator = NULL) explicit
Blob constructor.
Creates a string that is initialised by blob. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
blob The source blob.
encoding The character encoding of blob.
external If true, checks for BOM and performs byte-swapping as necessary.
allocator The new object's allocator.
References B::String::cf_ref().
B::MutableString::MutableString (const OSPtr< CFStringRef > & cfstr) explicit
OSPtr<CFStringRef> constructor.
Creates a string as a copy of cfstr, using cfstr's allocator.
Parameters
cfstr The source string.
References B::OSPtr< T >::get().
B::MutableString::MutableString (const OSPtr< CFMutableStringRef > & cfstr) explicit
OSPtr<CFMutableStringRef> constructor.
Creates a string object with cfstr. Does NOT copy cfstr.
Parameters
cfstr The source string.
template<class InputIterator > B::MutableString::MutableString (InputIterator first, InputIterator last, CFAllocatorRef allocator = NULL) explicit
Range constructor.
Creates a string that is initialised by all character of the range [first, last).
Parameters
first The start of the range of characters for the new string.
last The end of the range of characters for the new string.
allocator The new object's allocator.
Member Function Documentation
void B::MutableString::reserve (size_type n = 0)
Non-binding request to resize the internal storage to max(n, size()).
Stub implementation. CFMutableStringRef doesn't have a notion of capacity that parallels the one in std::basic_string.
int B::MutableString::compare (const MutableString & str) const
Compares the string to str.
Compares the string *this with the string str.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Parameters
str The string to compare against.
References cf_ref().
Referenced by operator!=(), B::operator!=(), operator<(), B::operator<(), operator<=(), B::operator<=(), operator==(), B::operator==(), operator>(), B::operator>(), operator>=(), and B::operator>=().
int B::MutableString::compare (size_type pos1, size_type n1, const MutableString & str) const
Compares the string to str.
Compares, at most, n1 characters of string *this, starting with index pos1 with string str.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
str The string to compare against.
References cf_ref().
int B::MutableString::compare (size_type pos1, size_type n1, const MutableString & str, size_type pos2, size_type n2) const
Compares the string to str.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string str starting with index pos2.
Returns
< 0 if *this < str; 0 if *this == str; > 0 if *this > str.
Exceptions
std::out_of_range If pos1 > size() or pos2 > str.size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
str The string to compare against.
pos2 The index of the first character to compare in str.
n2 The number of characters to compare in str.
References cf_ref().
int B::MutableString::compare (CFStringRef cfstr) const
Compares the string to cfstr.
Compares the string *this with the string cfstr.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Parameters
cfstr The string to compare against.
int B::MutableString::compare (size_type pos1, size_type n1, CFStringRef cfstr) const
Compares the string to cfstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with string cfstr.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
cfstr The string to compare against.
int B::MutableString::compare (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2) const
Compares the string to cfstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string cfstr starting with index pos2.
Returns
< 0 if *this < cfstr; 0 if *this == cfstr; > 0 if *this > cfstr.
Exceptions
std::out_of_range If pos1 > size() or pos2 > CFStringGetLength(cfstr).
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
cfstr The string to compare against.
pos2 The index of the first character to compare in cfstr.
n2 The number of characters to compare in cfstr.
int B::MutableString::compare (const UniChar * ustr) const
Compares the string to ustr.
Compares the string *this with the null-terminated UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Parameters
ustr The string to compare against.
int B::MutableString::compare (size_type pos1, size_type n1, const UniChar * ustr) const
Compares the string to ustr.
Compares, at most, n1 characters of string *this, starting with index pos1 with the null-terminated UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
ustr The string to compare against.
int B::MutableString::compare (size_type pos1, size_type n1, const UniChar * ustr, size_type n2) const
Compares the string to ustr.
Compares, at most, n1 characters of string *this, starting with index pos1 with n2 characters of UniChar array ustr.
Returns
< 0 if *this < ustr; 0 if *this == ustr; > 0 if *this > ustr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
ustr The string to compare against.
n2 The number of characters to compare in ustr.
int B::MutableString::compare (const std::string & sstr, CFStringEncoding encoding) const
Compares the string to sstr.
Compares the string *this with the string sstr, which is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Parameters
sstr The string to compare against.
encoding The character encoding of sstr.
int B::MutableString::compare (size_type pos1, size_type n1, const std::string & sstr, CFStringEncoding encoding) const
Compares the string to sstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with the string sstr, which is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Exceptions
std::out_of_range If pos1 > size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
sstr The string to compare against.
encoding The character encoding of sstr.
int B::MutableString::compare (size_type pos1, size_type n1, const std::string & sstr, CFStringEncoding encoding, size_type pos2, size_type n2) const
Compares the string to sstr.
Compares, at most, n1 characters of string *this, starting with index pos1 with, at most, n2 characters of string sstr starting with index pos2. Sstr is assumed to be encoded using the character encoding given in encoding.
Returns
< 0 if *this < sstr; 0 if *this == sstr; > 0 if *this > sstr.
Exceptions
std::out_of_range If pos1 > size() or pos2 > sstr.size().
Parameters
pos1 The index of the first character to compare in *this.
n1 The number of characters to compare in *this.
sstr The string to compare against.
encoding The character encoding of sstr.
pos2 The index of the first character to compare in str.
n2 The number of characters to compare in sstr.
MutableString::const_reference B::MutableString::operator[] (size_type pos) const
Returns the character at index pos.
If pos equals length(), the function returns '\0'. If pos is smaller than zero or greater than length(), the results are undefined.
Parameters
pos The index of the character to return.
References length().
MutableString::reference B::MutableString::operator[] (size_type pos)
Returns a modifiable reference to the character at index pos.
If pos is smaller than zero or greater than or equal to length(), the results are undefined.
MutableString::const_reference B::MutableString::at (size_type pos) const
Returns the character at index pos.
If pos is smaller than zero or greater than or equal to length(), the function throws an std::out_of_range exception.
Exceptions
std::out_of_range
MutableString::reference B::MutableString::at (size_type pos)
Returns a modifiable reference to the character at index pos.
If pos is smaller than zero or greater than or equal to length(), the function throws an std::out_of_range exception.
Exceptions
std::out_of_range
MutableString::size_type B::MutableString::copy (UniChar * ustr, size_type n, size_type pos = 0) const
Copies the string to a UniChar array.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by ustr. No null character is appended.
Returns
The number of copied characters.
Parameters
ustr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion.
Referenced by Write().
MutableString::size_type B::MutableString::copy (wchar_t * wcstr, size_type n, size_type pos = 0) const
Copies the string to a wchar_t array.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by wcstr. The string's characters are converted to wchar_t upon copying. No null character is appended.
Returns
The number of copied characters.
Parameters
wcstr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion.
MutableString::size_type B::MutableString::copy (char * cstr, size_type n, size_type & pos, CFStringEncoding encoding) const
Copies at most n bytes, starting at index pos in *this, into the buffer pointed to by cstr.
Copies at most n characters, starting at index pos in *this, into the buffer pointed to by wcstr. The string's characters are converted to encoding upon copying. No null character is appended.
Returns
The number of copied characters.
Parameters
cstr The output buffer.
n The maximum number of characters to copy.
pos The starting index (in *this) for conversion. On output, holds the index of the next character to convert, or npos if conversion is complete.
encoding The output buffer's encoding.
void B::MutableString::copy (CFMutableStringRef cfstr) const
Copies the string to a CFMutableStringRef.
The current contents of cfstr are completely replaced. If cfstr doesn't have enough capacity to hold the contents, the results are undefined.
Parameters
cfstr The output string.
References cf_ref().
void B::MutableString::copy (std::wstring & wstr) const
Copies the string to a std::wstring.
The string's characters are converted to wchar_t upon copying.
Parameters
wstr The output string.
void B::MutableString::copy (std::string & sstr, CFStringEncoding encoding) const
Copies the string to a std::string.
The string's characters are converted to encoding upon copying.
Parameters
sstr The output string.
encoding The output string's encoding.
void B::MutableString::copy (StringPtr pstr, size_type n, CFStringEncoding encoding) const
Copies the string to a Pascal String.
The string's characters are converted to encoding upon copying.
Parameters
pstr The output string.
n The maximum size of the output string, including length byte.
encoding The output string's encoding.
void B::MutableString::copy (std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external, char loss_byte = 0) const
Copies the string to a blob.
If external is true, then the string is converted to an "external form", which usually means it is made suitable for writing to a file. In Unicode-speak, this implies prepending a BOM (Byte-Order Mark) character. The string's characters are converted to encoding upon copying. If loss_byte is non-zero, then any characters unconvertible to encoding will be replaced by loss_byte; else, conversion errors will cause an exception.
Parameters
blob The output buffer.
encoding The output string's encoding.
external If true, blob get a leading BOM.
loss_byte The character to substitute for unconvertible characters.
MutableString & B::MutableString::operator= (const MutableString & str)
MutableString assignemnt.
Parameters
str The input string.
References cf_ref().
MutableString & B::MutableString::operator= (const String & str)
String assignemnt.
Parameters
str The input string.
References B::String::cf_ref().
MutableString & B::MutableString::operator= (CFStringRef cfstr)
CFStringRef assignemnt.
Parameters
cfstr The input string.
MutableString & B::MutableString::operator= (const OSPtr< CFStringRef > & cfstr)
OSPtr<CFStringRef> assignemnt.
Parameters
cfstr The input string.
MutableString & B::MutableString::operator= (const OSPtr< CFMutableStringRef > & cfstr)
OSPtr<CFMutableStringRef> assignemnt.
Parameters
cfstr The input string.
MutableString & B::MutableString::operator= (const UniChar * ustr)
Null-terminated UniChar array assignemnt.
Parameters
ustr The input string.
References B::String::cf_ref(), and B::String::npos.
MutableString & B::MutableString::operator= (UniChar c)
UniChar assignemnt.
Parameters
c The input character.
References B::String::cf_ref().
MutableString & B::MutableString::operator= (const std::wstring & wstr)
std::wstring assignemnt.
Parameters
wstr The input string.
MutableString & B::MutableString::operator= (const wchar_t * wcstr)
Null-terminated wchar_t array assignemnt.
Parameters
wcstr The input string.
References B::String::cf_ref(), and B::String::npos.
MutableString & B::MutableString::operator= (const std::string & sstr)
std::string assignemnt.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
sstr The input string.
MutableString & B::MutableString::operator= (const char * cstr)
Null-terminated char array assignemnt.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
cstr The input string.
References B::String::cf_ref(), and B::String::npos.
MutableString & B::MutableString::assign (const MutableString & str, size_type pos = 0, size_type n = String::npos)
MutableString assignemnt.
Assigns at most n characters of str starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References B::String::cf_ref().
Referenced by GetLine(), and Read().
MutableString & B::MutableString::assign (const String & str, size_type pos = 0, size_type n = String::npos)
String assignemnt.
Assigns at most n characters of str starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (CFStringRef cfstr, size_type pos = 0, size_type n = String::npos)
CFStringRef assignemnt.
Assigns at most n characters of cfstr starting with index pos.
Exceptions
Parameters
cfstr The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const UniChar * ustr, size_type n = String::npos)
UniChar array assignemnt.
Assigns n characters of ustr. If n is npos, then ustr is assumed to be null-terminated.
Parameters
ustr The input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (size_type n, UniChar c)
UniChar assignemnt.
Assigns num occurrences of character c.
Parameters
n The number of occurrences of c.
c The character to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const std::wstring & wstr, size_type pos = 0, size_type n = String::npos)
std::wstring assignemnt.
Assigns at most n characters of wstr starting with index pos.
Exceptions
Parameters
wstr The input string.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const wchar_t * wcstr, size_type n = String::npos)
wchar_t array assignemnt.
Assigns at most n characters of wcstr starting with index pos. If n is npos, then wcstr is assumed to be null-terminated.
Parameters
wcstr The input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0, size_type n = String::npos)
std::string assignemnt.
Assigns at most n characters of sstr starting with index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Exceptions
Parameters
sstr The input string.
encoding The input string's encoding.
pos The index of the first character to assign from the input string.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const char * cstr, CFStringEncoding encoding, size_type n = String::npos)
char array assignemnt.
Assigns at most n characters of cstr starting with index pos. If n is npos, then cstr is assumed to be null-terminated. The input string is assumed to be encoded using the character encoding given in encoding.
Parameters
cstr The input string.
encoding The input string's encoding.
n The number of characters to assign.
References B::String::cf_ref().
MutableString & B::MutableString::assign (ConstStringPtr pstr, CFStringEncoding encoding)
Pascal string assignemnt.
The input string is assumed to be encoded using the character encoding given in encoding.
Parameters
pstr The input string.
encoding The input string's encoding.
References B::String::cf_ref().
MutableString & B::MutableString::assign (const std::vector< UInt8 > & blob, CFStringEncoding encoding, bool external)
Blob assignemnt.
Assigns the string from blob. The source string is assumed to be encoded using the character encoding given in encoding.
Parameters
blob The source blob.
encoding The character encoding of blob.
external If true, checks for BOM and performs byte-swapping as necessary.
References B::String::cf_ref().
template<class InputIterator > MutableString & B::MutableString::assign (InputIterator first, InputIterator last)
Range assignment.
Assigns the string with all characters of the range [first, last).
Parameters
first The start of the range of characters to assign.
last The end of the range of characters to assign.
MutableString & B::MutableString::operator+= (const MutableString & str)
Appends a MutableString.
Parameters
str The input string.
References cf_ref().
MutableString & B::MutableString::operator+= (const String & str)
Appends a String.
Parameters
str The input string.
References B::String::cf_ref().
MutableString & B::MutableString::operator+= (CFStringRef cfstr)
Appends a CFStringRef.
Parameters
cfstr The input string.
MutableString & B::MutableString::operator+= (const UniChar * ustr)
Appends a null-terminated UniChar array.
Parameters
ustr The input string.
MutableString & B::MutableString::operator+= (const std::string & sstr)
Appends a std::string.
Note
The input string is assumed to be encoded as kCFStringEncodingASCII.
Parameters
sstr The input string.
References B::String::cf_ref().
MutableString & B::MutableString::append (const MutableString & str, size_type pos = 0, size_type n = String::npos)
Appends a MutableString.
Appends, at most, n characters for str, starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to append from the input string.
n The number of characters to append.
References cf_ref().
Referenced by resize().
MutableString & B::MutableString::append (const String & str, size_type pos = 0, size_type n = String::npos)
Appends a String.
Appends, at most, n characters for str, starting with index pos.
Exceptions
Parameters
str The input string.
pos The index of the first character to append from the input string.
n The number of characters to append.
References B::String::cf_ref().
MutableString & B::MutableString::append (CFStringRef cfstr, size_type pos = 0, size_type n = String::npos)
Appends a CFStringRef.
Appends, at most, n characters for cfstr, starting with index pos.
Exceptions
Parameters
cfstr The input string.
pos The index of the first character to append from the input string.
n The number of characters to append.
References B::String::cf_ref().
MutableString & B::MutableString::append (const UniChar * ustr, size_type n = String::npos)
Appends a UniChar array.
Appends, at most, n characters of ustr starting with index pos. If n is npos, then ustr is assumed to be null-terminated.
Parameters
ustr The input string.
n The number of characters to assign.
References B::String::npos.
MutableString & B::MutableString::append (size_type n, UniChar c)
Appends UniChars.
Appends num occurrences of character c.
Parameters
n The number of occurrences of c.
c The character to append.
References B::String::cf_ref().
template<class InputIterator > MutableString & B::MutableString::append (InputIterator first, InputIterator last)
Appends a range.
Appends all characters of the range [first, last).
Parameters
first The start of the range of characters to append.
last The end of the range of characters to append.
MutableString & B::MutableString::insert (size_type pos1, const MutableString & str, size_type pos2 = 0, size_type n = String::npos)
Inserts a MutableString.
Inserts, at most, n characters of str, starting with index pos2, so that the new characters start with index pos1.
Exceptions
Parameters
pos1 The index at which to start inserting characters.
str The input string.
pos2 The index of the first character to insert from the input string.
n The number of characters to insert.
References cf_ref().
Referenced by insert().
MutableString & B::MutableString::insert (size_type pos1, const String & str, size_type pos2 = 0, size_type n = String::npos)
Inserts a String.
Inserts, at most, n characters of str, starting with index pos2, so that the new characters start with index pos1.
Exceptions
Parameters
pos1 The index at which to start inserting characters.
str The input string.
pos2 The index of the first character to insert from the input string.
n The number of characters to insert.
References B::String::cf_ref().
MutableString & B::MutableString::insert (size_type pos1, CFStringRef cfstr, size_type pos2 = 0, size_type n = String::npos)
Inserts a CFStringRef.
Inserts, at most, n characters of cfstr, starting with index pos2, so that the new characters start with index pos1.
Exceptions
Parameters
pos1 The index at which to start inserting characters.
cfstr The input string.
pos2 The index of the first character to insert from the input string.
n The number of characters to insert.
References B::String::cf_ref().
MutableString & B::MutableString::insert (size_type pos, const UniChar * ustr, size_type n = String::npos)
Inserts a UniChar array.
Inserts n characters of ustr so that the new characters start with index pos. If n is npos, then ustr is assumed to be null-terminated.
Exceptions
Parameters
pos The index at which to start inserting characters.
ustr The input string.
n The number of characters to insert.
References B::String::cf_ref().
MutableString::iterator B::MutableString::insert (iterator it, UniChar c)
Inserts a UniChar.
Inserts a copy of character c before the character to which iterator it refers.
Parameters
it The location at which to insert c.
c The character to insert.
References B::String::cf_ref().
void B::MutableString::insert (iterator it, size_t n, UniChar c)
Inserts UniChars.
Inserts n occurences of c at the location in the string given in it.
Parameters
it The location at which to start inserting characters.
n The number of occurrences of c to insert.
c The character to insert.
References B::String::cf_ref().
template<class InputIterator > void B::MutableString::insert (iterator it, InputIterator first, InputIterator last)
Inserts a range.
Inserts all characters of the range [first, last) before the character to which iterator it refers.
Parameters
it The location at which to start inserting characters.
first The start of the range of characters to insert.
last The end of the range of characters to insert.
References insert().
MutableString & B::MutableString::erase (size_type pos, size_type n = String::npos)
Removes a range of characters.
Removes, at most, n characters from *this, starting at index pos.
Exceptions
Parameters
pos The index at which to start inserting characters.
n The number of characters to insert.
References B::String::npos, and size().
MutableString::iterator B::MutableString::erase (iterator it)
Removes one character.
Removes the single character to which iterator it refers.
Returns
An iterator referring to the first character remaining, or end().
Exceptions
MutableString::iterator B::MutableString::erase (iterator first, iterator last)
Removes a range of characters.
Removes the characters in the range [first, last).
Returns
An iterator referring to the first character remaining, or end().
Exceptions
void B::MutableString::resize (size_type n)
Resizes the string, inserting '\0' characters as necessary.
Changes the number of characters in *this to n. Thus, if n is not equal to size(), the function appends or removes characters at the end according to the new size.
Parameters
n The string's new size.
void B::MutableString::resize (size_type n, UniChar c)
Resizes the string, inserting c characters as necessary.
Changes the number of characters in *this to n. Thus, if n is not equal to size(), the function appends or removes characters at the end according to the new size.
Parameters
n The string's new size.
c The character to append if increasing the string's size.
References append(), erase(), B::String::npos, and size().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, const MutableString & str)
Replaces characters with a MutableString.
Replaces, at most, n1 characters of *this, starting with index pos1, with all characters of str.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
str The input string.
References cf_ref(), B::String::npos, and size().
Referenced by replace().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, const MutableString & str, size_type pos2, size_type n2)
Replaces characters with a MutableString.
Replaces, at most, n1 characters of *this, starting with index pos1, with at most n2 characters of str staring with index pos2.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
str The input string.
pos2 The index of the first character from the input string.
n2 The number of characters from the input string.
References replace().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, const String & str)
Replaces characters with a String.
Replaces, at most, n1 characters of *this, starting with index pos1, with all characters of str.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
str The input string.
References B::String::cf_ref(), B::String::npos, and size().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, const String & str, size_type pos2, size_type n2)
Replaces characters with a String.
Replaces, at most, n1 characters of *this, starting with index pos1, with at most n2 characters of str staring with index pos2.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
str The input string.
pos2 The index of the first character from the input string.
n2 The number of characters from the input string.
References replace().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, CFStringRef cfstr)
Replaces characters with a CFStringRef.
Replaces, at most, n1 characters of *this, starting with index pos1, with all characters of cfstr.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
cfstr The input string.
References B::String::npos, and size().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, CFStringRef cfstr, size_type pos2, size_type n2)
Replaces characters with a CFStringRef.
Replaces, at most, n1 characters of *this, starting with index pos1, with at most n2 characters of cfstr staring with index pos2.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
cfstr The input string.
pos2 The index of the first character from the input string.
n2 The number of characters from the input string.
References replace().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, const UniChar * ustr, size_type n2 = String::npos)
Replaces characters with a UniChar array.
Replaces, at most, n1 characters of *this, starting with index pos1, with n2 characters of ustr. If n is npos, then ustr is assumed to be null-terminated.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
ustr The input string.
n2 The number of characters from the input string.
References replace().
MutableString & B::MutableString::replace (size_type pos1, size_type n1, size_type n, UniChar c)
Replaces characters with UniChars.
Replaces, at most, n1 characters of *this, starting with index pos1, with n occurrences of character c.
Exceptions
Parameters
pos1 The index of the first character to replace.
n1 The number of characters to replace.
n The number of occurrences of c to insert.
c The character to insert.
References replace().
MutableString & B::MutableString::replace (iterator it1, iterator it2, const MutableString & str)
Replaces characters with a MutableString.
Replaces all characters of the range [first, last) with all characters of cfstr.
Parameters
it1 The start of the range of characters to replace.
it2 The end of the range of characters to replace.
str The input string.
References cf_ref().
MutableString & B::MutableString::replace (iterator it1, iterator it2, const String & str)
Replaces characters with a String.
Replaces all characters of the range [first, last) with all characters of cfstr.
Parameters
it1 The start of the range of characters to replace.
it2 The end of the range of characters to replace.
str The input string.
References B::String::cf_ref().
MutableString & B::MutableString::replace (iterator it1, iterator it2, CFStringRef cfstr)
Replaces characters with a CFStringRef.
Replaces all characters of the range [first, last) with all characters of cfstr.
Parameters
it1 The start of the range of characters to replace.
it2 The end of the range of characters to replace.
cfstr The input string.
MutableString & B::MutableString::replace (iterator it1, iterator it2, const UniChar * ustr, size_type n2 = String::npos)
Replaces characters with a UniChar array.
Replaces all characters of the range [first, last) with n2 characters of ustr. If n is npos, then ustr is assumed to be null-terminated.
Parameters
it1 The start of the range of characters to replace.
it2 The end of the range of characters to replace.
ustr The input string.
n2 The number of characters from the input string.
References replace().
MutableString & B::MutableString::replace (iterator it1, iterator it2, size_type n, UniChar c)
Replaces characters with UniChars.
Replaces all characters of the range [first, last) with n occurrences of character c.
Parameters
it1 The start of the range of characters to replace.
it2 The end of the range of characters to replace.
n The number of occurrences of c to insert.
c The character to insert.
References replace().
template<class InputIterator > MutableString & B::MutableString::replace (iterator it1, iterator it2, InputIterator first, InputIterator last)
Replaces characters with a range.
Replaces all characters of the range [first, last) with all characters of the range [it1, it2).
Parameters
it1 The start of the range of characters to erase.
it2 The end of the range of characters to erase.
first The start of the range of characters to insert.
last The end of the range of characters to insert.
References replace().
MutableString::size_type B::MutableString::find (UniChar c, size_type pos = 0) const
Finds the first occurrence of given character.
Searches for the first occurrence of the character c, starting at index pos.
Returns
The index of c, or npos if not found.
Parameters
c The character to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::rfind (UniChar c, size_type pos = 0) const
Finds the last occurrence of given character.
Searches for the last occurrence of the character c, starting at index pos.
Returns
The index of c, or npos if not found.
Parameters
c The character to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find (const MutableString & str, size_type pos = 0) const
Finds the first MutableString.
Searches for the first occurrence of the string str, starting at index pos.
Returns
The index of str, or npos if not found.
Parameters
str The string to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::rfind (const MutableString & str, size_type pos = 0) const
Finds the last MutableString.
Searches for the last occurrence of the string str, starting at index pos.
Returns
The index of str, or npos if not found.
Parameters
str The string to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::find (CFStringRef cfstr, size_type pos = 0) const
Finds the first CFStringRef.
Searches for the first occurrence of the string cfstr, starting at index pos.
Returns
The index of cfstr, or npos if not found.
Parameters
cfstr The string to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::rfind (CFStringRef cfstr, size_type pos = 0) const
Finds the last CFStringRef.
Searches for the last occurrence of the string cfstr, starting at index pos.
Returns
The index of cfstr, or npos if not found.
Parameters
cfstr The string to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the first UniChar array.
Searches for the first occurrence of the UniChar array ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of sstr, or npos if not found.
Parameters
ustr The string to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::rfind (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the last UniChar array.
Searches for the last occurrence of the UniChar array ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of sstr, or npos if not found.
Parameters
ustr The string to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::find (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first std::string.
Searches for the first occurrence of the string sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of sstr, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString::size_type B::MutableString::rfind (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last std::string.
Searches for the last occurrence of the string sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of sstr, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_first_of (const MutableString & str, size_type pos = 0) const
Finds the first character in a set given as a MutableString.
Searches for the first occurrence of a character contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::find_first_not_of (const MutableString & str, size_type pos = 0) const
Finds the first character not in a set given as a MutableString.
Searches for the first occurrence of a character not contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::find_first_of (CFStringRef cfstr, size_type pos = 0) const
Finds the first character in a set given as a CFStringRef.
Searches for the first occurrence of a character contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_first_not_of (CFStringRef cfstr, size_type pos = 0) const
Finds the first character not in a set given as a CFStringRef.
Searches for the first occurrence of a character not contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_first_of (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the first character in a set given as a UniChar array.
Searches for the first occurrence of a character contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::find_first_not_of (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the first character not in a set given as a UniChar array.
Searches for the first occurrence of a character not contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::find_first_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first character in a set given as a std::string.
Searches for the first occurrence of a character contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_first_not_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the first character not in a set given as a std::string.
Searches for the first occurrence of a character not contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_last_of (const MutableString & str, size_type pos = 0) const
Finds the last character in a set given as a MutableString.
Searches for the last occurrence of a character contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::find_last_not_of (const MutableString & str, size_type pos = 0) const
Finds the last character not in a set given as a MutableString.
Searches for the last occurrence of a character not contained in str, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
str The set of characters to look for.
pos The starting position for the search.
References cf_ref().
MutableString::size_type B::MutableString::find_last_of (CFStringRef cfstr, size_type pos = 0) const
Finds the last character in a set given as a CFStringRef.
Searches for the last occurrence of a character contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_last_not_of (CFStringRef cfstr, size_type pos = 0) const
Finds the last character not in a set given as a CFStringRef.
Searches for the last occurrence of a character not contained in cfstr, starting at index pos.
Returns
The index of the found character, or npos if not found.
Parameters
cfstr The set of characters to look for.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_last_of (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the last character in a set given as a UniChar array.
Searches for the last occurrence of a character contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::find_last_not_of (const UniChar * ustr, size_type pos = 0, size_type n = String::npos) const
Finds the last character not in a set given as a UniChar array.
Searches for the last occurrence of a character not contained in ustr of length n, starting at index pos. If n equals npos, then ustr is assumed to be null-terminated.
Returns
The index of the found character, or npos if not found.
Parameters
ustr The set of characters to look for.
pos The starting position for the search.
n The number of characters in ustr.
MutableString::size_type B::MutableString::find_last_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last character in a set given as a std::string.
Searches for the last occurrence of a character contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString::size_type B::MutableString::find_last_not_of (const std::string & sstr, CFStringEncoding encoding, size_type pos = 0) const
Finds the last character not in a set given as a std::string.
Searches for the last occurrence of a character not contained in sstr, starting at index pos. The input string is assumed to be encoded using the character encoding given in encoding.
Returns
The index of the found character, or npos if not found.
Parameters
sstr The string to look for.
encoding The character encoding of blob.
pos The starting position for the search.
MutableString B::MutableString::substr (size_type pos = 0, size_type n = String::npos) const
Returns a substring.
Returns a substring of, at most, n characters of the string *this starting with index pos.
Parameters
pos The starting position for the substring.
n The length of the substring.
References cf_ref(), get_allocator(), and MutableString().
The documentation for this class was generated from the following files:
BMutableString.h
BMutableString.cpp