B: B::DOC_POLICY Class Reference
B::DOC_POLICY Class Reference
Template for an document policy class.
#include <BDocumentPolicyConcept.h>
Public Member Functions
Constructor & Destructor
DOC_POLICY (AEObject *inApplication, const Bundle &inBundle, Nib *inAppNib)
~DOC_POLICY ()
Destructor. Releases resources.
Setup
void Init ()
void RegisterAppleEvents (AEObjectSupport &ioObjectSupport)
Inquiries
FactoryType & GetFactory ()
Returns the policy's document factory.
AppleEvent Handlers
void OpenApplication ()
The application calls this to handle the Open Application ('oapp') event.
void ReopenApplication ()
The application calls this to handle the Reopen Application ('rapp') event.
void QuitApplication (OSType inSaveOption=kAEAsk)
The application calls this to handle the Quit Application ('quit') event.
AEObject * OpenNewDocument (DescType inDocClass, const AEDesc &inProperties, const AEDesc &inData)
The application calls this to handle the "make" ('crel') event for documents.
Document Access
SInt32 CountDocuments (DescType inDocClass) const
Returns the number of documents of the given class.
AEObject * GetDocumentByIndex (DescType inDocClass, unsigned inIndex) const
Returns the document of the given class with the given index.
AEObject * GetDocumentByName (DescType inDocClass, const String &inName) const
Returns the document of the given class with the given name.
AEObject * GetDocumentByUniqueID (DescType inDocClass, SInt32 inUniqueID) const
Returns the document of the given class with the given unique ID.
Detailed Description
Template for an document policy class.
DOC_POLICY isn't a class; rather, its specifies the required interface for a class in order for it to be useable as a template parameter. So for example, if a class Foo is declared like so:
template <class DOC_POLICY> Foo { ... };
and class Bar implements the interface described herein, then one can instantiate Foo with Bar:
class MyFoo : public Foo<Bar> { ... };
Todo:
COMPLETE THIS DESCRIPTION !!!
Currently, only the Application class takes DOC_POLICY as a template parameter.
There are 3 notable examples of implementations of DOC_POLICY:
NullDocumentPolicy, for applications that don't use documents.
FixedDocumentPolicy, for applications that only support a single hard-wired document.
MultipleDocumentPolicy, for applications that can open more than one document at a time.
Constructor & Destructor Documentation
B::DOC_POLICY::DOC_POLICY (AEObject * inApplication, const Bundle & inBundle, Nib * inAppNib)
Constructor.
The implementation may install CarbonEvent handlers on inTarget for document-related menu commands. It may also keep a reference to inBundle and inAppNib, so these objects' lifetimes need to be at least as long as that of the document policy object.
Parameters
inApplication The AEObject representing the application. The bundle from which to obtain document type information.
inBundle The nib from which to load each document's UI; it may be NULL, in which case it is assumed that windows will load their own nibs.
Member Function Documentation
void B::DOC_POLICY::Init ()
Post-constructor initialisation. The application calls this once its initialisation is complete.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::Initialize().
void B::DOC_POLICY::RegisterAppleEvents (AEObjectSupport & ioObjectSupport)
The application calls this to let the document policy install the AppleEvent handlers it requires.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::RegisterAppleEvents().
void B::DOC_POLICY::QuitApplication (OSType inSaveOption = kAEAsk)
The application calls this to handle the Quit Application ('quit') event.
Parameters
inSaveOption Hint as to what to do with unsaved documents.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObject* B::DOC_POLICY::OpenNewDocument (DescType inDocClass, const AEDesc & inProperties, const AEDesc & inData)
The application calls this to handle the "make" ('crel') event for documents.
Returns
The newly created document.
Parameters
inDocClass The AEObject class of the document. Initial properties for the document (optional).
inProperties Initial intrinsic data for the document (optional).
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
SInt32 B::DOC_POLICY::CountDocuments (DescType inDocClass) const
Returns the number of documents of the given class.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the element count for a class A needs to include instances of classes derived from A.
Parameters
inDocClass The base class ID of the elements to count; must match the application's AppleScript dictionary.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObject* B::DOC_POLICY::GetDocumentByIndex (DescType inDocClass, unsigned inIndex) const
Returns the document of the given class with the given index.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "index-space" for an instance of class A includes instances of classes derived from A.
Parameters
inDocClass The base class ID of the elements to count; must match the application's AppleScript dictionary. The element's zero-based index.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObject* B::DOC_POLICY::GetDocumentByName (DescType inDocClass, const String & inName) const
Returns the document of the given class with the given name.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "name-space" for an instance of class A includes instances of classes derived from A.
Parameters
inDocClass The base class ID of the elements to count; must match the application's AppleScript dictionary. The element's name.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
AEObject* B::DOC_POLICY::GetDocumentByUniqueID (DescType inDocClass, SInt32 inUniqueID) const
Returns the document of the given class with the given unique ID.
Returns
A valid AEObject. In case of error an exception is thrown.
Exceptions
UnknownElementException If the class ID is unknown to the container.
Note
In general, the "id-space" for an instance of class A includes instances of classes derived from A.
Parameters
inDocClass The base class ID of the elements to count; must match the application's AppleScript dictionary. The element's unique id.
Referenced by B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication().
The documentation for this class was generated from the following file:
BDocumentPolicyConcept.h