B: B::DataBrowserItem Class Reference
B::DataBrowserItem Class Reference
Views
An item in a DataBrowser.
#include <BDataBrowserItem.h>
Public Member Functions
DataBrowserItem * GetParent () const
DataBrowserItemState GetState () const
bool IsSelected () const
bool IsOpen () const
UInt16 GetHeight () const
::Rect GetBounds (DataBrowserPropertyID inProperty, DataBrowserPropertyPart inPropertyPart) const
void Open ()
void Close ()
void Select ()
void Reveal (DataBrowserPropertyID inProperty, bool inCenterInView=false)
void Update (DataBrowserPropertyID inProperty)
virtual bool IsActive () const
virtual bool IsSelectable () const
virtual bool IsEditable (DataBrowserPropertyID inProperty) const
virtual bool IsContainer () const
virtual void ItemAdded ()
virtual void ItemRemoved ()
virtual void ItemSelected ()
virtual void ItemDeselected ()
virtual void ItemDoubleClicked ()
virtual void ContainerOpened ()
virtual bool IsContainerOpenable () const
virtual bool IsContainerClosable () const
virtual bool IsContainerSortable () const
virtual DataBrowserItemID GetContainerAliasID () const
virtual DataBrowserPropertyID GetMainProperty () const
virtual void ContainerClosing ()
virtual void ContainerClosed ()
virtual void ContainerSorting ()
virtual void ContainerSorted ()
virtual void UserToggledContainer ()
virtual void TargetChanged ()
virtual void EditStarted ()
virtual void EditStopped ()
virtual bool GetData (DataBrowserItemData &inItemData, DataBrowserPropertyID inProperty) const
virtual bool SetData (DataBrowserItemData &inItemData, DataBrowserPropertyID inProperty)
virtual int CompareTo (const DataBrowserItem &inItem, DataBrowserPropertyID inProperty) const
virtual bool AddDragFlavors (Drag &ioDrag, PasteboardItemID &outItemID) const
virtual bool IsDragAcceptable (const Drag &inDrag) const
virtual bool ReceiveDrag (const Drag &inDrag)
virtual bool SupplyHelpContent (DataBrowserPropertyID inProperty, String &outMinContent, bool &outMinContentIsLocalized, String &outMaxContent, bool &outMaxContentIsLocalized)
virtual bool KeyFilter (UInt16 &ioKeyCode, UInt16 &ioCharCode, EventModifiers &ioModifiers, bool &outPassUp)
virtual bool GetProperty (DataBrowserItemData &inItemData, DataBrowserPropertyID inProperty) const
virtual void CustomDraw (DataBrowserPropertyID inProperty, DataBrowserItemState inItemState, const Rect &inRect, SInt16 inDepth, Boolean inColorDevice) const
virtual bool CustomEdit (DataBrowserPropertyID inProperty, const String &inString, Rect &outMaxEditTextRect, bool &outShrinkToFit) const
virtual bool CustomHitTest (DataBrowserPropertyID inProperty, const Rect &inRect, const Rect &inMouseRect) const
virtual DataBrowserTrackingResult CustomTrack (DataBrowserPropertyID inProperty, const Rect &inRect, const Point &inStartPt, EventModifiers inModifiers) const
virtual void CustomDragRgn (DataBrowserPropertyID inProperty, const Rect &inRect, RgnHandle ioDragRgn) const
virtual bool CustomAcceptDrag (DataBrowserPropertyID inProperty, const Rect &inRect, DragRef inDragRef) const
virtual bool CustomReceiveDrag (DataBrowserPropertyID inProperty, DataBrowserDragFlags inDragFlags, DragRef inDragRef) const
Protected Member Functions
void SetParent (DataBrowserItem *inParentItem)
virtual void SetBrowser (DataBrowser *inBrowser)
Protected Attributes
DataBrowser * mDataBrowser
Friends
class DataBrowser
Detailed Description
An item in a DataBrowser.
Todo:
Document this class!
Member Function Documentation
void B::DataBrowserItem::Open ()
Opens the item (assuming it's a container).
void B::DataBrowserItem::Close ()
Closes the item (assuming it's a container).
bool B::DataBrowserItem::IsActive () const virtual
The data browser calls this member function to determine if the item is active. Override it if you want inactive items.
bool B::DataBrowserItem::IsSelectable () const virtual
The data browser calls this member function to determine if the item is selectable. Override it if you want selectable items.
bool B::DataBrowserItem::IsEditable (DataBrowserPropertyID inProperty) const virtual
The data browser calls this member function to determine if the item is editable. Override it if you want editable items.
bool B::DataBrowserItem::IsContainer () const virtual
The data browser calls this member function to determine if the item is a container. Override it if you want to implement containers.
void B::DataBrowserItem::ItemAdded () virtual
The data browser calls this member function just after the item has been added to the browser. Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ItemRemoved () virtual
The data browser calls this member function just after it removes the item from the browser. Override it to perform any special processing. The default behaviour is to delete the object.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ItemSelected () virtual
The data browser calls this member function when it selects the item. Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ItemDeselected () virtual
The data browser calls this member function when it deselects the item. Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ItemDoubleClicked () virtual
The data browser calls this member function when the user double-clicks the item. Override it to perform any special processing.
Referenced by B::DataBrowser::DoubleClickedItem().
void B::DataBrowserItem::ContainerOpened () virtual
The data browser calls this member function when it has opened the item (which is assumed to be a container). Override it to perform any special processing. For example, a derived class that implements container hierarchies will probably want to populate the container from within an override of this function.
Referenced by B::DataBrowser::ItemNotification().
bool B::DataBrowserItem::IsContainerOpenable () const virtual
The data browser calls this member function to determine if the item is a container and is openable. Override it if you want to implement openable containers.
bool B::DataBrowserItem::IsContainerClosable () const virtual
The data browser calls this member function to determine if the item is a container and is closeable. Override it if you want to implement closeable containers.
bool B::DataBrowserItem::IsContainerSortable () const virtual
The data browser calls this member function to determine if the item is a container and is sortable. Override it if you want to implement sortable containers.
void B::DataBrowserItem::ContainerClosing () virtual
The data browser calls this member function when it is about to close the item (which is assumed to be a container). Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ContainerClosed () virtual
The data browser calls this member function when it has finished closing the item (which is assumed to be a container). Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ContainerSorting () virtual
The data browser calls this member function when it is about to sort the item (which is assumed to be a container). Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
void B::DataBrowserItem::ContainerSorted () virtual
The data browser calls this member function when it has finished sorting the item (which is assumed to be a container). Override it to perform any special processing.
Referenced by B::DataBrowser::ItemNotification().
bool B::DataBrowserItem::GetData (DataBrowserItemData & inItemData, DataBrowserPropertyID inProperty) const virtual
The data browser calls this member function when it wants to display one column's worth of data for one item. You need to override this member function in order to supply the data for your column properties.
Referenced by B::DataBrowser::GetSetItemData().
bool B::DataBrowserItem::SetData (DataBrowserItemData & inItemData, DataBrowserPropertyID inProperty) virtual
The data browser calls this member function when it wants to modify one column's worth of data for one item. You need to override this member function in order to fetch the data for your column properties.
Referenced by B::DataBrowser::GetSetItemData().
int B::DataBrowserItem::CompareTo (const DataBrowserItem & inItem, DataBrowserPropertyID inProperty) const virtual
The data browser calls this member function when it wants to compare two items (in order to sort them). inProperty is the property (i.e., column) on which to perform the comparison. You need to override this member function in your derived class if you want to implement sorted columns. The function should return a value greater than, equal to, or less than zero, depending on whether the item compares greater than, equal to, or less than inItem.
Referenced by B::DataBrowser::Compare().
bool B::DataBrowserItem::AddDragFlavors (Drag & ioDrag, PasteboardItemID & outItemID) const virtual
This item is being dragged. Add this item's flavor data (or promised flavors) to the drag reference.
Referenced by B::DataBrowser::AddDragItem().
bool B::DataBrowserItem::IsDragAcceptable (const Drag & inDrag) const virtual
Returns whether a given drag to this item is acceptable. This will be false unless the item is a container.
Referenced by B::DataBrowser::IsDragOnItemAcceptable().
bool B::DataBrowserItem::ReceiveDrag (const Drag & inDrag) virtual
Receive the given drag, and return success or failure.
Referenced by B::DataBrowser::ReceiveDragOnItem().
bool B::DataBrowserItem::KeyFilter (UInt16 & ioKeyCode, UInt16 & ioCharCode, EventModifiers & ioModifiers, bool & outPassUp) virtual
The function determines if the character given in ioKeyCode/ioCharCode is acceptable. Returns true if the character is accepted. If it isn't, outPassUp determines if the character should be passed to the browser and on up through the commander chain.
References B::View::IsActive().
Referenced by B::DataBrowser::ReceiveDragOnItem().
The documentation for this class was generated from the following files:
BDataBrowserItem.h
BDataBrowserItem.cpp