B: B::Dialog Class Reference
B::Dialog Class Reference
Modal Dialogs, Modeless Dialogs, and Sheets.
#include <BDialog.h>
Classes
struct NullCallback
Convenience callback that does nothing.
Public Member Functions
Dialog (WindowRef inWindowRef, AEObjectPtr inContainer, DescType inClassID=cWindow)
Constructor.
Public Member Functions inherited from B::Window
void Select ()
void Show (bool showIt)
void Transition (WindowTransitionEffect inEffect, WindowTransitionAction inAction, Rect *inRect=NULL, Window *inParent=NULL)
void Reposition (WindowPositionMethod inMethod, Window *inParent=NULL)
virtual void Close ()
virtual void CloseWindow (OSType inSaveOption=kAEAsk, const Url &inUrl=Url())
bool IsComposited () const
bool IsVisible () const
bool IsZoomable () const
bool IsZoomed () const
bool IsCollapseable () const
bool IsCollapsed () const
bool IsCloseable () const
bool IsResizeable () const
bool IsFloating () const
bool IsModal () const
String GetName () const
HIViewRef GetContentView () const
operator WindowRef () const
Returns the object's underlying WindowRef.
WindowRef GetWindowRef () const
Returns the object's underlying WindowRef.
HIObjectRef GetObjectRef () const
Returns the object's underlying HIObjectRef.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
void SetMinimumSize (const Size &inMinimumSize)
void SetMaximumSize (const Size &inMaximumSize)
void SetIdealSize (const Size &inIdealSize)
void SetTitle (const String &inTitle)
void SetAlternateTitle (const String &inTitle)
void SetProxy (const Icon &inIcon)
void SetProxy (const Url &inUrl)
void SetProxy (OSType inCreator, OSType inFileType)
void ClearProxy ()
void SetModified (bool inModified)
void Zoom (bool inZoomItOut)
void Collapse (bool inCollapse)
Rect GetContentViewBounds () const
Rect GetStructureBounds () const
Point GetStructureOrigin () const
Size GetStructureSize () const
Rect GetContentBounds () const
Point GetContentOrigin () const
Size GetContentSize () const
void SetStructureBounds (const Rect &inBounds)
void MoveStructureTo (const Point &inOrigin)
void MoveStructureBy (float inDeltaX, float inDeltaY)
void ResizeStructureTo (const Size &inSize)
void ResizeStructureBy (float inDeltaWidth, float inDeltaHeight)
void SetContentBounds (const Rect &inBounds)
void ResizeContentTo (const Size &inSize)
void ResizeContentBy (float inDeltaWidth, float inDeltaHeight)
void MoveContentTo (const Point &inOrigin)
void MoveContentBy (float inDeltaX, float inDeltaY)
void SetToolbar (OSPtr< HIToolbarRef > inToolbar)
void ShowToolbar (bool inShowIt, bool inAnimate)
bool IsToolbarVisible () const
void AddToWindowList ()
void RemoveFromWindowList ()
bool IsInWindowList () const
virtual void WriteProperty (DescType inPropertyID, AEWriter &ioWriter) const
virtual void ReadProperty (DescType inPropertyID, AEReader &ioReader)
virtual void CloseObject (OSType inSaveOption=kAEAsk, const Url &inFileUrl=Url())
virtual void ActivateObject ()
virtual void DebugPrint () const
template<class VIEW >
void Register (CFStringRef inClassId, SInt32 inID)
Registers the class VIEW for HIViewRefs with the given class ID and inID.
template<class VIEW >
void Register (CFStringRef inClassId)
Registers the class VIEW for HIViewRefs with the given class ID and any id.
template<class VIEW >
VIEW * FindView (int inID) const
Returns the view matching the main bundle's signature and inID.
template<class VIEW >
VIEW * FindView (OSType inSignature, int inID) const
template<class VIEW >
VIEW * FindView (int inID, const std::nothrow_t &) const
Returns the view matching the main bundle's signature and inID, or NULL.
template<class VIEW >
VIEW * FindView (OSType inSignature, int inID, const std::nothrow_t &) const
Public Member Functions inherited from B::AEObject
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::iterator > MakeObjectListSpecifier (CONTAINER &container)
template<class CONTAINER >
ObjectListSpecifier< typename CONTAINER::const_iterator > MakeObjectListSpecifier (const CONTAINER &container)
AEObject (AEObjectPtr inContainer, DescType inClassID)
Constructor.
virtual ~AEObject ()
Destructor.
void SetContainer (AEObjectPtr inContainer)
Changes the object's container.
virtual unsigned GetIndex () const
Returns the object's (zero-based) index within its container.
virtual SInt32 GetUniqueID () const
Returns the object's unique id.
virtual size_t CountElements (DescType inElementType) const
Returns the number of elements of the given class.
virtual AEObjectPtr GetElementByIndex (DescType inElementType, size_t inIndex) const
Returns the element of the given class with the given index.
virtual AEObjectPtr GetElementByUniqueID (DescType inElementType, SInt32 inUniqueID) const
Returns the element of the given class with the given unique ID.
virtual AEObjectPtr GetElementByName (DescType inElementType, const String &inName) const
Returns the element of the given class with the given name.
virtual void GetAllElements (DescType inElementType, std::list< AEObjectPtr > &outElements) const
Returns all of the elements of the given class.
virtual AEObjectPtr GetPropertyObject (DescType inPropertyID) const
Returns the AEObject matching a given property, if any.
template<typename ITERATOR >
void GetPropertyIDs (boost::tribool inInProperties, boost::tribool inWriteable, ITERATOR inIterator) const
Writes the value of the property identified by inPropertyID into ioWriter.
template<typename ITERATOR >
void WriteProperties (ITERATOR inFirstPropertyID, ITERATOR inLastPropertyID, AEWriter &ioWriter) const
Writes the value of the property identified by inPropertyID into ioWriter.
virtual void AccessElements (const AEInfo::ClassInfo &inClassInfo, DescType inDesiredClass, DescType inKeyForm, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements and properties, according to inKeyForm and inKeyData.
virtual void AccessElementsByAbsolutePos (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formAbsolutePosition and inKeyData.
virtual void AccessElementsByName (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formName and inKeyData.
virtual void AccessElementsByUniqueID (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formUniqueID and inKeyData.
virtual void AccessElementsByRange (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRange and inKeyData.
virtual void AccessElementsByRelativePosition (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formRelativePosition and inKeyData.
virtual void AccessElementsByTest (const AEInfo::ClassInfo &inClassInfo, const AEInfo::ElementInfo &inElementInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access elements according to formTest and inKeyData.
virtual void AccessProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inKeyData.
virtual void AccessPropertyByID (const AEInfo::ClassInfo &inClassInfo, DescType inPropertyID, AEDesc &outTokenDesc) const
Access properties according to formPropertyID and inPropertyID.
virtual void AccessUserProperty (const AEInfo::ClassInfo &inClassInfo, const AEDesc &inKeyData, AEDesc &outTokenDesc) const
Access properties according to formUserPropertyID and inKeyData.
virtual AEObjectPtr CloneObject (DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties)
Implements the AppleScript "duplicate" event.
virtual AEObjectPtr CreateObject (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord &inProperties, const AEDesc &inData)
Implements the AppleScript "make" event.
virtual void DeleteObject ()
Implements the AppleScript "delete" event.
virtual AEObjectPtr MoveObject (DescType inPosition, AEObjectPtr inTarget)
Implements the AppleScript "move" event.
virtual void OpenObject ()
Implements the AppleScript "open" event.
virtual void PrintObject (PrintSettings *inSettings, Printer *inPrinter, bool inShowDialog)
Implements the AppleScript "print" event.
virtual void SaveObject (const Url &inUrl=Url(), const String &inObjectType=String())
Implements the AppleScript "save" event.
virtual void RevertObject ()
Implements the AppleScript "revert" event.
virtual void WriteValue (AEWriter &ioWriter) const
Writes the value of the object into ioWriter.
AEObjectPtr GetAEObjectPtr ()
Returns a shared pointer to the given object.
ConstAEObjectPtr GetAEObjectPtr () const
Returns a shared pointer to the given object (const variant).
AEObjectPtr GetContainer () const
Returns the object's container.
DescType GetClassID () const
Returns the object's classID.
bool InheritsFrom (DescType inBaseClassID) const
Returns true if the object's class is or derives from inBaseClassID.
AEObjectPtr SendCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "duplicate" event to the object.
void SendCloseAppleEvent (OSType inSaveOption=kAEAsk, const Url &inUrl=Url(), AESendMode inMode=0)
Sends a "close" event to the object.
SInt32 SendCountElementsAppleEvent (OSType inObjectClass, AESendMode inMode=0) const
Sends a "close" event to the object.
void SendDeleteAppleEvent (AESendMode inMode=0)
Sends a "delete" event to the object.
void SendGetDataAppleEvent (AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
template<DescType TYPE>
void SendGetDataAppleEvent (typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve the object's data.
void SendGetPropertyAppleEvent (DescType inPropertyID, AEDesc &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
template<DescType TYPE>
void SendGetPropertyAppleEvent (DescType inPropertyID, typename DescParam< TYPE >::ValueType &outValue, DescType inRequestedType=typeWildCard, AESendMode inMode=0) const
Sends a "get" event to retrieve one of the object's properties.
AEObjectPtr SendMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AESendMode inMode=0)
Sends a "move" event to the object.
void SendOpenAppleEvent (AESendMode inMode=0)
Sends a "open" event to the object.
void SendPrintAppleEvent (bool inShowDialog=false, const AERecord *inProperties=NULL, AESendMode inMode=0)
Sends a "print" event to the object.
void SendSaveAppleEvent (const Url &inUrl=Url(), const String &inObjectType=String(), AESendMode inMode=0)
Sends a "save" event to the object.
void SendRevertAppleEvent (AESendMode inMode=0)
Sends a "revert" event to the object.
void SendSelectAppleEvent (AESendMode inMode=0)
Sends a "select" event to the object.
void SendSetDataAppleEvent (const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
template<DescType TYPE>
void SendSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change the object's data.
void SendSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
template<DescType TYPE>
void SendSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AESendMode inMode=0)
Sends "set" event to change one of the object's properties.
void MakeCloneAppleEvent (DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "duplicate" event targeting the object.
void MakeCloseAppleEvent (OSType inSaveOption, const Url &inUrl, AppleEvent &outEvent) const
Creates a "close" event targeting the object.
void MakeCountElementsAppleEvent (OSType inObjectClass, AppleEvent &outEvent) const
Creates a "count" event targeting the object.
void MakeDeleteAppleEvent (AppleEvent &outEvent) const
Creates a "delete" event targeting the object.
void MakeGetDataAppleEvent (DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting the object.
void MakeGetPropertyAppleEvent (DescType inPropertyID, DescType inRequestedType, AppleEvent &outEvent) const
Creates a "get" event targeting one of the object's properties.
void MakeMoveAppleEvent (DescType inPosition, AEObjectPtr inTarget, AppleEvent &outEvent) const
Creates a "move" event targeting the object.
void MakeOpenAppleEvent (AppleEvent &outEvent) const
Creates a "open" event targeting the object.
void MakePrintAppleEvent (bool inShowDialog, const AERecord *inProperties, AppleEvent &outEvent) const
Creates a "print" event targeting the object.
void MakeRevertAppleEvent (AppleEvent &outEvent) const
Creates a "revert" event targeting the object.
void MakeSaveAppleEvent (const Url &inUrl, const String &inObjectType, AppleEvent &outEvent) const
Creates a "save" event targeting the object.
void MakeSelectAppleEvent (AppleEvent &outEvent) const
Creates a "select" event targeting the object.
void MakeSetDataAppleEvent (const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
template<DescType TYPE>
void MakeSetDataAppleEvent (const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting the object.
void MakeSetPropertyAppleEvent (DescType inPropertyID, const AEDesc &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
template<DescType TYPE>
void MakeSetPropertyAppleEvent (DescType inPropertyID, const typename DescParam< TYPE >::ValueType &inValue, AppleEvent &outEvent) const
Creates a "set" event targeting one of the object's properties.
virtual void MakePropertySpecifier (DescType inPropertyID, AEWriter &ioWriter) const
Writes out an object specifier representation of one of the object's properties.
virtual bool Compare (DescType inComparisonOp, ConstAEObjectPtr inObject) const
Returns true if the object compares to inObject, according to inComparisonOp.
Protected Member Functions
virtual bool HandleCommand (const HICommandExtended &inHICommand)
Protected Member Functions inherited from B::Window
void PostCreateWindow (Nib *inFromNib)
virtual void RegisterViews ()
View * Instantiate (HIViewRef inViewRef) const
virtual bool ShouldWindowClose ()
virtual Size GetIdealSize () const
virtual void HandleShowing ()
virtual void HandleHiding ()
virtual void HandleShown ()
virtual void HandleHidden ()
virtual void HandleActivated ()
virtual void HandleDeactivated ()
virtual bool HandleFocusAcquired ()
virtual bool HandleFocusRelinquish ()
virtual bool HandleZoomed ()
virtual bool HandleResizeCompleted ()
virtual bool HandleDragCompleted ()
virtual bool HandleTransitionCompleted (void *inUserData)
virtual bool HandleCollapsed ()
virtual bool HandleExpanded ()
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
virtual void HandleSheetOpened (WindowRef inSheetWindowRef)
virtual void HandleSheetClosed (WindowRef inSheetWindowRef)
virtual void MakeSpecifier (AEWriter &ioWriter) const
Window (WindowRef inWindowRef, AEObjectPtr inContainer, DescType inClassID=cWindow)
Constructor. In B, Window objects are created after their WindowRef.
virtual ~Window ()
Destructor.
void operator delete (void *p)
Operator delete.
Protected Member Functions inherited from B::AEObject
void WritePropertiesProperty (AEWriter &ioWriter, bool inWriteableOnly) const
Writes the pProperties property into ioWriter.
void ReadPropertiesProperty (AEReader &ioReader, bool inIgnoreReadOnly)
Reads the pProperties property from ioReader.
void ConvertIndexedKeyData (const AEDesc &inKeyData, size_t inNumElements, size_t &outIndex, bool &outWantsAll) const
Reads the key data for formAbsolutePosition.
AEObjectPtr ResolveBoundsToken (const AEDesc &inKeyData, AEKeyword inKeyword) const
Reads a boundary object for formRange.
const AEInfo::ClassInfo & GetClassInfo () const
Inquiries
UInt32 GetDismissingCommand () const
Returns the dialog's dismissing command.
Modifiers
void SetModality (const DialogModality &inModality)
Sets the dialog's modality, which determines its behaviour when it is displayed and dismissed.
void SetCloseOnDismiss (bool inCloseOnDismiss)
Determines whether the dialog gets closed (i.e. destroyed) after it's dismissed.
void SetAnimateOnDismiss (bool inAnimate)
Determines whether the dialog will animate when it's dismissed.
template<class DIALOG >
void SetCallback (B_DIALOG_CB inFunction)
Installs a callback that will be called once the dialog is dismissed.
Making Dialogs
In B parlance, "Making" a dialog means to instantiate it, returning a smart pointer (in this case, an OSPtr<WindowRef>) that controls its lifetime.
template<class DIALOG >
static boost::shared_ptr< DIALOG > Make (Nib &inNib, const char *inDialogName, AEObjectPtr inContainer, const DialogModality &inModality, B_DIALOG_CB inFunction=NullCallback< DIALOG >())
Instantiates and returns a DIALOG with the given modality and callback.
template<class DIALOG , typename STATE >
static boost::shared_ptr< DIALOG > MakeWithState (Nib &inNib, const char *inDialogName, AEObjectPtr inContainer, STATE inState, const DialogModality &inModality, B_DIALOG_CB inFunction=NullCallback< DIALOG >())
Instantiates and returns a DIALOG with the given modality and callback, passing inState to its constructor.
Entering Dialogs
In B parlance, "Entering" a dialog means to display it according to its modality, i.e. if it's application-modal then the function doesn't return until the dialog is dismissed.
void Enter ()
Displays the dialog according to its modality.
template<class DIALOG >
static void Enter (boost::shared_ptr< DIALOG > inDialogPtr)
Displays the given dialog according to its modality, taking control of the dialog's lifetime.
Starting Dialogs
In B parlance, "Starting" is shorthand for "Making" followed by "Entering".
template<class DIALOG >
static void Start (Nib &inNib, const char *inDialogName, AEObjectPtr inContainer, const DialogModality &inModality, B_DIALOG_CB inFunction=NullCallback< DIALOG >())
Instantiates a DIALOG with the given modality and callback, then enters it.
Running Dialogs
These are convenience functions for displaying dialogs in an application-modal fashion. Because they don't return until the dialog is dismissed, the dismissing command is returned as the function result.
UInt32 Run ()
Displays the dialog in an application-modal fashion.
UInt32 EnterAppModalLoop ()
Deprecated. Use Run() instead.
template<class DIALOG , typename STATE >
static UInt32 RunWithState (Nib &inNib, const char *inDialogName, AEObjectPtr inContainer, STATE inState)
Instantiates a DIALOG, then enters a modal event loop for it.
template<class DIALOG >
static UInt32 Run (Nib &inNib, const char *inDialogName, AEObjectPtr inContainer)
Overridables
virtual void ConfirmDialog (UInt32 inCommand)
Called in response to dialog-confirming action on the part of the user.
virtual void CancelDialog (UInt32 inCommand)
Called in response to dialog-infirming action on the part of the user.
virtual bool Validate (UInt32 inCommand)
Hook to perform input validation.
virtual void DismissDialog (UInt32 inCommand)
Dismisses the dialog.
Additional Inherited Members
Static Public Member Functions inherited from B::Window
static Window * FromWindowRef (WindowRef inWindowRef)
static SInt32 CountWindowsOfClass (DescType inClassID)
static Window * GetWindowOfClassByIndex (DescType inClassID, unsigned inIndex)
static Window * GetWindowOfClassByName (DescType inClassID, const String &inName)
static Window * GetWindowOfClassByUniqueID (DescType inClassID, SInt32 inUniqueID)
template<class WINDOW >
static boost::shared_ptr< WINDOW > CreateFromNib (Nib &inNib, const char *inWindowName, AEObjectPtr inContainer)
Create a window and its views from a nib.
template<class WINDOW , typename STATE >
static boost::shared_ptr< WINDOW > CreateFromNibWithState (Nib &inNib, const char *inWindowName, AEObjectPtr inContainer, STATE inState)
Create a window and its views from a nib.
template<class WINDOW , typename STATE >
static boost::shared_ptr< WINDOW > CreateFromNibWithState (Nib &inNib, const char *inWindowName, STATE inState)
Static Public Member Functions inherited from B::AEObject
static AEObjectPtr GetDefaultObject ()
Returns the default object. This is usually the application.
static void SetDefaultObject (AEObjectPtr inObject)
Sets the default object.
static void BuildNameSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, const String &inName, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and name in the given container.
static void BuildIndexSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inIndex, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and index in the given container.
static void BuildUniqueIDSpecifier (ConstAEObjectPtr inContainer, DescType inObjectClass, SInt32 inUniqueID, AEWriter &ioWriter)
Write out an object specifier for an element of a given class and unique id in the given container.
static void BuildPropertySpecifier (ConstAEObjectPtr inObject, DescType inPropertyID, AEWriter &ioWriter)
Write out an object specifier for the given property in the given object.
static void WriteTokenValue (const AEToken &inToken, DescType inDesiredType, AEWriter &ioValueWriter)
static void WriteTokenValue (const AEToken &inToken, AEWriter &ioValueWriter)
static void WriteTokenSpecifier (const AEToken &inToken, AEWriter &ioValueWriter)
static void RegisterClassEventHandlers (AEObjectSupport &ioObjectSupport)
static bool DoesClassInheritFrom (DescType inClassID, DescType inBaseClassID)
Returns true if inClassID is or derives from inBaseClassID.
static AEObjectPtr SendCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties=NULL, const AEDesc *inData=NULL, AESendMode inMode=0)
Sends a "make" event to the object.
static void MakeCreateElementAppleEvent (DescType inObjectClass, DescType inPosition, AEObjectPtr inTarget, const AERecord *inProperties, const AEDesc *inData, AppleEvent &outEvent)
Creates a "create" event targeting the object.
static AEObjectPtr Resolve (const AEDesc &inDesc)
Resolves an object specifier into a AEObject.
static AEObjectPtr Resolve (const AEDesc &inDesc, const std::nothrow_t &)
Resolves an object specifier into a AEObject (nothrow variant).
static bool CompareObjects (DescType inComparisonOp, ConstAEObjectPtr inObject1, ConstAEObjectPtr inObject2)
Compare two objects according to inComparisonOp.
Static Protected Member Functions inherited from B::AEObject
static bool TestProperty (const AEInfo::PropertyInfo &inPropertyInfo, boost::tribool inInProperties, boost::tribool inWriteable)
static void WriteOneProperty (AEObjectPtr inObject, AEWriter &ioWriter, DescType inPropertyID)
Related Functions inherited from B::AEObject
AEWriter & operator<< (AEWriter &writer, const AEObject &obj)
AEWriter & operator<< (AEWriter &writer, const AEObject *obj)
AEWriter & operator<< (AEWriter &writer, ConstAEObjectPtr ptr)
Detailed Description
Modal Dialogs, Modeless Dialogs, and Sheets.
Dialog is a derivative of window that closes itself when it receives kHICommandOK or kHICommandCancel. Crucially, it can also display itself as a modeless dialog, an application-modal dialog, or a sheet.
Dialog (and any derived classes) should be instantiated via Make() or MakeWithState(); this will ensure that the dialog's window class matches the requested modality.
Once instantiated, the dialog may be entered via Enter().
The Run() and RunWithState() functions are available as a convenience for cases where the caller wants to display the dialog in an application-modal fashion.
See also
Dialogs, Alerts and Navigation Services
Member Function Documentation
void B::Dialog::SetModality (const DialogModality & inModality)
Sets the dialog's modality, which determines its behaviour when it is displayed and dismissed.
Parameters
inModality The dialog's modality.
References B::DialogModality::GetModality(), and B::DialogModality::GetParent().
Referenced by Enter(), and Run().
void B::Dialog::SetAnimateOnDismiss (bool inAnimate)
Determines whether the dialog will animate when it's dismissed.
If the dialog has window-modal modality (i.e., it's a sheet), then a value of true for inAnimate will cause the sheet to hide in the normal way. If inAnimate is false however, the sheet will hide itself without the normal animation, and the parent window will not be notified that the sheet has been hidden. This is meant for cases where dismissing the dialog will have the effect of closing the parent window; it such cases it's undesirable to have the user wait for the animation to complete when the parent window is about to go away anyway. This function is specifically meant to be called from within the dialog callback.
If the dialog is not a sheet, this function does nothing.
template<class DIALOG > void B::Dialog::SetCallback (B_DIALOG_CB inFunction)
Installs a callback that will be called once the dialog is dismissed.
Todo:
Complete this!
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
template<class DIALOG > boost::shared_ptr< DIALOG > B::Dialog::Make (Nib & inNib, const char * inDialogName, AEObjectPtr inContainer, const DialogModality & inModality, B_DIALOG_CB inFunction = NullCallback<DIALOG>()) static
Instantiates and returns a DIALOG with the given modality and callback.
Instantiates a dialog of class DIALOG, from the window definition inDialogName in nib file inNib.
This function checks that the window class (as returned from the nib) matches the modality requested in inModality. If they do not match, a new window is created with reasonable default values for inModality, and the original window's contents (including HIViews) are moved to the new window. An instance of DIALOG is then created with the new window. This mechanism allows callers to define a single window in a nib file, and use it as a modeless dialog, modal dialog, or sheet, depending on circumstances.
The instance of DIALOG is then configured with inModality, inParent, and inFunction. The dialog is then returned, ready to be displayed via Enter().
The function result type needs some explaining. It's an std::pair, with the first element holding a smart pointer to a WindowRef, and the second holding a pointer to the DIALOG object. The reason for this is that the dialog's lifetime is controlled by the smart pointer; one can't destroy a dialog object by calling operator delete on it. So if an exception occurs further up the call chain, the dialog will be disposed properly when the smart pointer is destructed. Obviously, the second part of the pair (the DIALOG pointer) is there for convenient type-safe access to the dialog object.
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
Parameters
inNib The nib file from which to read the dialog.
inDialogName The dialog's name in the nib file.
inContainer The AEOM container of the dialog. This will usually be the application or a document.
inModality The dialog's modality.
inFunction A callback that is invoked when the dialog is dismissed.
template<class DIALOG , typename STATE > boost::shared_ptr< DIALOG > B::Dialog::MakeWithState (Nib & inNib, const char * inDialogName, AEObjectPtr inContainer, STATE inState, const DialogModality & inModality, B_DIALOG_CB inFunction = NullCallback<DIALOG>()) static
Instantiates and returns a DIALOG with the given modality and callback, passing inState to its constructor.
This function is identical to Make(), except that the DIALOG constructor will be passed an object of type STATE. This can be used to communicate information between the dialog and the code that instantiates it.
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
STATE Template parameter. Any C/C++ type. It is passed to DIALOG's constructor but is otherwise uninterpreted.
See also
Make()
Parameters
inNib The nib file from which to read the dialog.
inDialogName The dialog's name in the nib file.
inContainer The AEOM container of the dialog. This will usually be the application or a document.
inState Some state that is passed to DIALOG's constructor.
inModality The dialog's modality.
inFunction A callback that is invoked when the dialog is dismissed.
void B::Dialog::Enter ()
Displays the dialog according to its modality.
The exact action performed depends on the dialog's modality:
For a modeless dialog, the dialog is shown and made active. The function returns immediately.
For a modal dialog, the dialog is shown and a modal event loop is entered. The loop can only be exited by calling DismissDialog(), which will happend automatically if the user clicks an OK or Cancel button.
For a sheet, the dialog is shown attached to its parent. The function returns immediately.
For modal dialogs and sheets, if an interaction timeout exception occurs, the dialog callback (if any) is called immediately with kHICommandCancel, then the function returns.
Derived classes wishing to perform some processing prior to the dialog becoming visible should override Window::HandleShowing().
References B::DialogModality::Modal(), and SetModality().
Referenced by Run(), and Start().
template<class DIALOG > void B::Dialog::Enter (boost::shared_ptr< DIALOG > inDialogPtr) static
Displays the given dialog according to its modality, taking control of the dialog's lifetime.
Parameters
inDialogPtr The dialog to enter.
template<class DIALOG > void B::Dialog::Start (Nib & inNib, const char * inDialogName, AEObjectPtr inContainer, const DialogModality & inModality, B_DIALOG_CB inFunction = NullCallback<DIALOG>()) static
Instantiates a DIALOG with the given modality and callback, then enters it.
Instantiates a dialog of class DIALOG, as per Make(). The dialog is then displayed via Enter(). Whether the dialog has been dismissed by the time the function returns depends upon inModality. See Enter() for more information.
Note
The dialog is automatically disposed upon dismissal. If you would rather hang on to the dialog (to reuse it later without having to read it in from the nib file again), call Make() or MakeWithState(), then Enter().
The dialog's constructor is not passed a STATE object. If your constructor requires one, call MakeWithState() and Enter() directly.
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
See also
Make(), Enter()
Parameters
inNib The nib file from which to read the dialog.
inDialogName The dialog's name in the nib file.
inContainer The AEOM container of the dialog. This will usually be the application or a document.
inModality The dialog's modality.
inFunction A callback that is invoked when the dialog is dismissed.
References Enter().
UInt32 B::Dialog::Run ()
Displays the dialog in an application-modal fashion.
This function is shorthand for SetModality() / Enter() / GetDismissingCommand(). Refer to those functions' documentation for more information.
Returns
The HICommand that dismissed the dialog.
Note
Unlike Run() and RunWithState(), this function does not dynamically change the dialog's window class to match its modality.
References Enter(), GetDismissingCommand(), B::DialogModality::Modal(), SetCloseOnDismiss(), and SetModality().
Referenced by EnterAppModalLoop().
template<class DIALOG , typename STATE > UInt32 B::Dialog::RunWithState (Nib & inNib, const char * inDialogName, AEObjectPtr inContainer, STATE inState) static
Instantiates a DIALOG, then enters a modal event loop for it.
Instantiates a dialog of class DIALOG, from the window definition inDialogName in nib file inNib. The DIALOG constructor will be passed an object of type STATE. This can be used to communicate information between the window and the code that instantiates it.
The dialog's modality is set to application-modal. After instantiation, the dialog is entered. Control does not return from this function until the dialog is dismissed.
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
STATE Template parameter. Any C/C++ type. It is passed to DIALOG's constructor but is otherwise uninterpreted.
Returns
The HICommand that dismissed the dialog.
Parameters
inNib The nib file from which to read the dialog.
inDialogName The dialog's name in the nib file.
inContainer The AEOM container of the dialog. This will usually be the application or a document.
inState Some state that is passed to DIALOG's constructor.
References B::DialogModality::Modal().
template<class DIALOG > UInt32 B::Dialog::Run (Nib & inNib, const char * inDialogName, AEObjectPtr inContainer) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Instantiates a dialog of class DIALOG, from the window definition inDialogName in nib file inNib. Then the dialog's modality is set to application-modal, and it is entered. Control does not return from this function until the dialog is dismissed.
Parameters
DIALOG Template parameter. The class of the instantiated window. Must be Dialog or a class derived from Dialog.
Returns
The HICommand that dismissed the dialog.
Parameters
inNib The nib file from which to read the dialog.
inDialogName The dialog's name in the nib file.
inContainer The AEOM container of the dialog. This will usually be the application or a document.
References B::DialogModality::Modal().
UInt32 B::Dialog::EnterAppModalLoop ()
Deprecated. Use Run() instead.
Deprecated:
This function is here for backward compatibility only, and will be removed in a future release.
References Run().
void B::Dialog::ConfirmDialog (UInt32 inCommand) protected virtual
Called in response to dialog-confirming action on the part of the user.
React to a dialog-confirming action on the part of the user. inCommand is the user-generated command (usually kHICommandOK).
The default implementation dismisses the dialog; inCommand becomes the dismissing command, which is returned from EnterModalLoop().
Derived classes may override this function to perform additional processing when a dialog is confirmed. They may assume that Validate() will already have been called.
References DismissDialog().
Referenced by HandleCommand().
void B::Dialog::CancelDialog (UInt32 inCommand) protected virtual
Called in response to dialog-infirming action on the part of the user.
React to a dialog-infirming action on the part of the user. inCommand is the user-generated command (usually kHICommandCancel).
The default implementation dismisses the dialog; inCommand becomes the dismissing command, which is returned from EnterModalLoop().
Derived classes may override this function to perform additional processing when a dialog is infirmed.
References DismissDialog().
Referenced by HandleCommand().
bool B::Dialog::Validate (UInt32 inCommand) protected virtual
Hook to perform input validation.
Perform dialog-wide validation in reaction to the user-generated command inCommand.
Derived classes may override this function to perform their own input validation. They are responsible for signalling any invalid input to the user.
The default implementation always returns true.
Returns
true if the dialog's input is valid; else false.
Referenced by HandleCommand().
void B::Dialog::DismissDialog (UInt32 inCommand) protected virtual
Dismisses the dialog.
This function calls the dialog callback, if any. It then performs actions depending on the dialog's modality:
For a modeless dialog, the dialog is hidden.
For a modal dialog, the dialog's modal event loop is exited. The loop can only be exited by calling DismissDialog().
For a sheet, the dialog is shown attached to its parent. The function returns immediately.
In all cases, if the dialog is set to be closed upon hiding, it will finally be closed.
The exact action performed depends on whether the dialog is in a modal event loop. If so, the loop is exited.
Derived classes may override this function to perform additional processing whenever the dialog is dismissed. They should call the base class after doing their work.
Referenced by CancelDialog(), and ConfirmDialog().
bool B::Dialog::HandleCommand (const HICommandExtended & inHICommand) protected virtual
Dialog overrides this function to intercept the kHICommandOK and kHICommandCancel commands.
Derived classes may override this function to intercept additional dialog-dismissing commands.
Reimplemented from B::Window.
References B_BUILDING_CAN_USE_10_3_APIS, CancelDialog(), ConfirmDialog(), B::WindowUtils::GetAttributes(), B::WindowUtils::GetClass(), B::WindowUtils::GetContentBounds(), B::WindowUtils::GetContentView(), B::DialogModality::GetModality(), B::Window::GetWindowRef(), B::ViewUtils::rbegin(), B::ViewUtils::rend(), B::InteractWithUserDialog::Run(), and Validate().
The documentation for this class was generated from the following files:
BDialog.h
BDialog.cpp