B: B::AEObjectSupport::ObjectResolutionException Class Reference
B::AEObjectSupport::ObjectResolutionException Class Reference
Public Member Functions
ObjectResolutionException (const ObjectResolutionException &ex)
Copy constructor.
ObjectResolutionException (OSStatus inStatus, const AEDesc &inErrorDesc)
OSStatus constructor.
ObjectResolutionException (std::istream &istr)
Stream constructor.
virtual ~ObjectResolutionException () throw ()
Destructor.
ObjectResolutionException & operator= (const ObjectResolutionException &ex)
Copy assignment.
virtual const char * what () const throw ()
Returns the exception's textual description.
void Write (std::ostream &ostr) const
Writes out the exception's internal state to ostr.
Public Member Functions inherited from B::RuntimeOSStatusException
RuntimeOSStatusException (const RuntimeOSStatusException &ex) throw ()
Copy constructor.
RuntimeOSStatusException (OSStatus inStatus) throw ()
OSStatus constructor.
RuntimeOSStatusException (std::istream &istr)
Stream constructor.
virtual ~RuntimeOSStatusException () throw ()
Destructor.
RuntimeOSStatusException & operator= (const RuntimeOSStatusException &ex) throw ()
Copy assignment.
virtual OSStatus GetStatus () const throw ()
Returns the OS-defined error code.
void Write (std::ostream &ostr) const
Writes out the exception's internal state to ostr.
Public Member Functions inherited from B::OSStatusException
virtual ~OSStatusException () throw ()
Destructor.
Member Function Documentation
AEObjectSupport::ObjectResolutionException & B::AEObjectSupport::ObjectResolutionException::operator= (const ObjectResolutionException & ex)
Copy assignment.
Parameters
ex The original exception.
References B::RuntimeOSStatusException::operator=().
void B::AEObjectSupport::ObjectResolutionException::Write (std::ostream & ostr) const
Writes out the exception's internal state to ostr.
Derived classes should override this function if they contain internal state. They should call the base class implementation prior to writing out their own state.
References B::AEObjectSupport::AddCachedInfoToAppleEventReply(), and B::RuntimeOSStatusException::Write().
The documentation for this class was generated from the following files:
BAEObjectSupport.h
BAEObjectSupport.cpp