B: B::DataBrowser Class Reference
B::DataBrowser Class Reference
Views
Data Browser control.
#include <BDataBrowser.h>
Public Types
typedef std::vector< DataBrowserItem * > ItemVector
typedef boost::signal0< void > Signal
Public Types inherited from B::View
typedef ViewUtils::SubviewIterator const_iterator
A constant iterator that moves forward through a view's subviews.
typedef ViewUtils::ReverseSubviewIterator const_reverse_iterator
A constant iterator that moves backward through a view's subviews.
Public Member Functions
DataBrowserSelectionFlags GetSelectionFlags () const
OSPtr< CFDictionaryRef > GetUserState () const
unsigned GetHeaderHeight () const
unsigned GetRowHeight () const
unsigned GetColumnWidth () const
void SetDisclosureColumn (DataBrowserTableViewColumnID inColumnID)
void SetSortColumn (DataBrowserTableViewColumnID inColumnID)
void SetUserState (OSPtr< CFDictionaryRef > inUserState)
void SetRootContainer (DataBrowserItem *inContainer)
void UseDragAndDrop ()
unsigned CountColumns () const
DataBrowserTableViewColumnID GetColumnID (unsigned index) const
unsigned GetColumnPosition (DataBrowserTableViewColumnID inColumnID) const
UInt16 GetColumnWidth (DataBrowserTableViewColumnID inColumnID) const
void SetColumnWidth (DataBrowserTableViewColumnID inColumnID, UInt16 inWidth)
void SetColumnEditable (DataBrowserTableViewColumnID inColumnID, bool editable)
virtual void AddColumn (DataBrowserListViewColumnDesc &inColumnDesc, DataBrowserTableViewColumnIndex inPosition=kDataBrowserListViewAppendColumn, SInt16 inInitialWidth=0)
void AddItem (DataBrowserItem *inItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
void AddItem (DataBrowserItem *inParentItem, DataBrowserItem *inItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual void AddItems (DataBrowserItem *inParentItem, const ItemVector &inItems, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
void RemoveItem (DataBrowserItem *inItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual void RemoveItems (const ItemVector &inItems, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
void RemoveAllItems (DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual void RemoveChildren (DataBrowserItem *inParentItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
void UpdateItem (DataBrowserItem *inItem, DataBrowserPropertyID inProperty=kDataBrowserNoItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual void UpdateItems (DataBrowserItem *inParentItem, const ItemVector &inItems, DataBrowserPropertyID inProperty=kDataBrowserNoItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual void UpdateChildren (DataBrowserItem *inParentItem, DataBrowserPropertyID inProperty=kDataBrowserNoItem, DataBrowserPropertyID inPresorted=kDataBrowserItemNoProperty)
virtual UInt32 GetItems (DataBrowserItem *inParentItem, bool inRecurse, DataBrowserItemState inState, ItemVector &outItems) const
virtual UInt32 CountItems (DataBrowserItem *inParentItem, bool inRecurse, DataBrowserItemState inState) const
virtual DataBrowserItemState GetItemState (const DataBrowserItem *inItem) const
virtual ::Rect GetItemBounds (const DataBrowserItem *inItem, DataBrowserPropertyID inProperty, DataBrowserPropertyPart inPropertyPart) const
virtual UInt16 GetItemHeight (const DataBrowserItem *inItem) const
virtual void SetItemHeight (const DataBrowserItem *inItem, UInt16 inHeight)
void ForEachItemDo (DataBrowserItem *inParentItem, bool inRecurse, DataBrowserItemState inState, DataBrowserItemProcPtr inProc, void *inArg)
UInt32 CountSelectedItems () const
DataBrowserItem * GetFirstSelectedItem () const
UInt32 GetSelectedItems (ItemVector &outItems) const
void SelectItem (DataBrowserItem *inItem)
virtual void SelectItems (const ItemVector &inItems, DataBrowserSetOption inOperation=kDataBrowserItemsAssign)
void SelectAllItems ()
void UnselectItem (DataBrowserItem *inItem)
void UnselectItems (const ItemVector &inItems)
void UnselectAllItems ()
virtual void RevealItem (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, bool inCenterInView=false)
virtual void OpenContainer (DataBrowserItem *inContainerItem)
virtual void CloseContainer (DataBrowserItem *inContainerItem)
virtual void OpenEditSession (DataBrowserItem *inItem, DataBrowserPropertyID inProperty)
virtual bool IsEditSessionOpen () const
virtual void CancelEdit () const
Constructor
DataBrowser (HIViewRef inViewRef)
Constructor.
Signals
Signal & GetSelectionChangedSignal ()
This signal is sent when the data browser's selection changes.
Signal & GetUserStateChangedSignal ()
This signal is sent when the data browser's user state (column position & widths) changes.
Public Member Functions inherited from B::View
virtual void SetText (const String &inText)
void SetViewID (const HIViewID &inID)
Returns the view's full HIViewID.
void SetID (SInt32 inID)
Sets the view's HIViewID::id field while preserving its HIViewID::signature.
void SetCommandID (UInt32 inCommandID)
void SetFrame (const Rect &inNewFrame)
void MoveFrameBy (float deltaX, float deltaY)
void MoveFrameTo (float x, float y)
void ResizeFrameBy (float deltaWidth, float deltaHeight)
void ResizeFrameTo (float width, float height)
void SetValue (int inValue)
void SetMinimum (int inMininum)
void SetMaximum (int inMaximum)
void SetFocus (HIViewPartCode part)
void SetHighlight (HIViewPartCode part)
void Activate (bool inActivate)
void Enable (bool inEnable)
void Show (bool inShow)
void SendCommandToUserFocus (bool inSendIt)
void AddSubview (View *subview)
void RemoveFromSuperview ()
operator HIViewRef () const
Returns the object's underlying HIViewRef.
HIViewRef GetViewRef () const
Returns the object's underlying HIViewRef.
HIObjectRef GetObjectRef () const
Returns the object's underlying HIObjectRef.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
SInt32 GetSize () const
Returns the view's size variant.
void SetSize (SInt32 inSize)
Sets the view's size variant.
ControlFontStyleRec GetFontStyle () const
Returns the view's font/style attributes.
void SetFontStyle (const ControlFontStyleRec &inFontStyle)
Sets the view's font/style attributes.
ControlActionUPP GetActionProc () const
Returns the view's action proc.
void SetActionProc (ControlActionUPP inActionProc)
Sets the view's action proc.
virtual String GetText () const
Returns the view's text.
HIViewKind GetKind () const
Returns the view's kind. This is an immutable property of the view.
HIViewID GetViewID () const
Returns the view's full HIViewID.
SInt32 GetID () const
Returns the view's HIViewID::id field.
UInt32 GetCommandID () const
Rect GetBounds () const
Rect GetFrame () const
std::pair< Rect, float > GetBestBounds () const
int GetValue () const
Returns the view's current value.
int GetMinimum () const
Returns the view's minimum value.
int GetMaximum () const
Returns the view's maximum value.
HIViewPartCode GetFocusPart () const
Returns the view's currently focused part.
bool IsFocused () const
Returns whether the view has the focus.
HIViewPartCode GetHighlightPart () const
Returns the view's currently highlighted part.
bool IsHighlighted () const
Returns whether the view has a highlighted part.
bool IsActive () const
Returns whether the view is active.
bool IsViewActive () const
Returns whether the view is active, independently of the active state of its parent views.
bool IsEnabled () const
Returns whether the view is enabled.
bool IsViewEnabled () const
Returns whether the view is enabled, independently of the enabled state of its parent views.
bool IsVisible () const
Returns whether the view is visible.
bool IsViewVisible () const
Returns whether the view is visible, independently of the visible state of its parent views.
bool IsCommandSentToUserFocus () const
WindowRef GetOwner () const
void DebugPrint () const
void SetLeftBinding (HIBindingKind inBinding)
Sets the binding of the view's left side.
void SetTopBinding (HIBindingKind inBinding)
Sets the binding of the view's top side.
void SetRightBinding (HIBindingKind inBinding)
Sets the binding of the view's right side.
void SetBottomBinding (HIBindingKind inBinding)
Sets the binding of the view's bottom side.
void SetBindings (HIBindingKind inLeftBinding, HIBindingKind inTopBinding, HIBindingKind inRightBinding, HIBindingKind inBottomBinding)
Sets the bindings of all of the view's sides at once.
void SetHorizontalScale (float inRatio, View *inView=NULL)
Sets the view's horizontal scaling.
void SetVerticalScale (float inRatio, View *inView=NULL)
Sets the view's vertical scaling.
void SetHorizontalPosition (HIPositionKind inPosition, View *inView=NULL, float inOffset=0.0f)
Sets the view's horizontal position.
void SetVerticalPosition (HIPositionKind inPosition, View *inView=NULL, float inOffset=0.0f)
Sets the view's vertical position.
void SetLayout (const HILayoutInfo &inLayout)
Sets the view's full layout info.
HILayoutInfo GetLayout () const
Gets the view's full layout info.
void ApplyLayout ()
Changes the view's size & location to match its layout information.
void SuspendLayout ()
Disables layout for this view and its children.
void ResumeLayout ()
Enables layout for this view and its children.
bool IsLayoutActive () const
Returns whether layout is enabled for this view.
bool IsViewLayoutActive () const
Returns whether layout is enabled for this view, independently of the layout state of its parent views.
const_iterator begin () const
Returns an iterator pointing to the beginning of the view's subviews.
const_iterator end () const
Returns an iterator pointing to the end of the view's subviews.
const_reverse_iterator rbegin () const
Returns an reverse iterator pointing to the beginning of the view's subviews.
const_reverse_iterator rend () const
Returns an reverse iterator pointing to the end of the view's subviews.
HIViewRef FindSubview (int inID) const
Returns the view's subview that matches the main bundle's signature and inID.
HIViewRef FindSubview (const HIViewID &inID) const
HIViewRef FindSubview (int inID, const std::nothrow_t &) const
Returns the view's subview that matches the main bundle's signature and inID, or NULL.
HIViewRef FindSubview (const HIViewID &inID, const std::nothrow_t &) const
template<class VIEW >
VIEW * FindTypedSubview (int inID) const
Returns the view's properly typed subview that matches the main bundle's signature and inID.
template<class VIEW >
VIEW * FindTypedSubview (const HIViewID &inID) const
Static Public Member Functions
Instantiation
static View * Instantiate (HIViewRef inViewRef)
Create an object given an existing HIToolbox view.
static DataBrowser * Create (const HIViewID &inViewID, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, const ViewFactory *inFactory, DataBrowserViewStyle inViewStyle)
Create an object and its HIToolbox view, from the given parameters.
Static Public Member Functions inherited from B::View
static void InstantiateSubviews (HIViewRef inSuperView, const ViewFactory &inFactory)
Create instances of View for each subview of inSuperView.
static void AwakenViewAndChildren (HIViewRef inView, Nib *inFromNib)
Tell inView and its subviews to awaken.
static View * GetViewFromRef (HIViewRef inViewRef)
Returns the View object associated with inViewRef.
static View * GetViewFromRef (HIViewRef inViewRef, const std::nothrow_t &)
Returns the View object associated with inViewRef, without throwing an exception.
template<class VIEW >
static VIEW * GetTypedViewFromRef (HIViewRef inViewRef)
Returns the properly typed View object associated with inViewRef.
template<class VIEW >
static VIEW * GetTypedViewFromRef (HIViewRef inViewRef, const std::nothrow_t &)
Returns the properly typed View object associated with inViewRef, without throwing an exception.
template<class VIEW >
static VIEW * FindTypedSubview (HIViewRef inSuperview, int inID)
Returns the properly typed subview of inSuperview that matches the main bundle's signature and inID.
template<class VIEW >
static VIEW * FindTypedSubview (HIViewRef inSuperview, const HIViewID &inID)
Protected Member Functions
virtual ~DataBrowser ()
Destructor.
void Cleanup ()
virtual void SelectionChanged ()
virtual void UserStateChanged ()
virtual void DoubleClickedItem (DataBrowserItem *inItem)
virtual bool GetProperty (DataBrowserItemData &inItemData, DataBrowserPropertyID inProperty) const
virtual bool IsRootContainerSortable () const
virtual void GetSetItemData (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, DataBrowserItemDataRef inItemData, bool inChangeValue)
virtual bool Compare (DataBrowserItem *inItem1, DataBrowserItem *inItem2, DataBrowserPropertyID inSortProperty)
virtual void ItemNotification (DataBrowserItem *inItem, DataBrowserItemNotification inMessage)
virtual bool AddDragItem (Drag &ioDrag, DataBrowserItem *inItem, PasteboardItemID &outItemID)
virtual bool IsDragOnBrowserAcceptable (const Drag &inDrag)
virtual bool IsDragOnItemAcceptable (const Drag &inDrag, const DataBrowserItem *inItem)
virtual bool ReceiveDragOnBrowser (const Drag &inDrag)
virtual bool ReceiveDragOnItem (const Drag &inDrag, DataBrowserItem *ioItem)
virtual void PostProcessDrag (const Drag &inDrag, OSStatus inTrackDragResult)
virtual void GetContextualMenu (MenuRef &outMenuRef, UInt32 &outHelpType, CFStringRef &outHelpItemString, AEDesc &outSelection)
virtual void SelectContextualMenu (MenuRef inMenuRef, UInt32 inSelectionType, SInt16 inMenuID, MenuItemIndex inMenuItem)
virtual bool KeyFilter (UInt16 &ioKeyCode, UInt16 &ioCharCode, EventModifiers &ioModifiers, bool &outPassUp)
virtual void CustomItemDraw (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, DataBrowserItemState inItemState, const Rect &inRect, SInt16 inDepth, Boolean inColorDevice)
virtual bool CustomItemEdit (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, const String &inString, Rect &outMaxEditTextRect, bool &outShrinkToFit)
virtual bool CustomItemHitTest (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, const Rect &inRect, const Rect &inMouseRect)
virtual DataBrowserTrackingResult CustomItemTrack (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, const Rect &inRect, const Point &inStartPt, EventModifiers inModifiers)
virtual void CustomItemDragRgn (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, const Rect &inRect, RgnHandle ioDragRgn)
virtual bool CustomItemAcceptDrag (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, const Rect &inRect, DragRef inDragRef)
virtual bool CustomItemReceiveDrag (DataBrowserItem *inItem, DataBrowserPropertyID inProperty, DataBrowserDragFlags inDragFlags, DragRef inDragRef)
virtual bool HandleCommand (const HICommandExtended &inHICommand)
virtual bool HandleUpdateStatus (const HICommandExtended &inHICommand, CommandData &ioCmdData)
Protected Member Functions inherited from B::PredefinedView
PredefinedView (HIViewRef inViewRef)
Constructor.
Protected Member Functions inherited from B::View
View (HIViewRef inViewRef)
Static Protected Member Functions
static DataBrowserItem * GetItem (DataBrowserItemID inItemID)
Static Protected Member Functions inherited from B::PredefinedView
static View * SetupView (const HIViewID &inViewID, HIViewRef inViewRef, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, const ViewFactory *inFactory)
Helper function to set up a programatically-created views.
template<class VIEW >
static VIEW * SetupTypedView (const HIViewID &inViewID, HIViewRef inViewRef, HIViewRef inSuperview, const Rect *inFrame, Nib *inFromNib, const ViewFactory *inFactory)
Helper function to set up a programatically-created views.
Additional Inherited Members
Protected Attributes inherited from B::View
bool mAwakened
Detailed Description
Data Browser control.
Todo:
Document this class!
Member Function Documentation
DataBrowser * B::DataBrowser::Create (const HIViewID & inViewID, HIViewRef inSuperview, const Rect * inFrame, Nib * inFromNib, const ViewFactory * inFactory, DataBrowserViewStyle inViewStyle) static
Create an object and its HIToolbox view, from the given parameters.
Note
The view is initially invisible.
Parameters
inViewID The new view's ID; may be zero in which case the view doesn't get an HIViewID.
inSuperview The new view's superview; may be NULL, in which case the view is "standalone".
inFrame The new view's frame; may be NULL, in which case the view doesn't get a frame with particular values. If inSuperview is not NULL, the frame is assumed to be in inSuperview's coordinates.
inFromNib The nib from which to load other resources; may be NULL.
inFactory The factory to use for instantiating the derivative of View;; may be NULL, in which case the default view factory is used instead.
DataBrowserSelectionFlags B::DataBrowser::GetSelectionFlags () const
Returns selections flags for databrowser object
References B::OSPtr< T >::get().
void B::DataBrowser::AddColumn (DataBrowserListViewColumnDesc & inColumnDesc, DataBrowserTableViewColumnIndex inPosition = kDataBrowserListViewAppendColumn, SInt16 inInitialWidth = 0) virtual
Adds the column describes by inColumnDesc to the data browser.
void B::DataBrowser::AddItem (DataBrowserItem * inItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty)
Insert the given item into the top level of the data browser.
References AddItems().
void B::DataBrowser::AddItem (DataBrowserItem * inParentItem, DataBrowserItem * inItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty)
Insert the given item into the data browser. If inParentItem is NULL, it will be placed as a top-level item; otherwise it will be a child of inParentItem.
References AddItems().
void B::DataBrowser::AddItems (DataBrowserItem * inParentItem, const ItemVector & inItems, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty) virtual
Insert each item from inItems into the data browser. If inParentItem is NULL, the items will be placed in the top level; otherwise they will be inserted as children of inParentItem. This routine allows a number of items to be batch-processed and inserted all at once, rather than individually, to avoid redraws after each.
Referenced by AddItem().
void B::DataBrowser::RemoveItem (DataBrowserItem * inItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty)
Remove the given item from the data browser.
References RemoveItems().
void B::DataBrowser::RemoveItems (const ItemVector & inItems, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty) virtual
Remove each item from inItems from the data browser.
Referenced by RemoveItem().
void B::DataBrowser::RemoveAllItems (DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty)
Remove every item from the data browser.
References RemoveChildren().
Referenced by Cleanup().
void B::DataBrowser::RemoveChildren (DataBrowserItem * inParentItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty) virtual
Remove every child of the given item from the data browser.
Referenced by RemoveAllItems().
void B::DataBrowser::UpdateItem (DataBrowserItem * inItem, DataBrowserPropertyID inProperty = kDataBrowserNoItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty)
Instruct the data browser to re-fetch property inProperty of inItem.
References UpdateItems().
void B::DataBrowser::UpdateItems (DataBrowserItem * inParentItem, const ItemVector & inItems, DataBrowserPropertyID inProperty = kDataBrowserNoItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty) virtual
Instruct the data browser to re-fetch property inProperty of each item in inItems.
Referenced by UpdateItem().
void B::DataBrowser::UpdateChildren (DataBrowserItem * inParentItem, DataBrowserPropertyID inProperty = kDataBrowserNoItem, DataBrowserPropertyID inPresorted = kDataBrowserItemNoProperty) virtual
Instruct the data browser to re-fetch property inProperty of each child of inParentItem.
UInt32 B::DataBrowser::GetItems (DataBrowserItem * inParentItem, bool inRecurse, DataBrowserItemState inState, ItemVector & outItems) const virtual
Return the items under inParentItem with the given state.
Referenced by GetSelectedItems(), IsRootContainerSortable(), SelectAllItems(), and UnselectAllItems().
UInt32 B::DataBrowser::CountItems (DataBrowserItem * inParentItem, bool inRecurse, DataBrowserItemState inState) const virtual
Return the number of items under inParentItem with the given state.
Referenced by CountSelectedItems(), and IsRootContainerSortable().
DataBrowserItemState B::DataBrowser::GetItemState (const DataBrowserItem * inItem) const virtual
Returns the state of the given item.
UInt32 B::DataBrowser::CountSelectedItems () const
Return the number of selected items in the data browser.
References CountItems().
DataBrowserItem * B::DataBrowser::GetFirstSelectedItem () const
Fetch the "first" selected item. This is actually a quickie way of determining whether there are any selected items in the data browser.
UInt32 B::DataBrowser::GetSelectedItems (ItemVector & outItems) const
Return the selected items.
References GetItems().
void B::DataBrowser::SelectItem (DataBrowserItem * inItem)
Select the given item.
References SelectItems().
void B::DataBrowser::SelectItems (const ItemVector & inItems, DataBrowserSetOption inOperation = kDataBrowserItemsAssign) virtual
Select/Deselect/Toggle the items given in inItems, depending upon the operation given in inOperation. By default, the data browser's selection set is replaced by the given items.
Referenced by SelectAllItems(), SelectItem(), UnselectAllItems(), UnselectItem(), and UnselectItems().
void B::DataBrowser::SelectAllItems ()
Selects all items.
References GetItems(), and SelectItems().
void B::DataBrowser::UnselectItem (DataBrowserItem * inItem)
Unselect the given item.
References SelectItems().
void B::DataBrowser::UnselectItems (const ItemVector & inItems)
Unselect the given items.
References SelectItems().
void B::DataBrowser::UnselectAllItems ()
Unselects all items.
References GetItems(), and SelectItems().
void B::DataBrowser::RevealItem (DataBrowserItem * inItem, DataBrowserPropertyID inProperty, bool inCenterInView = false) virtual
Select the given item, scrolling the data browser if necessary so that the given property of the given item is visible.
void B::DataBrowser::OpenContainer (DataBrowserItem * inContainerItem) virtual
Open the given container.
void B::DataBrowser::CloseContainer (DataBrowserItem * inContainerItem) virtual
Close the given container.
void B::DataBrowser::Cleanup () protected
Removes all items.
References RemoveAllItems().
Referenced by GetUserStateChangedSignal(), and ~DataBrowser().
void B::DataBrowser::SelectionChanged () protected virtual
React to a selection change within the data browser. By default, we broadcast a "selection changed" signal.
Referenced by GetUserStateChangedSignal(), and ItemNotification().
void B::DataBrowser::UserStateChanged () protected virtual
React to a user state change within the data browser. By default, we broadcast a "user state changed" signal.
Referenced by GetUserStateChangedSignal(), and ItemNotification().
void B::DataBrowser::DoubleClickedItem (DataBrowserItem * inItem) protected virtual
React to a double-click within the data browser. By default, we forward the message to the double-cliked item.
References IsRootContainerSortable(), and B::DataBrowserItem::ItemDoubleClicked().
Referenced by GetUserStateChangedSignal(), and ItemNotification().
bool B::DataBrowser::IsRootContainerSortable () const protected virtual
Determines whether the root container is sortable. Override it if you want to implement a sortable top-level container.
References CountItems(), and GetItems().
Referenced by DoubleClickedItem(), and GetUserStateChangedSignal().
void B::DataBrowser::GetSetItemData (DataBrowserItem * inItem, DataBrowserPropertyID inProperty, DataBrowserItemDataRef inItemData, bool inChangeValue) protected virtual
This is called whenever the browser wants to get/set data for the indicated item. The default behavior is to tell the item to get or set its own data; we don't know what the item contains.
References B::DataBrowserItem::GetData(), and B::DataBrowserItem::SetData().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::Compare (DataBrowserItem * inItem1, DataBrowserItem * inItem2, DataBrowserPropertyID inSortProperty) protected virtual
This is called whenever the browser wants to compare two items.
References B::DataBrowserItem::CompareTo().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
void B::DataBrowser::ItemNotification (DataBrowserItem * inItem, DataBrowserItemNotification inMessage) protected virtual
This is called whenever the user does something with an item. The default behavior is to pass along the notification to the item.
References B::DataBrowserItem::ContainerClosed(), B::DataBrowserItem::ContainerClosing(), B::DataBrowserItem::ContainerOpened(), B::DataBrowserItem::ContainerSorted(), B::DataBrowserItem::ContainerSorting(), DoubleClickedItem(), B::DataBrowserItem::ItemAdded(), B::DataBrowserItem::ItemDeselected(), B::DataBrowserItem::ItemRemoved(), B::DataBrowserItem::ItemSelected(), SelectionChanged(), and UserStateChanged().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::AddDragItem (Drag & ioDrag, DataBrowserItem * inItem, PasteboardItemID & outItemID) protected virtual
This is called when the user drags an item. The default behavior is to tell the item to add whatever drag flavors are appropriate for itself.
References B::DataBrowserItem::AddDragFlavors().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::IsDragOnBrowserAcceptable (const Drag & inDrag) protected virtual
This is called when the user initially drags something into the list, and the control needs to know whether the drag is acceptable. The inItem parameter is NULL if the drag is going into the top level of the hierarchy, otherwise it's the container object into which things are being dragged.
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::IsDragOnItemAcceptable (const Drag & inDrag, const DataBrowserItem * inItem) protected virtual
This is called when the user initially drags something into the list, and the control needs to know whether the drag is acceptable. The inItem parameter is NULL if the drag is going into the top level of the hierarchy, otherwise it's the container object into which things are being dragged.
References B::DataBrowserItem::IsDragAcceptable().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::ReceiveDragOnBrowser (const Drag & inDrag) protected virtual
This is called after the user drops something into the list. The inItem parameter is NULL if the drop is going into the top level of the hierarchy, otherwise it's the container object into which things have been dropped.
The drag contains items that are acceptable, as defined by the DragIsAcceptable() and ItemIsAcceptable() member functions.
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
bool B::DataBrowser::ReceiveDragOnItem (const Drag & inDrag, DataBrowserItem * inItem) protected virtual
This is called after the user drops something into the list. The inItem parameter is NULL if the drop is going into the top level of the hierarchy, otherwise it's the container object into which things have been dropped.
The drag contains items that are acceptable, as defined by the DragIsAcceptable() and ItemIsAcceptable() member functions.
References AddDragItem(), B_VAR_EXPORT, B::String::cf_ptr(), Compare(), B::String::empty(), GetSetItemData(), B::ErrorHandler::GetStatus(), IsDragOnBrowserAcceptable(), IsDragOnItemAcceptable(), ItemNotification(), B::DataBrowserItem::KeyFilter(), B::DataBrowserItem::ReceiveDrag(), ReceiveDragOnBrowser(), ReceiveDragOnItem(), and B::OSPtr< T >::release().
Referenced by GetUserStateChangedSignal(), and ReceiveDragOnItem().
The documentation for this class was generated from the following files:
BDataBrowser.h
BDataBrowser.cpp