B: B::AEEventBase Class Reference
B::AEEventBase Class Reference
Apple Events
Common base class for representing Apple Events.
#include <BAEEvent.h>
Public Member Functions
void CheckRequiredParams ()
Constructors & Destructor
AEEventBase (const AppleEvent &inAppleEvent, AEWriter &ioWriter)
Constructs an AEEventBase for an incoming Apple Event.
virtual ~AEEventBase ()
Destructor.
Synchronisation
void Update ()
Sets output parameters.
Static Public Member Functions
Sending Apple Events
static void SendEvent (const AppleEvent &inEvent, AESendMode inMode=0)
Sends inEvent using inMode.
static void SendEvent (const AppleEvent &inEvent, AEDesc &outResult, AESendMode inMode=0)
Sends inEvent using inMode. The reply is returned in outResult.
Public Attributes
const AppleEvent & mAppleEvent
The incoming Apple Event.
Static Protected Member Functions
Simple Apple Events
A 'simple' Apple Event has the following characteristics:
It is sent to the application itself.
It has either no parameters or a single direct object parameter.
It doesn't return a result.
template<typename TARGET , typename OBJ_SPEC >
static void SendSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, OBJ_SPEC inDirectObject, AESendMode inMode=0)
Constructs and sends a simple Apple Event with a direct object parameter.
template<typename TARGET >
static void SendSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, AESendMode inMode=0)
Constructs and sends a simple Apple Event with no parameters.
template<typename TARGET , typename OBJ_SPEC >
static void MakeSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, OBJ_SPEC inDirectObject, AppleEvent &outEvent)
Constructs a simple Apple Event with a direct object parameter, returning it in outEvent.
template<typename TARGET >
static void MakeSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, AppleEvent &outEvent)
Constructs a simple Apple Event with no parameters, returning it in outEvent.
Protected Attributes
AEWriter & mWriter
Detailed Description
Common base class for representing Apple Events.
This class contains member functions and variables that are independent of the specifics of a particular event. Its main purpose is to serve as a common base class for the various template instantiations of AEEvent. It is rarely if ever used by itself.
AEEventBase and its derivatives have three distinct responsibilities:
Extracting parameters from incoming Apple Events, making them accessible to clients. This is done by adding code in the derived class' constructors to retrieve the parameters.
Writing return values in the Apple Event reply. This is done by overriding Update() as appropriate.
Constructing and sending outgoing Apple Events. This is done by adding specific static member functions to the derived classes.
Constructor & Destructor Documentation
B::AEEventBase::AEEventBase (const AppleEvent & inAppleEvent, AEWriter & ioWriter)
Constructs an AEEventBase for an incoming Apple Event.
Parameters
inAppleEvent The incoming Apple Event.
ioWriter The reponse to inAppleEvent. May be null (eg, if the caller doesn't want a reply).
Member Function Documentation
void B::AEEventBase::Update ()
Sets output parameters.
This function is called after an Apple Event has been handled, but prior to returning control to the toolbox.
Derived classes should override this if they need to return output parameters to the caller. The idea is that the outputs are cached as member variables of the derived class, and written to the Apple Event reply (aka mResult) from within this function.
References mAppleEvent.
Referenced by B::AEEvent< kAECoreSuite, kAEClone >::~AEEvent(), B::AEEvent< kAECoreSuite, kAECountElements >::~AEEvent(), B::AEEvent< kAECoreSuite, kAECreateElement >::~AEEvent(), B::AEEvent< kAECoreSuite, kAEDoObjectsExist >::~AEEvent(), B::AEEvent< kAECoreSuite, kAEGetData >::~AEEvent(), and B::AEEvent< kAECoreSuite, kAEMove >::~AEEvent().
void B::AEEventBase::SendEvent (const AppleEvent & inEvent, AESendMode inMode = 0) static
Sends inEvent using inMode.
Parameters
inEvent The Apple Event to send.
inMode The event's send mode.
References B::AEObjectSupport::RethrowExceptionFromAppleEventReply().
Referenced by B::AEUndoAction::Perform(), B::AEWriter::Send(), B::AEEvent< kCoreEventClass, kAEQuitApplication >::Send(), B::AEEvent< kAECoreSuite, kAEClone >::Send(), B::AEEvent< kAECoreSuite, kAEClose >::Send(), B::AEEvent< kAECoreSuite, kAECountElements >::Send(), B::AEEvent< kAECoreSuite, kAECreateElement >::Send(), B::AEEvent< kAECoreSuite, kAEDoObjectsExist >::Send(), B::AEEvent< kAECoreSuite, kAEGetData >::Send(), B::AEEvent< kAECoreSuite, kAEMove >::Send(), B::AEEvent< kCoreEventClass, kAEPrint >::Send(), B::AEEvent< kAECoreSuite, kAESave >::Send(), B::AEEvent< kAECoreSuite, kAESetData >::Send(), B::AEEvent< kASAppleScriptSuite, kASCommentEvent >::Send(), B::AEObject::SendSetDataAppleEvent(), and B::AEObject::SendSetPropertyAppleEvent().
void B::AEEventBase::SendEvent (const AppleEvent & inEvent, AEDesc & outResult, AESendMode inMode = 0) static
Sends inEvent using inMode. The reply is returned in outResult.
Parameters
inEvent The Apple Event to send.
outResult The event's result.
inMode The event's send mode.
References B::AEObjectSupport::RethrowExceptionFromAppleEventReply().
template<typename TARGET , typename OBJ_SPEC > void B::AEEventBase::SendSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, OBJ_SPEC inDirectObject, AESendMode inMode = 0) static protected
Constructs and sends a simple Apple Event with a direct object parameter.
The Apple Event has class inEventClass and ID inEventID. inDirectObject needs to respond to operator << in order to write itself out to the event.
Parameters
inEventClass The Apple Event class of the event to send.
inEventID The Apple Event ID of the event to send.
inTarget A functor that generates the event's recipient.
inDirectObject A functor that generates the event's direct parameter.
inMode The event's send mode.
Referenced by B::AEEvent< kAECoreSuite, kAEDelete >::Send(), B::AEEvent< kCoreEventClass, kAEOpen >::Send(), B::AEEvent< kAEMiscStandards, kAERedo >::Send(), B::AEEvent< kAEMiscStandards, kAERevert >::Send(), B::AEEvent< kAEMiscStandards, kAESelect >::Send(), and B::AEEvent< kAEMiscStandards, kAEUndo >::Send().
template<typename TARGET > void B::AEEventBase::SendSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, AESendMode inMode = 0) static protected
Constructs and sends a simple Apple Event with no parameters.
The Apple Event has class inEventClass and ID inEventID.
Parameters
inEventClass The Apple Event class of the event to send.
inEventID The Apple Event ID of the event to send.
inTarget A functor that generates the event's recipient.
inMode The event's send mode.
template<typename TARGET , typename OBJ_SPEC > void B::AEEventBase::MakeSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, OBJ_SPEC inDirectObject, AppleEvent & outEvent) static protected
Constructs a simple Apple Event with a direct object parameter, returning it in outEvent.
The Apple Event has class inEventClass and ID inEventID. inDirectObject needs to respond to operator << in order to write itself out to the event.
Parameters
inEventClass The Apple Event class of the event to send.
inEventID The Apple Event ID of the event to send.
inTarget A functor that generates the event's recipient.
inDirectObject A functor that generates the event's direct parameter.
outEvent The constructed event.
Referenced by B::AEEvent< kAECoreSuite, kAEDelete >::Make(), B::AEEvent< kCoreEventClass, kAEOpen >::Make(), B::AEEvent< kAEMiscStandards, kAERedo >::Make(), B::AEEvent< kAEMiscStandards, kAERevert >::Make(), B::AEEvent< kAEMiscStandards, kAESelect >::Make(), and B::AEEvent< kAEMiscStandards, kAEUndo >::Make().
template<typename TARGET > void B::AEEventBase::MakeSimpleEvent (AEEventClass inEventClass, AEEventID inEventID, TARGET inTarget, AppleEvent & outEvent) static protected
Constructs a simple Apple Event with no parameters, returning it in outEvent.
The Apple Event has class inEventClass and ID inEventID.
Parameters
inEventClass The Apple Event class of the event to send.
inEventID The Apple Event ID of the event to send.
inTarget A functor that generates the event's recipient.
outEvent The constructed event.
References B::AEWriter::Close().
The documentation for this class was generated from the following files:
BAEEvent.h
BAEEvent.cpp