B: B::NavReplyDialog::PopupMenuItem Class Reference
B::NavReplyDialog::PopupMenuItem Class Reference
Describes one element of the dialog's filtering pop-up menu.
#include <BNavDialogs.h>
Public Member Functions
PopupMenuItem ()
Default constructor. Makes a kFilterSeparator menu item.
PopupMenuItem (FilterKind inFilterKind, const String &inName, const String &inLocName=String())
Constructs a menu item from the given arguments.
PopupMenuItem (const Bundle::DocumentType &inDocType, const Bundle &inBundle, CFStringRef inTable)
Constructs a menu item from the given document type.
FilterKind GetFilterKind () const
Returns the type of filtering applied by this element.
String GetName () const
Returns the internal name for this filter (valid if GetFilterKind() == kFilterName).
String GetLocName () const
Returns the menu item text for this element.
Detailed Description
Describes one element of the dialog's filtering pop-up menu.
Constructor & Destructor Documentation
B::NavReplyDialog::PopupMenuItem::PopupMenuItem (FilterKind inFilterKind, const String & inName, const String & inLocName = String())
Constructs a menu item from the given arguments.
Parameters
inFilterKind The type of filter.
inName The filter's name.
inLocName The menu item text.
B::NavReplyDialog::PopupMenuItem::PopupMenuItem (const Bundle::DocumentType & inDocType, const Bundle & inBundle, CFStringRef inTable)
Constructs a menu item from the given document type.
Parameters
inDocType The document type.
inBundle A bundle from which to extract localised strings.
inTable The table (i.e. a ".strings" file) within inBundle from which to read the localised strings.
References B::String::assign(), B::Bundle::cf_ref(), B::String::cf_ref(), B::NavReplyDialog::kFilterName, B::NavReplyDialog::kFilterSeparator, and B::Bundle::DocumentType::mName.
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp