B: B::Array< T > Class Template Reference
B::Array< T > Class Template Reference
Adapter class for immutable arrays.
#include <BArray.h>
Classes
class const_iterator
class iterator
class reference
Public Types
Types
typedef OSPtr< T > value_type
The type of the array's elements.
typedef size_t size_type
The unsigned integral type for size values and indices.
typedef ptrdiff_t difference_type
The signed integral type for difference values.
typedef value_type const_reference
The type of constant element references.
typedef value_type * pointer
The type of element pointers.
typedef const value_type * const_pointer
The type of constant element pointers.
typedef CFAllocatorRef allocator_type
The type of constant iterators.
typedef std::reverse_iterator< iterator > reverse_iterator
The type of reverse iterators.
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
The type of constant reverse iterators.
Public Member Functions
template<class InputIterator >
Array< T > & assign (InputIterator first, InputIterator last)
Constructors / Destructor
Array ()
Default constructor.
Array (const Array &arr)
Copy constructor.
Array (CFAllocatorRef allocator)
Allocator constructor.
Array (size_type num, CFAllocatorRef allocator=NULL)
Size constructor.
Array (size_type num, T value, CFAllocatorRef allocator=NULL)
T constructor.
Array (const MutableArray< T > &arr)
MutableArray constructor.
Array (CFArrayRef cfarr)
CFArrayRef constructor.
Array (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> constructor.
Array (OSPtr< CFMutableArrayRef > cfarr)
OSPtr<CFMutableArrayRef> constructor.
Array (const std::vector< value_type > &vec)
vector constructor.
template<class InputIterator >
Array (InputIterator first, InputIterator last, CFAllocatorRef allocator=NULL)
Range constructor.
~Array ()
Destructor.
Operations for Size and Capacity
size_type size () const
Returns the number of elements in the array.
bool empty () const
Returns whether the array is empty.
size_type max_size () const
Returns the maximum number of characters an array could contain.
size_type capacity () const
Returns the number of elements the array could contain without reallocation.
Assignment
These various overloads of operator = and assign() replace the array's underlying CFArrayRef.
Array & operator= (const Array &arr)
Replaces all existing elements with copies of the elements of arr.
Array & operator= (const MutableArray< T > &arr)
MutableArray assignemnt.
Array & operator= (CFArrayRef cfarr)
CFArrayRef assignemnt.
Array & operator= (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> assignemnt.
Array & operator= (OSPtr< CFMutableArrayRef > cfarr)
OSPtr<CFMutableArrayRef> assignemnt.
Array & operator= (const std::vector< value_type > &vec)
vector assignemnt.
Array & assign (size_type num, T value)
Replaces all existing elements with num copies of value.
template<class InputIterator >
Array & assign (InputIterator first, InputIterator last)
Replaces all existing elements with copies of the elements in the range [first, last).
void swap (Array &arr)
Exchanges the contents with arr.
Direct Element Access
const_reference at (size_type index) const
Returns the element with index index.
const_reference operator[] (size_type index) const
Returns the element with index index.
const_reference front () const
Returns the first element.
const_reference back () const
Returns the last element.
void copy (std::vector< value_type > &vec) const
Converts the array into a vector.
Operations to Generate Iterators
const_iterator begin () const
Returns an iterator for the beginning of the array.
const_iterator end () const
Returns an iterator for the end of the array.
const_reverse_iterator rbegin () const
Returns an iterator for the beginning of a reverse iteration of the array.
const_reverse_iterator rend () const
Returns an iterator for the end of a reverse iteration of the array.
Inserting and Removing Elements
void clear ()
Removes all of the elements.
Generating CFArrayRefs.
CFArrayRef cf_ref () const
Returns the underlying CFArrayRef.
OSPtr< CFArrayRef > cf_ptr () const
Returns a "smart pointer" to the underlying CFArrayRef.
Allocator Support
allocator_type get_allocator () const
Returns the memory model of the array.
Related Functions
(Note that these are not member functions.)
Array Comparisons
template<typename T >
bool operator== (const Array< T > &a1, const Array< T > &a2)
template<typename T >
bool operator!= (const Array< T > &a1, const Array< T > &a2)
Miscellaneous
template<typename T >
void swap (Array< T > &s1, Array< T > &s2)
Detailed Description
template<typename T>
class B::Array< T >
Adapter class for immutable arrays.
Array provides a wrapper around a CoreFoundation CFArrayRef object, giving it an interface similar (nearly identical in fact) to std::vector. This makes it possible to use Array with STL algorithms, with standard streams, etc.
Array tries to share its underlying CFArrayRef whenever possible.
Specifically, Array implements the const member functions of std::vector. This reflects the immutable nature of the underlying CFArrayRef. The exception to this is the various overloads of operator = () and assign(), whose absence would have made the class much more difficult to use; they are implemented by replacing the underlying CFArrayRef, rather than by changing its contents.
Other notable differences with std::vector :
- The template parameter @a T is assumed to be a CoreFoundation type.  Specifically,
  it needs to obey the semantics of @c CFRetain() and @c CFRelease(), and there
  needs to be a template specialisation of @c CFUGetType<>() for it.
- There are more conversions.  This reflects Array's role as an
  adapter between CoreFoundation and the Standard C++ Library.  For example, one
  may construct instances of Array with any of the following types:
    - Array
    - MutableArray
    - <tt>CFArrayRef</tt>
    - <tt>OSPtr<CFArrayRef></tt>
    - <tt>OSPtr<CFMutableArrayRef></tt>
    - <tt>std::vector</tt>
- Likewise, one may copy() an Array back into an @c std::vector.
- The allocator type is fixed as @c CFAllocatorRef.  The allocator type is not a
  template parameter, however allocators @e are passed as arguments to
  constructors and can be retrieved via get_allocator().
- The underlying @c CFArrayRef's storage is not accessible, so it's not
  possible to take the address of an element of an Array.  Likewise, at(),
  operator [] (), front() and back() return objects which can extract the
  element's value.  Array is incompatible with the STL in this respect.
- Array doesn't support the following global comparison operators:
  @c < @c <= @c > @c >= .  This is because ordering of CoreFoundation types isn't
  well-defined.  The operators @c == and @c != @e are supported and are
  implemented in terms of @c CFEqual().
Member Typedef Documentation
template<typename T> typedef CFAllocatorRef B::Array< T >::allocator_type
The type of constant iterators.
The type of the allocator.
Constructor & Destructor Documentation
template<typename T > B::Array< T >::Array ()
Default constructor.
Creates an empty array using the default allocator.
template<typename T > B::Array< T >::Array (const Array< T > & arr)
Copy constructor.
Creates a shallow copy of arr.
References B::Array< T >::cf_ref(), and B::Array< T >::get_allocator().
template<typename T > B::Array< T >::Array (CFAllocatorRef allocator) explicit
Allocator constructor.
Creates an empty array using allocator.
template<typename T > B::Array< T >::Array (size_type num, CFAllocatorRef allocator = NULL) explicit
Size constructor.
Creates an array containing num elements of type T whose value is NULL.
template<typename T > B::Array< T >::Array (size_type num, T value, CFAllocatorRef allocator = NULL) explicit
T constructor.
Creates an array that is initialised by n occurrences of value.
template<typename T > B::Array< T >::Array (const MutableArray< T > & arr) explicit
MutableArray constructor.
Creates an array as a copy of arr, using arr's allocator.
Parameters
arr The source array.
References B::MutableArray< T >::cf_ref(), and B::MutableArray< T >::get_allocator().
template<typename T > B::Array< T >::Array (CFArrayRef cfarr) explicit
CFArrayRef constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
template<typename T > B::Array< T >::Array (OSPtr< CFArrayRef > cfarr) explicit
OSPtr<CFArrayRef> constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
References B::OSPtr< T >::get().
template<typename T > B::Array< T >::Array (OSPtr< CFMutableArrayRef > cfarr) explicit
OSPtr<CFMutableArrayRef> constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
References B::OSPtr< T >::get().
template<typename T > B::Array< T >::Array (const std::vector< value_type > & vec) explicit
vector constructor.
Parameters
vec The source vector.
template<typename T > template<class InputIterator > B::Array< T >::Array (InputIterator first, InputIterator last, CFAllocatorRef allocator = NULL) explicit
Range constructor.
Creates an array that is initialised by all elements of the range [first, last).
Member Function Documentation
template<typename T > Array< T > & B::Array< T >::operator= (const MutableArray< T > & arr)
MutableArray assignemnt.
Parameters
arr The input array.
References B::Array< T >::swap().
template<typename T > Array< T > & B::Array< T >::operator= (CFArrayRef cfarr)
CFArrayRef assignemnt.
Parameters
cfarr The input array.
References B::Array< T >::swap().
template<typename T > Array< T > & B::Array< T >::operator= (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> assignemnt.
Parameters
cfarr The input array.
References B::Array< T >::swap().
template<typename T > Array< T > & B::Array< T >::operator= (OSPtr< CFMutableArrayRef > cfarr)
OSPtr<CFMutableArrayRef> assignemnt.
Parameters
cfarr The input array.
References B::Array< T >::swap().
template<typename T > Array< T > & B::Array< T >::operator= (const std::vector< value_type > & vec)
vector assignemnt.
Parameters
vec The input vector.
References B::Array< T >::swap().
The documentation for this class was generated from the following file:
BArray.h