B: B::Cursor Class Reference
B::Cursor Class Reference
A simple cursor class.
#include <BCursor.h>
Classes
class ColorCursorWrapper
Internal class for managing color cursors.
Public Types
Types
typedef ::Cursor QuickdrawCursor
Synonym for ::Cursor.
Public Member Functions
Constructors / Destructor
Cursor ()
Default constructor.
Cursor (const Cursor &inCursor)
Copy constructor.
Cursor (ThemeCursor inCursor)
ThemeCursor constructor.
Cursor (const QuickdrawCursor &inCursor)
QuickdrawCursor constructor.
Cursor (CCrsrHandle inCursor)
CCrsrHandle constructor.
Cursor (const std::string &inCursor)
Named pixmap constructor.
Cursor (short inCursorID, bool inColorCursor)
Resource ID constructor.
Assignment
Cursor & operator= (const Cursor &inCursor)
Copy assignment.
Cursor & operator= (ThemeCursor inCursor)
ThemeCursor assignment.
Cursor & operator= (const QuickdrawCursor &inCursor)
QuickdrawCursor assignment.
Cursor & operator= (CCrsrHandle inCursor)
CCrsrHandle assignment.
Cursor & operator= (const std::string &inCursor)
Named pixmap assignment.
Cursor & Assign (short inCursorID, bool inColorCursor)
Resource ID assignment.
Setting
void Set ()
Changes the cursor.
Utility
void Clear ()
Resets the cursor to the arrow.
void swap (Cursor &ioCursor)
Exchanges the contents of two cursors.
Detailed Description
A simple cursor class.
This is a very simple concrete class that allows one to load a variety of different cursor types (theme, Quickdraw black & white, Quickdraw color, named pixmap). Of course once loaded you can make a cursor current (ie change the shape of the pointer on the screen). Note that this class only manages the storage of a cursor's bits, it doesn't provide screen management for cursor-tracking purposes.
Constructor & Destructor Documentation
B::Cursor::Cursor ()
Default constructor.
The cursor is initialised to the arrow.
Referenced by Assign(), Cursor(), and operator=().
B::Cursor::Cursor (CCrsrHandle inCursor) explicit
CCrsrHandle constructor.
Note
The newly constructed object takes ownership of inCursor.
B::Cursor::Cursor (const std::string & inCursor) explicit
Named pixmap constructor.
Note
The named pixmap cursor should already be registered. See under QDRegisterNamedPixMapCursor() in Quickdraw.h for more information.
B::Cursor::Cursor (short inCursorID, bool inColorCursor) explicit
Resource ID constructor.
The function uses the Resource Manager to look for a 'CURS' or 'crsr' resource with ID inCursorID. The particular resource type is determined by inColorCursor; if true, we look for a 'crsr' resource, else we look for 'CURS'.
Parameters
inCursorID The resource ID of the cursor.
inColorCursor Should the cursor be color or black & white?
References B::AutoTypedResourceHandle< T >::get(), and B::AutoTypedResourceHandle< T >::load().
The documentation for this class was generated from the following files:
BCursor.h
BCursor.cpp