B: B::MutableArray< T > Class Template Reference
B::MutableArray< T > Class Template Reference
Adapter class for changeable arrays.
#include <BMutableArray.h>
Public Types
Types
typedef Array< T >::value_type value_type
The type of the characters.
typedef Array< T >::size_type size_type
The unsigned integral type for size values and indices.
typedef Array< T >::difference_type difference_type
The signed integral type for difference values.
typedef Array< T >::reference reference
The signed integral type for difference values.
typedef Array< T >::const_reference const_reference
The type of constant character references.
typedef Array< T >::pointer pointer
The type of character pointers.
typedef Array< T >::const_pointer const_pointer
The type of character pointers.
typedef Array< T >::iterator iterator
The type of iterators.
typedef Array< T >::const_iterator const_iterator
The type of constant iterators.
typedef Array< T >::reverse_iterator reverse_iterator
The type of reverse iterators.
typedef Array< T >::const_reverse_iterator const_reverse_iterator
The type of constant reverse iterators.
typedef Array< T >::allocator_type allocator_type
The type of the allocator.
Public Member Functions
template<class InputIterator >
MutableArray< T > & assign (InputIterator first, InputIterator last)
Constructors / Destructor
MutableArray ()
Default constructor.
MutableArray (const MutableArray &arr)
Copy constructor.
MutableArray (const Array< T > &arr)
Array constructor.
MutableArray (CFAllocatorRef allocator)
Allocator constructor.
MutableArray (size_type num, CFAllocatorRef allocator=NULL)
Size constructor.
MutableArray (size_type num, T value, CFAllocatorRef allocator=NULL)
T constructor.
MutableArray (CFArrayRef cfarr)
CFArrayRef constructor.
MutableArray (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> constructor.
MutableArray (OSPtr< CFMutableArrayRef > cfarr, bool acquire)
OSPtr<CFMutableArrayRef> constructor.
MutableArray (const std::vector< value_type > &vec)
vector constructor.
template<class InputIterator >
MutableArray (InputIterator first, InputIterator last, CFAllocatorRef allocator=NULL)
Range constructor.
~MutableArray ()
Destructor.
Operations for Size and Capacity
size_type size () const
Returns the number of elements in the array.
bool empty () const
Returns whether the array is empty.
size_type max_size () const
Returns the maximum number of characters an array could contain.
size_type capacity () const
Returns the number of elements the array could contain without reallocation.
void reserve (size_type n=0)
Non-binding request to resize the internal storage to max(n, size()).
Assignments
MutableArray & operator= (const MutableArray &arr)
Replaces all existing elements with copies of the elements of arr.
MutableArray & operator= (const Array< T > &arr)
Array assignemnt.
MutableArray & operator= (CFArrayRef cfarr)
CFArrayRef assignemnt.
MutableArray & operator= (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> assignemnt.
MutableArray & operator= (OSPtr< CFMutableArrayRef > cfarr)
OSPtr<CFMutableArrayRef> assignemnt.
MutableArray & operator= (const std::vector< value_type > &vec)
vector assignemnt.
MutableArray & assign (size_type num, T value)
Replaces all existing elements with num copies of value.
template<class InputIterator >
MutableArray & assign (InputIterator first, InputIterator last)
Replaces all existing elements with copies of the elements in the range [first, last).
void swap (MutableArray &arr)
Exchanges the contents with arr.
Direct Element Access
reference at (size_type index)
Returns the element with index index.
const_reference at (size_type index) const
Returns the element with index index.
reference operator[] (size_type index)
Returns the element with index index.
const_reference operator[] (size_type index) const
Returns the element with index index.
reference front ()
Returns the first element.
const_reference front () const
Returns the first element.
reference back ()
Returns the last element.
const_reference back () const
Returns the last element.
void copy (std::vector< value_type > &vec) const
Converts the array into a vector.
Operations to Generate Iterators
iterator begin ()
Returns an iterator for the beginning of the array.
const_iterator begin () const
Returns an iterator for the beginning of the array.
iterator end ()
Returns an iterator for the end of the array.
const_iterator end () const
Returns an iterator for the end of the array.
reverse_iterator rbegin ()
Returns an iterator for the beginning of a reverse iteration of the array.
const_reverse_iterator rbegin () const
Returns an iterator for the beginning of a reverse iteration of the array.
reverse_iterator rend ()
Returns an iterator for the end of a reverse iteration of the array.
const_reverse_iterator rend () const
Returns an iterator for the end of a reverse iteration of the array.
Inserting and Removing Elements
iterator insert (iterator pos, T value)
Inserts a copy of value at the position of iterator pos.
void insert (iterator pos, size_type num, T value)
Inserts num copies of value at the position of iterator pos.
template<class InputIterator >
void insert (iterator pos, InputIterator first, InputIterator last)
Inserts copies of the elements in the range [first, last) at the position of iterator pos.
void push_back (T value)
Appends a copy of value at the end of the array.
iterator erase (iterator pos)
Removes the element at the position of iterator pos.
iterator erase (iterator first, iterator last)
Removes the elements in the range [first, last).
void pop_back ()
Removes the last element of the array.
void resize (size_type num, T value=NULL)
Changes the number of elements to num.
void clear ()
Removes all of the elements.
Generating CFMutableArrayRefs.
CFMutableArrayRef cf_ref () const
Returns the underlying CFMutableArrayRef.
OSPtr< CFMutableArrayRef > cf_ptr () const
Returns a "smart pointer" to the underlying CFMutableArrayRef.
Allocator Support
allocator_type get_allocator () const
Returns the memory model of the array.
Related Functions
(Note that these are not member functions.)
MutableArray Comparisons
template<typename T >
bool operator== (const MutableArray< T > &a1, const MutableArray< T > &a2)
template<typename T >
bool operator!= (const MutableArray< T > &a1, const MutableArray< T > &a2)
Miscellaneous
template<typename T >
void swap (MutableArray< T > &a1, MutableArray< T > &a2)
Detailed Description
template<typename T>
class B::MutableArray< T >
Adapter class for changeable arrays.
MutableArray provides a wrapper around a CoreFoundation CFMutableArrayRef object, giving it an interface similar (nearly identical in fact) to std::vector. This makes it possible to use MutableArray with STL algorithms, with standard streams, etc.
Unlike Array, MutableArray does not share CFMutableArrayRefs between its instances. Each MutableArray gets its own independent CFMutableArrayRefs. The one exception to this is the OSPtr<CFMutableArrayRef> constructor, which can optionally share its argument instead of copying it.
Other notable differences with std::vector :
- The template parameter @a T is assumed to be a CoreFoundation type.  Specifically,
  it needs to obey the semantics of @c CFRetain() and @c CFRelease(), and there
  needs to be a template specialisation of @c CFUGetType<>() for it.
- There are more conversions.  This reflects MutableArray's role as an
  adapter between CoreFoundation and the Standard C++ Library.  For example, one
  may construct instances of MutableArray with any of the following types:
    - Array
    - MutableArray
    - <tt>CFArrayRef</tt>
    - <tt>OSPtr<CFArrayRef></tt>
    - <tt>OSPtr<CFMutableArrayRef></tt>
    - <tt>std::vector</tt>
- Likewise, one may copy() a MutableArray back into an @c std::vector.
- The allocator type is fixed as @c CFAllocatorRef.  The allocator type is not a
  template parameter, however allocators @e are passed as arguments to
  constructors and can be retrieved via get_allocator().
- The underlying @c CFMutableArrayRef's storage is not accessible, so it's not
  possible to take the address of an element of an MutableArray.  Likewise, at(),
  operator [] (), front() and back() return objects which can extract the
  element's value.  MutableArray is incompatible with the STL in this respect.
- MutableArray doesn't support the following global comparison operators:
  @c < @c <= @c > @c >= .  This is because ordering of CoreFoundation types isn't
  well-defined.  The operators @c == and @c != @e are supported and are
  implemented in terms of @c CFEqual().
Constructor & Destructor Documentation
template<typename T > B::MutableArray< T >::MutableArray ()
Default constructor.
Creates an empty array using the default allocator.
template<typename T > B::MutableArray< T >::MutableArray (const MutableArray< T > & arr)
Copy constructor.
Creates a shallow copy of arr.
template<typename T> B::MutableArray< T >::MutableArray (const Array< T > & arr)
Array constructor.
Creates a shallow copy of arr.
References B::Array< T >::cf_ref().
template<typename T> B::MutableArray< T >::MutableArray (CFAllocatorRef allocator) explicit
Allocator constructor.
Creates an empty array using allocator.
template<typename T> B::MutableArray< T >::MutableArray (size_type num, CFAllocatorRef allocator = NULL) explicit
Size constructor.
Creates an array containing num elements of type T whose value is NULL.
template<typename T> B::MutableArray< T >::MutableArray (size_type num, T value, CFAllocatorRef allocator = NULL) explicit
T constructor.
Creates an array that is initialised by n occurrences of value.
template<typename T> B::MutableArray< T >::MutableArray (CFArrayRef cfarr) explicit
CFArrayRef constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
template<typename T> B::MutableArray< T >::MutableArray (OSPtr< CFArrayRef > cfarr) explicit
OSPtr<CFArrayRef> constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
template<typename T> B::MutableArray< T >::MutableArray (OSPtr< CFMutableArrayRef > cfarr, bool acquire) explicit
OSPtr<CFMutableArrayRef> constructor.
Creates an array as a copy of cfarr, using cfarr's allocator.
Parameters
cfarr The source array.
acquire If true, we take cfarr as our internal storage, rather than making a copy.
References B::OSPtr< T >::get().
template<typename T> B::MutableArray< T >::MutableArray (const std::vector< value_type > & vec) explicit
vector constructor.
Parameters
vec The source vector.
template<typename T > template<class InputIterator > B::MutableArray< T >::MutableArray (InputIterator first, InputIterator last, CFAllocatorRef allocator = NULL) explicit
Range constructor.
Creates an array that is initialised by all elements of the range [first, last).
Member Function Documentation
template<typename T > void B::MutableArray< T >::reserve (size_type n = 0)
Non-binding request to resize the internal storage to max(n, size()).
Stub implementation. CFMutableArrayRef doesn't have a notion of capacity that parallels the one in std::vector.
template<typename T> MutableArray< T > & B::MutableArray< T >::operator= (CFArrayRef cfarr)
CFArrayRef assignemnt.
Parameters
cfarr The input array.
template<typename T> MutableArray< T > & B::MutableArray< T >::operator= (OSPtr< CFArrayRef > cfarr)
OSPtr<CFArrayRef> assignemnt.
Parameters
cfarr The input array.
template<typename T> MutableArray< T > & B::MutableArray< T >::operator= (OSPtr< CFMutableArrayRef > cfarr)
OSPtr<CFMutableArrayRef> assignemnt.
Parameters
cfarr The input array.
template<typename T> MutableArray< T > & B::MutableArray< T >::operator= (const std::vector< value_type > & vec)
vector assignemnt.
Parameters
vec The input vector.
References B::MutableArray< T >::size().
The documentation for this class was generated from the following files:
BArray.h
BMutableArray.h