B: B::EventTarget Class Reference
B::EventTarget Class Reference
Carbon Events
Base class for custom derivatives of HIObject.
#include <BEventTarget.h>
Public Member Functions
template<>
EventTargetRef GetEventTarget (WindowRef inObj)
template<>
EventTargetRef GetEventTarget (HIViewRef inObj)
template<>
EventTargetRef GetEventTarget (HIObjectRef inObj)
template<>
EventTargetRef GetEventTarget (EventTargetRef inObj)
Modifiers
void SetAccessible (bool inAccessible)
Make the object archivable.
void SetAccessibilityAttribute (CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetAccessibilityAttribute (UInt64 inIdentifier, CFStringRef inAttributeName, CFTypeRef inAttributeValue)
Set a non-user-modifiable accessibility attribute.
void SetArchivable (bool inArchivable)
Make the object archivable.
Static Public Member Functions
Class Registration
template<class T >
static void Register ()
Registers class T (which must derive from EventTarget) with the HIToolbox.
template<class T >
static void Unregister ()
Unregisters class T (which must derive from EventTarget) from the HIToolbox.
template<class T >
static HIObjectClassRef GetObjectClass ()
Returns the object class associated with type T (which must derive from EventTarget), or NULL.
Object Creation
template<class T >
static OSPtr< HIObjectRef > Create (EventRef inEvent=NULL)
Creates an instance of class T.
static OSPtr< HIObjectRef > Create (CFStringRef inClassID, EventRef inEvent=NULL)
Creates an instance of class inClassID.
Static Public Attributes
static const CFStringRef kHIObjectBaseClassID = NULL
The default base class ID, representing HIObject.
Protected Types
Types
typedef EventTarget *(* ConstructProcPtr) (HIObjectRef inObjectRef)
Object construction callback.
Protected Member Functions
Constructors / Destructor
EventTarget (HIObjectRef inObjectRef)
Constructor.
virtual ~EventTarget ()
Destructor.
Free Store
void operator delete (void *ptr)
Protected delete prevents external clients from deleting instances directly.
Handling Events
virtual void Initialize (EventRef inEvent)
Override to extract initialisation arguments from inEvent.
virtual bool IsEqualTo (HIObjectRef inObjectRef)
Returns true if this is "equal" to inObjectRef.
virtual void PrintDebugInfo ()
Override to print debugging information to stdout.
virtual void Unarchive (HIArchiveRef ioArchive)
Decode the object into the given archive. This is called instead of Initialize().
virtual void Archive (HIArchiveRef ioArchive) const
Encode the object into the given archive.
Static Protected Member Functions
Class Registration / Unregistration / Instantiation
static void PrivateRegister (CFStringRef inClassID, CFStringRef inBaseClassID, ConstructProcPtr inConstructor)
Registers class inClassID.
static void PrivateUnregister (CFStringRef inClassID)
Unregisters class inClassID.
static HIObjectClassRef PrivateFindClassObject (CFStringRef inClassID)
Returns the object class associated with type inClassID, or NULL.
static HIObjectRef PrivateCreate (CFStringRef inClassID, EventRef inEvent)
Creates an instance of class inClassID.
Protected Attributes
const HIObjectRef mObjectRef
The underlying toolbox object.
Friends
class Init
Inquiries
template<class T >
static T * InstanceData (HIObjectRef objRef)
Retrieves the C++ object of type T associated with the HIObjectRef objRef.
bool IsAccessible () const
Is the object accessible?
bool IsArchivable () const
Is the object archivable?
Conversions
template<typename T >
static EventTargetRef GetEventTarget (T inObject)
Retrieves the EventTargetRef associated with inObject.
operator HIObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
HIObjectRef GetObjectRef () const
Retrieves the HIObjectRef associated with this C++ object.
EventTargetRef GetEventTarget () const
Retrieves the underlying EventTargetRef.
Detailed Description
Base class for custom derivatives of HIObject.
Once an EventTarget is instantiated, its lifetime is tied to that of its underlying HIObjectRef. Its lifetime should be controlled using the normal CF mechanisms (CFRetain & CFRelease) rather than operator delete.
Constructor & Destructor Documentation
B::EventTarget::EventTarget (HIObjectRef inObjectRef) protected
Constructor.
Parameters
inObjectRef The underlying toolbox object.
Member Function Documentation
template<class T > void B::EventTarget::Register () static
Registers class T (which must derive from EventTarget) with the HIToolbox.
The template parameter T must have the following characterstics:
It must contain a static member variable of type CFStringRef called kHIObjectClassID. This variable contains the class's unique identifier.
It may contain a static member variable of type CFStringRef called kHIObjectBaseClassID. This variable contains the base class's unique identifier. If this variable isn't present, a default value defined in EventTarget is used, in which case T is assumed to derived directly from HIObject.
It must contain a public static member function called Instantiate which has the same signature as ConstructProcPtr. The function needs to instantiate a T and return it as an EventTarget.
Parameters
T Template parameter. Should be a class that derives from EventTarget.
template<class T > void B::EventTarget::Unregister () static
Unregisters class T (which must derive from EventTarget) from the HIToolbox.
The template parameter T must have the following characterstics:
It must contain a static member variable of type CFStringRef called kHIObjectClassID. This variable contains the class's unique identifier.
Parameters
T Template parameter. Should be a class that derives from EventTarget.
template<class T > HIObjectClassRef B::EventTarget::GetObjectClass () static
Returns the object class associated with type T (which must derive from EventTarget), or NULL.
The template parameter T must have the following characterstics:
It must contain a static member variable of type CFStringRef called kHIObjectClassID. This variable contains the class's unique identifier.
Parameters
T Template parameter. Should be a class that derives from EventTarget.
template<class T > OSPtr< HIObjectRef > B::EventTarget::Create (EventRef inEvent = NULL) static
Creates an instance of class T.
The template parameter T must have the following characterstics:
It must contain a static member variable of type CFStringRef called kHIObjectClassID. This variable contains the class's unique identifier.
Parameters
T Template parameter. Should be a class that derives from EventTarget.
Parameters
inEvent Initialisation event for the new object.
Referenced by B::ToolbarItem::Create(), and B::Toolbar::Initialize().
OSPtr< HIObjectRef > B::EventTarget::Create (CFStringRef inClassID, EventRef inEvent = NULL) static
Creates an instance of class inClassID.
Parameters
inEvent Initialisation event for the new object.
template<class T > T * B::EventTarget::InstanceData (HIObjectRef objRef) static
Retrieves the C++ object of type T associated with the HIObjectRef objRef.
The template parameter T must have the following characterstics:
It must contain a static member variable of type CFStringRef called kHIObjectClassID. This variable contains the class's unique identifier.
Parameters
T Template parameter. Must be a class that derives from EventTarget.
Returns
A T* if objRef is of the proper type, else NULL.
void B::EventTarget::PrivateRegister (CFStringRef inClassID, CFStringRef inBaseClassID, ConstructProcPtr inConstructor) static protected
Registers class inClassID.
Parameters
inClassID The class's ID.
inBaseClassID The base class's ID.
inConstructor A function that will create instances of the class identified by inClassID.
void B::EventTarget::PrivateUnregister (CFStringRef inClassID) static protected
Unregisters class inClassID.
Parameters
inClassID The class's ID.
HIObjectClassRef B::EventTarget::PrivateFindClassObject (CFStringRef inClassID) static protected
Returns the object class associated with type inClassID, or NULL.
Parameters
inClassID The class's ID.
HIObjectRef B::EventTarget::PrivateCreate (CFStringRef inClassID, EventRef inEvent) static protected
Creates an instance of class inClassID.
Parameters
inClassID The class's ID.
inEvent The initialisation event. This is passed to the newly created object.
References Archive(), B::EventParamAndType< NAME, TYPE >::Get(), B::EventParamAndType< NAME, EventParamNameTrait< NAME >::kTypeTag >::Get(), B::EventParamAndType< kEventParamDirectObject, TYPE >::Get(), B::OSPtr< T >::get(), GetEventTarget(), Initialize(), IsArchivable(), IsEqualTo(), PrintDebugInfo(), B::EventParamAndType< NAME, TYPE >::Set(), and Unarchive().
void B::EventTarget::operator delete (void * ptr) protected
Protected delete prevents external clients from deleting instances directly.
We don't actually have a real implementation of delete, so call through to the global version.
void B::EventTarget::Initialize (EventRef inEvent) protected virtual
Override to extract initialisation arguments from inEvent.
inEvent is the same EventRef passed to HIObjectCreate() or EventTarget::Create().
Note
If the object supports archiving, then Unarchive() will be called instead.
Parameters
inEvent The initialisation event.
Reimplemented in B::ToolbarItem, and B::Toolbar.
Referenced by PrivateCreate().
void B::EventTarget::Unarchive (HIArchiveRef ioArchive) protected virtual
Decode the object into the given archive. This is called instead of Initialize().
Note
If the object does not support archiving, then Initialize() will be called instead.
Referenced by PrivateCreate().
The documentation for this class was generated from the following files:
BEventTarget.h
BEventTarget.cpp