B: B::AEWriter Class Reference
B::AEWriter Class Reference
Apple Events
Encapsulates a writable Apple Event descriptor "stream". It's basically a wrapper around AEStreamRef.
#include <BAEWriter.h>
Public Member Functions
Constructors / Destructor
AEWriter ()
Default constructor. Opens the stream for writing a single descriptor.
AEWriter (AEEventClass clazz, AEEventID id, short returnID=kAutoGenerateReturnID, long transactionID=kAnyTransactionID)
Constructor that opens the stream for writing an Apple Event targeting the current process.
template<typename TARGET >
AEWriter (AEEventClass clazz, AEEventID id, TARGET target, short returnID=kAutoGenerateReturnID, long transactionID=kAnyTransactionID)
Constructor that opens the stream for writing an Apple Event.
AEWriter (AppleEvent &event)
Constructor that opens the stream for appending to an existing Apple Event.
AEWriter (AEStreamRef stream)
Constructor that opens the stream on an existing AEStreamRef.
~AEWriter ()
Destructor.
Inquiries
bool IsOpen () const
Returns whether the stream is open or not.
Opening & Closing The Stream
void Open ()
Opens the stream for writing a single descriptor.
void Open (AEEventClass clazz, AEEventID id, short returnID=kAutoGenerateReturnID, long transactionID=kAnyTransactionID)
Opens the stream for writing an Apple Event targeting the current process.
template<typename TARGET >
void Open (AEEventClass clazz, AEEventID id, TARGET target, short returnID=kAutoGenerateReturnID, long transactionID=kAnyTransactionID)
Opens the stream for writing an Apple Event.
void Open (AppleEvent &event)
Opens the stream for appending to an existing Apple Event.
void Close (AEDesc &outDesc)
Closes the stream, returning its output in outDesc.
void Close (std::vector< UInt8 > &outBuff)
Closes the stream, returning a flattened form of the output descriptor in outBuff.
void Close ()
Closes the stream, discarding any output.
Opening & Closing Descriptors
Note
You need to open the stream before you can open a descriptor.
void OpenDesc (DescType type)
Opens a descriptor of type type.
void OpenDescKey (AEKeyword key, DescType type)
Opens a descriptor of type type, identified by key.
void CloseDesc ()
Closes the currently open descriptor.
Opening & Closing Records
Note
You need to open the stream before you can open a record.
void OpenRecord (DescType type=typeAERecord)
Opens a descriptor record of type type.
void OpenRecordKey (AEKeyword key, DescType type=typeAERecord)
Opens a descriptor record of type type, identified by key.
void CloseRecord ()
Closes the currently open descriptor record.
Opening & Closing Lists
Note
You need to open the stream before you can open a list.
void OpenList ()
Opens a descriptor list.
void OpenListKey (AEKeyword key)
Opens a descriptor list identified by key.
void CloseList ()
Closes the currently open descriptor list.
Writing Values
template<DescType TYPE>
AEWriter & Write (const typename DescParam< TYPE >::ValueType &value)
Writes a single value as a descriptor in a type-safe manner.
AEWriter & WriteObject (const AEObject &value)
Writes the given AEObject as an object specifier.
AEWriter & WriteDesc (const AEDesc &value)
Copies value into the stream.
AEWriter & Append (const void *inPtr, size_t inSize)
Sending Events
void Send (AESendMode inMode=0)
void Send (AEDesc &outResult, AESendMode inMode=0)
Keywords
void CacheNextKeyword (AEKeyword key)
Caches key until the next time a descriptor is written.
void FlushNextKeyword ()
Writes out the currently cached AEKeyword, if any.
void OptionalParam (AEKeyword key)
Friends
class AETypedObjectBase
Related Functions
(Note that these are not member functions.)
AEWriter & operator<< (AEWriter &writer, const AEDesc &desc)
AEWriter & operator<< (AEWriter &writer, const String &value)
AEWriter & operator<< (AEWriter &writer, const Url &value)
Detailed Description
Encapsulates a writable Apple Event descriptor "stream". It's basically a wrapper around AEStreamRef.
Reading Apple's documentation for AEStreamRef will probably go a long way toward clarifying how this class should be used. Here's where to get it:
http://developer.apple.com/technotes/tn/tn2046.html
Constructor & Destructor Documentation
B::AEWriter::AEWriter (AEEventClass clazz, AEEventID id, short returnID = kAutoGenerateReturnID, long transactionID = kAnyTransactionID)
Constructor that opens the stream for writing an Apple Event targeting the current process.
Parameters
clazz The Apple Event's event class.
id The Apple Event's event ID.
returnID The return ID, used to pair up events with replies.
transactionID The transaction ID, used to track a series of related events.
References Open().
template<typename TARGET > B::AEWriter::AEWriter (AEEventClass clazz, AEEventID id, TARGET target, short returnID = kAutoGenerateReturnID, long transactionID = kAnyTransactionID)
Constructor that opens the stream for writing an Apple Event.
The target argument allows the caller complete flexibility in specifying the recipient of the event.
Consult the Apple Event Manager documentation for more information.
Parameters
clazz The Apple Event's event class.
id The Apple Event's event ID.
target The event's receiving process.
returnID The return ID, used to pair up events with replies.
transactionID The transaction ID, used to track a series of related events.
References Open().
B::AEWriter::AEWriter (AppleEvent & event)
Constructor that opens the stream for appending to an existing Apple Event.
Parameters
event The Apple Event to append to.
References Open().
B::AEWriter::AEWriter (AEStreamRef stream)
Constructor that opens the stream on an existing AEStreamRef.
Parameters
stream The stream to append to.
B::AEWriter::~AEWriter ()
Destructor.
If the stream is open and owned by us (i.e. it wasn't instantiated via the AEStreamRef constructor), then it is closed and any generated output is discarded.
Member Function Documentation
void B::AEWriter::Open ()
Opens the stream for writing a single descriptor.
If the stream is already open, it is closed then re-opened.
References Close(), and IsOpen().
Referenced by AEWriter(), OpenDesc(), OpenDescKey(), OpenList(), OpenListKey(), OpenRecord(), and OpenRecordKey().
void B::AEWriter::Open (AEEventClass clazz, AEEventID id, short returnID = kAutoGenerateReturnID, long transactionID = kAnyTransactionID)
Opens the stream for writing an Apple Event targeting the current process.
If the stream is already open, it is closed then re-opened.
Parameters
clazz The Apple Event's event class.
id The Apple Event's event ID.
returnID The return ID, used to pair up events with replies.
transactionID The transaction ID, used to track a series of related events.
References Close(), and IsOpen().
template<typename TARGET > void B::AEWriter::Open (AEEventClass clazz, AEEventID id, TARGET target, short returnID = kAutoGenerateReturnID, long transactionID = kAnyTransactionID)
Opens the stream for writing an Apple Event.
If the stream is already open, it is closed then re-opened.
The target argument allows the caller complete flexibility in specifying the recipient of the event.
Consult the Apple Event Manager documentation for more information.
Parameters
clazz The Apple Event's event class.
id The Apple Event's event ID.
target The event's receiving process.
returnID The return ID, used to pair up events with replies.
transactionID The transaction ID, used to track a series of related events.
References Close(), and IsOpen().
void B::AEWriter::Open (AppleEvent & event)
Opens the stream for appending to an existing Apple Event.
If the stream is already open, it is closed then re-opened.
Parameters
event The Apple Event to append to.
References Close(), and IsOpen().
void B::AEWriter::Close (AEDesc & outDesc)
Closes the stream, returning its output in outDesc.
Parameters
outDesc The Apple Event descriptor result.
Referenced by B::AEObject::AccessElementsByAbsolutePos(), B::AEObjectSupport::CompareStrings(), B::AEObjectSupport::CountAllElements(), B::DescParamHelper::GetCoercedData(), B::AEEvent< kASAppleScriptSuite, kASCommentEvent >::Make(), B::AEEventBase::MakeSimpleEvent(), B::AEObject::Resolve(), B::AEObjectSupport::RethrowExceptionFromAppleEventReply(), and B::Window::SetIdealSize().
void B::AEWriter::Close (std::vector< UInt8 > & outBuff)
Closes the stream, returning a flattened form of the output descriptor in outBuff.
Parameters
outBuff The flattened (i.e., serialised) Apple Event descriptor result.
References Close().
void B::AEWriter::OpenDesc (DescType type)
Opens a descriptor of type type.
Use this function when writing a single descriptor or an element of a descriptor list.
If the stream itself isn't already open, it is opened via Open().
Parameters
type The descriptor's type.
References FlushNextKeyword(), and Open().
Referenced by B::AutoAEWriterDesc::AutoAEWriterDesc().
void B::AEWriter::OpenDescKey (AEKeyword key, DescType type)
Opens a descriptor of type type, identified by key.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
Parameters
key The descriptor's keyword within its enclosing AERecord.
type The descriptor's type.
References Open().
Referenced by B::AutoAEWriterDesc::AutoAEWriterDesc().
void B::AEWriter::CloseDesc ()
Closes the currently open descriptor.
It's an error to call this function when there isn't a currently opened descriptor.
Referenced by B::AutoAEWriterDesc::~AutoAEWriterDesc().
void B::AEWriter::OpenRecord (DescType type = typeAERecord)
Opens a descriptor record of type type.
Use this function when writing a single descriptor or an element of a descriptor list.
If the stream itself isn't already open, it is opened via Open().
Parameters
type The descriptor's type.
References FlushNextKeyword(), and Open().
Referenced by B::AutoAEWriterRecord::AutoAEWriterRecord().
void B::AEWriter::OpenRecordKey (AEKeyword key, DescType type = typeAERecord)
Opens a descriptor record of type type, identified by key.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
Parameters
key The descriptor's keyword within its enclosing AERecord.
type The descriptor's type.
References Open().
Referenced by B::AutoAEWriterRecord::AutoAEWriterRecord().
void B::AEWriter::CloseRecord ()
Closes the currently open descriptor record.
It's an error to call this function when there isn't a currently opened descriptor record.
References FlushNextKeyword().
Referenced by B::AutoAEWriterRecord::~AutoAEWriterRecord().
void B::AEWriter::OpenList ()
Opens a descriptor list.
Use this function when writing a single descriptor or an element of a descriptor list.
If the stream itself isn't already open, it is opened via Open().
References FlushNextKeyword(), and Open().
Referenced by B::AutoAEWriterList::AutoAEWriterList(), and B::AEObjectSupport::CompareStrings().
void B::AEWriter::OpenListKey (AEKeyword key)
Opens a descriptor list identified by key.
Use this function when writing an element of a descriptor record.
If the stream itself isn't already open, it is opened via Open().
Parameters
key The descriptor's keyword within its enclosing AERecord.
References Open().
Referenced by B::AutoAEWriterList::AutoAEWriterList().
void B::AEWriter::CloseList ()
Closes the currently open descriptor list.
It's an error to call this function when there isn't a currently opened descriptor list.
Referenced by B::AEObjectSupport::CompareStrings(), and B::AutoAEWriterList::~AutoAEWriterList().
template<DescType TYPE> AEWriter & B::AEWriter::Write (const typename DescParam< TYPE >::ValueType & value)
Writes a single value as a descriptor in a type-safe manner.
The language type of value determines the descriptor type that is used, via the magic of DescParam<TYPE>.
Use this function when writing a single descriptor or to an element of a descriptor list.
Parameters
value The value to write.
References FlushNextKeyword(), and B::DescParam< TYPE >::Write().
Referenced by B::AbstractDocument::MakeCurrent(), operator<<(), B::AEObjectSupport::RethrowExceptionFromAppleEventReply(), B::Window::SetIdealSize(), B::AEEvent< kAECoreSuite, kAECountElements >::Update(), B::AEEvent< kAECoreSuite, kAEDoObjectsExist >::Update(), and B::AEObject::WriteProperty().
AEWriter & B::AEWriter::WriteDesc (const AEDesc & value)
Copies value into the stream.
Appends the binary blob identified by inPtr and inSize to the currently open descriptor.
Use this function when writing a single descriptor or an element of a descriptor list.
Parameters
value The Apple Event descriptor to copy verbatim into the stream.
References FlushNextKeyword().
Referenced by B::AEObjectSupport::CompareStrings(), B::AEEventFunctor::OptionalAEDesc::operator()(), operator<<(), B::Application< DOC_POLICY, UNDO_POLICY, PRINT_POLICY >::QuitApplication(), B::AEObject::Resolve(), and B::AEObjectSupport::RethrowExceptionFromAppleEventReply().
AEWriter & B::AEWriter::Append (const void * inPtr, size_t inSize)
Use this function when writing a single descriptor.
Parameters
inPtr The start of the data to write.
inSize The number of bytes to write.
void B::AEWriter::Send (AESendMode inMode = 0)
Use this function when writing an Apple Event.
Parameters
inMode Flags that control how the event is sent.
References Close(), and B::AEEventBase::SendEvent().
Referenced by B::MultipleUndoPolicy::Redo(), and B::SingleUndoPolicy::Undo().
void B::AEWriter::Send (AEDesc & outResult, AESendMode inMode = 0)
Use this function when writing an Apple Event.
Parameters
outResult The result returned by the event's recipient.
inMode Flags that control how the event is sent.
References Close(), and B::AEEventBase::SendEvent().
void B::AEWriter::FlushNextKeyword ()
Writes out the currently cached AEKeyword, if any.
Tags the keyword key as being optional.
Referenced by CloseRecord(), OpenDesc(), OpenList(), OpenRecord(), Write(), WriteDesc(), and WriteObject().
void B::AEWriter::OptionalParam (AEKeyword key)
Use this function when writing an Apple Event.
Parameters
key The Apple Event parameter being tagged as optional.
The documentation for this class was generated from the following files:
BAEWriter.h
BAEWriter.cpp