B: B::NavDialog Class Reference
B::NavDialog Class Reference abstract
Abstract base class for Navigation Services dialogs.
#include <BNavDialogs.h>
Public Member Functions
virtual ~NavDialog ()
Destructor. Releases resources.
Setup
Configuration functions meant for clients of the NavDialog classes.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
Retrieving Results
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
Protected Member Functions
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
Overridables
virtual NavDialogRef CreateDialog ()=0
Creates the NavDialogRef.
virtual void HandleUserAction (NavUserAction inUserAction)=0
Action notification.
virtual void DialogStarting (NavCBRec &ioParams)
Override this to do some processing after the dialog is created and initialised, but before it's displayed.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
Low-level function to handle Nav dialog events. There's normally no need to override this function.
Entering Dialogs
In B parlance, "Entering" a dialog means to display it according to its modality, i.e. if it's application-modal then the function doesn't return until the dialog is dismissed.
void Enter ()
Displays the nav dialog according to its modality.
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Dialog Control
These functions allow the developer to manipulate (aka control) the dialog. They are thin wrappers around NavCustomControl(). Most of them are only pertinent to the complex dialogs (get file, put file, etc.) and not the alert-style ones.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Detailed Description
Abstract base class for Navigation Services dialogs.
NavDialog is an abstract base class. It provides the common functionality required of all Navigation Services dialogs, but doesn't actually create Navigation Services dialog objects (i.e., NavDialogRefs); that is left to derived classes.
NavDialog's public interface is taken up mostly by configuration functions; they allow clients to tweak the dialog's behaviour prior to its being displayed. There is also a much smaller group of functions that allow the dialog to be "entered", i.e. to be displayed according to its modality.
Since NavDialog's main purpose is to be derived from, it supports a protected interface which serves as hooks for derived classes.
See also
Dialogs, Alerts and Navigation Services
Constructor & Destructor Documentation
B::NavDialog::NavDialog () protected
Protected default constructor to discourage stack-based instantiation.
Doesn't actually create the dialog (that is done in Display()), but sets up all member variables to reasonable values.
Member Function Documentation
void B::NavDialog::SetModality (const DialogModality & inModality)
Sets the dialog's modality.
Parameters
inModality The dialog's modality.
References B::DialogModality::GetModality(), and B::DialogModality::GetParent().
Referenced by B::AskSaveChangesDialog::Configure(), B::AskDiscardChangesDialog::Configure(), B::AskReviewDocumentsDialog::Configure(), and RunDialog().
void B::NavDialog::SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
Parameters
flags The flags to set.
Referenced by B::NavReplyDialog::NavReplyDialog(), B::PutFileDialog::PutFileDialog(), B::GetFileDialog::SelectDocumentType(), and B::NavReplyDialog::SetPopupMenuContents().
void B::NavDialog::ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
Parameters
flags The flags to clear.
Referenced by B::GetFileDialog::SelectDocumentType(), and B::NavReplyDialog::SetPopupMenuContents().
void B::NavDialog::SetLocation (const Point & pt)
Sets the dialog's location on the screen.
Parameters
pt The location of the dialog's top left corner.
void B::NavDialog::SetAppName (const String & name)
Sets the application's name in the dialog's title bar.
Note
It's not clear whether this is ever used under Aqua.
Parameters
name The name. Should be localised.
References B::String::cf_ref().
void B::NavDialog::SetTitle (const String & title)
Sets the dialog's title.
Parameters
title The title. Should be localised.
References B::String::cf_ref().
void B::NavDialog::SetMessage (const String & message)
Sets the dialog's message.
Parameters
message The message. Should be localised.
References B::String::cf_ref().
void B::NavDialog::SetFileName (const String & fileName)
Sets the file name.
Parameters
fileName The default file name. Should be localised.
References B::String::cf_ref().
Referenced by B::AskSaveChangesDialog::Configure(), B::AskDiscardChangesDialog::Configure(), and B::PutFileDialog::SelectDocumentType().
void B::NavDialog::SetActionButtonLabel (const String & label)
Sets the title of the "action" button (i.e., Open, Save, etc).
Parameters
label The label. Should be localised.
References B::String::cf_ref().
void B::NavDialog::SetCancelButtonLabel (const String & label)
Sets the title of the Cancel button.
Parameters
label The label. Should be localised.
References B::String::cf_ref().
void B::NavDialog::SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
Parameters
inPopupStrings The contents of the pop-up menu. Should be localised.
Referenced by B::NavReplyDialog::SetPopupMenuContents().
void B::NavDialog::SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
The prefs key is used to distinguish between dialogs for the purpose of storing configuration information, so that for example the size & location of an "Open File" dialog can be different from the size & location of a "Open Dictionary" dialog.
Parameters
key The key identifying a particular instance of a Nav dialog.
template<class NAV_DIALOG > void B::NavDialog::Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr) static
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Parameters
inDialogPtr The dialog to enter.
NavUserAction B::NavDialog::GetUserAction () const
Returns the action that dismissed the dialog.
Prior to dialog dismissal, this function will return kNavUserActionNone.
Referenced by B::AskSaveChangesDialog::GetAction(), B::AskDiscardChangesDialog::GetAction(), B::AskReviewDocumentsDialog::GetAction(), and RunDialog().
virtual NavDialogRef B::NavDialog::CreateDialog () protected pure virtual
Creates the NavDialogRef.
This is a pure virtual function, which all derived classes must override. All of the arguments must be passed through to one of the NavCreateXXXDialog functions.
Returns
The NavDialogRef. Never returns NULL; if an error occurs, an exception is thrown instead.
Referenced by Enter().
void B::NavDialog::HandleUserAction (NavUserAction inUserAction) protected pure virtual
Action notification.
Override this to handle user actions, such as clicking in dialog-dismissing buttons.
This is a pure virtual function, which all derived classes must override.
Parameters
inUserAction The user-initiated action.
Implemented in B::AskReviewDocumentsDialog, B::AskDiscardChangesDialog, B::AskSaveChangesDialog, and B::NavReplyDialog.
Referenced by HandleEvent().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp