B: B::NavReplyDialog Class Reference
B::NavReplyDialog Class Reference abstract
Abstract base class for complex Navigation Services dialogs.
#include <BNavDialogs.h>
Classes
class PopupMenuItem
Describes one element of the dialog's filtering pop-up menu.
Public Types
Constants
enum FilterKind {
kFilterName = 1, kFilterAllFiles, kFilterAllAppFiles, kFilterAllReadableFiles,
kFilterSeparator
}
< Types of file system object filtering.
Types
typedef std::vector< PopupMenuItem > PopupMenuContentsVector
The entire contents of the filtering pop-up menu.
Public Member Functions
virtual ~NavReplyDialog ()
Destructor.
Setup
Configuration functions meant for clients of the NavDialog classes.
void SetPopupMenuContents (PopupMenuContentsVector &inContents)
Sets the custom elements in the show & format pop-up menus.
void FilterAllFiles ()
Selects the "All Documents" pop-up menu item.
void FilterAllReadableFiles ()
Selects the "All Reaadable Documents" pop-up menu item.
void FilterByName (const String &inFilterName)
Selects the pop-up menu item for the given filter name.
void SetCustomView (Nib &inNib, const char *inViewName)
Sets the top-level custom view.
Retrieving Results
void GetNavReply (AutoNavReply &outNavReply) const
Returns the dialog's nav reply.
Public Member Functions inherited from B::NavDialog
virtual ~NavDialog ()
Destructor. Releases resources.
void SetModality (const DialogModality &inModality)
Sets the dialog's modality.
void SetDeleteOnDismiss (bool inDeleteOnDismiss)
Determines whether the NavDialog object gets deleted after the dialog is dismissed.
void SetFlags (NavDialogOptionFlags flags)
Sets some of the dialog option flags.
void ClearFlags (NavDialogOptionFlags flags)
Clears some of the dialog option flags.
void SetLocation (const Point &pt)
Sets the dialog's location on the screen.
void SetAppName (const String &name)
Sets the application's name in the dialog's title bar.
void SetTitle (const String &title)
Sets the dialog's title.
void SetMessage (const String &message)
Sets the dialog's message.
void SetFileName (const String &fileName)
Sets the file name.
void SetActionButtonLabel (const String &label)
Sets the title of the "action" button (i.e., Open, Save, etc).
void SetCancelButtonLabel (const String &label)
Sets the title of the Cancel button.
void SetPopupStrings (OSPtr< CFArrayRef > inPopupStrings)
Sets the custom elements in the show & format pop-up menus.
void SetPrefsKey (UInt32 key)
Sets the dialog's prefs key.
NavUserAction GetUserAction () const
Returns the action that dismissed the dialog.
void Enter ()
Displays the nav dialog according to its modality.
Protected Member Functions
NavReplyDialog ()
Protected default constructor to discourage stack-based instantiation.
View * FindCustomViewByID (int inID) const
View * FindCustomViewByID (OSType inSignature, int inID) const
virtual bool Preview (NavCBRecPtr ioParams)
Preview hook.
Overridables
virtual void HandleReply (NavUserAction inUserAction, NavReplyRecord &ioNavReply)=0
Action notification.
virtual void NegotiateCustomArea (Size &ioSize)
Override this function to negotiate an area in the dialog for custom UI elements.
virtual void DialogResized (Rect &ioCustomBounds, Rect &ioPreviewBounds)
Override this to do some processing when the dialog is resized.
virtual void LocationChanged (const AEDesc &inNewLocation)
Override this to do some processing when the location displayed in the browser list changes.
virtual void GoneToDesktop ()
Override this to do some processing when the desktop is displayed in the dialog.
virtual void PopupMenuSelect (const NavMenuItemSpec &inMenuItemSpec)
Override this to do some processing when the user choose an item in the show or format pop-up menu.
virtual void SelectionChanged (const AEDescList &inNewSelection)
Override this to do some processing when the selection in the browser list changes.
virtual void AdjustPreview (bool visible)
Override this to do some processing when preview area is turned on or off.
virtual void SelectionOpened ()
Override this to do some processing when the selection in the browser list is opened.
virtual void DialogAccepted ()
Override this to do some processing when the user performs a confirming action.
virtual void DialogCancelled ()
Override this to do some processing when the user performs a cancelling action.
File Filtering
Derived classes may override these to perform more specialised filtering.
virtual bool FilterObject (const AEDesc &inItem, const NavFileOrFolderInfo &inInfo, NavFilterModes inFilterMode)
Determines whether the object denoted by inItem, inInfo and inFilterMode should be displayed.
virtual bool FilterObjectByAllFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when "All Documents" is selected in the pop-up menu.
virtual bool FilterObjectByAllReadableFiles (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when "All Readable Documents" is selected in the pop-up menu.
virtual bool FilterObjectByFilterName (const FSRef &inRef, const LSItemInfoRecord &inInfo, NavFilterModes inFilterMode)
Performs filtering when a document type is selected in the pop-up menu.
virtual void SelectFilter (FilterKind inFilterKind, const String &inFilterName=String())
Changes the current filter.
Overrides from NavDialog
virtual void HandleUserAction (NavUserAction inUserAction)
virtual void HandleEvent (NavEventCallbackMessage inSelector, NavCBRec &ioParams)
virtual void DialogStarting (NavCBRec &ioParams)
Protected Member Functions inherited from B::NavDialog
NavDialog ()
Protected default constructor to discourage stack-based instantiation.
virtual NavDialogRef CreateDialog ()=0
Creates the NavDialogRef.
virtual void DialogEnding ()
Override this to do some processing before the dialog is destroyed.
const NavDialogCreationOptions & GetCreationOptions () const
Returns the options struct to pass to the NavCreateXXXDialog functions.
bool IsStarted () const
Is the dialog started ?
NavDialogRef GetDialogRef () const
Returns the underlying nav dialog object.
void Cancel ()
Tells the dialog to dismiss itself as if the user had clicked the Cancel button.
void Accept ()
Tells the dialog to dismiss itself as if the user had clicked the "accept" button.
void Terminate ()
Tells the dialog to dismiss itself.
NavUserAction RunDialog ()
Makes the dialog app-modal, turns delete-on-dismiss off, enter dialog, then returns dismissing action.
void * GetEventContext ()
Returns the user data to use for handling dialog events.
Protected Attributes
PopupMenuContentsVector mPopupMenuContents
FilterKind mCurrentFilterKind
The filter type of the currently selected item in the file type pop-up menu.
String mCurrentFilterName
The filter name of the currently selected item in the file type pop-up menu.
Dialog Control
These functions allow the developer to manipulate (aka control) the dialog. They are thin wrappers around NavCustomControl(). Most of them are only pertinent to the complex dialogs (get file, put file, etc.) and not the alert-style ones.
void ShowDesktop ()
Tells the dialog to display the desktop.
void SortBy (NavSortKeyField inField)
Tells the dialog to sort the browser list according to inField.
void SortOrder (NavSortOrder inOrder)
Tells the dialog to sort the browser list in ascending or descending order, according to inOrder.
void ScrollHome ()
Tells the dialog to scroll the browser list to the top.
void ScrollEnd ()
Tells the dialog to scroll the browser list to the bottom.
void ScrollPageUp ()
Tells the dialog to scroll the browser list up a page.
void ScrollPageDown ()
Tells the dialog to scroll the browser list down a page.
void GetLocation (AEDesc &outLocation)
Tells the dialog to return the location displayed in the browser list.
void SetLocation (const AEDesc &inLocation)
Tells the dialog to change the location displayed in the browser list.
void GetSelection (AEDesc &outSelection)
Tells the dialog to return the selection in the browser list.
void SetSelection (const AEDesc &inSelection)
Tells the dialog to change the selection in the browser list.
void ShowSelection ()
Tells the dialog to reveal the selection in the browser list.
void OpenSelection ()
Tells the dialog to open the selected item in the browser list.
void EjectVolume (short inVRefNum)
Tells the dialog to eject the volume identified by inVRefNum.
bool IsPreviewShowing ()
Returns true if the preview area is currently available.
void SelectCustomType (const NavMenuItemSpec &inSpec)
Tells the dialog to choose the custom pop-up menu item identified by inSpec.
void SelectAllType (MenuItemIndex inItem)
Tells the dialog to choose the standard pop-up menu item identified by inItem.
void SelectEditFileName (const struct ControlEditTextSelectionRec &inSelection)
Tells the dialog to change the selection in the file name field.
void BrowserSelectAll ()
Tells the dialog to select all items in the browser list.
void GotoParent ()
Tells the dialog to navigate to the parent item of the current selection.
void SetActionState (NavActionState inActionState)
Tells the dialog to prevent the user from performing certain actions, such clicking the Cancel button.
void BrowserRedraw ()
Tells the dialog to refresh its browser list.
bool RunReplyDialog (NavUserAction inConfirmAction, AutoNavReply &outNavReply)
Runs the dialog, returning the nav reply if the user confirmed the dialog.
static NavObjectFilterUPP GetObjectFilterUPP ()
Returns the UPP to use for filtering file system objects.
static NavPreviewUPP GetPreviewUPP ()
Returns the UPP to use for previewing.
Additional Inherited Members
Static Public Member Functions inherited from B::NavDialog
template<class NAV_DIALOG >
static void Enter (std::auto_ptr< NAV_DIALOG > inDialogPtr)
Displays the given nav dialog according to its modality, taking control of the dialog's lifetime.
Static Protected Member Functions inherited from B::NavDialog
static NavEventUPP GetEventUPP ()
Returns the UPP to use for handling dialog events.
Detailed Description
Abstract base class for complex Navigation Services dialogs.
NavReplyDialog derives from NavDialog and is also an abstract base class. It provides numerous additional services for the more complex NavServices dialogs. Its public interface supports:
Retrieving a NavReplyRecord. The returned structure is wrapped in an AutoNavReply object, which will ensure its proper disposal.
Setting up the file type pop-up menu. This menu is used for two purposes. In PutFileDialog, it allows the user to choose which file format to use when saving the file. In the other dialogs (eg GetFileDialog) it allows the user to filter the displayed file system contents. In all cases, the menu is optional.
Setting up a custom view area from a Nib. This allows clients to insert their own UI widgets into the dialog.
Since NavReplyDialog's main purpose is to be derived from, it supports a large protected interface, part of which serves as hooks for derived classes. That interface can be subdivided into the following categories:
Action notification. There are numerous virtual functions that are called whenever interesting things happen in the dialog. For example, PopupMenuSelect() is called when the user chooses an item in the file type pop-up menu.
Filtering hooks. A group of virtual functions can be overridden to customize the filtering that occurs for a given filter type.
Dialog control. There is a large number of functions that allow the nav dialog to be controlled in various ways. These are almost all wrappers around the NavCustomControl() function.
See also
Dialogs, Alerts and Navigation Services
Member Enumeration Documentation
enum B::NavReplyDialog::FilterKind
< Types of file system object filtering.
Enumerator
kFilterName
Filter is specified in mName field of PopupMenuItem struct.
kFilterAllFiles
All files, regardless of extension, file type or creator.
kFilterAllAppFiles
All files matching a creator code (UNIMPLEMENTED).
kFilterAllReadableFiles
All files matching one of a set of extensions and file types.
kFilterSeparator
Menu item separator.
Constructor & Destructor Documentation
B::NavReplyDialog::NavReplyDialog () protected
Protected default constructor to discourage stack-based instantiation.
Doesn't actually create the dialog (that is done in Display()), but sets up all member variables to reasonable values.
References B::NavDialog::SetFlags().
Member Function Documentation
void B::NavReplyDialog::FilterByName (const String & inFilterName)
Selects the pop-up menu item for the given filter name.
Parameters
inFilterName The filter name to use for matching of files.
References kFilterName, and SelectFilter().
Referenced by B::GetFileDialog::SelectDocumentType(), and B::PutFileDialog::SelectDocumentType().
void B::NavReplyDialog::SetCustomView (Nib & inNib, const char * inViewName)
Sets the top-level custom view.
In the current implementation, inViewName is the name of a window defined in inNib. The "custom view" in the Nav dialog is constructed by moving all subviews of the window's content view into a user pane control residing in the dialog. The window must be sized to the minimum size of the custom area, since this size is used during custom area negotiation. Needless to say, all subviews must react properly when moved from one window to another.
Note
This function must be called before the dialog is displayed.
Parameters
inNib The nib from which to load the view.
inViewName The name of the view to load.
References B::NavDialog::IsStarted().
void B::NavReplyDialog::GetNavReply (AutoNavReply & outNavReply) const
Returns the dialog's nav reply.
Parameters
outNavReply The nav reply.
References AdjustPreview(), B::ViewFactory::Default(), DialogAccepted(), DialogCancelled(), DialogResized(), B::NavDialog::DialogStarting(), B::WindowUtils::GetContentView(), B::NavDialog::GetDialogRef(), GoneToDesktop(), B::NavDialog::HandleEvent(), B::View::InstantiateSubviews(), LocationChanged(), mCurrentFilterKind, mCurrentFilterName, NegotiateCustomArea(), PopupMenuSelect(), B::ViewUtils::rbegin(), B::ViewUtils::rend(), B::AutoNavReply::reset(), SelectFilter(), SelectionChanged(), and SelectionOpened().
Referenced by HandleUserAction(), and RunReplyDialog().
virtual void B::NavReplyDialog::HandleReply (NavUserAction inUserAction, NavReplyRecord & ioNavReply) protected pure virtual
Action notification.
Override this to handle user actions, such as clicking in dialog-dismissing buttons.
This is a pure virtual function, which all derived classes must override.
Referenced by HandleUserAction().
bool B::NavReplyDialog::FilterObject (const AEDesc & inItem, const NavFileOrFolderInfo & inInfo, NavFilterModes inFilterMode) protected virtual
Determines whether the object denoted by inItem, inInfo and inFilterMode should be displayed.
This is the main object-filtering function. It basically just dispatches to the more specialised filtering functions, depending on the current file filter.
Parameters
inItem Contains one object to filter. This may or may not be a file system object.
inInfo Old-style NavServices information about the file. Unfortunately, it doesn't have all the information we need so we must call LSCopyItemInfoForRef anyway.
inFilterMode Specifies where this object will appear in the dialog.
References FilterObjectByAllFiles(), FilterObjectByAllReadableFiles(), FilterObjectByFilterName(), B::DescParam< TYPE >::Get(), kFilterAllAppFiles, kFilterAllFiles, kFilterAllReadableFiles, kFilterName, mCurrentFilterKind, and B::OSPtr< T >::reset().
Referenced by BrowserRedraw().
bool B::NavReplyDialog::FilterObjectByAllFiles (const FSRef & inRef, const LSItemInfoRecord & inInfo, NavFilterModes inFilterMode) protected virtual
Performs filtering when "All Documents" is selected in the pop-up menu.
The default implementation always returns true.
Parameters
inRef Contains the file system object to filter.
inInfo Pertinent info about inRef.
inFilterMode Specifies where this object will appear in the dialog.
Referenced by FilterObject().
bool B::NavReplyDialog::FilterObjectByAllReadableFiles (const FSRef & inRef, const LSItemInfoRecord & inInfo, NavFilterModes inFilterMode) protected virtual
Performs filtering when "All Readable Documents" is selected in the pop-up menu.
The default implementation always returns true.
Parameters
inRef Contains the file system object to filter.
inInfo Pertinent info about inRef.
inFilterMode Specifies where this object will appear in the dialog.
Reimplemented in B::GetFileDialog.
Referenced by FilterObject().
bool B::NavReplyDialog::FilterObjectByFilterName (const FSRef & inRef, const LSItemInfoRecord & inInfo, NavFilterModes inFilterMode) protected virtual
Performs filtering when a document type is selected in the pop-up menu.
The default implementation always returns true.
Parameters
inRef Contains the file system object to filter.
inInfo Pertinent info about inRef.
inFilterMode Specifies where this object will appear in the dialog.
Reimplemented in B::GetFileDialog.
Referenced by FilterObject().
bool B::NavReplyDialog::Preview (NavCBRecPtr ioParams) protected virtual
Preview hook.
This function is really just a hook to implement previewing. We don't really know at this point what previewing entails, so it's pointless to try something more elaborate for now.
References B::ViewFactory::Default(), B::NavDialog::GetDialogRef(), B::View::GetViewFromRef(), B::ViewFactory::Instantiate(), B::NavDialog::IsStarted(), and B::Bundle::Main().
Referenced by BrowserRedraw().
void B::NavReplyDialog::HandleUserAction (NavUserAction inUserAction) protected virtual
Parameters
inUserAction The user action.
Implements B::NavDialog.
References B::AutoNavReply::get(), GetNavReply(), and HandleReply().
The documentation for this class was generated from the following files:
BNavDialogs.h
BNavDialogs.cpp