B: B::Event< CLASS, KIND > Class Template Reference
B::Event< CLASS, KIND > Class Template Reference
Carbon Events
Template class representing a specific Carbon Event.
#include <BEvent.h>
Public Types
Template Parameters
typedef UInt32 CLASS
Template parameter. Should be an integral four-char constant representing a Carbon Event class.
typedef UInt32 KIND
Template parameter. Should be an integral four-char constant representing a Carbon Event kind in CLASS's namespace.
Public Member Functions
Constructors
Event ()
Creates a new Carbon Event.
Event (EventHandlerCallRef inHandlerCallRef, EventRef inEvent)
Creates a object wrapping an existing Carbon Event.
Public Member Functions inherited from B::EventBase
EventBase (UInt32 inClassID, UInt32 inKind)
Creates a new Carbon Event.
EventBase (EventHandlerCallRef inHandlerCallRef, EventRef inEvent)
Creates a object wrapping an existing Carbon Event.
virtual ~EventBase ()
Destructor. Releases the embedded EventRef.
bool IsIncoming () const
Returns true if this is an incoming event.
operator EventRef ()
Returns the EventRef embedded within the object.
void Send (EventTargetRef inTarget, OptionBits inOptions=0)
Sends the event to an event target.
OSStatus Send (EventTargetRef inTarget, const std::nothrow_t &, OptionBits inOptions=0)
Sends the event to an event target without throwing an exception.
void Send (HIObjectRef inObject, OptionBits inOptions=0)
OSStatus Send (HIObjectRef inObject, const std::nothrow_t &, OptionBits inOptions=0)
void Send (WindowRef inWindow, OptionBits inOptions=0)
OSStatus Send (WindowRef inWindow, const std::nothrow_t &, OptionBits inOptions=0)
void Send (HIViewRef inView, OptionBits inOptions=0)
OSStatus Send (HIViewRef inView, const std::nothrow_t &, OptionBits inOptions=0)
void Send (MenuRef inMenu, OptionBits inOptions=0)
OSStatus Send (MenuRef inMenu, const std::nothrow_t &, OptionBits inOptions=0)
void SendToApp (OptionBits inOptions=0)
OSStatus SendToApp (const std::nothrow_t &, OptionBits inOptions=0)
void SendToUserFocus (OptionBits inOptions=0)
OSStatus SendToUserFocus (const std::nothrow_t &, OptionBits inOptions=0)
void Post (EventPriority inPriority=kEventPriorityStandard)
Posts the event to the main event queue.
bool Forward ()
Forwards an incoming event to the next event handler in the chain.
OSStatus Forward (const std::nothrow_t &)
Forwards an incoming event to the next event handler in the chain without throwing an exception.
virtual void Update ()
Sets output parameters.
virtual void Retrieve ()
Retrieves output parameters.
Additional Inherited Members
Static Public Member Functions inherited from B::EventBase
static OSStatus StoreExceptionIntoCarbonEvent (EventRef inEvent, const std::exception &ex)
static void RethrowExceptionFromCarbonEvent (EventRef inEvent, OSStatus inStatus)
Detailed Description
template<UInt32 CLASS, UInt32 KIND>
class B::Event< CLASS, KIND >
Template class representing a specific Carbon Event.
Usually this template is specialised in order to add member variables holding event parameters, or to override Update() and/or Retrieve(). However, if a Carbon Event has no input or output parameters, this class may be instantiated directly.
See also
Handling Carbon Events
Todo:
Flesh out the missing template specialisations for events of these classes:
kEventClassKeyboard
kEventClassTextInput
kEventClassApplication
kEventClassAppleEvent
kEventClassMenu
kEventClassWindow
kEventClassControl
kEventClassCommand
kEventClassTablet
kEventClassVolume
kEventClassAppearance
kEventClassService
kEventClassToolbar
kEventClassToolbarItem
kEventClassToolbarItemView
kEventClassAccessibility
kEventClassSystem
kEventClassInk
kEventClassTSMDocumentAccess
Constructor & Destructor Documentation
template<UInt32 CLASS, UInt32 KIND> B::Event< CLASS, KIND >::Event ()
Creates a new Carbon Event.
The event's class and kind come from CLASS and KIND template parameters, respectively.
Use this constructor to create a Carbon Event prior to sending or posting it.
Referenced by B::Event< CLASS, KIND >::Event(), and B::EventBase::Retrieve().
template<UInt32 CLASS, UInt32 KIND> B::Event< CLASS, KIND >::Event (EventHandlerCallRef inHandlerCallRef, EventRef inEvent)
Creates a object wrapping an existing Carbon Event.
The event's class and kind come from CLASS and KIND template parameters, respectively.
Use this constructor when handling incoming Carbon Events.
Parameters
inHandlerCallRef The caller ref representing a location in the chain of event handlers.
inEvent The Carbon Event. It gets retained by the constructor.
References B::Event< CLASS, KIND >::Event(), B::EventBase::Retrieve(), and B::EventBase::Update().
The documentation for this class was generated from the following file:
BEvent.h