B: B::OSPtr<T> Global Functions
B::OSPtr<T> Global Functions
Functions
template<typename T >
bool operator== (const OSPtr< T > &t1, const OSPtr< T > &t2)
template<typename T >
bool operator== (const OSPtr< T > &t1, T t2)
template<typename T >
bool operator== (T t1, const OSPtr< T > &t2)
template<typename T >
bool operator!= (const OSPtr< T > &t1, const OSPtr< T > &t2)
template<typename T >
bool operator!= (const OSPtr< T > &t1, T t2)
template<typename T >
bool operator!= (T t1, const OSPtr< T > &t2)
Detailed Description
Function Documentation
template<typename T > bool operator== (const OSPtr< T > & t1, const OSPtr< T > & t2) related
Returns true if t1 equals t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 A "smart pointer" wrapping an object of type T.
t2 A "smart pointer" wrapping an object of type T.
References B::OSPtr< T >::get().
template<typename T > bool operator== (const OSPtr< T > & t1, T t2) related
Returns true if t1 equals t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 A "smart pointer" wrapping an object of type T.
t2 An OS object of type T.
References B::OSPtr< T >::get().
template<typename T > bool operator== (T t1, const OSPtr< T > & t2) related
Returns true if t1 equals t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 An OS object of type T.
t2 A "smart pointer" wrapping an object of type T.
References B::OSPtr< T >::get().
template<typename T > bool operator!= (const OSPtr< T > & t1, const OSPtr< T > & t2) related
Returns true if t1 does not equal t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 A "smart pointer" wrapping an object of type T.
t2 A "smart pointer" wrapping an object of type T.
References B::OSPtr< T >::get().
template<typename T > bool operator!= (const OSPtr< T > & t1, T t2) related
Returns true if t1 does not equal t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 A "smart pointer" wrapping an object of type T.
t2 An OS object of type T.
References B::OSPtr< T >::get().
template<typename T > bool operator!= (T t1, const OSPtr< T > & t2) related
Returns true if t1 does not equal t2.
Parameters
T Template parameter. Should be an OS-defined type.
Parameters
t1 An OS object of type T.
t2 A "smart pointer" wrapping an object of type T.
References B::OSPtr< T >::get().