B: Apple Events
Apple Events
Namespaces
B::AEEventFunctor
Functors for writing out Apple Events.
Classes
struct B::DescParamHelper
Common utility functions for the use of DescParam.
struct B::DescParam< TYPE >
Reads & writes an Apple Event descriptor in a type-safe manner.
class B::AEDescriptor
Wrapper class around an Apple Event descriptor.
class B::AETypedDescriptor< TYPE >
Type-safe wrapper class around an Apple Event descriptor.
class B::AEEventBase
Common base class for representing Apple Events.
class B::AEEvent< EVT_CLASS, EVT_ID >
Wrapper class for a single Apple Event.
class B::AEEvent< kCoreEventClass, kAEQuitApplication >
Specialisation of AEEvent for the quit Apple Event.
class B::AEEvent< kAECoreSuite, kAEClone >
Specialisation of AEEvent for the duplicate Apple Event.
class B::AEEvent< kAECoreSuite, kAEClose >
Specialisation of AEEvent for the close Apple Event.
class B::AEEvent< kAECoreSuite, kAECountElements >
Specialisation of AEEvent for the count Apple Event.
class B::AEEvent< kAECoreSuite, kAECreateElement >
Specialisation of AEEvent for the make Apple Event.
class B::AEEvent< kAECoreSuite, kAEDelete >
Specialisation of AEEvent for the delete Apple Event.
class B::AEEvent< kAECoreSuite, kAEDoObjectsExist >
Specialisation of AEEvent for the exists Apple Event.
class B::AEEvent< kAECoreSuite, kAEGetData >
Specialisation of AEEvent for the get Apple Event.
class B::AEEvent< kAECoreSuite, kAEMove >
Specialisation of AEEvent for the move Apple Event.
class B::AEEvent< kCoreEventClass, kAEOpen >
Specialisation of AEEvent for the open Apple Event.
class B::AEEvent< kCoreEventClass, kAEPrint >
Specialisation of AEEvent for the print Apple Event.
class B::AEEvent< kAECoreSuite, kAESave >
Specialisation of AEEvent for the save Apple Event.
class B::AEEvent< kAECoreSuite, kAESetData >
Specialisation of AEEvent for the set Apple Event.
class B::AEEvent< kAEMiscStandards, kAERedo >
Specialisation of AEEvent for the redo Apple Event.
class B::AEEvent< kAEMiscStandards, kAERevert >
Specialisation of AEEvent for the revert Apple Event.
class B::AEEvent< kAEMiscStandards, kAESelect >
Specialisation of AEEvent for the select Apple Event.
class B::AEEvent< kAEMiscStandards, kAEUndo >
Specialisation of AEEvent for the undo Apple Event.
class B::AEEvent< kASAppleScriptSuite, kASCommentEvent >
Specialisation of AEEvent for the kASAppleScriptSuite / kASCommentEvent Apple Event.
class B::AEObject::ObjectWriter
Helper class that writes out an AEObject to an AEWriter.
class B::AEObject::ObjectListSpecifier< INPUT_ITERATOR >
Writes out a list of object specifiers to an AEWriter.
class B::AEObject::InsertionLocationSpecifier
Convenience wrapper around AEEventFunctor::InsertionLocation<...>.
class B::AEObject::IndexSpecifier
Convenience wrapper around AEEventFunctor::IndexSpecifier<...>.
class B::AEObject::NameSpecifier
Convenience wrapper around AEEventFunctor::NameSpecifier<...>.
class B::AEObject::UniqueIDSpecifier
Convenience wrapper around AEEventFunctor::UniqueIDSpecifier<...>.
class B::AEObject::PropertySpecifier
Convenience wrapper around AEEventBase::PropertySpecifier<...>.
class B::AEObject
The root class for objects visible to AppleScript.
class B::AEObjectSupport
This class provides essential support for the Apple Event Object Model (AEOM) in the B framework.
class B::AEWriter
Encapsulates a writable Apple Event descriptor "stream". It's basically a wrapper around AEStreamRef.
class B::AutoAEWriterDesc
A stack-based class for opening a descriptor.
class B::AutoAEWriterRecord
A stack-based class for opening a descriptor record.
class B::AutoAEWriterList
A stack-based class for opening a descriptor list.
class B::AESelfTarget
Functor for sending Apple Events to the current process.
class B::AEPsnTarget
Functor for sending Apple Events to an arbitrary (Carbon or Classic) process.
class B::AEPidTarget
Functor for sending Apple Events to an arbitrary UNIX process.
class B::AEUrlTarget
Functor for sending Apple Events to a URL.
class B::AEKey
Functor for writing Apple Event keywords to an AEWriter.
class B::AETypedObject< TYPE >
Functor for writing tagged data to an AEWriter.
class B::AEOptionalTypedObject< TYPE >
Functor for optionally writing tagged data to an AEWriter.
Functions
void swap (AEDescriptor &desc1, AEDescriptor &desc2)
template<DescType TYPE>
void swap (AETypedDescriptor< TYPE > &desc1, AETypedDescriptor< TYPE > &desc2)
std::ostream & operator<< (std::ostream &ostr, const AEDesc &desc)
std::istream & operator>> (std::istream &is, AEDesc &desc)
AEWriter & operator<< (AEWriter &writer, const AEDesc &desc)
AEWriter & operator<< (AEWriter &writer, const String &value)
AEWriter & operator<< (AEWriter &writer, const Url &value)
AEWriter & operator<< (AEWriter &writer, const AEKey &key)
template<DescType TYPE>
AEWriter & operator<< (AEWriter &writer, const AETypedObject< TYPE > &value)
template<DescType TYPE>
AEWriter & operator<< (AEWriter &writer, const AEOptionalTypedObject< TYPE > &value)
Detailed Description
Classes supporting Apple Events
Function Documentation
void swap (AEDescriptor & desc1, AEDescriptor & desc2) related
Exchanges the contents of two AEDescriptor objects.
Exceptions
none
References B::AEDescriptor::swap().
template<DescType TYPE> void swap (AETypedDescriptor< TYPE > & desc1, AETypedDescriptor< TYPE > & desc2) related
Exchanges the contents of two AETypedDescriptor objects.
Exceptions
none
References B::AETypedDescriptor< TYPE >::swap().
std::ostream & operator<< (std::ostream & ostr, const AEDesc & desc) related
Writes out a flattened representation of desc (as returned by AEFlattenDesc()) to os.
std::istream & operator>> (std::istream & is, AEDesc & desc) related
Reads in a flattened representation of an Apple Event descriptor (as generated by AEFlattenDesc()) and copies the resulting AEDesc to desc.
AEWriter & operator<< (AEWriter & writer, const AEDesc & desc) related
Writes the Apple Event descriptor desc to the stream contained in writer.
References B::AEWriter::WriteDesc().
AEWriter & operator<< (AEWriter & writer, const String & value) related
Writes a String to the stream contained in writer.
References B::AEWriter::Write().
AEWriter & operator<< (AEWriter & writer, const Url & value) related
Writes a Url to the stream contained in writer.
References B::AEWriter::Write().
AEWriter & operator<< (AEWriter & writer, const AEKey & key) related
Writes the Apple Event keyword contained in key to the stream contained in writer.
template<DescType TYPE> AEWriter & operator<< (AEWriter & writer, const AETypedObject< TYPE > & value) related
Writes the Apple Event descriptor contained in value to the stream contained in writer.
template<DescType TYPE> AEWriter & operator<< (AEWriter & writer, const AEOptionalTypedObject< TYPE > & value) related
Writes the Apple Event descriptor contained in value to the stream contained in writer.