B: String Global Functions
String Global Functions
Miscellaneous
void swap (String &s1, String &s2)
String Concatenation
String B::operator+ (const String &s1, CFStringRef s2)
String B::operator+ (CFStringRef s1, const String &s2)
String B::operator+ (const String &s1, const UniChar *s2)
String B::operator+ (const UniChar *s1, const String &s2)
String B::operator+ (const String &s1, const UniChar c)
String B::operator+ (const UniChar c, const String &s2)
String B::operator+ (const String &s1, const std::string &s2)
String B::operator+ (const std::string &s1, const String &s2)
String operator+ (const String &s1, const String &s2)
Input/Output Functions
String only supports I/O to char streams (i.e., std::basic_ostream<char,char_traits<char>>).
std::ostream & operator<< (std::ostream &os, const String &str)
std::istream & operator>> (std::istream &is, String &str)
std::istream & getline (std::istream &is, String &str, char delim)
std::istream & getline (std::istream &is, String &str)
String Comparisons
bool B::operator== (const String &s1, CFStringRef s2)
bool B::operator== (CFStringRef s1, const String &s2)
bool B::operator== (const String &s1, const UniChar *s2)
bool B::operator== (const UniChar *s1, const String &s2)
bool B::operator!= (const String &s1, CFStringRef s2)
bool B::operator!= (CFStringRef s1, const String &s2)
bool B::operator!= (const String &s1, const UniChar *s2)
bool B::operator!= (const UniChar *s1, const String &s2)
bool B::operator< (const String &s1, CFStringRef s2)
bool B::operator< (CFStringRef s1, const String &s2)
bool B::operator< (const String &s1, const UniChar *s2)
bool B::operator< (const UniChar *s1, const String &s2)
bool B::operator<= (const String &s1, CFStringRef s2)
bool B::operator<= (CFStringRef s1, const String &s2)
bool B::operator<= (const String &s1, const UniChar *s2)
bool B::operator<= (const UniChar *s1, const String &s2)
bool B::operator> (const String &s1, CFStringRef s2)
bool B::operator> (CFStringRef s1, const String &s2)
bool B::operator> (const String &s1, const UniChar *s2)
bool B::operator> (const UniChar *s1, const String &s2)
bool B::operator>= (const String &s1, CFStringRef s2)
bool B::operator>= (CFStringRef s1, const String &s2)
bool B::operator>= (const String &s1, const UniChar *s2)
bool B::operator>= (const UniChar *s1, const String &s2)
bool operator== (const String &s1, const String &s2)
bool operator!= (const String &s1, const String &s2)
bool operator< (const String &s1, const String &s2)
bool operator<= (const String &s1, const String &s2)
bool operator> (const String &s1, const String &s2)
bool operator>= (const String &s1, const String &s2)
Detailed Description
Function Documentation
String B::operator+ (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::cf_ref(), B::String::get_allocator(), and B::String::String().
String B::operator+ (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::cf_ref(), B::String::get_allocator(), and B::String::String().
String B::operator+ (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::npos.
String B::operator+ (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::get_allocator(), and B::String::npos.
String B::operator+ (const String & s1, UniChar c)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
String B::operator+ (UniChar c, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::get_allocator().
String B::operator+ (const String & s1, const std::string & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
String B::operator+ (const std::string & s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::get_allocator(), and B::String::npos.
bool B::operator== (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator== (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator== (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator== (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator!= (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator!= (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator!= (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator!= (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator< (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator< (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator< (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator< (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator<= (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator<= (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator<= (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator<= (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator> (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator> (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator> (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator> (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator>= (const String & s1, CFStringRef s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator>= (CFStringRef s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator>= (const String & s1, const UniChar * s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
bool B::operator>= (const UniChar * s1, const String & s2)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
References B::String::compare().
String operator+ (const String & s1, const String & s2) related
Returns a new string consisting of the concatenation of s1 and s2.
References B::String::cf_ref(), B::String::get_allocator(), and B::String::String().
Referenced by B::String::get_allocator(), and B::String::swap().
std::ostream & operator<< (std::ostream & os, const String & str) related
Writes the characters of str to os. str is converted to ASCII prior to being written. If the conversion fails (eg there are non-7-bit-ASCII characters in str), an exception may be thrown.
If you need to write characters to a std::ostream that are in an encoding other than 7-bit ASCII, use String::Write() instead.
References B::String::Write().
std::istream & operator>> (std::istream & is, String & str) related
Reads the characters of the next word from is into the string str. The characters read from is are assumed to be 7-bit ASCII. If they aren't, an exception may be thrown.
If you need to read characters from a std::istream that are in an encoding other than 7-bit ASCII, use String::Read() instead.
References B::String::Read().
std::istream & getline (std::istream & is, String & str, char delim) related
Reads the characters of the next line from is into the string str. The characters read from is are assumed to be 7-bit ASCII. If they aren't, an exception may be thrown.
If you need to read characters from a std::istream that are in an encoding other than 7-bit ASCII, use String::Read() instead.
References B::String::GetLine().
Referenced by B::String::GetLine().
std::istream & getline (std::istream & is, String & str) related
Reads the characters of the next line from is into the string str. The characters read from is are assumed to be 7-bit ASCII. If they aren't, an exception may be thrown.
If you need to read characters from a std::istream that are in an encoding other than 7-bit ASCII, use String::Read() instead.
References B::String::GetLine().
bool operator== (const String & s1, const String & s2) related
Compares two strings for equality.
Returns
true if s1 is equal to s2
References B::String::compare().
Referenced by B::String::swap().
bool operator!= (const String & s1, const String & s2) related
Compares two strings for inequality.
Returns
true if s1 is not equal to s2
References B::String::compare().
Referenced by B::String::swap().
bool operator< (const String & s1, const String & s2) related
Orders two strings according to <.
Returns
true if s1 is less than s2
References B::String::compare().
Referenced by B::String::swap().
bool operator<= (const String & s1, const String & s2) related
Orders two strings according to <=.
Returns
true if s1 is less than or equal to s2
References B::String::compare().
Referenced by B::String::swap().
bool operator> (const String & s1, const String & s2) related
Orders two strings according to >.
Returns
true if s1 is greater than s2
References B::String::compare().
Referenced by B::String::swap().
bool operator>= (const String & s1, const String & s2) related
Orders two strings according to >=.
Returns
true if s1 is greater than or equal to s2
References B::String::compare().
Referenced by B::String::swap().
void swap (String & s1, String & s2) related
Exchanges the contents of s1 and s2.
References B::String::operator!=(), B::String::operator+(), B::String::operator<(), B::String::operator<=(), B::String::operator==(), B::String::operator>(), B::String::operator>=(), and B::String::swap().