B: Array Global Functions
Array Global Functions
Array Comparisons
template<typename T >
bool operator== (const Array< T > &a1, const Array< T > &a2)
template<typename T >
bool operator!= (const Array< T > &a1, const Array< T > &a2)
Miscellaneous
template<typename T >
void swap (Array< T > &s1, Array< T > &s2)
Detailed Description
Function Documentation
template<typename T > bool operator== (const Array< T > & a1, const Array< T > & a2) related
Compares two arrays for equality.
Returns
true if a1 is equal to a2
References B::Array< T >::cf_ref().
template<typename T > bool operator!= (const Array< T > & a1, const Array< T > & a2) related
Compares two arrays for inequality.
Returns
true if a1 is not equal to a2
References B::Array< T >::cf_ref().
template<typename T > void swap (Array< T > & s1, Array< T > & s2) related
Exchanges the contents of s1 and s2.
References B::Array< T >::swap().