B: B::ViewUtils Namespace Reference
B::ViewUtils Namespace Reference
A collection of useful utility functions for getting information about HIViewRefs.
Classes
struct CoordinateSpaceTraits
struct CoordinateSpaceTraits< HIViewRef >
struct CoordinateSpaceTraits< WindowRef >
class ImageContent
Helper class for custom views that display image content.
class ReverseSubviewIterator
Iterates over the children of an HIView in reverse order.
class SubviewIterator
Iterates over the children of an HIView.
Functions
HIViewID MakeViewID (SInt32 id)
bool operator== (const SubviewIterator &it1, const SubviewIterator &it2)
Compares it1 and it2 for equality.
bool operator!= (const SubviewIterator &it1, const SubviewIterator &it2)
Compares it1 and it2 for inequality.
bool operator== (const ReverseSubviewIterator &it1, const ReverseSubviewIterator &it2)
Compares it1 and it2 for equality.
bool operator!= (const ReverseSubviewIterator &it1, const ReverseSubviewIterator &it2)
Compares it1 and it2 for inequality.
HIViewID MakeViewID (OSType sig, SInt32 id)
HIViewID MakeViewID ()
ControlKind MakeControlKind (OSType sig, OSType kind)
Coordinate Conversions
CGPoint ConvertValue (const CGPoint &inValue, HICoordinateSpace inSrcSpace, void *inSrcObject, HICoordinateSpace inDstSpace, void *inDstObject)
Converts inValue from the coordinate system of inSrcSpace and inSrcObject to that of inDstSpace and inDstObject.
CGSize ConvertValue (const CGSize &inValue, HICoordinateSpace inSrcSpace, void *inSrcObject, HICoordinateSpace inDstSpace, void *inDstObject)
CGRect ConvertValue (const CGRect &inValue, HICoordinateSpace inSrcSpace, void *inSrcObject, HICoordinateSpace inDstSpace, void *inDstObject)
template<typename VALUE , typename SRC_SPACE , typename DST_SPACE >
VALUE Convert (const VALUE &inValue, SRC_SPACE inSrcSpace, DST_SPACE inDstSpace)
Converts inValue from the coordinate system of inSrcSpace to that of inDstSpace.
template<typename VALUE , typename SRC_SPACE >
VALUE ConvertToGlobal (const VALUE &inValue, SRC_SPACE inSrcSpace)
Converts inValue from the coordinate system of inSrcSpace to global coordinates.
template<typename VALUE , typename DST_SPACE >
VALUE ConvertFromGlobal (const VALUE &inValue, DST_SPACE inDstSpace)
Converts inValue from global coordinates to the coordinate system of inDstSpace.
template<typename VALUE , typename SRC_SPACE >
VALUE ConvertToScreen (const VALUE &inValue, SRC_SPACE inSrcSpace)
Converts inValue from the coordinate system of inSrcSpace to screen coordinates.
template<typename VALUE , typename DST_SPACE >
VALUE ConvertFromScreen (const VALUE &inValue, DST_SPACE inDstSpace)
Converts inValue from screen coordinates to the coordinate system of inDstSpace.
Content View
HIViewRef GetOwnerContentView (HIViewRef inViewRef)
Returns the content view of inViewRef's owning window.
HIViewRef GetOwnerContentView (HIViewRef inView, bool inComposited)
Rect GetOwnerContentViewBounds (HIViewRef inViewRef)
Returns the bounds of the content view of inViewRef's owning window.
Rect GetOwnerContentViewBounds (HIViewRef inView, bool inComposited)
Finding Views
HIViewRef FindSubview (HIViewRef inSuperview, const HIViewID &inID)
Returns the subview of inSuperview that matches inID.
HIViewRef FindSubview (HIViewRef inSuperview, int inID)
Returns the subview of inSuperview that matches the main bundle's signature and inID.
HIViewRef FindSubview (HIViewRef inSuperview, const HIViewID &inID, const std::nothrow_t &)
Returns the subview of inSuperview that matches inID, or NULL.
HIViewRef FindSubview (HIViewRef inSuperview, int inID, const std::nothrow_t &)
Returns the subview of inSuperview that matches the main bundle's signature and inID, or NULL.
Iterators
SubviewIterator begin (HIViewRef inSuperview)
Returns an iterator pointing to the beginning of inSuperview's subviews.
SubviewIterator end (HIViewRef)
Returns an iterator pointing to the end of inSuperview's subviews.
ReverseSubviewIterator rbegin (HIViewRef inSuperview)
Returns an reverse iterator pointing to the beginning of inSuperview's subviews.
ReverseSubviewIterator rend (HIViewRef)
Returns an reverse iterator pointing to the end of inSuperview's subviews.
Detailed Description
A collection of useful utility functions for getting information about HIViewRefs.
Function Documentation
CGSize B::ViewUtils::ConvertValue (const CGSize & inValue, HICoordinateSpace inSrcSpace, void * inSrcObject, HICoordinateSpace inDstSpace, void * inDstObject)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
CGRect B::ViewUtils::ConvertValue (const CGRect & inValue, HICoordinateSpace inSrcSpace, void * inSrcObject, HICoordinateSpace inDstSpace, void * inDstObject)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
HIViewRef B::ViewUtils::GetOwnerContentView (HIViewRef inView)
Returns the content view of inViewRef's owning window.
In a compositing window, the function returns the bona fide content view. In a non-compositing window, it returns the root control.
Parameters
inView The view.
References B::WindowUtils::GetContentView().
Referenced by ConvertFromScreen().
HIViewRef B::ViewUtils::GetOwnerContentView (HIViewRef inView, bool inComposited)
Use this variant when you know already whether inView's owning window is a compositing window.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inViewRef The view.
inComposited Is inView in a compositing window?
References B::WindowUtils::GetContentView().
Rect B::ViewUtils::GetOwnerContentViewBounds (HIViewRef inView)
Returns the bounds of the content view of inViewRef's owning window.
In a compositing window, the function returns the bounds of the bona fide content view. In a non-compositing window, it returns the bounds of the root control.
Parameters
inView The view.
References B::WindowUtils::GetContentViewBounds().
Referenced by ConvertFromScreen().
Rect B::ViewUtils::GetOwnerContentViewBounds (HIViewRef inView, bool inComposited)
Use this variant when you know already whether inView's owning window is a compositing window.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inViewRef The view.
inComposited Is inView in a compositing window?
References B::WindowUtils::GetContentViewBounds().
HIViewRef B::ViewUtils::FindSubview (HIViewRef inSuperview, const HIViewID & inID)
Returns the subview of inSuperview that matches inID.
Returns
The requested subview of inSuperview. Never returns NULL (an exception is thrown if something goes wrong).
Parameters
inSuperview The root of the search.
inID The identity of the view we want.
Referenced by ConvertFromScreen(), B::RadioGroup::CreateAndEmbedSubviews(), FindSubview(), B::View::FindSubview(), and B::View::FindTypedSubview().
HIViewRef B::ViewUtils::FindSubview (HIViewRef inSuperview, int inID)
Returns the subview of inSuperview that matches the main bundle's signature and inID.
The signature portion of the HIViewID is taken from the main bundle.
Returns
The requested subview of inSuperview. Never returns NULL (an exception is thrown if something goes wrong).
Parameters
inSuperview The root of the search.
inID The identity of the view we want.
References FindSubview(), B::Bundle::Main(), and B::Bundle::PackageCreator().
HIViewRef B::ViewUtils::FindSubview (HIViewRef inSuperview, const HIViewID & inID, const std::nothrow_t &)
Returns the subview of inSuperview that matches inID, or NULL.
Returns
The requested subview of inSuperview, or NULL if the view wasn't found.
Parameters
inSuperview The root of the search.
inID The identity of the view we want.
HIViewRef B::ViewUtils::FindSubview (HIViewRef inSuperview, int inID, const std::nothrow_t & nt)
Returns the subview of inSuperview that matches the main bundle's signature and inID, or NULL.
The signature portion of the HIViewID is taken from the main bundle.
Returns
The requested subview of inSuperview, or NULL if the view wasn't found.
Parameters
inSuperview The root of the search.
inID The identity of the view we want.
nt An indication that the caller doesn't want the function to throw.
References FindSubview(), B::Bundle::Main(), and B::Bundle::PackageCreator().
SubviewIterator B::ViewUtils::begin (HIViewRef inSuperview)
Returns an iterator pointing to the beginning of inSuperview's subviews.
Parameters
inSuperview The view over whose subviews we shall iterate.
Referenced by B::View::AwakenViewAndChildren(), B::View::InstantiateSubviews(), and B::Window::operator delete().
ReverseSubviewIterator B::ViewUtils::rbegin (HIViewRef inSuperview)
Returns an reverse iterator pointing to the beginning of inSuperview's subviews.
Parameters
inSuperview The view over whose subviews we shall iterate.
References B::ViewUtils::ReverseSubviewIterator::ReverseSubviewIterator().
Referenced by B::NavReplyDialog::GetNavReply(), and B::Dialog::HandleCommand().