B: B::WindowUtils Namespace Reference
B::WindowUtils Namespace Reference
A collection of useful utility functions for getting information about WindowRefs.
Classes
class WindowIterator
Iterates over the children of an HIView.
Functions
bool operator== (const WindowIterator &it1, const WindowIterator &it2)
Compares it1 and it2 for equality.
bool operator!= (const WindowIterator &it1, const WindowIterator &it2)
Compares it1 and it2 for inequality.
General
bool IsComposited (WindowRef inWindowRef)
Is inWindowRef a composited window?
bool IsMetal (WindowRef inWindowRef)
Is inWindowRef a Metal window?
WindowClass GetClass (WindowRef inWindowRef)
Returns the window class of inWindowRef.
WindowAttributes GetAttributes (WindowRef inWindowRef)
Returns the window atributes of inWindowRef.
WindowModality GetModality (WindowRef inWindowRef)
Returns the window modality of inWindowRef.
Content View
HIViewRef GetContentView (WindowRef inWindowRef)
Returns inWindowRef's content view.
HIViewRef GetContentView (WindowRef inWindowRef, bool inComposited)
Rect GetContentViewBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's content view.
Rect GetContentViewBounds (WindowRef inWindowRef, bool inComposited)
Rect GetContentViewBounds (WindowRef inWindowRef, bool inComposited, HIViewRef inContentView)
Bounds, Origins, and Sizes
Rect GetStructureBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's structure region, in global coordinates.
Point GetStructureOrigin (WindowRef inWindowRef)
Returns the origin of inWindowRef's structure region, in global coordinates.
Size GetStructureSize (WindowRef inWindowRef)
Returns the size of inWindowRef's structure region, in global coordinates.
Rect GetContentBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's content region, in global coordinates.
Point GetContentOrigin (WindowRef inWindowRef)
Returns the origin of inWindowRef's content region, in global coordinates.
Size GetContentSize (WindowRef inWindowRef)
Returns the size of inWindowRef's content region, in global coordinates.
Coordinate Conversions
CGPoint ConvertFromWindowToLocal (const CGPoint &inPoint, WindowRef inWindowRef)
Converts inPoint from the window coordinates of inWindowRef to its local coordinates.
CGRect ConvertFromWindowToLocal (const CGRect &inRect, WindowRef inWindowRef)
CGPoint ConvertFromLocalToWindow (const CGPoint &inPoint, WindowRef inWindowRef)
Converts inPoint from the local coordinates of inWindowRef to its window coordinates.
CGRect ConvertFromLocalToWindow (const CGRect &inRect, WindowRef inWindowRef)
Iterators
WindowIterator begin (WindowClass inClass, bool inOnlyVisibleWindows)
Returns an iterator pointing to the first window matching inClass and inOnlyVisibleWindows.
WindowIterator end (WindowClass, bool)
Returns an iterator pointing to the end of the windows matching inClass and inOnlyVisibleWindows.
Detailed Description
A collection of useful utility functions for getting information about WindowRefs.
These functions are here for the benefit of classes other than Window, especially the view classes. They often need certain pieces of information about the owning window of a view and isolating that information here avoids introducing a dependency between the view and window classes.
Function Documentation
bool B::WindowUtils::IsComposited (WindowRef inWindowRef)
Is inWindowRef a composited window?
Parameters
inWindowRef The window.
References GetAttributes().
Referenced by GetContentView(), and GetContentViewBounds().
bool B::WindowUtils::IsMetal (WindowRef inWindowRef)
Is inWindowRef a Metal window?
Parameters
inWindowRef The window.
References GetAttributes().
Referenced by B::SplitView::Instantiate().
WindowClass B::WindowUtils::GetClass (WindowRef inWindowRef)
Returns the window class of inWindowRef.
Parameters
inWindowRef The window.
Referenced by B::Dialog::HandleCommand().
WindowAttributes B::WindowUtils::GetAttributes (WindowRef inWindowRef)
Returns the window atributes of inWindowRef.
Parameters
inWindowRef The window.
Referenced by B::Dialog::HandleCommand(), IsComposited(), and IsMetal().
WindowModality B::WindowUtils::GetModality (WindowRef inWindowRef)
Returns the window modality of inWindowRef.
Parameters
inWindowRef The window.
HIViewRef B::WindowUtils::GetContentView (WindowRef inWindowRef)
Returns inWindowRef's content view.
In a compositing window, the function returns the bona fide content view. In a non-compositing window, it returns the root control.
Parameters
inWindowRef The window.
References IsComposited().
Referenced by ConvertFromLocalToWindow(), ConvertFromWindowToLocal(), GetContentViewBounds(), B::NavReplyDialog::GetNavReply(), B::ViewUtils::GetOwnerContentView(), and B::Dialog::HandleCommand().
HIViewRef B::WindowUtils::GetContentView (WindowRef inWindowRef, bool inComposited)
Use this variant when you know already whether inWindowRef is a compositing window.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inWindowRef The window.
inComposited Is this a compositing window?
Rect B::WindowUtils::GetContentViewBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's content view.
In a compositing window, the function returns the bounds of the bona fide content view. In a non-compositing window, it returns the bounds of the root control.
Parameters
inWindowRef The window.
References IsComposited().
Referenced by B::ViewUtils::GetOwnerContentViewBounds(), and B::Window::SetIdealSize().
Rect B::WindowUtils::GetContentViewBounds (WindowRef inWindowRef, bool inComposited)
Use this variant when you know already whether inWindowRef is a compositing window.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inWindowRef The window.
inComposited Is this a compositing window?
References GetContentView().
Rect B::WindowUtils::GetContentViewBounds (WindowRef inWindowRef, bool inComposited, HIViewRef inContentView)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inWindowRef The window.
inComposited Is this a compositing window?
Rect B::WindowUtils::GetStructureBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's structure region, in global coordinates.
Parameters
inWindowRef The window.
Referenced by GetStructureOrigin(), GetStructureSize(), and B::Window::SetIdealSize().
Point B::WindowUtils::GetStructureOrigin (WindowRef inWindowRef)
Returns the origin of inWindowRef's structure region, in global coordinates.
Parameters
inWindowRef The window.
References GetStructureBounds().
Referenced by B::Window::SetIdealSize().
Size B::WindowUtils::GetStructureSize (WindowRef inWindowRef)
Returns the size of inWindowRef's structure region, in global coordinates.
Parameters
inWindowRef The window.
References GetStructureBounds().
Referenced by B::Window::SetIdealSize().
Rect B::WindowUtils::GetContentBounds (WindowRef inWindowRef)
Returns the bounds of inWindowRef's content region, in global coordinates.
Parameters
inWindowRef The window.
Referenced by GetContentOrigin(), GetContentSize(), B::Dialog::HandleCommand(), and B::Window::SetIdealSize().
Point B::WindowUtils::GetContentOrigin (WindowRef inWindowRef)
Returns the origin of inWindowRef's content region, in global coordinates.
Parameters
inWindowRef The window.
References GetContentBounds().
Referenced by B::Window::SetIdealSize().
Size B::WindowUtils::GetContentSize (WindowRef inWindowRef)
Returns the size of inWindowRef's content region, in global coordinates.
Parameters
inWindowRef The window.
References GetContentBounds().
Referenced by B::Window::SetIdealSize().
CGPoint B::WindowUtils::ConvertFromWindowToLocal (const CGPoint & inPoint, WindowRef inWindowRef)
Converts inPoint from the window coordinates of inWindowRef to its local coordinates.
Parameters
inPoint The point to convert.
inWindowRef The window in whose coordinates is @ ioPoint.
References GetContentView().
CGRect B::WindowUtils::ConvertFromWindowToLocal (const CGRect & inRect, WindowRef inWindowRef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inRect The rect to convert.
inWindowRef The window in whose coordinates is @ ioPoint.
References GetContentView().
CGPoint B::WindowUtils::ConvertFromLocalToWindow (const CGPoint & inPoint, WindowRef inWindowRef)
Converts inPoint from the local coordinates of inWindowRef to its window coordinates.
Parameters
inPoint The point to convert.
inWindowRef The window in whose coordinates is @ ioPoint.
References GetContentView().
CGRect B::WindowUtils::ConvertFromLocalToWindow (const CGRect & inRect, WindowRef inWindowRef)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
inRect The rect to convert.
inWindowRef The window in whose coordinates is @ ioPoint.
References GetContentView().
WindowIterator B::WindowUtils::begin (WindowClass inClass, bool inOnlyVisibleWindows)
Returns an iterator pointing to the first window matching inClass and inOnlyVisibleWindows.
Parameters
inClass The window class to look for. May be kAllWindowClasses.
inOnlyVisibleWindows Indicates whether to iterate over invisible windows.
References B::WindowUtils::WindowIterator::WindowIterator().