B: B::ViewDataTrait< T > Struct Template Reference
B::ViewDataTrait< T > Struct Template Reference
Views
Gets & sets HIVieRef data in a type-safe manner.
#include <BViewData.h>
Public Types
Types
typedef T Type
An easy-to-access synonym for T.
Static Public Member Functions
View Access
Allows access to the data for a given view, part, and tag. Clients will use these functions to interact with the view.
static void Get (HIViewRef view, ControlPartCode part, ResType tag, T &value)
Retrieves the view data for the given view, part, and tag.
static void Set (HIViewRef view, ControlPartCode part, ResType tag, const T &value)
Changes the view data for the given view, part, and tag.
static OSStatus Get (HIViewRef view, ControlPartCode part, ResType tag, T &value, const std::nothrow_t &)
Retrieves the view data for the given view, part, and tag (no-throw variant).
static OSStatus Set (HIViewRef view, ControlPartCode part, ResType tag, const T &value, const std::nothrow_t &)
Changes the view data for the given view, part, and tag (no-throw variant).
Memory Access
Allows access to the data at a given memory address. Implementations of custom controls will use these functions to read and write the data to/from Carbon Events.
static OSStatus Get (const void *data, size_t size, T &value)
Retrieves the view data from an arbitrary address in memory.
static OSStatus Set (void *data, size_t size, const T &value)
Copies the view data to an arbitrary address in memory.
Public Attributes
Template Parameters
typedef T
The template parameter. Any C/C++ language type.
Detailed Description
template<typename T>
struct B::ViewDataTrait< T >
Gets & sets HIVieRef data in a type-safe manner.
ViewDataTrait provides a type-safe wrapper around the Control Manager calls GetControlData() and SetControlData().
The template parameter, T, is a C/C++ language type. It's the type of the data to be stored into or retrieved from the view.
Member Function Documentation
template<typename T > void B::ViewDataTrait< T >::Get (HIViewRef view, ControlPartCode part, ResType tag, T & value) static
Retrieves the view data for the given view, part, and tag.
Parameters
view The view (HIViewRef a.k.a. ControlRef).
part The part code (often kHIViewEntireView).
tag The tag.
value Holds the output.
Referenced by B::View::GetFontStyle(), B::ViewDataTrait< T >::Set(), and B::TextFieldPart::~TextFieldPart().
template<typename T > void B::ViewDataTrait< T >::Set (HIViewRef view, ControlPartCode part, ResType tag, const T & value) static
Changes the view data for the given view, part, and tag.
Parameters
view The view (HIViewRef a.k.a. ControlRef).
part The part code (often kHIViewEntireView).
tag The tag.
value The new value.
Referenced by B::ViewDataTrait< T >::Set(), and B::TextFieldPart::~TextFieldPart().
template<typename T > OSStatus B::ViewDataTrait< T >::Get (HIViewRef view, ControlPartCode part, ResType tag, T & value, const std::nothrow_t &) static
Retrieves the view data for the given view, part, and tag (no-throw variant).
Returns
An OS status code.
Exceptions
none
Parameters
view The view (HIViewRef a.k.a. ControlRef).
part The part code (often kHIViewEntireView).
tag The tag.
value Holds the output.
template<typename T > OSStatus B::ViewDataTrait< T >::Set (HIViewRef view, ControlPartCode part, ResType tag, const T & value, const std::nothrow_t &) static
Changes the view data for the given view, part, and tag (no-throw variant).
Returns
An OS status code.
Exceptions
none
Parameters
view The view (HIViewRef a.k.a. ControlRef).
part The part code (often kHIViewEntireView).
tag The tag.
value The new value.
template<typename T > OSStatus B::ViewDataTrait< T >::Get (const void * data, size_t size, T & value) static
Retrieves the view data from an arbitrary address in memory.
Note that the size is checked to ensure it is equal to sizeof(value).
Returns
An OS status code.
Exceptions
none
Parameters
data The source address of the view data.
size The size of the view data.
value Holds the output.
References B::ViewDataTrait< T >::T.
template<typename T > OSStatus B::ViewDataTrait< T >::Set (void * data, size_t size, const T & value) static
Copies the view data to an arbitrary address in memory.
Note that the size is checked to ensure it is equal to sizeof(value).
Returns
An OS status code.
Exceptions
none
Parameters
data The destination address of the view data.
size The size of the view data.
value The new value.
References B::ViewDataTrait< T >::Get(), B::ViewDataTrait< T >::Set(), and B::ViewDataTrait< T >::T.
The documentation for this struct was generated from the following files:
BFwd.h
BViewData.h