B: B::MenuItemProperty< SIG, TAG, T > Struct Template Reference
B::MenuItemProperty< SIG, TAG, T > Struct Template Reference
Gets & sets a menu item property in a type-safe manner.
#include <BMenuItemProperty.h>
Public Types
Types
typedef inherited::ObjectTraits ObjectTraits
The traits for the toolbox object type.
typedef inherited::ObjectType ObjectType
The type representing the toolbox object in function arguments.
typedef inherited::TypeTraits TypeTraits
The traits for C/C++ language type of the property.
typedef inherited::PropertyType PropertyType
The type representing the property data in function arguments. See ToolboxObjectPropertyTypeTrait.
Static Public Member Functions
Inquiries
static bool Exists (MenuRef menu, MenuItemIndex index)
Returns true if the property identified by SIG and TAG exists within obj.
static size_t Size (MenuRef menu, MenuItemIndex index)
Returns the size of the property identified by SIG and TAG within obj.
Getting / Setting / Removing Properties
static PropertyType Get (MenuRef menu, MenuItemIndex index)
Retrieves the property identified by SIG and TAG within obj.
static void Get (MenuRef menu, MenuItemIndex index, PropertyType &value)
static bool Get (MenuRef menu, MenuItemIndex index, PropertyType &value, const std::nothrow_t &)
static void Set (MenuRef menu, MenuItemIndex index, const PropertyType &value)
Sets the property identified by SIG and TAG within obj.
static void Remove (MenuRef menu, MenuItemIndex index)
Removes the property identified by SIG and TAG within obj.
Attributes
static UInt32 GetAttrs (MenuRef menu, MenuItemIndex index)
Returns the attributes of the property identified by SIG and TAG within obj.
static void SetAttrs (MenuRef menu, MenuItemIndex index, UInt32 setAttributes, UInt32 clearAttributes)
Changes the attributes of the property identified by SIG and TAG within obj.
Template Parameters
typedef OSType SIG
Template parameter. The creator to use when accessing the property.
typedef OSType TAG
Template parameter. The tag to use when accessing the property.
typedef T
Template parameter. Any C/C++ language type.
Detailed Description
template<OSType SIG, OSType TAG, typename T>
struct B::MenuItemProperty< SIG, TAG, T >
Gets & sets a menu item property in a type-safe manner.
MenuItemProperty allows one to access a specific property (identified by the SIG and TAG template parameters) of a MenuRef/MenuItemIndex pair in a type-safe manner (this safety is provided indirectly by the T template parameter).
The idea is to allow for easy definition of properties in a type-safe manner. For example, if a client of a MenuRef needs to associate a URL with a menu item, it can simply declare a typedef for it:
typedef B::MenuItemProperty<kMySig, kMyURLTag, CFURLRef>    UrlMenuItemProperty;
The client can then get & set the property:
MenuRef  myMenu;
B::Url   myUrl;
myUrl = UrlMenuItemProperty::Get(myMenu, 1);
UrlMenuItemProperty::Set(myMenu, 2, myUrl);
Member Function Documentation
template<OSType SIG, OSType TAG, typename T > bool B::MenuItemProperty< SIG, TAG, T >::Exists (MenuRef menu, MenuItemIndex index) static
Returns true if the property identified by SIG and TAG exists within obj.
Parameters
menu The menu.
index The menu item.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > size_t B::MenuItemProperty< SIG, TAG, T >::Size (MenuRef menu, MenuItemIndex index) static
Returns the size of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
index The menu item.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > MenuItemProperty< SIG, TAG, T >::PropertyType B::MenuItemProperty< SIG, TAG, T >::Get (MenuRef menu, MenuItemIndex index) static
Retrieves the property identified by SIG and TAG within obj.
Returns
PropertyType The property's value.
Parameters
menu The menu.
index The menu item.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
Referenced by B::ContextualMenu::GetFirstItem().
template<OSType SIG, OSType TAG, typename T > void B::MenuItemProperty< SIG, TAG, T >::Get (MenuRef menu, MenuItemIndex index, PropertyType & value) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
menu The menu.
index The menu item.
value Holds the output property value.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > bool B::MenuItemProperty< SIG, TAG, T >::Get (MenuRef menu, MenuItemIndex index, PropertyType & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
Boolean indication of sucess or failure.
Exceptions
none
Parameters
menu The menu.
index The menu item.
value Holds the output property value.
nt An indication that the caller doesn't want to have the function throw an exception.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuItemProperty< SIG, TAG, T >::Set (MenuRef menu, MenuItemIndex index, const PropertyType & value) static
Sets the property identified by SIG and TAG within obj.
Parameters
menu The menu.
index The menu item.
value The new value.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
Referenced by B::ContextualMenu::GetFirstItem().
template<OSType SIG, OSType TAG, typename T > void B::MenuItemProperty< SIG, TAG, T >::Remove (MenuRef menu, MenuItemIndex index) static
Removes the property identified by SIG and TAG within obj.
Parameters
menu The menu.
index The menu item.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
Referenced by B::ContextualMenu::GetFirstItem().
template<OSType SIG, OSType TAG, typename T > UInt32 B::MenuItemProperty< SIG, TAG, T >::GetAttrs (MenuRef menu, MenuItemIndex index) static
Returns the attributes of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
index The menu item.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuItemProperty< SIG, TAG, T >::SetAttrs (MenuRef menu, MenuItemIndex index, UInt32 setAttributes, UInt32 clearAttributes) static
Changes the attributes of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
index The menu item.
setAttributes The attributes to set.
clearAttributes The attributes to clear.
References B::ToolboxObjectPropertyMenuItemObjectTraits::ObjectType::ObjectType().
The documentation for this struct was generated from the following file:
BMenuItemProperty.h