B: B::EventParamAndType< NAME, TYPE > Struct Template Reference
B::EventParamAndType< NAME, TYPE > Struct Template Reference
Carbon Events
Gets & sets a specific Carbon Event parameter of a specific type in a type-safe manner.
#include <BEventParams.h>
Public Types
Template Parameters
typedef EventParamName NAME
Template parameter. Should be an integral four-char constant (an EventParamName).
typedef EventParamAndType TYPE
Template parameter. Should be an integral four-char constant (an EventParamType).
Types
typedef EventParamTypeTrait< TYPE > IOType
The traits for TYPE. This is the class that actually gets & sets values.
typedef IOType::Type ValueType
The language type.
Static Public Member Functions
Inquiries
static bool Exists (EventRef inEvent)
Determines whether the parameter exists in a Carbon Event.
Getting & Setting Parameters
static ValueType Get (EventRef inEvent)
Retrieves a Carbon Event parameter, returning it as the function result.
static void Get (EventRef inEvent, ValueType &value)
Retrieves a Carbon Event parameter, returning it in value.
static bool Get (EventRef inEvent, ValueType &value, const std::nothrow_t &)
Retrieves a Carbon Event parameter, returning it in value and without throwing an exception.
static void Set (EventRef inEvent, const ValueType &inValue)
Sets a Carbon Event parameter.
Detailed Description
template<EventParamName NAME, EventParamType TYPE>
struct B::EventParamAndType< NAME, TYPE >
Gets & sets a specific Carbon Event parameter of a specific type in a type-safe manner.
EventParamAndType utilises EventParamTypeTrait<TYPE> to actually retrieve & store the data. See EventParamTypeTrait for more information.
See also
Handling Carbon Events
Member Function Documentation
template<EventParamName NAME, EventParamType TYPE> bool B::EventParamAndType< NAME, TYPE >::Exists (EventRef inEvent) static
Determines whether the parameter exists in a Carbon Event.
The parameter's name and type are determined by the NAME and TYPE template parameters, respectively.
Returns
A boolean indication of success or failure.
Exceptions
none
Parameters
inEvent The Carbon Event.
template<EventParamName NAME, EventParamType TYPE> EventParamAndType< NAME, TYPE >::ValueType B::EventParamAndType< NAME, TYPE >::Get (EventRef inEvent) static
Retrieves a Carbon Event parameter, returning it as the function result.
The parameter's name and type are determined by the NAME and TYPE template parameters, respectively.
Returns
The value.
Parameters
inEvent The Carbon Event.
Referenced by B::EventTarget::PrivateCreate(), and B::EventBase::Retrieve().
template<EventParamName NAME, EventParamType TYPE> void B::EventParamAndType< NAME, TYPE >::Get (EventRef inEvent, ValueType & value) static
Retrieves a Carbon Event parameter, returning it in value.
The parameter's name and type are determined by the NAME and TYPE template parameters, respectively.
Parameters
inEvent The Carbon Event.
value Holds the output value.
template<EventParamName NAME, EventParamType TYPE> bool B::EventParamAndType< NAME, TYPE >::Get (EventRef inEvent, ValueType & value, const std::nothrow_t &) static
Retrieves a Carbon Event parameter, returning it in value and without throwing an exception.
The parameter's name and type are determined by the NAME and TYPE template parameters, respectively.
Returns
Boolean indication of sucess or failure.
Exceptions
none
Parameters
inEvent The Carbon Event.
value Holds the output value.
template<EventParamName NAME, EventParamType TYPE> void B::EventParamAndType< NAME, TYPE >::Set (EventRef inEvent, const ValueType & inValue) static
Sets a Carbon Event parameter.
The parameter's name and type are determined by the NAME and TYPE template parameters, respectively.
Parameters
inEvent The Carbon Event.
inValue The new value.
Referenced by B::EventTarget::PrivateCreate(), and B::EventBase::Retrieve().
The documentation for this struct was generated from the following file:
BEventParams.h