B: B::DescParam< TYPE > Struct Template Reference
B::DescParam< TYPE > Struct Template Reference
Apple Events
Reads & writes an Apple Event descriptor in a type-safe manner.
#include <BAEDescParam.h>
Public Types
Template Parameters
typedef DescType TYPE
The template parameter. Should be an integral four-char constant (a DescType).
Types
typedef TaggedTypeTrait< TYPE >::Type ValueType
The language type. See TaggedTypeTrait.
Static Public Member Functions
Reading Apple Event Descriptors
static void Get (const AEDesc &desc, ValueType &value)
Converts the contents of an Apple Event descriptor into a C/C++ language type.
static OSStatus Get (const AEDesc &desc, ValueType &value, const std::nothrow_t &)
Writing Apple Event Descriptors
static void Put (AEDesc &desc, const ValueType &value)
Converts a C/C++ language type value into an Apple Event descriptor.
static void Write (AEStreamRef stream, const ValueType &value)
Appends a C/C++ language type value to an Apple Event descriptor stream.
Detailed Description
template<DescType TYPE>
struct B::DescParam< TYPE >
Reads & writes an Apple Event descriptor in a type-safe manner.
DescParam provides a type-safe wrapper around the Apple Event Manager calls that read and write Apple Event descriptors.
The class's type-safety is provided by the related type TaggedTypeTrait, which maps an DescType onto a C/C++ language type. Thus DescParam augments TaggedTypeTrait with Apple Event accessors.
Member Function Documentation
template<DescType TYPE> void B::DescParam< TYPE >::Get (const AEDesc & desc, ValueType & value) static
Converts the contents of an Apple Event descriptor into a C/C++ language type.
Parameters
desc The Apple Event descriptor.
value Holds the output value.
References B::DescParamHelper::GetCoercedData().
Referenced by B::AEObject::AccessElementsByName(), B::AEObject::AccessElementsByUniqueID(), B::AEObject::AccessProperty(), B::AEObjectSupport::CompareStrings(), B::AEObject::ConvertIndexedKeyData(), B::NavReplyDialog::FilterObject(), B::DescParamHelper::GetCoercedData(), B::AEEventFunctor::DescParamResult< TYPE >::operator()(), B::DescParamHelper::ReadKey(), B::DescParamHelper::ReadParam(), B::AEObjectSupport::RethrowExceptionFromAppleEventReply(), and B::AEObjectSupport::SetDefaultEventHandler().
template<DescType TYPE> OSStatus B::DescParam< TYPE >::Get (const AEDesc & desc, ValueType & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
An OS status code.
Exceptions
none
Parameters
desc The Apple Event descriptor.
value Holds the output value.
References B::DescParamHelper::GetCoercedData().
template<DescType TYPE> void B::DescParam< TYPE >::Put (AEDesc & desc, const ValueType & value) static
Converts a C/C++ language type value into an Apple Event descriptor.
Parameters
desc The Apple Event descriptor record.
value The new value.
Referenced by B::AETypedDescriptor< TYPE >::AETypedDescriptor(), B::DescParamHelper::GetCoercedData(), and B::DescParamHelper::WriteKey().
template<DescType TYPE> void B::DescParam< TYPE >::Write (AEStreamRef stream, const ValueType & value) static
Appends a C/C++ language type value to an Apple Event descriptor stream.
Use this function if you are appending to an open descriptor or to an open descriptor list.
Parameters
stream The Apple Event descriptor stream.
value The new value.
Referenced by B::DescParamHelper::GetCoercedData(), B::AEWriter::Write(), and B::AEWriter::WriteObject().
The documentation for this struct was generated from the following file:
BAEDescParam.h