B: B::MenuCommandProperty< SIG, TAG, T > Struct Template Reference
B::MenuCommandProperty< SIG, TAG, T > Struct Template Reference
Gets & sets a menu command property in a type-safe manner.
#include <BMenuCommandProperty.h>
Public Types
Types
typedef inherited::ObjectTraits ObjectTraits
The traits for the toolbox object type.
typedef inherited::ObjectType ObjectType
The type representing the toolbox object in function arguments.
typedef inherited::TypeTraits TypeTraits
The traits for C/C++ language type of the property.
typedef inherited::PropertyType PropertyType
The type representing the property data in function arguments. See ToolboxObjectPropertyTypeTrait.
Static Public Member Functions
Inquiries
static bool Exists (MenuRef menu, MenuCommand cmd)
Returns true if the property identified by SIG and TAG exists within obj.
static bool Exists (MenuCommand cmd)
static size_t Size (MenuRef menu, MenuCommand cmd)
Returns the size of the property identified by SIG and TAG within obj.
static size_t Size (MenuCommand cmd)
Getting / Setting / Removing Properties
static PropertyType Get (MenuRef menu, MenuCommand cmd)
Retrieves the property identified by SIG and TAG within obj.
static PropertyType Get (MenuCommand cmd)
static void Get (MenuRef menu, MenuCommand cmd, PropertyType &value)
static void Get (MenuCommand cmd, PropertyType &value)
static bool Get (MenuRef menu, MenuCommand cmd, PropertyType &value, const std::nothrow_t &)
static bool Get (MenuCommand cmd, PropertyType &value, const std::nothrow_t &)
static void Set (MenuRef menu, MenuCommand cmd, const PropertyType &value)
Sets the property identified by SIG and TAG within obj.
static void Set (MenuCommand cmd, const PropertyType &value)
static void Remove (MenuRef menu, MenuCommand cmd)
Removes the property identified by SIG and TAG within obj.
static void Remove (MenuCommand cmd)
Attributes
static UInt32 GetAttrs (MenuRef menu, MenuCommand cmd)
Returns the attributes of the property identified by SIG and TAG within obj.
static UInt32 GetAttrs (MenuCommand cmd)
static void SetAttrs (MenuRef menu, MenuCommand cmd, UInt32 setAttributes, UInt32 clearAttributes)
Changes the attributes of the property identified by SIG and TAG within obj.
static void SetAttrs (MenuCommand cmd, UInt32 setAttributes, UInt32 clearAttributes)
Template Parameters
typedef OSType SIG
Template parameter. The creator to use when accessing the property.
typedef OSType TAG
Template parameter. The tag to use when accessing the property.
typedef T
Template parameter. Any C/C++ language type.
Detailed Description
template<OSType SIG, OSType TAG, typename T>
struct B::MenuCommandProperty< SIG, TAG, T >
Gets & sets a menu command property in a type-safe manner.
MenuCommandProperty allows one to access a specific property (identified by the SIG and TAG template parameters) of a MenuRef/MenuCommand pair in a type-safe manner (this safety is provided indirectly by the T template parameter).
The idea is to allow for easy definition of properties in a type-safe manner. For example, if a client of a MenuRef needs to associate a URL with a menu command, it can simply declare a typedef for it:
typedef B::MenuCommandProperty<kMySig, kMyURLTag, CFURLRef> UrlMenuCommandProperty;
The client can then get & set the property:
B::Url   myUrl;
myUrl = UrlMenuCommandProperty::Get(kMyCmd);
UrlMenuCommandProperty::Set(kMyCmd, myUrl);
Member Function Documentation
template<OSType SIG, OSType TAG, typename T > bool B::MenuCommandProperty< SIG, TAG, T >::Exists (MenuRef menu, MenuCommand cmd) static
Returns true if the property identified by SIG and TAG exists within obj.
Parameters
menu The menu.
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > bool B::MenuCommandProperty< SIG, TAG, T >::Exists (MenuCommand cmd) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > size_t B::MenuCommandProperty< SIG, TAG, T >::Size (MenuRef menu, MenuCommand cmd) static
Returns the size of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > size_t B::MenuCommandProperty< SIG, TAG, T >::Size (MenuCommand cmd) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
PropertyType The property's value.
Parameters
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > MenuCommandProperty< SIG, TAG, T >::PropertyType B::MenuCommandProperty< SIG, TAG, T >::Get (MenuRef menu, MenuCommand cmd) static
Retrieves the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > MenuCommandProperty< SIG, TAG, T >::PropertyType B::MenuCommandProperty< SIG, TAG, T >::Get (MenuCommand cmd) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
PropertyType The property's value.
Parameters
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Get (MenuRef menu, MenuCommand cmd, PropertyType & value) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
menu The menu.
cmd The menu command.
value Holds the output property value.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Get (MenuCommand cmd, PropertyType & value) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
value Holds the output property value.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > bool B::MenuCommandProperty< SIG, TAG, T >::Get (MenuRef menu, MenuCommand cmd, PropertyType & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
Boolean indication of sucess or failure.
Exceptions
none
Parameters
menu The menu.
cmd The menu command.
value Holds the output property value.
nt An indication that the caller doesn't want to have the function throw an exception.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > bool B::MenuCommandProperty< SIG, TAG, T >::Get (MenuCommand cmd, PropertyType & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns
Boolean indication of sucess or failure.
Exceptions
none
Parameters
cmd The menu command.
value Holds the output property value.
nt An indication that the caller doesn't want to have the function throw an exception.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Set (MenuRef menu, MenuCommand cmd, const PropertyType & value) static
Sets the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
value The new value.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Set (MenuCommand cmd, const PropertyType & value) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
value The new value.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Remove (MenuRef menu, MenuCommand cmd) static
Removes the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::Remove (MenuCommand cmd) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > UInt32 B::MenuCommandProperty< SIG, TAG, T >::GetAttrs (MenuRef menu, MenuCommand cmd) static
Returns the attributes of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > UInt32 B::MenuCommandProperty< SIG, TAG, T >::GetAttrs (MenuCommand cmd) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::SetAttrs (MenuRef menu, MenuCommand cmd, UInt32 setAttributes, UInt32 clearAttributes) static
Changes the attributes of the property identified by SIG and TAG within obj.
Parameters
menu The menu.
cmd The menu command.
setAttributes The attributes to set.
clearAttributes The attributes to clear.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
template<OSType SIG, OSType TAG, typename T > void B::MenuCommandProperty< SIG, TAG, T >::SetAttrs (MenuCommand cmd, UInt32 setAttributes, UInt32 clearAttributes) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
cmd The menu command.
setAttributes The attributes to set.
clearAttributes The attributes to clear.
References B::ToolboxObjectPropertyMenuCommandObjectTraits::ObjectType::ObjectType().
The documentation for this struct was generated from the following file:
BMenuCommandProperty.h