B: B::ToolboxObjectPropertyTypeTrait< T, OBJTR > Struct Template Reference
B::ToolboxObjectPropertyTypeTrait< T, OBJTR > Struct Template Reference
Traits class for toolbox object properties.
#include <BToolboxObjectProperty.h>
Public Types
Types
typedef T PropertyType
The type representing the property data in function arguments.
typedef OBJTR ObjectTraits
The traits for the toolbox object type.
typedef ObjectTraits::ObjectType ObjectType
The type representing the toolbox object in function arguments.
Static Public Member Functions
Getting & Setting Properties
static PropertyType Get (ObjectType obj, OSType creator, OSType tag)
Retrieves the property with the given creator and tag.
static bool Get (ObjectType obj, OSType creator, OSType tag, PropertyType &value)
Retrieves the property with the given creator and tag, without throwing an exception.
static void Set (ObjectType obj, OSType creator, OSType tag, const PropertyType &value)
Changes the property with the given creator and tag.
Public Attributes
Template Parameters
typedef T
Template parameter. Any C/C++ language type.
typedef OBJTR
Template parameter. The traits class for the toolbox object. See ToolboxObjectPropertyObjectTraitsArchetype.
Detailed Description
template<typename T, class OBJTR>
struct B::ToolboxObjectPropertyTypeTrait< T, OBJTR >
Traits class for toolbox object properties.
This class allows clients to get & set the properties of toolbox objects in a type-safe manner. The default implementation simply performs a bitwise copy into and out of the toolbox objet. However, this behaviour may be overriden by specialising this class.
The template parameter, T, is a C/C++ language type. It's the type of the data to be stored into or retrieved from the toolbox object. The property data is passed to and returned from as the PropertyType typedef, which by default is a synonym for T. Again this may be changed by specialising the template.
Member Function Documentation
template<typename T , class OBJTR > ToolboxObjectPropertyTypeTrait< T, OBJTR >::PropertyType B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Get (ObjectType obj, OSType creator, OSType tag) static
Retrieves the property with the given creator and tag.
Returns
The property's value.
Parameters
obj The toolbox object.
creator The property's owner.
tag The property's name.
Referenced by B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Set().
template<typename T , class OBJTR > bool B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Get (ObjectType obj, OSType creator, OSType tag, PropertyType & value) static
Retrieves the property with the given creator and tag, without throwing an exception.
Returns
true if the property exists; else false.
Exceptions
none
Note
The function assumes that PropertyType's copy-assignment operator doesn't throw.
Parameters
obj The toolbox object.
creator The property's owner.
tag The property's name.
value The property's value.
template<typename T , class OBJTR > void B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Set (ObjectType obj, OSType creator, OSType tag, const PropertyType & value) static
Changes the property with the given creator and tag.
Parameters
obj The toolbox object.
creator The property's owner.
tag The property's name.
value The new value.
References B::String::assign(), B::String::clear(), B::String::copy(), B::ToolboxObjectPropertyObjectTraitsArchetype::Get(), B::ToolboxObjectPropertyTypeTrait< T, OBJTR >::Get(), B::ToolboxObjectPropertyObjectTraitsArchetype::ObjectType, and B::ToolboxObjectPropertyObjectTraitsArchetype::Set().
The documentation for this struct was generated from the following file:
BToolboxObjectProperty.h