B: B::DescParamHelper Struct Reference
B::DescParamHelper Struct Reference
Apple Events
Common utility functions for the use of DescParam.
#include <BAEDescParam.h>
Static Public Member Functions
static void GetCoercedData (const AEDesc &desc, DescType type, void *data, size_t size)
Coerces the given Apple Event descriptor to the given type.
static OSStatus GetCoercedData (const AEDesc &desc, DescType type, void *data, size_t size, const std::nothrow_t &)
template<DescType TYPE>
static void ReadKey (const AERecord &record, AEKeyword key, typename TaggedTypeTrait< TYPE >::Type &value)
Converts an element of an Apple Event descriptor record into a C/C++ language type.
template<DescType TYPE>
static OSStatus ReadKey (const AERecord &record, AEKeyword key, typename TaggedTypeTrait< TYPE >::Type &value, const std::nothrow_t &)
template<DescType TYPE>
static void ReadParam (const AEDescList &list, long index, typename TaggedTypeTrait< TYPE >::Type &value)
Converts an element of an Apple Event descriptor list into a C/C++ language type.
template<DescType TYPE>
static OSStatus ReadParam (const AEDescList &list, long index, typename TaggedTypeTrait< TYPE >::Type &value, const std::nothrow_t &)
template<DescType TYPE>
static void WriteKey (AERecord &record, AEKeyword key, const typename TaggedTypeTrait< TYPE >::Type &value)
Adds a value of the C/C++ language type matching TYPE to an Apple Event record.
Detailed Description
Common utility functions for the use of DescParam.
Member Function Documentation
void B::DescParamHelper::GetCoercedData (const AEDesc & desc, DescType type, void * data, size_t size) static
Coerces the given Apple Event descriptor to the given type.
Parameters
desc The Apple Event descriptor.
type The destination type of the coercion.
data The destination address.
size The destination's size.
Referenced by B::DescParam< TYPE >::Get().
OSStatus B::DescParamHelper::GetCoercedData (const AEDesc & desc, DescType type, void * data, size_t size, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function calls MOSL to perform the coercion. This means that if desc is an object specifier, the specifier is resolved prior to coercion. For example, if desc represents
the number of words of paragraph 3 of document "foo"
and type is typeIEEE32BitFloatingPoint, then @ desc is resolved (yielding the integer count of words), then coerced into a floating-point value.
Returns
An OS status code.
Exceptions
none
Parameters
desc The Apple Event descriptor.
type The destination type of the coercion.
data The destination address.
size The destination's size.
References B::String::cf_ref(), B::String::clear(), B::AEWriter::Close(), B::AEObjectSupport::Get(), B::DescParam< TYPE >::Get(), B::ErrorHandler::GetStatus(), B::AEObject::MakeSpecifier(), B::DescParam< TYPE >::Put(), B::OSPtr< T >::reset(), B::AEObjectSupport::Resolve(), and B::DescParam< TYPE >::Write().
template<DescType TYPE> void B::DescParamHelper::ReadKey (const AERecord & record, AEKeyword key, typename TaggedTypeTrait< TYPE >::Type & value) static
Converts an element of an Apple Event descriptor record into a C/C++ language type.
Parameters
TYPE An integral four-char constant in the DescType namespace.
Parameters
record The Apple Event descriptor record.
key The key of the requested descriptor.
value Holds the output value.
References B::DescParam< TYPE >::Get().
template<DescType TYPE> OSStatus B::DescParamHelper::ReadKey (const AERecord & record, AEKeyword key, typename TaggedTypeTrait< TYPE >::Type & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
TYPE An integral four-char constant in the DescType namespace.
Returns
An OS status code.
Exceptions
none
Parameters
record The Apple Event descriptor record.
key The key of the requested descriptor.
value Holds the output value.
References B::DescParam< TYPE >::Get().
template<DescType TYPE> void B::DescParamHelper::ReadParam (const AEDescList & list, long index, typename TaggedTypeTrait< TYPE >::Type & value) static
Converts an element of an Apple Event descriptor list into a C/C++ language type.
Parameters
TYPE An integral four-char constant in the DescType namespace.
Parameters
list The Apple Event descriptor list.
index The index of the requested descriptor.
value Holds the output value.
References B::DescParam< TYPE >::Get().
template<DescType TYPE> OSStatus B::DescParamHelper::ReadParam (const AEDescList & list, long index, typename TaggedTypeTrait< TYPE >::Type & value, const std::nothrow_t & nt) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Parameters
TYPE An integral four-char constant in the DescType namespace.
Returns
An OS status code.
Exceptions
none
Parameters
list The Apple Event descriptor list.
index The index of the requested descriptor.
value Holds the output value.
References B::DescParam< TYPE >::Get().
template<DescType TYPE> void B::DescParamHelper::WriteKey (AERecord & record, AEKeyword key, const typename TaggedTypeTrait< TYPE >::Type & value) static
Adds a value of the C/C++ language type matching TYPE to an Apple Event record.
Parameters
TYPE An integral four-char constant in the DescType namespace.
Parameters
record The Apple Event descriptor record.
key The key of the input value.
value The input value.
References B::DescParam< TYPE >::Put().
The documentation for this struct was generated from the following files:
BAEDescParam.h
BAEDescParam.cpp